[Spring 지하철 노선도 - 1,2단계] 조시(조현근) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #180
Opened 2022-05-03 15:41 UTC by hyunrrr

스티치 안녕하세요!!
지하철 노선도 미션 리뷰받게된 조시입니다!!
아직 많이 부족하지만 리뷰 보내주시면 열심히 고민하고 공부해서 반영하겠습니다!!
잘부탁드립니다!!

2022-05-05 07:00 UTC, lxxjn0 requested changes
조시, 이번에 지하철 노선도 미션 리뷰를 담당하게 된 스티치 입니다 :)

전체적으로 코드가 깔끔하고 구현도 과하지도, 부족하지도 않게 적절히 잘 작성하신 것 같아요!! 👍🏼  특별히 고치거나 해야할 부분은 보이진 않았지만 몇 가지 부분에 대해서만 코멘트 달아두었습니다!!

해당 부분들 확인하시고 피드백 반영하시면 이번 미션은 충분히 마무리해도 될 것 같아요!! 피드백 확인 부탁드릴게요 :)

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/StationController.java
> +    }
Constructor injection 방식으로 빈을 주입했네요 👍🏼 혹시 여러가지 빈 주입 방식에 따른 장단점을 학습해보지 않았다면 이번 기회에 학습해보는 것도 좋을 것 같아요 :)

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/StationController.java
> +    public ResponseEntity<StationResponse> createStation(@RequestBody @Valid StationRequest stationRequest) {
Request 객체에 대한 유효성 검증 👍🏼

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/StationController.java
> +        StationResponse stationResponse = new StationResponse(station);
코드를 보니 조시는 dto의 사용 범위를 controller까지로 제한하고 service와 데이터를 주고 받을 때는 entity를 사용하는 군요. 혹시 어떠한 생각으로 이러한 결정을 했는지 이야기 해줄 수 있을까요??

> 절대 지적이나 잘못되었다는 의미가 아닙니다 :) 조쉬의 생각을 듣고 한번 이야기해보면 좋을만한 주제로 보여져서요 😄

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/StationController.java
>          return ResponseEntity.created(URI.create("/stations/" + newStation.getId())).body(stationResponse);
(제 생각에는) 체이닝 메서드의 경우 적절하게 개행을 하면 더 가독성이 좋아지는 것 같아요 :)

> 물론 이렇게 한 라인으로 쓰는 것이 더 가독성이 좋다고 생각하는 사람들도 많아서 이 부분은 조시의 생각대로 가져가도 됩니다

```suggestion
        return ResponseEntity
                .created(URI.create("/stations/" + newStation.getId()))
                .body(stationResponse);
```

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/StationController.java
>          return ResponseEntity.ok().body(stationResponses);
header에 추가적인 처리 없이 단순히 body만 넘길 경우 `@ResponseStatus` 어노테이션도 활용할 수 있어요!! 한번 학습해시면 좋을 것 같아서 남겨봅니다 :)

> 물론 지금 방법을 사용하는 것도 전혀 이상 없습니다!! 다른 방법이 존재하구나 정도의 관점으로 공부하고 본인에게 더 좋다고 생각되는 방향으로 가져가면 좋을 것 같아요 👍🏼

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private final RowMapper<Line> lineMapper = (resultSet, rowNum) -> new Line(
해당 값은 성격상 상수에 더 가까운 것 같은데 조시의 생각은 어떤가요? 해당 값을 LineDao의 필드로 가지고 있는게 과연 적절한가 라는 의문이 생기는 것 같아요!!

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +                .usingGeneratedKeyColumns("id");
이 두 구현체는 이번에 리뷰를 하면서 처음 봤는데 jdbc를 사용하는 코드를 상당히 깔끔하고 간편하게 관리할 수 있도록 도와주는 코드네요 👍🏼

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +                .addValue("color", line.getColor());
해당 코드는 `BeanPropertySqlParameterSource`를 사용해서는 처리가 어려울까요??

2022-05-05 07:00 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/handler/RestExceptionHandler.java
> +public class RestExceptionHandler {
다양한 에러를 적절한 응답 코드로 처리하는 부분이 좋네요 👍🏼 여기서 추가적으로 프론트에서 어떠한 상황인지 인지할 수 있도록 에러 메시지도 함께 던져보는 것은 어떨까요??

2022-05-05 07:00 UTC, lxxjn0 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        Long id = Long.parseLong(createResponse.header("Location").split("/")[2]);
자주 사용되는 메서드를 private 메서드로 추출해보는 건 어떨까요??

2022-05-05 07:01 UTC, lxxjn0 commented
아, 추가로 처음에 1단계에서는 스프링 의존성 관리를 사용하지 않고 코드를 작성하고 2단계에서 스프링 사용을 한 것으로 알고 있어요!! 그 변환 시점에서 느낀 느낌점 같은 것도 같이 이야기해주시면 좋을 것 같아요 :)

2022-05-05 11:08 UTC, hyunrrr commented on src/main/java/wooteco/subway/ui/StationController.java
> +    }
가이드해주셔서 감사합니다!!!
간단하게 공부해보았는데 빈 주입 방식에는 
1. constructor injection 
2. setter injection
3. field injection
이 있다고 공부했습니다. 공식문서에선 필수적인 필드는 생성자 주입을 사용하고 선택적 필드엔 setter를 사용하라 하더라고요.

생성자 주입을 사용하게 되면  장점으로
1. 필드에 null값이 안들어간다. 
2. 의존성 주입에 실패하면 객체가 아예 생성되지 않는다. 
3. 필드에 final 키워드를 붙일 수 있다.
정도가 있다고 이해했습니다!!

세터 주입을 사용했을때 장점은 사실 잘 모르겠습니다. 공식문서에서 선택적 필드에 setter를 사용하라 하던데 선택적 필드가 어떤 경우에 발생하는지 아직 잘 모르겠습니다.
단점으로는
1. 필드가 null이지만 객체가 생성된다.
2. 필드에 final를 붙일 수 없다.
로 이해했습니다. 신기하게 private setter일때도 의존성 주입은 잘 되더라고요!

마지막으로 필드 주입을 사용했을때 역시 장점은 잘 모르겠습니다.
단점으로는
1. 필드에 final를 붙일 수 없다.
로 이해했습니다. 필드 역시 private 접근제어자여도 의존성 주입이 잘 되었습니다!

의존성 주입을 하는 3가지 방법이 있지만 생성자 주입이 나머지 두 방법보다 상위호환이라는 느낌을 받았습니다.
아직 스프링을 많이 사용해보지 않아서 이해되지 않는 것들이 좀 있네요..

2022-05-05 12:16 UTC, hyunrrr commented on src/main/java/wooteco/subway/ui/StationController.java
> +        StationResponse stationResponse = new StationResponse(station);
이전 미션을 진행할 때 어디선가 dao에서 dto를 만드는 것이 어색하다 라는 이야기를 들었습니다. 
왜냐하면 우선 dao에서는 비즈니스 로직을 처리하는데 필요한 특정 데이터를 뽑아오기 보단(ex. select name ~~) 전체 데이터를 모두 뽑아오고, 다른 계층에서 필요한 데이터만 뽑아내는 것이 dao를 일반화 할 수 있어 좋다. 라고 들었습니다. 이렇게하면 db가 아닌 다른 스토리지를 사용할때도 추상화를 통해 쉽게 확장할 수 있다 라고 생각하게 되었습니다.
모든 데이터를 뽑아왔으면 비즈니스 로직에서 사용하기 위해 데이터를 변환해야 하는데(ex. db에서 뽑아온 string을 도메인 객체로 변환) 만약 dto를 사용한다면 dto 내부에 이런 변환 로직이 들어가게 되어 어색해 집니다. 그래서 entity라는 것을 사용하고 내부에서 변환할 수 있게 하면 dto는 getter/setter이외의 다른 메서드를 가지면 안된다. 라는 일관성을 지킬 수 있겠다 생각했습니다.
현재 코드에선 entity를 추가하는것이 굳이라고 생각되어 dto에서 도메인 객체를 생성하고 dao에서 도메인 객체를 이용해 데이터를 저장하지만 나중에 미션이 커지면 여러 계층을 추가하고 entity객체를 만들어 dto에 있는 변환 로직을 entity객체로 이동시킬 수 있지 않을까 생각합니다!!!

사실 이런 생각을 가지고 코드를 짠건 아니고.. 코드를 별 생각없이 짜고 난 후 질문이 들어와서 제 생각을 한번 정리해보았습니다..
혹시 제가 잘못 생각하고 있는 부분이나 부족한 부분이 있으면 지적 부탁드리겠습니다!! 감사합니다!!!

2022-05-05 15:32 UTC, hyunrrr commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private final RowMapper<Line> lineMapper = (resultSet, rowNum) -> new Line(
음.. 제가 아직은 맞게 생각했는지 잘 모르겠습니다.
필드, static, final, static final에 대해 다시 한번 생각해 봤습니다.

우선 static만 붙이게 되면 클래스 변수가 되는데 lineMapper는 모든 객체에서 동일하게 사용되니 static을 붙여 클래스 변수로 사용해도 괜찮겠다는 생각이 들었습니다.
이런 생각이 드니 인스턴스 변수로 가지고 있는게 어색하다는 생각이 드네요. 모든 객체에서 똑같은 상태를 가지는 변수를 사용할테니 인스턴스 변수보다는 클래스 변수가 어울리다는 생각이 들었습니다.

final에 대해서도 lineMapper에 할당되는 값이 런타임동안 변하면 안되고, 변할일이 없으니 붙이는게 당연하다고 생각되네요.

이런 두가지 근거가 합쳐져서 lineMapper에 static키워드, final 키워드가 붙어 상수로 관리되는게 자연스러운 건가요?
이제까지 항상 매직넘버나 string들만 상수로 관리했어서 무언가 어색함이 느껴지네요..

2022-05-05 16:01 UTC, hyunrrr commented on src/main/java/wooteco/subway/ui/StationController.java
>          return ResponseEntity.ok().body(stationResponses);
가이드 감사합니다!!!!

우선 몇개만 @ResponseStatus를 사용하도록 변경해보았습니다!! 코드가 더 깔끔해지네요!!
어떤것을 쓰는게 더 좋을지 한번 고민해보고 전체적으로 수정해보겠습니다 감사합니다!!

2022-05-05 17:06 UTC, hyunrrr commented
스티치 리뷰 정말 감사드립니다!!! 안다고 생각했는데 몰랐던 것들도 알게되고 새로운것들도 알게되었습니다!!
사실 이번 미션에서 스프링 의존성 관리의 도움없이 코드를 짰을때 저는 큰 불편함을 느끼지 못했습니다.... 자연스럽게 1단계에서 2단계로 넘어가서 그런지 프로젝트가 작아서 그런지 체감이 되는 편리함은 사실 못 느꼈습니다..

2022-05-06 10:13 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/StationController.java
> +    }
중요한 내용에 대해서는 조시가 모두 다 학습해주신 것 같네요 👍🏼

2022-05-06 10:28 UTC, lxxjn0 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private final RowMapper<Line> lineMapper = (resultSet, rowNum) -> new Line(
조시의 생각의 흐름이 딱 적절한 것 같아요 :) 상수는 꼭 문자열이나 숫자 등과 같이 primitive type에 대해서만 사용하는 것이 아니라 변하지 않는 값을 통틀어서 말해요!! 즉, static final을 붙이면 어떤 객체든 상관없이 변경될 수 없는 값이 되기 때문에 이렇게 선언한 변수를 주로 상수라고 말을 하구요.

조시가 말해준 흐름대로 해당 값은 정해진 후 변경되지 않아야 하는 값이기 때문에 상수로 관리하기가 적절하다는 생각이 들었고 그래서 말씀드려봤어요 :)

2022-05-06 10:31 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/StationController.java
> +        StationResponse stationResponse = new StationResponse(station);
조시의 의견을 잘 설명해주셔서 감사합니다 :) 다시 보니 service가 아니라 dao였군요.. 제가 코드를 잘못봤네요 ㅠㅠ dao를 사용하면서 적절한 이유로 entity를 전달받아 사용하는 것 같아서 저도 해당 의견에는 이견이 없습니다!! 👍🏼

2022-05-06 10:50 UTC, lxxjn0 approved these changes
조시, 피드백 반영한 부분 잘 봤어요!! 이전 피드백에 대한 대답은 코멘트 남겨두었습니다!! :)

이번 지하철 노선도 미션 기간이 그리 넉넉하지가 않더라구요 ㅠㅠ 그래서 이번 1, 2단계 미션은 여기서 마무리해도 될 것 같아요!! 전체적인 코드도 잘 정돈되어서 구현된 것 같습니다 :)

몇 가지 피드백만 남겨두었으니 해당 피드백들은 다음 미션을 진행할 때 반영해주세요 👍🏼

2022-05-06 10:50 UTC, lxxjn0 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private static final RowMapper<Line> lineMapper = (resultSet, rowNum) -> new Line(
상수 네이밍 컨벤션을 확인해주세요 :)

2022-05-06 10:50 UTC, lxxjn0 commented on src/main/java/wooteco/subway/ui/StationController.java
> +        return ResponseEntity.ok().body(stationResponses);*/
사용하지 않는 코드는 삭제해주셔도 될 것 같아요!! :) git을 사용하고 있는 만큼 추후에 다시 코드가 필요해질 경우에는 git에서 찾아볼 수 있을 것 같아요!!

2022-05-06 10:50 UTC, lxxjn0 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    public void updateById(Line line) {
코드가 변경되면서 현재 내용을 보면 단순히 line을 업데이트 하는 로직인 것 같아요!! 그에 맞게 메서드 명을 바꿔보는 것은 어떨까요??

2022-05-06 10:50 UTC, lxxjn0 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    }
Map.of 메서드를 사용하면 따로 private 메서드로 뽑지 않고도 깔끔하게 사용할 수 있을 것 같아요!!

2022-05-06 10:50 UTC, merged