[Spring 지하철 노선도 - 1,2단계] 조한석(조조그린) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #181
Opened 2022-05-03 16:05 UTC by jojogreen91

안녕하세요 제이!
저는 조조그린이라고 해요. 이렇게 만나 뵙게 돼서 반갑습니다 :)

이번 미션을 하면서 중심적으로 구현한 부분은
첫째로, 지금까지 배웠던 것을 토대로 주어진 API 스펙을 구현하려고 해봤고
두번째로, E2E 테스트를 비롯해서 Service, Repository 레이어의 테스트들을 신경써서 구현해 봤습니다.

페어랑 열심히 했는데 어떨지 모르겠네요😂
그럼 떨리는 마음으로 리뷰 기다리고 있겠습니다!
감사합니다 제이 :)

2022-05-05 18:15 UTC, jjj0611 requested changes
안녕하세요 조조그린! 리뷰어 제이입니다.
지하철 노선도 미션으로 만나게 되어서 반가워요!

구현해주신 코드는 잘 확인했습니다!
고민해볼만한 부분들에 코멘트 남겨두었어요!
확인해보시고 궁금하신 점 있으시면 코멘트 주시거나 DM 부탁드려요!

아 한 가지 궁금한 점이 있는데, 이번 미션 부터는 README.md는 작성하지 않나요??
기능 요구 사항 같은 것들을 따로 정리해두신 부분들이 없어서 여쭤봅니다 :)

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/entity/LineEntity.java
> +public class LineEntity {
LineEntity와 Line 도메인을 나눈 효용은 어떤걸까요?
현 시점에서 나누어야할 필요성을 느낀 부분이 있을까요?

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/entity/StationEntity.java
> +public class StationEntity {
ditto LineEntity 코멘트를 확인해주세요

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/StationService.java
> +        }
RDB에 unique 칼럼으로 생성해두셨던데,
한 번 더 조회쿼리를 날리게 되네요.

여기서 한 번 더 체크를 하는 것의 장단점이 무엇이 있을까요??

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/StationService.java
> +public class StationService {
Service 레이어에서는 어떤 역할을 하고 있나요?
register만하더라도 new StationEntity를 하고, save하는 로직밖에 없는데,
굳이 Service 레이어를 분리한 이유가 있을까요?

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +        final LineEntity savedLineEntity = lineDao.save(lineEntity);
이런 상태라면

```
final LineEntity savedLineEntity = lineDao.save(new LineEntity(new Line(name, color)));
```

이렇게 작성되는게 더 낫지 않을까요??

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/StationService.java
> +        final StationEntity savedStationEntity = stationDao.save(new StationEntity(station));
Line을 저장하는 것과는 또 다른 방식으로 생성해주셨네요.
일관성을 지켜보는 것은 어떨까요??

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/StationService.java
> +        return new Station(savedStationEntity.getId(), savedStationEntity.getName());
station entity에서 station을 받아서 생성이 되면,
station entity에서 station을 바로 생성도 할 수 있어야 하는거 아닐까요??

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void modify(final Long id, final String name, final String color) {
파라미터가 너무 많은 것은 아닐까요?

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +        lineDao.update(new LineEntity(newLine));
업데이트 시에 노선이 없는 것을 알 수 있지 않을까요?
한 번더 쿼리를 하면 어떤 효용이 있을까요??

2022-05-05 18:15 UTC, jjj0611 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        List<Long> expectedLineIds = Arrays.asList(createResponse1, createResponse2).stream()
intellij의 노란 가이드선이 뜨는 부분이 있지 않나요?!

2022-05-05 18:15 UTC, jjj0611 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .map(it -> it.getId())
여기도 있지 않을까요?!

2022-05-05 18:15 UTC, jjj0611 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .get("/lines/" + id)
```
"/lines/{id}", id
```

이런 방법도 있답니다 :)

2022-05-05 18:15 UTC, jjj0611 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(modifyResponse.statusCode()).isEqualTo(HttpStatus.OK.value());
LineController의 57번 라인을 누군가가 빠뜨려도 테스트는 통과하고, 정상작동한다고 생각할 수도 있겠네요 :)

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/controller/LineController.java
> +    @PostMapping("/lines")
request mapping을 사용해 중복을 줄일 수 있지 않을까요??

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/controller/StationController.java
> +    @GetMapping(value = "/stations")
여기도 다른 곳과는 조금 다른 방식으로 작성되었네요!
일관성을 지켜보면 어떨까요??

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +    }
NoSuchElementException이 발생하는 상황 중에 400번과 어울리지 않는 상황이 있는 것 같은데,
http code의 400과 404를 공부해보시겠어요?

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/controller/LineController.java
> +    }
실제로 어떻게 생성이 되고, 언제 이 LineService가 만들어지나요??

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +    private final NamedParameterJdbcTemplate jdbcTemplate;
이 객체는 누가 만들어주는걸까요??

2022-05-05 18:15 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +    private final RowMapper<LineEntity> rowMapper = (resultSet, rowNum) -> new LineEntity(
멤버 변수로 선언한 이유가 있을까요??

2022-05-06 02:12 UTC, jojogreen91 commented on src/main/java/wooteco/subway/repository/entity/LineEntity.java
> +public class LineEntity {
`LineEntity` 를 만든 가장 큰 이유는 `Service` 레이어와 `Repository` 레이어의 결합도를 느슨하게 하면서 레이어를 의존관계를 정리하기 위해서 였습니다.
어플리케이션의 레이어들이 `Controller -> Service ->  Repository` 이런 식으로 의존하도록 만들기 위해서 `Line` 도메인 클래스와 크게 다르지 않는 형태일지라도 `LineEntity` 를 만들었습니다. 

사실 `LineEntity` 는 `Line` 도메인 클래스를 기준으로 만들었다기 보다 DB 의 LINE 테이블을 기준으로 만들었습니다. 그래서 `Line` 클래스가 변경됨에 따라 수정하는 것이 아닌 DB 의 LINE 테이블이 수정됨에 따라 수정될 것이기 때문에 시점과 상관없이 당연히 만들어야 하는 것이라고 생각했습니다!

추가적으로 추후에 도메인 클래스 `Line` 은 언제든지 메서드를 가질수 있지만 `LineEntity` 는 DB Column 과 1 대 1 매칭되는 데이터 전달용 클래스로서 비즈니스와 관련된 메서드를 가질 수 없기 때문에 형태에서도 차이가 생길거라고 생각합니다.

2022-05-06 03:50 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/StationService.java
> +        }
중복된 이름을 저장하는 쿼리를 날릴 때 발생하는 부적절한 쿼리에 대한 예외 보다 좀 더 구체적인 이유를 설명할 수 있는 예외를 던질 수 있고 그에 따른 에러 메시지도 설정 할 수 있다고 생각해서 name Column 이 unique 임에도 Service 레이어에서 유효성 검사를 했습니다!

2022-05-06 04:49 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/StationService.java
> +public class StationService {
사실 이 부분은 저도 이번 레벨2에서 스프링을 써보면서 의문을 좀 가지고 있는 부분인데요.

기본적으로 클라이언트에서 생성하고자 하는 것이 우리가 설정한 비즈니스 도메인으로서 적절한지 검사하는 등의
여러가지 유효성검사를 해야하고 (리소스로 생성되어 DB에 저장되기 전에)
클라이언트의 요청에 대한 비즈니스 로직을 수행해야 하기에 `Service` 레이어가 필요하는 생각은 들어요.

만약 `Service` 레이어가 없으면 `Controller` 에서 바로 DB에 접근해서 부적절한 리소스를 생성할 수도 있고
클라이언트의 요청에 따른 비즈니스 로직을 사용해야 할 때는
복수의 도메인 클래스들을 의존하면서 `Controller` 가 직접적으로 메서드를 호출해야 하기에 `Controller` 가 너무 많은 책임을 가진다고 생각해서  `Service` 클래스, 레이어가 필요하다고는 생각합니다.

근데 제가 의문을 가지는 부분은
`Service` 클래스의 `remove()` 같은 메서드는 단순히 Dao 의 메서드를 바이패스해서 사용하는 형태라서 이런부분에서는 굳이 이럴 필요가 있을까? 라는 생각이 드는 것 같아요.

그래도 위에 적은 이유 때문에 `Service` 레이어가 필요하다는 생각은 있어서 `Service` 레이어가 존재한다면 `Controller` 는 `Service` 레이어만 의존하도록 해서 `Controller -> Service -> Repository` 이 의존구조를 지키는게 더 좋은 설계가 아닐까 생각은 듭니다.

제이는 혹시 어떻게 생각하시나요?🥲

2022-05-06 04:53 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/LineService.java
> +        final LineEntity savedLineEntity = lineDao.save(lineEntity);
가독성 측면에서 너무 복잡하게 보여서 한번 분리해준거긴 한데 그냥 인라인으로 처리하는게 더 좋았을까요?👀

2022-05-06 04:59 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/StationService.java
> +        final StationEntity savedStationEntity = stationDao.save(new StationEntity(station));
아 그렇네요!
`StationService` 에서 한 방식이 더 이해하기 좋은것 같아서 `LineService` 쪽을 수정했습니다!

2022-05-06 05:16 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/StationService.java
> +        return new Station(savedStationEntity.getId(), savedStationEntity.getName());
그렇네요!
추가했습니다🔧

2022-05-06 05:22 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void modify(final Long id, final String name, final String color) {
`modify` 메서드가 `Line` 객체를 받도록 수정했습니다! 🔧

2022-05-06 05:29 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/LineService.java
> +        lineDao.update(new LineEntity(newLine));
> RDB에 unique 칼럼으로 생성해두셨던데, 한 번 더 조회쿼리를 날리게 되네요.
> 
> 여기서 한 번 더 체크를 하는 것의 장단점이 무엇이 있을까요??

에 남겼던 답변이랑 비슷한 이유로 그렇게 했습니다!
(여기에도 추가적으로 커스텀예외를 만들었습니다.)

사실 확신은 없는데요. 제이가 지적해주신걸 생각해보니까 이중으로 쿼리를 날리는게 비효율적일 수 있다는 생각도 드네요.🥲

2022-05-06 05:43 UTC, jojogreen91 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        List<Long> expectedLineIds = Arrays.asList(createResponse1, createResponse2).stream()
엇 저는 이 부분에서는 안뜨는데 이 부분 말고 `LineAcceptanceTest` 다른 부분에서 수정 추천하는 라인이 있어서 수정했습니다 :)

2022-05-06 05:58 UTC, jojogreen91 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .get("/lines/" + id)
오 그렇군요!
수정했습니다! 🔧

2022-05-06 06:43 UTC, jojogreen91 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(modifyResponse.statusCode()).isEqualTo(HttpStatus.OK.value());
앗! 그러네요😂
수정한 리소스를 다시 조회해서 확인하도록 수정했습니다! 🔧

2022-05-06 07:00 UTC, jojogreen91 commented on src/main/java/wooteco/subway/controller/LineController.java
> +    @PostMapping("/lines")
아 그렇네요!
수정했습니다! 🔧

2022-05-06 07:00 UTC, jojogreen91 commented on src/main/java/wooteco/subway/controller/StationController.java
> +    @GetMapping(value = "/stations")
여긴 왜 이렇게 했을까요😂
수정했습니다! 🔧

2022-05-06 07:13 UTC, jojogreen91 commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +    }
커스텀 예외를 적용하면서 `ExceptionAdvice` 도 수정했습니다!
전반적으로 각 예외별로 적절한 상태 코드를 응답하려고 설정해봤는데 어떨지 모르겠네요🥲

2022-05-06 07:19 UTC, jojogreen91 commented on src/main/java/wooteco/subway/controller/LineController.java
> +    }
스프링 어플리케이션이 실행되고 생성된 `LineService` 빈이 생성자 주입 방식으로 `LineController` 에 주입 되는거 아닌가요?!

2022-05-06 07:27 UTC, jojogreen91 commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +    private final NamedParameterJdbcTemplate jdbcTemplate;
스프링 어플리케이션이 실행되면 `JdbcTemplateAutoConfiguration` 이 생성해주는 것 처럼 보이는데 맞나요?👀

<img width="1086" alt="스크린샷 2022-05-06 오후 4 25 51" src="https://user-images.githubusercontent.com/82805588/167086517-239b805e-0580-4674-a093-581214d267e9.png">

2022-05-06 07:30 UTC, jojogreen91 commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +    private final RowMapper<LineEntity> rowMapper = (resultSet, rowNum) -> new LineEntity(
지금까지는 `RowMapper` 가 필요하면 메서드 안에서 람다식으로 사용하거나 `private` 메서드를 만들어서 람다식을 반환 받았는데
함수형 인터페이스니까 그냥 멤버변수로 해놓고 람다식 초기화 해놔도 괜찮지 않을까? 생각해서 해봤는데 별로일까요?🥲

2022-05-06 07:31 UTC, jojogreen91 commented on src/main/java/wooteco/subway/repository/entity/StationEntity.java
> +public class StationEntity {
엇...무슨말씀인지 잘 이해가 안되네용 ㅠㅠㅠ🥲

2022-05-06 07:33 UTC, jojogreen91 commented
안녕하세요 제이!
남겨주신 피드백 반영해봤고 관련된 질문들도 댓글에 남겨두었습니다 :)
감사합니다 제이😀

2022-05-06 07:33 UTC, jojogreen91 commented
안녕하세요 제이!
남겨주신 피드백 반영해봤고 관련된 질문들도 댓글에 남겨두었습니다 :)
감사합니다 제이😀

2022-05-07 14:22 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +        final LineEntity savedLineEntity = lineDao.save(lineEntity);
엇 아뇨! 22번 라인에서는 new Line을 어차피 안 쪽에 넣어두셔서 이야기 드린 것이었어요!
가독성 측면을 생각하셨더라면 22번 라인도 가독성에서는 조금 떨어진다고 생각합니다!

2022-05-07 14:31 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/entity/LineEntity.java
> +public class LineEntity {
네네 저도 현재 시스템에서 DB에 저장되는 명세와 도메인으로서의 객체를 분리하여 관리하고 있긴한데요.
현 시점에서 나눌 필요가 있었는가 싶긴해서 드린 코멘트였습니다.
현재는 Line은 도메인으로서의 역할을 하고 있지도 않고, Line과 LineEntity, Station과 StationEntity는 거의 똑같이 작성되어 있다고 느껴져서요!

필요가 생겼을 때 분리하는 것이 좀 더 합리적이지 않을까 싶긴 합니다.

2022-05-07 14:32 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/StationService.java
> +        }
> 중복된 이름을 저장하는 쿼리를 날릴 때 발생하는 부적절한 쿼리에 대한 예외 보다

어떤 의미인지 잘 모르겠는데, 중복된 이름을 저장하는 쿼리 시에 예외가 발생하면 그 상황의 예외를 잡아서 조조그린이 새로 생성한 커스텀예외로 던지면 안될까요?

여전히 한 번 더 체크하는 것의 장점이 와 닿지 않아요!
다시 고민해주실 수 있을까요??

2022-05-07 14:37 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/StationService.java
> +public class StationService {
조조그린, 제가 드린 코멘트는 조조그린이 `현재` 작성한 코드에 대한 이야기입니다.

> 기본적으로 클라이언트에서 생성하고자 하는 것이 우리가 설정한 비즈니스 도메인으로서 적절한지 검사하는 등의 여러가지 유효성검사를 해야하고

어떤 유효성 검사가 이뤄져야 하나요?

> Service 레이어가 없으면 Controller 에서 바로 DB에 접근해서 부적절한 리소스를 생성할 수도 있고

Service 레이어에서는 바로 DB에 접근해서 부적절한 리소스를 생성할 수 없나요? 정확히 무엇을 의미하신지 모르겠습니다.

> 클라이언트의 요청에 따른 비즈니스 로직을 사용해야 할 때는

그 때 Service 레이어가 필요에 따라 등장하면 되지 않나요??

> 복수의 도메인 클래스들을 의존하면서

그 땐 Service가 너무 많은 책임을 지는 것 아닐까요?

2022-05-07 14:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +    private final RowMapper<LineEntity> rowMapper = (resultSet, rowNum) -> new LineEntity(
엇 아뇨 별로가 아니라, 위와 같은 형태라면 상수가 좀 더 어울리지 않나 싶어서 여쭤본 코멘트였어요.
해당 멤버 변수는 인스턴스마다 바뀌는 값이 아니지 않나요??

2022-05-07 14:41 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void modify(final Long id, final String name, final String color) {
저도 controller와 service layer를 분리한다면, 도메인 객체는 controller에서 참조하지 않는 편이 더 좋다고 생각하는 편이긴 합니다.
즉, 전자의 방식을 선호합니다.

2022-05-07 14:58 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +        lineDao.update(new LineEntity(newLine));
비효율은 좀 여러 측면에서 고민해볼 필요가 있을 것 같은데요.
위에도 남겨드려서 한 번 더 고민해보시고, 다시 이야기 해봐요 :)

2022-05-07 14:58 UTC, jjj0611 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .get("/lines/" + id)
앗 꼭 수정을 말씀드린건 아니고, 다른 방법도 있다고 말씀드린거였어요!!

2022-05-07 15:19 UTC, jjj0611 requested changes
안녕하세요 조조그린! 리뷰어 제이입니다.

수정해주신 부분들과 코멘트 남겨주신 부분들 잘 봤습니다.

고민해볼만한 부분들 몇 개 더 드렸고, 기존 질문들에 답변 달아드렸으니 확인 부탁드려요!

혹시 이해 가지 않는 부분이 있다면 코멘트 주시거나 DM 편하게 부탁드려요!

2022-05-07 15:19 UTC, jjj0611 commented on README.md
> +## 🔧 기능 요구 사항
기능 요구사항이 레벨1 때에 비해 단순해보이는건 기분탓일까요?!
기능 목록 작성은 언제나 좀 더 상세하게 해주셔도 지나치지 않습니다 :)

2022-05-07 15:19 UTC, jjj0611 commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +        return ResponseEntity.status(HttpStatus.CONFLICT).body(e.getMessage());
409 응답과 일치할까요?
또한 payload에 대해서도 고민해보면 좋을 것 같은데,
409 응답에 대해 찾아보셨을까요??

2022-05-07 15:19 UTC, jjj0611 commented on src/main/java/wooteco/subway/controller/LineController.java
> +    }
너무 단순화해서 이야기 해주셨는데,
스프링이 빈을 관리하는 방식과 주기에 대해 좀 더 깊게 이야기 해볼까요? :)

2022-05-07 15:19 UTC, jjj0611 commented on src/main/java/wooteco/subway/controller/LineController.java
> +@RequestMapping("/lines")
👍

2022-05-07 15:19 UTC, jjj0611 commented on src/main/java/wooteco/subway/dto/response/LineResponseDto.java
> +    private List<StationResponseDto> stations;
Line 도메인에도 없는 station response가 갑자기 추가된 이유가 뭘까요??

2022-05-07 15:19 UTC, jjj0611 commented on src/main/java/wooteco/subway/dto/request/SectionRequestDto.java
> +public class SectionRequestDto {
section에 대한 요구사항은 이번 미션에서는 없지 않았나요?

2022-05-07 15:19 UTC, jjj0611 commented on src/main/resources/schema.sql
> +);
EOF에 대한 키워드로 한 번 검색해보시겠어요??

2022-05-07 15:19 UTC, jjj0611 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +                () -> assertThat(created.getColor()).isEqualTo("bg-green-600")
2번째 indent의 컨벤션이 스페이스 8칸이었을까요??

2022-05-09 02:46 UTC, jojogreen91 commented on src/main/java/wooteco/subway/repository/entity/LineEntity.java
> +public class LineEntity {
저는 모양이 똑같다고해서 반드시 역할을 합쳐야한다는 생각이 안들어서 지금 상황에서 엔티티를 만든것 같아요 :)

엔티티는 db table 에 종속적이면서 db 에 있는 리소스를 자바객체로 대응해주기 위해 존재하기 때문에 엔티티를 씀에 있어 현재 도메인 객체는 고려할필요가 없다고 생각해요!

2022-05-09 03:00 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/StationService.java
> +public class StationService {
예를 들어서 사용자가 새로운 역을 등록하려고 할 때
빈값등의 유효하지 않은 이름을 입력하면 안된다는 도메인 규칙을 적용해야하는데

물론 프론트쪽에서 잘못된 값을 입력하지 못하도록 할수도 있고 db 에서도 제약을 두어 예외를 발생시킬수 있을것입니다.

하지만 기본적으로 이런 도메인 규칙은 어플리케이션의 서비스레이어와 도메인 영역에 존재해야한다고 생각합니다.

프론트나 db 에서 해주는 기능들은 도메인 규칙을 참고하여 프로그램에서 보조적인 역할에 지나지 않아야하고
서비스 레이어의 도메인 코드는 그 자체만으로 완전한 도메인의 역할을 다 해야하기 때문에 지금 상황에서도 서비스 레이어가 필요하다고 생각합니다!

2022-05-09 03:09 UTC, jojogreen91 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +                () -> assertThat(created.getColor()).isEqualTo("bg-green-600")
우테코 자바 컨벤션을 사용하는데 그런것 같습니다..!

2022-05-09 03:11 UTC, jojogreen91 commented on src/main/java/wooteco/subway/dto/response/LineResponseDto.java
> +    private List<StationResponseDto> stations;
제가 클래스 이름에 Dto 를 붙이는 수정을 했는데 그거 때문인것 같습니다😂

2022-05-09 05:50 UTC, jojogreen91 commented on src/main/resources/schema.sql
> +);
수정했습니다! 🔧

2022-05-09 07:06 UTC, jojogreen91 commented on README.md
> +## 🔧 기능 요구 사항
1, 2단계에서 주어진 API 스펙을 구현하는게 주된 부분이라 저정도 적었는데 3단계에서는 좀 더 상세하게 적을 수 있을 것 같습니다! 👍

2022-05-09 08:22 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/StationService.java
> +        }
아 그냥 Dao 에서 발생하는 예외를 잡아서 처리하면 쿼리를 한번 더 보내지 않고 예외처리를 할 수 있군요!
수정했습니다! 🔧

근데 궁금하게 이 방법을 사용하면 효율적이지만
다소 db 에 종속적인 구조가 되는 것 같은 생각도 드는데 제이는 어떻게 생각하시나요?🤔

2022-05-09 08:59 UTC, jojogreen91 commented on src/main/java/wooteco/subway/service/LineService.java
> +    public void modify(final Long id, final String name, final String color) {
수정했습니다! 🔧

2022-05-09 09:03 UTC, jojogreen91 commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +    private final RowMapper<LineEntity> rowMapper = (resultSet, rowNum) -> new LineEntity(
아 그렇군요! 상수로 하는게 더 울리네요!
수정했습니다! 🔧

2022-05-09 10:36 UTC, jojogreen91 commented on src/main/java/wooteco/subway/controller/LineController.java
> +    }
스프링 어플리케이션이 실행되면 스프링 컨테이너가 생성되고
@Component 혹은 @Component 를 상속받는 annotation 이 붙은 클래스들을 컴포넌트 스캔을 통하여 빈으로 등록됩니다.
그리고 싱글톤으로(기본 세팅) 만들어진 빈들이 스프링 컨테이너에 의해 의존관계 주입이 발생하고 어플리케이션이 종료되면 빈은 사라진다.
가 맞을까요?!

2022-05-09 10:47 UTC, jojogreen91 commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +        return ResponseEntity.status(HttpStatus.CONFLICT).body(e.getMessage());
CONFLICT 라는게 다른 400번대 에러들 가운데 400을 제외하고
"이미 중복되는 이름이 있어서 요청을 수행할 수 없다." 는 상황에 제일 어울린다고 생각해서 409를 반환하도록 해봤는데요.
제가 이해하기로 CONFLICT 는 비즈니스 로직 상 불가능하거나 모순이 생기는 경우라고 이해해서 이렇게 해봤습니다..!
근데 잘 모르겠네요 어떤게 적절한지 헷갈리네요 ㅠㅠ

payload 는 "우리가 실질적으로 보내고자하는 데이터 그 자체" 라고 알고 있는데 지금 상황에 어떻게 관계 있을까요?🤔

2022-05-09 10:54 UTC, jojogreen91 commented on src/main/java/wooteco/subway/dto/request/SectionRequestDto.java
> +public class SectionRequestDto {
이번 요구사항에는 없었는데 미션에서 기본적으로 제공한 프로젝트에서 존재했던 클래스인데 안지웠네요 제가.
제거했습니다!

2022-05-09 10:57 UTC, jojogreen91 commented
남겨주신 피드백 반영하고 관련된 질문도 댓글로 남겼습니다!
감사합니다 제이😀

2022-05-10 09:39 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/entity/LineEntity.java
> +public class LineEntity {
엇 조조그린 저는 `똑같다`에 집중했다기보다 `도메인으로서의 Line과 Entity로서의 Line이 다른 역할을 하는가`에 집중해서 말씀을 드렸던 거긴 합니다 :)

2022-05-10 09:41 UTC, jjj0611 approved these changes
안녕하세요 조조그린! 리뷰어 제이입니다.

수정해주신 코드 확인했습니다.
전체적으로 잘 반영해주셨네요!

3단계 진행을 위해 코드는 여기서 이만 머지할게요!
질문 달아주신 부분은 오늘이나 늦으면 내일까지 답변 남겨두도록 하겠습니다!

3단계 때 뵈어요!

2022-05-10 09:41 UTC, merged

2022-05-10 12:32 UTC, jjj0611 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +                () -> assertThat(created.getColor()).isEqualTo("bg-green-600")
오 그러네요!

두 번째 들여쓰기부터 +8 스페이스군요!

2022-05-10 12:33 UTC, jjj0611 commented on src/main/java/wooteco/subway/domain/Line.java
> +        if (name.isBlank()) {
null 방어 로직은 왜 제거하신걸까요??

2022-05-10 12:34 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +    private static final RowMapper<LineEntity> rowMapper = (resultSet, rowNum) -> new LineEntity(
상수의 네이밍 컨벤션을 잘 따른 걸까요?

2022-05-10 12:34 UTC, jjj0611 commented on src/main/java/wooteco/subway/repository/dao/JdbcStationDao.java
> +    private static final RowMapper<StationEntity> rowMapper = (resultSet, rowNum) -> new StationEntity(
상수의 네이밍 컨벤션을 잘 따른걸까요??

2022-05-10 12:37 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +        } catch (EmptyResultDataAccessException exception) {
해당 예외 처리는 Service 레이어가 아닌 dao에서 처리해주면 어떨까요??