[Spring 지하철 노선도 - 1,2단계] 알렉스(이영환) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #182
Opened 2022-05-03 16:23 UTC by yxxnghwan

안녕하세요 미르! 반갑습니다 알렉스입니다🤗

저번 체스 미션에 저는 도메인과 엔티티를 따로 구분하지 않았었는데요,
이번 미션에서는 DB의 테이블 구조와 같은 구조를 가지는 엔티티를 정의하고 서비스 레이어에서 도메인으로 변환하는 방식으로 구현해봤습니다!
각각 장단점이 있다고 생각되지만, 여러 방법으로 구현해보는 것이 의미있을 것 같아서요!

그 외에는 미션에서 제공된 API스펙에 따라 맞춰 구현했습니다.
서버에 HTTP요청을 보내는 클라이언트 입장에서 의도된 결과가 도출되는지 e2e테스트도 작성해봤어요.

많이 배우고 싶습니다! 리뷰 잘부탁드려요!

2022-05-05 04:14 UTC, ddu0422 requested changes
안녕하세요 알렉스! 만나서 반가워요 미르예요 ㅎ_ㅎ

1, 2단계 미션 빠르게 구현해주셨네요 !_!
간단한 코멘트 남겨드렸으니 확인해주시면 감사하겠습니다 !

궁금한 점은 언제든지 코멘트 남겨주시거나 DM주세요 ㅎ_ㅎ
어린이날 즐겁게 보내세요 !

2022-05-05 04:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +    @ExceptionHandler({IllegalArgumentException.class, IllegalStateException.class, NoSuchElementException.class})
Exception이 늘어난다면, 해당 라인이 계속 수정되지 않을까요?
좋은 방법이 없을까요? 🤔

2022-05-05 04:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
정적 팩토리 메서드를 사용하여 의도를 명확하게 나타내는 건 어떨까요?

2022-05-05 04:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +        final long id = Objects.requireNonNull(keyHolder.getKey()).longValue();
올바른 예외처리일까요?
keyHolder.getKey()가 null인 경우 어떤 에러가 발생할까요?

2022-05-05 04:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/LineService.java
> +        }
API를 이용하지 않고 DB에 접속해서 insert를 하는 경우 같은 노선 이름으로 들어갈 수 있지 않을까요?
후자의 경우라면 어떤 방식으로 처리해야할까요?

2022-05-05 04:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/LineService.java
> +        lineDao.update(new LineEntity(newLine));
있으면 수정할 수 있고 없으면 에러가 발생하는 로직이군요 !
[자바 9에서 추가된 Optional 기능](https://www.daleseo.com/java9-optional/)을 사용해보면 어떨까요?

2022-05-05 04:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +    public ResponseEntity<String> clientError(final Exception exception) {
이름은 clientError지만, 현재 발생하는 에러는 서버에서 발생하는 내용이 아닐까요?

2022-05-05 04:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/controller/LineController.java
> +                new LineResponseDto(newLine.getId(), newLine.getName(), newLine.getColor(), new ArrayList<>());
1, 2단계에서 제공하는 API Response와 다른 값을 반환하지 않을까요?

2022-05-05 04:14 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/LineService.java
> +    public Line register(final String name, final String color) {
이전 미션에서 적용한 @<!-- -->Transaction을 적용하지 않은 특별한 이유가 있을까요?

2022-05-05 04:14 UTC, ddu0422 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
노선을 생성하는 로직이 여러군데에서 사용하고 있군요 !
중복 제거를 해보는 건 어떨까요?

2022-05-05 04:14 UTC, ddu0422 commented on src/test/java/wooteco/subway/mockDao/MockLineDao.java
> +        findById(id).ifPresent(lineEntity -> store.remove(lineEntity));
Method Reference를 활용해보는건 어떨까요?

2022-05-05 15:14 UTC, yxxnghwan commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +    @ExceptionHandler({IllegalArgumentException.class, IllegalStateException.class, NoSuchElementException.class})
예외마다 핸들러 메서드를 분리했습니다. 예외가 새로 추가된다면 핸들러 메서드를 새로 정의하는 방식으로 문제를 해결할 수 있을 것 같아요!

2022-05-05 15:16 UTC, yxxnghwan commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
`createWithoutId()`라는 정적 팩토리 메서드를 정의해서 네이밍으로 id필드가 없는 객체를 생성한다는 의미를 담아봤습니다!😁

2022-05-05 15:18 UTC, yxxnghwan commented on src/main/java/wooteco/subway/repository/dao/JdbcLineDao.java
> +        final long id = Objects.requireNonNull(keyHolder.getKey()).longValue();
keyHolder.getKey()가 null인 경우 그냥 NullPointerException이 발생하고 예외 핸들링이 전혀 안될 것 같네요 ㅠㅠ
따로 null인지 확인하는 분기문을 추가했습니다.

2022-05-05 15:41 UTC, yxxnghwan commented on src/main/java/wooteco/subway/service/LineService.java
> +        }
해당 어플리케이션을 거치치 않고 DB에 직접 접근해서 insert 하는 경우는 name컬럼을 유니크 키로 설정해둔 것으로 방지할 수 있을 것 같은데요,

예외 처리방식에서 유니크 키를 중복해서 넣었을 경우 발생하는 `DuplicateKeyException`을 캐치해서 핸들링하는 방법과 먼저 해당 이름으로 조회해보고 있으면 예외를 발생시키는 방법을 고민했는데, 전 후자가 더 낫다고 판단했어요.

이유는 DuplicationKeyException을 캐치할 경우 Service 레이어에서 핸들링할 경우 DB에서 발생하는 예외를 인지해야하는 상황이 되는 것이 싫었고, Dao에서 예외를 핸들링 한다면 서비스가 DB에서 발생하는 예외를 모르게할 순 있지만 서비스의 어떤 로직이 실행될 때 예외가 발생했는 지 알 수가 없기 때문에 에러 메시지를 친절하게 작성할 수가 없었습니다.

2022-05-05 15:42 UTC, yxxnghwan commented on src/main/java/wooteco/subway/service/LineService.java
> +        lineDao.update(new LineEntity(newLine));
Optional의 `ifPresentOrElse()`메서드를 사용해서 리팩토링 했습니다! 감사합니다!

2022-05-05 15:43 UTC, yxxnghwan commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +    public ResponseEntity<String> clientError(final Exception exception) {
커스텀 예외를 정의하고 예외마다 핸들링 메서드를 나누면서 문제를 해결해봤는데, 피드백 부탁드립니다!

2022-05-05 15:51 UTC, yxxnghwan commented on src/main/java/wooteco/subway/controller/LineController.java
> +                new LineResponseDto(newLine.getId(), newLine.getName(), newLine.getColor(), new ArrayList<>());
1,2단계에서는 stations를 받지 않게 스펙이 기재돼있기 때문에 stations필드는 제거했습니다! 추후 3단계에서 다시 추가할게요!

2022-05-05 15:52 UTC, yxxnghwan commented on src/main/java/wooteco/subway/service/LineService.java
> +    public Line register(final String name, final String color) {
API스펙에 맞춰 개발하는 것과 테스트만 신경쓰다 빼먹었네요! 추가했습니다!

2022-05-05 15:52 UTC, yxxnghwan commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
메서드 분리를 통해 노선을 생성하는 로직과, 지하철역을 생성하는 로직의 중복을 제거했어요!

2022-05-05 15:53 UTC, yxxnghwan commented on src/test/java/wooteco/subway/mockDao/MockLineDao.java
> +        findById(id).ifPresent(lineEntity -> store.remove(lineEntity));
피드백 반영하여 변경했습니다!

2022-05-05 15:55 UTC, yxxnghwan commented
안녕하세요 미르!
코멘트에 달아주신 피드백 반영해서 다시 리뷰요청 드립니다!
이번에도 잘 부탁드려요!

2022-05-06 12:29 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/LineService.java
> +        }
아하 unique를 못봤었네요 :)

저는 오히려 Service Layer이기 때문에 `DuplicateKeyException`를 사용해도 괜찮다고 생각해요. 
저는 Service Layer가 Domain이 오염되지 않도록 캡슐화하여 Domain 순서 보장을 해주고 기술적인 내용(Transaction 등)을 처리하는 역할이라고 생각하기 때문이예요.

(JPA를 사용할 때는 DataIntegrityViolationException를 사용해야합니다. H2도 같은 에러를 발생하기 때문에 DataIntegrityViolationException를 추천드려요.)

```java
try {
    final LineEntity lineEntity = new LineEntity(Line.createWithoutId(name, color));
    final LineEntity savedLineEntity = lineDao.save(lineEntity);
    return new Line(savedLineEntity.getId(), savedLineEntity.getName(), savedLineEntity.getColor());
} catch (DataIntegrityViolationException e) {
    throw new DuplicateNameException("[ERROR] 이미 존재하는 노선 이름입니다.");
}
```
와 같이 작성한다면 에러 메시지를 친절하게 작성할 수 있지 않을까요?

2022-05-06 12:34 UTC, ddu0422 commented on src/main/java/wooteco/subway/controller/ExceptionAdvice.java
> +    public ResponseEntity<String> clientError(final Exception exception) {
RuntimeException을 상속받는 CustomException을 만든 후, CustomException을 활용한다면 ExceptionHandler를 줄일 수 있을 것 같아요.

```
RuntimeExceptoin -> CustomException (HttpStatus, Message) -> DuplicateNameException
                                                          -> NotFoundStationException (NoSuchElementException 대신 사용)
```

2022-05-06 12:37 UTC, ddu0422 approved these changes
안녕하세요 알렉스 ! 미르예요 :)

빠르게 피드백 반영해주셨네요 ㅎ_ㅎ 이만 머지해도 될 것 같아서 이만 머지하겠습니다.
몇가지 코멘트 남겼는데 더 많은 대화를 나누어 보고 싶어요 😄 

3단계까지 화이팅이예요 🔥

2022-05-06 12:37 UTC, merged