[Spring 지하철 노선도 - 1,2단계] 썬(윤선용) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #185
Opened 2022-05-04 03:21 UTC by syoun602

안녕하세요 핀!
이번 지하철 노선도 미션 리뷰를 받게된 썬입니다. 😎

이번 미션에서는 주어진 API 스펙에 맞게 요청과 응답을 하도록 만들어봤습니다.
1단계에서는 스프링 빈 주입없이 직접 객체를 관리해본 뒤, 2단계에서는 직접 관리하던 객체들을
스프링 컨테이너가 관리하도록 변경해봤는데, 진짜 편리하구나를 느낄 수 있었습니다!.
해당 과정에서 E2E 테스트, 즉 사용자 입장에서 사용자가 사용하는 상황을 가정하고 테스트해봤는데, 아직 익숙하지 않아서
제대로 작성한 것이 맞는지 모르겠네요. 😅
그 외에도 Mockito 라이브러리를 사용하여 Dao를 Mock 객체로 사용해봤는데,
제대로 작성한게 맞는지 궁금합니다!

리뷰 잘 부탁드리겠습니다!

2022-05-04 03:23 UTC, syoun602 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    }
`Mockito` 라이브러리를 사용할 때, 반환 값이 없는 `delete`나 `update`의 경우에 어떻게 테스트해야 할지 모르겠습니다. 이런 방식으로 한번만 실행된다는 것만을 확인하는 방법 외에는 없을까요?

2022-05-06 00:47 UTC, lalize requested changes
안녕하세요 썬 ☀️
1, 2단계 구현 잘해주셨네요 👍 
몇가지 리뷰 남겼으니 확인 부탁드릴게요~
궁금한 점 있으시면 편하게 DM 주셔도 좋아요~

2022-05-06 00:47 UTC, lalize commented on docs/README.md
> +    - [ ] Service Layer 추가
👀

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/domain/Line.java
> +    public Line() {
이 생성자는 어디에 사용되나요?

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
주 생성자/부 생성자를 나눠보면 어떨까요?
클래스내 다른 생성자를 호출하는 방법으로 this 키워드를 활용할 수 있어요 :)

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/dto/LineRequest.java
> +    public Line toEntity() {
👍

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/dto/LineResponse.java
> +    public static LineResponse from(final Line line) {
👍

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/service/LineService.java
> +    @Autowired
생성자가 1개인 경우 `@Autowired`를 생략할 수 있어요 :)

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/ui/ControllerAdvice.java
> +}
* `IllegalArgumentException`, `NullPointerException` 예외가 항상 클라이언트의 잘못된 요청으로 인해 발생한다고 확신할 수 없을 것 같은데 어떻게 생각하시나요?
* 표준 예외 객체의 메시지를 가공 없이 응답으로 내리면 어떤 문제가 생길 수 있을까요?

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/ui/LineController.java
> +@RequestMapping("/lines")
👍

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @PostMapping()
```suggestion
    @PostMapping
```

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/ui/LineController.java
> +        final LineResponse lineResponse = LineResponse.from(newLine);
Service가 Request를 받고 Response를 반환하면 어떨까요?

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
produces는 어떤 역할을 하나요?

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
전체를 조회해야만 확인할 수 있을까요?
DB에 저장된 데이터가 계속해서 늘어나면(100만개, 1000만개, ...) 어떤 문제가 발생할 수 있을까요?

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/service/LineService.java
> +        validateExist(id);
존재하는지 확인하고 삭제해야 하는 이유가 있을까요?

2022-05-06 00:47 UTC, lalize commented on src/main/java/wooteco/subway/service/LineService.java
> +        lineDao.update(id, newLine);
DB에 바로 덮어 씌우는 게 아닌 id에 해당하는 Line 객체를 가져와서 도메인 로직(line.update(...))을 수행하여 DB에 반영해야 하지 않을까요?

2022-05-06 00:47 UTC, lalize commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    }
지금처럼 테스트 케이스에 해당하는 로직을 정상적으로 탔는지 확인하는 거면 충분하지 않을까요?
mocking을 제외한 서비스 로직은 모두 테스트 했다고 볼 수 있을 것 같아요.

2022-05-06 00:47 UTC, lalize commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        params.put("color", "bg-red-600");
LineRequest를 활용해보면 어떨까요?

2022-05-06 03:52 UTC, syoun602 commented on docs/README.md
> +    - [ ] Service Layer 추가
허걱... 다했다는 생각에 깜빡하고 업데이트를 안했네요ㅜㅜ 바로 반영했습니다!

2022-05-06 03:55 UTC, syoun602 commented on src/main/java/wooteco/subway/domain/Line.java
> +    public Line() {
앗 사용되지 않는 생성자는 전체적으로 제거했습니다!

2022-05-06 04:10 UTC, syoun602 commented on src/main/java/wooteco/subway/service/LineService.java
> +    @Autowired
앗... 인지하고 있던 부분인데 아무 생각없이 어노테이션을 붙였네요.. 놓친 곳이 있는지 확인해보고 정리했습니다!

2022-05-06 04:20 UTC, syoun602 commented on src/main/java/wooteco/subway/ui/ControllerAdvice.java
> +}
표준 예외 객체의 메시지를 가공없이 응답으로 내린다면 서버측에서 어떤 오류가 발생하든 클라이언트에 무조건적으로 전달됩니다. 이때, 만약 주요 비즈니스 로직에 대한 내용이 포함되어 있다면 로직이 노출될 위험이 있을 것 같습니다. 
또한, 사용자 입장에서 무슨 오류인지 인지하기 힘들 것 같습니다. 하여, 조금 더 사용자 친화적인 예외 메시지로 가공한 후 던져줌으로써 현재 어떤 이유로 동작하지 않는지 알려주는 것이 좋을 것 같다는 생각을 해봤습니다.

2022-05-06 04:24 UTC, syoun602 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @PostMapping()
앗 생락해도 되는 부분인데 넣어놨었네요! `Controller` 전반적으로 또 있는지 살펴보고 제거했습니다!

2022-05-06 04:35 UTC, syoun602 commented on src/main/java/wooteco/subway/ui/LineController.java
> +        final LineResponse lineResponse = LineResponse.from(newLine);
해당 부분에 대해서는 저 또한 많이 고민해봤는데요! 저는 다음과 같은 이유로 현재는 `Controller`에서 `DTO`를 변환하도록 작성했습니다.
1. `Controller`가 `View`와 통신하는 목적을 가지고 있으므로 해당 책임에 따라 `DTO`를 생성한다.
2. 여러 종류의 `Controller`가 존재할 때, 같은 `Service` 메서드를 불러오더라도 필요에 따라 다른 `ResponseDto`를 반환해야할 수 있으므로 서비스에서 도메인을 반환한다.
3. `Service` 레이어가 "핵심" 로직만을 담아야 하는데 모든 메서드에서 필요에 따른 `DTO`로의 변환 로직을 가진다면 자칫 무거워질 수 있다.
4. `Controller`에서 `Dto`로 변환해서 넘겨준다면 `Service`가 컨트롤러에 의존하게 된다.

다만, 이에 대한 단점도 있을 것 같습니다.
1. `Controller`가 무거워질 수 있다.
2. 핵심 도메인이 `View`단까지 넘어와야 한다. 즉, 도메인에 대한 의존성이 높아진다.

등이 있을 것 같습니다. 다만, 그 단점이 앞서 나열한 장점보다 리스크가 더 적다고 생각해서 해당 방식을 이용했습니다. 이에 대한 해결책으로 `Assembler`를 도입해 `Dto`와 관련된 모든 로직을 담당하는 클래스를 생성하는 것도 본 적이 있는데, 그 정도 설계까지는 필요하지 않다고 생각해서 지금처럼 작성했습니다! 혹시 핀은 이에 대해서 어떻게 생각하시나요?

2022-05-06 04:41 UTC, syoun602 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
`produces`는 생산 가능한 미디어 타입의 목록을 지정하는 걸로 알고 있습니다. 즉, 생산(반환)하는 데이터 타입을 강제함으로써 오류 상황을 줄일 수 있다는 장점이 있습니다. 현재의 경우 서버가 클라이언트에게 JSON을 반환하겠다는 것을 명시하고 있습니다!

그와 반대로 `consumes`는 받는 데이터에 대한 타입을 정의할 때인데, 해당 uri를 호출하는 쪽에서 헤더에 보내는 데이터가 무엇인지 명시하게 합니다. 이를 통해 잘못된 데이터 타입이 들어오거나 나가는 것을 방지할 수 있다는 장점이 있습니다.

2022-05-06 04:47 UTC, syoun602 commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
적용했습니다!

2022-05-06 08:13 UTC, syoun602 commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
다시 확인해보니 `select`문으로도 충분히 가능할거 같네요! `select exists` 를 활용해서 존재여부만을 확인하는 쿼리를 날리도록 변경했습니다. 

전체를 조회했을 때의 문제점은 다음과 같습니다. 현재 방식은 DB에 저장된 모든 데이터를 불러와서 name으로 매핑한 후  같은 이름이 존재하는 지 여부를 확인합니다. 이렇게 된다면 데이터가 방대해졌을 때, 불필요한 데이터를 모두 불러와서 처리하므로 서버에 부하가 발생해 처리 속도가 느려질 가능성이 있을 것 같습니다.

2022-05-06 08:17 UTC, syoun602 commented on src/main/java/wooteco/subway/service/LineService.java
> +        validateExist(id);
만약 존재하지 않는 데이터를 삭제하려고 한다면 클라이언트 측의 잘못이라고 판단했습니다. 서비스의 `delete`에서 검증을 하지 않아도 예외는 발생하지 않지만, 명백히 잘못된 요청임을 클라이언트 측에 알려주기 위해 추가했습니다.

혹시 보통 현업의 경우에는 어떤 방식을 사용하는지 알 수 있을까요? 이 부분에 대해서 핀은 어떻게 생각하시는지 궁금합니다!!

2022-05-06 08:51 UTC, syoun602 commented on src/main/java/wooteco/subway/service/LineService.java
> +        lineDao.update(id, newLine);
도메인 자체에 로직이 존재하지 않고 있어서 `Response`를 객체로 만들어 그냥 덮어씌우도록 했었습니다. 😢 저도 핀의 말씀해주신 방법으로 수정하는게 맞다고 생각되어 변경했습니다! 근데 현재의 방식을 사용할 시, 그저 수정자를 통한 변경과 같이 느껴졌는데 이럴 경우 캡슐화가 깨질 수 있는건가요?

2022-05-07 07:13 UTC, syoun602 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        params.put("color", "bg-red-600");
전체적으로 테스트에서 `Request`를 사용하도록 변경했습니다!

2022-05-07 07:46 UTC, syoun602 commented on src/main/java/wooteco/subway/ui/ControllerAdvice.java
> +}
`IllegalArgumentException`, `NullPointerException`이 항상 클라이언트의 오류임을 보장할 수 없다고 생각합니다. 자바 라이브러리 내에서도 해당 예외가 발생할 수 있다는 것을 인지하고 `ClientRuntimeException` 을 추가했습니다. 이를 통해 클라이언트의 잘못된 요청을 따로 처리하도록 수정했고 나머지 예외사항들은 서버 내부의 오류임을 나타내도록 변경했습니다!

2022-05-07 07:47 UTC, syoun602 commented
안녕하세요 핀! 두번째 리뷰 요청 남깁니다!
전반적인 변경사항은 이전의 코멘트의 답글로 남겨놨습니다 감사합니다!

2022-05-08 08:23 UTC, lalize approved these changes
안녕하세요~ 썬!
리뷰 반영 잘해주셨어요~
간단히 리뷰 남겼으니 다음 단계에서 진행해주세요!

2022-05-08 08:23 UTC, lalize commented on src/main/java/wooteco/subway/ui/LineController.java
> +    public ResponseEntity<LineResponse> createLine(@RequestBody final LineRequest lineRequest) {
bean validation으로 요청 값에 대한 유효성 검사를 해보면 어떨까요?

2022-05-08 08:23 UTC, lalize commented on src/main/java/wooteco/subway/ui/LineController.java
> +        final LineResponse lineResponse = LineResponse.from(newLine);
많은 고민을 하셨군요 💯  지금 구조도 충분히 좋기 때문에 그대로 진행해주셔도 무방해요!

>Assembler를 도입해 Dto와 관련된 모든 로직을 담당하는 클래스를 생성하는 것도 본 적이 있는데, 그 정도 설계까지는 필요하지 않다고 생각해서 지금처럼 작성했습니다! 혹시 핀은 이에 대해서 어떻게 생각하시나요?

Assembler는 Dto 정적 팩토리 메서드를 모아놓은 유틸리티 클래스로 보이는데(제가 잘못 알고 있는 거면 코멘트 주세요!) 이것을 도입한다고 장점은 유지하고 단점은 해결해줄 수 있는 게 맞나요?

---

서비스도 애플리케이션 서비스와 도메인 서비스로 나눌 수 있는데요. 두 서비스의 차이를 학습해보시면 좋을 것 같아요.
해당 내용이 DDD(도메인 주도 설계)에서 나와서 관련 내용이 나올 텐데 서비스 차이만 보시고 나머지는 스킵해주세요. (지금보면 주화입마에 빠질 수 있어요!)

LineSerivce, StationService가 애플리케이션 서비스에 가깝다고 생각되기 때문에 dto를 반환해도 무방하다고 생각하는 입장입니다 ㅎㅎ

2022-05-08 08:23 UTC, lalize commented on src/main/java/wooteco/subway/domain/Line.java
> +        Validator.requireNonNull(color);
도메인 레벨의 예외를 던지는 게 아닌 애플리케이션 레벨의 예외를 던지는 것 같아요.
레벨에 맞는 예외를 던져야 하지 않을까요?

2022-05-08 08:23 UTC, lalize commented on src/main/java/wooteco/subway/service/LineService.java
> +        validateExist(id);
비즈니스적으로 꼭 필요한 부분이 아니라면 쿼리를 수행하는 것을 최대한 지양하고 있습니다!

2022-05-08 08:23 UTC, lalize commented on src/main/java/wooteco/subway/ui/ControllerAdvice.java
> +    }
💯

2022-05-08 08:24 UTC, merged