[Spring 지하철 노선도 - 1,2단계] 라쿤(이병훈) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #198
Opened 2022-05-04 06:27 UTC by nbalance97

안녕하세요 토니😀 만나뵙게 되어 굉장히 반갑습니다ㅎㅎ

이번 미션에서는 Spring Bean을 사용하지 않았다가, 사용하도록 변경해 보면서 
Spring Bean의 편리성을 뼈저리게 체감해보는 기회가 되었던 것 같아요😂 

코드리뷰를 위해 바쁜 시간 내어주셔서 감사합니다🙇‍♂️

2022-05-04 13:52 UTC, toneyparky requested changes
안녕하세요 라쿤!

리뷰 완료했습니다~! 구조를 깔끔하게 잘 짜주셔서 리뷰하기 수월했어요!

요구사항 측면에서 조금 부족한 부분이 보여서 리뷰 남겼어요. 추가로 질문을 남겼으니 확인 후 대댓글 부탁드릴게요!

언제든 DM은 환영이에요~!!! 남은 하루 잘보내세용!

2022-05-04 13:52 UTC, toneyparky commented on src/main/java/wooteco/subway/dao/LineDao.java
> +package wooteco.subway.dao;
라쿤~ `README.md` 파일을 활용하여 요구사항에 대해서 정리하신 내용은 따로 커밋하지 않으신걸까요~?

2022-05-04 13:52 UTC, toneyparky commented on src/main/java/wooteco/subway/dao/LineDao.java
> +@Component
`@Component` 와 `@Repository` 의 차이에 대해서 공부해보죠! 

https://www.baeldung.com/spring-component-repository-service

2022-05-04 13:52 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    private final LineService lineService;
커밋을 확인해보니 Dao 를 활용하시다가 Service를 활용하시도록 수정하셨더라구요!

이런 선택을 내리신 이유가 있을까요?

2022-05-04 13:52 UTC, toneyparky commented on src/main/resources/application.yml
> +  port: 9090
>노선 관리 API에 대한 스펙은 [API 문서v1](https://techcourse-storage.s3.ap-northeast-2.amazonaws.com/d5c93e187919493da3280be44de0f17f#Line)를 참고

<img width="698" alt="image" src="https://user-images.githubusercontent.com/37579660/166692818-213bb2e2-e38d-444f-b6f7-ba770f9176e7.png">

요구사항에 따르면 8080 포트를 사용해야 하는군요! 라쿤이 9090을 사용하신 특별한 이유가 있을까요?

2022-05-04 13:52 UTC, toneyparky commented on src/main/resources/schema.sql
> +    name varchar(255) not null unique,
unique를 통해 DB 단에서 프로그램의 요구사항을 보장해주신 부분이 좋네요 👍

2022-05-04 13:52 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +public class LineAcceptanceTest extends AcceptanceTest {
라쿤은 인수 테스트의 목적이 뭐라고 생각하시나요? 

어떤 내용을 검증하려고 `LineAcceptanceTest`를 작성하셨을지 궁금해요!

2022-05-04 13:52 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
이런 중복된 로직은 메서드로 분리해봐도 좋겠어요! 

지금처럼 세부 구현을 늘어놔도 좋지만 가독성 있는 이름의 메서드로 분리한다면 테스트를 읽기 쉬워질거에요.

2022-05-04 13:52 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    @DisplayName("특정 노선을 업데이트한다")
특정 노선이 없을 경우에 대해서도 검증해주는건 어때요?

라쿤이 생각하시는 인수테스트에서는 이런 상황에 대해서 검증하지 않아도 될까요?

2022-05-04 13:52 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +    @Transactional
`@Transactional`이 테스트 코드에서 사용되면 어떤 역할을 하는가요 ?

2022-05-04 13:52 UTC, toneyparky commented on src/test/java/wooteco/subway/dao/LineDaoTest.java
> +        lineDao.save(new Line("신분당선", "red"));
Dao 테스트에 사용되는 색상과 인수 테스트에서 사용되는 색상의 형식이 다르네요..! 

제가 처음 이 프로젝트를 본다면 두가지 방식의 색상 중 어떤 형식으로 작성해야하는지 고민이 될거 같아요!

2022-05-04 13:52 UTC, toneyparky commented on src/test/java/wooteco/subway/dao/LineDaoTest.java
> +        );
이런 SQL 문을 파일로 관리하는 방법을 학습해보고 적용해볼까요?

2022-05-04 13:52 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    public ResponseEntity<LineResponse> createLine(@RequestBody final LineRequest lineRequest) {
현재 이름이 아니라 color만 동일한 노선을 생성할 경우에 예외가 발생하네요 😭

2022-05-04 13:52 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    public ResponseEntity<List<LineResponse>> getLines() {
[요구사항](https://techcourse-storage.s3.ap-northeast-2.amazonaws.com/d5c93e187919493da3280be44de0f17f#_%EC%A7%80%ED%95%98%EC%B2%A0%EC%97%AD_%EB%AA%A9%EB%A1%9D)에 맞지 않는 정보까지 반환하고 있어요..!

요구사항 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/37579660/166694670-8bd2cd0a-5d6d-4f48-9c33-6ddc1470909e.png">


실제 반환 
```

[
    {
        "id": 1,
        "name": "신분당선1",
        "color": "bg-red-600",
        "stations": [] // 불필요한 정보
    },
    {
        "id": 2,
        "name": "신분당선3",
        "color": "bg-red-601",
        "stations": []
    },
    {
        "id": 3,
        "name": "신분당선13",
        "color": "bg-red-6012",
        "stations": []
    }
]
```

2022-05-04 13:52 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
두가지 질문을 드릴게요!

1. 모든 `RuntimeException`이 BadRequest일까요?
2. 만일 `Exception`이 발생한다면 어떤 응답이 보내지게 될까요?

2022-05-04 13:52 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/StationController.java
> +
라쿤이 스프링의 기능을 활용하여 객체 관리를 위임하면서 편의성을 뼈져리게 느끼셨다고 PR 본문에 적어주셨네요 😂

어떤 부분에서 편의성을 느끼셨는지 살짝 들어볼 수 있을까요?

2022-05-04 14:04 UTC, nbalance97 commented on src/main/resources/application.yml
> +  port: 9090
포트 8080이 로컬 환경에서 이미 사용중이어서 포트를 임의로 다른 포트를 사용하도록 변경했었습니다😅

2022-05-04 14:05 UTC, nbalance97 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    public ResponseEntity<LineResponse> createLine(@RequestBody final LineRequest lineRequest) {
페어를 하면서 이 부분을 고민했었는데, 지하철 노선도에서 겹치는 색의 노선이 없는 것 같았습니다!

따라서 노선의 경우는 color 자체도 중복이 되면 안된다고 생각이 되어 예외처리를 시켜주었습니다😅

2022-05-04 14:11 UTC, nbalance97 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +package wooteco.subway.dao;
앗.. 생각해 보니 구현 사항 작성이 누락되었었네요🙏

2022-05-04 14:46 UTC, nbalance97 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +@Component
기존에는 Repository와 Component 어노테이션이 실제로는 차이가 없기도 하고 Repository 어노테이션은 Repository 계층에서 사용하는 거라고 생각해서 Component 어노테이션을 붙였었습니다ㅎㅎ

Repository 어노테이션은 데이터 베이스 저장소 계층에서 사용하는 거이므로 DAO layer에서는 Repository 어노테이션이 더 적합하겠네요😅

2022-05-05 22:07 UTC, nbalance97 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    private final LineService lineService;
리팩토링 과정에서 Controller에서 Dao를 가지고 있으면 Controller이 비교적 너무 많은 일을 한다고 느껴져서 

Service를 활용하도록 구현하였습니다😀

2022-05-05 22:23 UTC, nbalance97 commented on src/main/java/wooteco/subway/ui/StationController.java
> +
우선 저같은 경우는 관리 대상이 되는 클래스를 Static으로 여는 방식을 택했었는데, 
Controller에서 Dao를 가지고 있는 구조여서 단순히 Dao를 Static으로 여는 방식만 택해도 쉽게 구현할 수 있었지만,

Service로 분리를 해주면서 Dao와 Service를 모두 Static으로 열어두는 것은 사용해야 하는 클래스 이외의 클래스에서도 접근할 수 있는 문제점이 생길 것 같았습니다. 또한 주입으로 코드를 짜기에는 Dao -> Service -> Controller에 각각의 객체를 직접 생성하고 주입해주면서 헷갈리게 느끼는 부분도 많아 문제가 생길 것 같았고, 주입해주는 역할은 어떤 클래스에서 해주어야 하는지도 애매하게 느껴졌습니다😥

이러한 과정을 고민할 필요 없이 스프링이 주입을 해주니 온전히 구현에 초점을 맞출 수 있어서 편의성을 느꼈던 것 같습니다😀

2022-05-05 22:31 UTC, nbalance97 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +public class LineAcceptanceTest extends AcceptanceTest {
인수 테스트의 목적은 제공하는 Api가 요구사항대로 정상적으로 동작하는지 테스트하는 것이 목적이라고 생각합니다😅

저는 Api가 정상적으로 동작하는지 테스트하려고 했었는데.. 토니의 리뷰들을 보니 
제가 인수 테스트를 정상적인 흐름만을 고려하고, 예외 흐름에 대해서는 테스트하지 않았던 것 같아요😥

2022-05-05 22:54 UTC, nbalance97 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
토니의 조언대로 Line 생성 부분 메소드 분리를 해보니까 훨씬 코드 길이도 짧아지고 가독성도 좋아지네요 😱

2022-05-06 00:33 UTC, nbalance97 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    @DisplayName("특정 노선을 업데이트한다")
인수 테스트인데 누락된 테스트가 많이 있었네요..😥 

특정 노선이나 역이 없는 경우에 대한 테스트를 추가했습니다😊

2022-05-06 00:35 UTC, nbalance97 commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +    @Transactional
테스트 코드에서의 Transactional은 롤백의 역할이 된다고 생각했는데, 이번에 인수 테스트 관련해서 찾아보니 Transactional이 사용이 안된다고 학습했습니다🙂

이는 Transactional을 따로 제거해 주었습니다🙂

2022-05-06 00:44 UTC, nbalance97 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
모든 RuntimeException이 BadRequest인 것은 아닌 것 같습니다😅
에러의 경우는 무조건 4xx 코드를 반환해야 한다는 생각이 있었는데 이번에 HTTP Status code를 찾아보면서 NoSuchElementException의 경우는 BadRequest 보다는 noContent 상태 코드가 더 직관적인 것 같아 noContent 상태 코드를 사용하도록 변경하였습니다.

Exception이 발생하는 경우에 대해서는 Exception의 경우는 명시적으로 try-catch를 해주어야 한다고 생각하여 RuntimeException이 checked Exception의 최상위라고 생각하여 RuntimeException을 선택하였습니다😅

2022-05-06 03:51 UTC, nbalance97 commented on src/test/java/wooteco/subway/dao/LineDaoTest.java
> +        lineDao.save(new Line("신분당선", "red"));
이전까지는 테스트만 잘 되면 된다고 생각했었는데 토니의 말씀대로 테스트 코드를 일관된 방식으로 작성해야 하는게 맞는거 같아요😂

이 부분은 Color을 동일한 포매팅으로 변경하였습니다🙂

2022-05-06 04:24 UTC, nbalance97 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    public ResponseEntity<List<LineResponse>> getLines() {
앗.. 기존에 있는 DTO를 사용하려고 하다 보니 불필요한 정보도 같이 넘어갔네요😅

이 부분은 새로이 DTO를 구성하여 사용하도록 변경하였습니다!

2022-05-06 04:43 UTC, nbalance97 commented on src/test/java/wooteco/subway/dao/LineDaoTest.java
> +        );
`@Sql ` 어노테이션을 사용하여 SQL문을 파일로 빼서 관리하였습니다!! 😀

2022-05-06 04:48 UTC, nbalance97 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
또한 제가 작성한 예외에 대해서는 BadRequest, noContent 등 상태 코드를 써줄 수 있었는데, 이외의 예외에 대해서는 어떤 상태 코드를 반환해야 할까요..? 

애매하게 느껴져서 이 부분은 일단 InternalServerError 상태 코드를 반환하도록 구현 해 두었습니다😅

2022-05-06 11:20 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +        // given
여기에 given은 제거해도 될거 같네요!

2022-05-06 11:20 UTC, toneyparky commented on src/main/java/wooteco/subway/dao/LineDao.java
> +package wooteco.subway.dao;
크크 새로운 미션이라 설레서 까먹으셨군요! 3단계에는 꼭 작성해주세요! 

저도 현업에서 따로 노션이나 노트에 구현할 내용을 정리해둔답니다 😉

2022-05-06 11:20 UTC, toneyparky commented on src/main/java/wooteco/subway/dao/LineDao.java
> +@Component
네, 좀 더 명시적으로 표현할 수 있죠! 말씀해주신 예외 처리도 해주구요. 

학습하신 내용과 적용까지 확인했습니다 👍

2022-05-06 11:20 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    private final LineService lineService;
크.. 잘 리팩터링 해주셨네요! 이로써 컨트롤러는 요청을 받아서 비즈니스 로직을 수행하는 서비스에 요청을 전달하고 결과를 적절한 응답으로 보내는 역할만을 수행하게 되었어요!! 

추가로 컨트롤러에 domain 패키지에서 import한 클래스가 없음을 통해 컨트롤러와 도메인 간의 결합도 제거해주셨어요 💯

2022-05-06 11:20 UTC, toneyparky commented on src/main/resources/application.yml
> +  port: 9090
그렇군요~! 요구사항에 적혀있는 내용이기에 지켜주시면 좋았겠다는 생각이 들어서 여쭤봤어요!
9090을 사용하신 이유 이해했습니다~

2022-05-06 11:20 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +public class LineAcceptanceTest extends AcceptanceTest {
인수 테스트는 말 그대로 프로그램의 제작을 요청한 사람(혹은 회사)이 프로그램을 인수(최종 구매)할지 결정하는 데 검증 과정이에요. 
그렇기에 요구사항에 정상적으로 동작하는 경우와 더불어 예외 상황에 대해서도 알려줘야 요청자가 해당 상황을 이해할 수 있겠죠?
그리고 응답의 body도 검증해주신 부분 좋네요 😀

2022-05-06 11:20 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
적절한 분리는 가독성과 유지보수에 도움이 된답니다!

2022-05-06 11:20 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +    @Transactional
오호 좋네요~! 인수 테스트에서 해당 어노테이션은 왜 동작하지 않는지 이유도 찾아보셨을까요?! 댓글로 적어주세요 😎

2022-05-06 11:20 UTC, toneyparky commented on src/test/java/wooteco/subway/dao/LineDaoTest.java
> +        lineDao.save(new Line("신분당선", "red"));
코드를 작성하는 스타일이나 방법론은 많지만 핵심은 의도를 잘 표현하고 읽는 사람에게 혼동을 주지 않아야 한다고 생각해요. 테스트 코드에도 이와 같은 관점을 적용해주신다면 코드를 읽는 사람이 라쿤의 코드는 편하게 잘 읽힌다는 피드백을 줄거에요 🤓

2022-05-06 11:20 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    public ResponseEntity<LineResponse> createLine(@RequestBody final LineRequest lineRequest) {
그렇군요! 요구사항에 없던 부분이라 실수로 처리하셨을까하여 남겨봤어요. 

리드미에 정리해주셨더라면 이해하고 넘어갔겠네요! 확인했습니다~!

2022-05-06 11:20 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    public ResponseEntity<List<LineResponse>> getLines() {
네, 요구사항을 지켜서 개발하는 것은 중요해요. 본의 아니게 이번 리뷰에 여러번 강조를 드리는군요 

프론트 개발자가 요청한 스팩과 다른 결과물을 개발한다면 개발에 차질이 생기겠죠? 만일 현업이라면... 수정하는 동안 업무에 차질이 생길거에요.. 😇

2022-05-06 11:20 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
라쿤이 고민하고 작성하신 흔적이네요! 고생 많으셨어요 👍 

모든 Exception을 잡아서 Runtime이나 다른 예외로 바꿔서 보내준다면 Exception이 발생할 일이 없겠군요..! 

---

말씀주신 204 noContent에 대해서는 올바르지 않은 리팩터링 같아요. 

우선 200대 응답은 성공에 대한 응답인데 NoSuchElementException이 발생하는 경우는 요청 실패에 대한 응답이니까요. 오히려 사용자가 잘못 요청했기에 해당 예외가 발생했다는 의도로 기존 BadRequest가 좋다고 생각해요. 요건 다음 미션에서 수정해주세요!

---

라쿤이 예측 가능한 예외에 대해서는 지금처럼 ExceptionHandler로 예외를 잡도록 처리해주면 되요. 그리고 예측 가능하지만 자바나 스프링이 제공하는 예외로 충분하지 않을 때에는 커스텀 예외 클래스를 만들어서 처리하구요. 

하지만 적어주신 예측 가능하지 않은 예외에 대해서는 말씀하신대로 서버 내부의 에러라고 처리하고 500을 내려주는 지금의 방법도 괜찮다고 생각합니다!

2022-05-06 11:20 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/StationController.java
> +
Static은 다 열려있기에 말씀해주신 문제가 발생하네요! 클래스의 가시성에 대해서 고민하신 점이 좋아요! 

무작정 기술을 사용하기보다는 사용하기 전에는 어떤 문제/불편함이 있고 이를 기술로 어떻게 해결했는가를 고민해보면 좋겠어요. 지금도 잘 해주고 계시구요! 나중에 면접을 볼 때에도 도움이 될거에요 😬

2022-05-06 11:21 UTC, toneyparky approved these changes
안녕하세요 라쿤~! 

리뷰 반영하시느라 고생 많으셨어요. 학습을 요하는 리뷰가 많았는데 학습 후 적용도 잘 해주셨네요! 좋습니다.

질문에 대한 답변과 간단한 수정사항들 남겨봤어요. 다음 미션에서 처리 부탁드려요~!

이만 머지하겠습니다. 주말 잘 보내세용~

2022-05-06 11:21 UTC, merged

2022-05-06 13:54 UTC, nbalance97 commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +    @Transactional
@Transactional은 트랜잭션이 시작한 쓰레드에서 롤백을 시켜주기 때문에 단일 쓰레드에서만 동작한다고 해요🙂

인수 테스트의 경우 클라이언트와 서버가 각각 다른 스레드에서 실행되기 때문에 롤백이 되지 않는다고 합니다😎

2022-05-07 02:26 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +    @Transactional
이유를 잘 적어주셨어요 😃