[Spring 지하철 노선도 - 1, 2단계]  에덴(김성산) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #202
Opened 2022-05-04 06:56 UTC by leo0842

안녕하세요 토니! 에덴입니다.😄

이렇게 만나뵙게 되어 영광입니다!

이번 미션 잘 부탁드립니다!!🙇‍♂️

2022-05-04 14:17 UTC, toneyparky requested changes
안녕하세요 에덴~ 지하철 노선도 첫 미션의 리뷰어 토니입니다~

전체적으로 요구사항에 맞게 잘 구현해주셨네요! 눈에 보이는 수정 사항과 질문을 드렸으니 댓글로 답변 부탁드려요! 

시작이 좋네요! 궁금한 사항은 DM 부탁해요~~

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/application/LineService.java
> +public class LineService {
에덴! 서비스 로직에 대한 테스트 없이도 충분히 프로젝트 로직을 검증할 수 있을까요?

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/application/LineService.java
> +        lineDao.updateLineById(id, name, color);
기존에 존재하는 다른 노선의 이름으로 수정할 경우에 사용자는 어떤 경험을 할까요? 해당 상황에 맞는 적절한 예외를 통해 사용자가 당황하지 않도록 처리할 수 있을거 같아요.

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/dao/LineDao.java
> +@Repository
이 어노테이션은 `@Component`와 어떤 차이가 있을까요?

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    }
사용하지 않는 메서드가 있네요 😬

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Line.java
> +//    private int distance;
불필요한 주석은 제거해도 좋겠어요!

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @GetMapping(value = "/lines", produces = MediaType.APPLICATION_JSON_VALUE)
해당 어노테이션에 추가하신 `produces`는 어떤 옵션인가요?

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/StationController.java
> +    }
커밋을 확인해보니 컨트롤러에서 DAO를 직접 사용하시다가 Service를 사용하는 방향으로 수정하셨더라구요!

에덴이 이런 선택을 하신 이유가 궁금하네요 😀

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
에덴이 직접 객체를 관리하다가 스프링의 기능을 이용하여 관리하도록 수정하는 게 이번 미션이었죠!

개체 관리를 스프링에 위임하는 변화를 겪으며 어떤 생각이 드셨을지 궁금해요 😉

2022-05-04 14:17 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/SubwayExceptionController.java
> +public class SubwayExceptionController {
만일 서버 내부에서 Exception이 던져진다면 사용자는 어떤 메시지를 확인하게 될까요?

2022-05-04 14:17 UTC, toneyparky commented on src/main/resources/schema.sql
> +    name varchar(255) not null unique,
Unique를 활용하여 DB에서부터 요구사항을 지켜주신 점 좋습니다!

2022-05-04 14:17 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        assertAll(
assertAll을 활용하신 부분 좋네요!

2022-05-04 14:17 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
이런 반복되는 코드는 Fixture 혹은 메서드로 분리해도 괜찮을거 같아요.

2022-05-04 14:17 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
>  public class StationAcceptanceTest extends AcceptanceTest {
에덴은 인수 테스트를 어떤 목적으로 작성하셨나요? 에덴이 인수 테스트에서 검증하고 싶은 내용이 궁금하네요!

2022-05-04 14:17 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    @DisplayName("지하철 노선을 제거한다.")
인수테스트를 통해 사용자가 올바르게 요청하지 않은 사항에 대한 검증을 해주는건 어떻게 생각하시나요?!

예를 들면 생성 되지 않은 지하철의 식별자로 제거 요청을 보내는 경우가 있겠네요!

2022-05-07 16:42 UTC, leo0842 commented on src/main/java/wooteco/subway/ui/StationController.java
> +    }
처음 1단계에서는 기본적으로 주어지는 로직에서 큰 변화없이 진행해보려고 했어요! 그러다보니 1단계를 완료한 직후에는 Controller 가 비즈니스 로직도 가지고, 클라이언트와의 요청, 응답에 대한 책임도 가지고 점점 Controller 가 비대해지는 것을 느꼈습니다.

이에 따라 2단계를 진행할 때에는 서비스 레이어를 추가하여 기존에 Controller 에서 처리하던 비즈니스 로직을 서비스 레이어로 옮겨주었습니다. 그 결과 Controller 와 Dao 사이의 결합도도 줄일 수 있었고, 각각의 레이어의 책임을 조금 더 명확하게 할 수 있었습니다!

2022-05-07 16:49 UTC, leo0842 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
먼저 이번 1단계에서는 직접 객체의 의존성을 관리했다기 보다는, dao의 메서드를 static으로 사용했었습니다. 그 결과 객체지향적이지도 않고, 어디서든 부를 수 있다는 단점들이 눈에 보이기 시작했습니다. 
둘째로, static 으로 사용하지 않고 객체를 직접 관리하였다면, 서로 얽혀있는 복잡한 의존 관계를 관리하다가 실수가 발생할 수도 있고, 의존을 관리하는 데에 드는 리소스가 불필요하게 많아질 것 같다는 생각을 했습니다.

이에 따라 객체 관리를 어노테이션만으로 스프링에 위임하면서 객체 지향의 특징을 가지며 의존 관계를 편하게 관리할 수 있었습니다. 그리고 직접 관리할 때 드는 리소스를 비즈니스 로직에 쓸 수 있게 되어 조금 더 로직에 집중할 수 있었습니다!

2022-05-07 16:52 UTC, leo0842 commented on src/main/java/wooteco/subway/ui/SubwayExceptionController.java
> +public class SubwayExceptionController {
`서버 내부에서 Exception` 을 Checked Exception 으로 생각하고 말씀드리겠습니다!

직접 관리하던 IllegalArgumentException 이외의 RuntimeException 은 하나의 메서드로 모아 서버 에러를 던지게 했었지만 Checked Exception 까지는 생각하지 못하였습니다. 토니의 피드백을 보고 직접 테스트를 해보니 Checked Exception 은 전혀 잡지 못하고 의도하던 Response Entity 를 응답하지 못하는 것을 알았습니다. 이에 따라 Checked Exception 을 처리하기 위해 Exception 을 하나의 메서드로 모아 또 다른 예외 응답을 처리할 수 있도록 하였습니다!

2022-05-07 16:53 UTC, leo0842 commented on src/main/resources/schema.sql
> +    name varchar(255) not null unique,
앞으로도 DB에서부터 요구사항을 지키도록 구성하겠습니다!

2022-05-07 16:54 UTC, leo0842 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
토니의 피드백을 적용하여 반복되는 테스트용 객체와 메서드를 Fixture 로 분리해보았습니다!

그 결과 코드가 상당히 깔끔해졌고, 테스트가 의도하는 바를 더욱 쉽게 캐치할 수 있었습니다. 지적 감사드립니다!!

2022-05-07 16:56 UTC, leo0842 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    @DisplayName("지하철 노선을 제거한다.")
비즈니스 로직에서는 해당 예외 사항을 검증해주었는데, 테스트에서 해당 예외를 적용하지 않았었습니다 😢 

제거에서 발생하는 예외 뿐만 아니라 수정에서 발생하는 예외도 모두 테스트 케이스로 추가하였습니다. 지적 감사드립니다!

2022-05-07 17:04 UTC, leo0842 commented on src/main/java/wooteco/subway/application/LineService.java
> +public class LineService {
철저히 확인하지 않고 구현하는 데에만 집중하여 서비스 로직 테스트를 빠뜨렸습니다 😢 

서비스 로직 테스트를 작성하면서 여러 가지 방법에 대해 생각해보았습니다.

1. 서비스 레이어 테스트에서 DB까지 확인하는 방법
  - 해당 방법은 SpringBootTest 으로 모든 빈을 등록하고 실제 DB에까지 적용되는지 확인하는 방법으로 생각하였습니다. 
  - 하지만 먼저 인수테스트에서 서비스 레이어 이전인 컨트롤러 레이어에서 DB 까지 적용되는지 확인하는 테스트가 존재하기도 하고, 
  - 서비스 로직 단위 테스트로 적합하지 않다고 생각하여 해당 방법을 적용하지 않았습니다.

그렇다면 Dao 빈을 등록하지 않고 서비스 로직 테스트를 해야하는데
2. Dao 를 한 단계 추상화하여 인터페이스로 만들고 Mock 객체를 테스트 패키지에서 만들어 사용하는 방법
  - 해당 방법은 추상화를 위한 구조 변경이 불가피하기도 하고, 현재 단계에서는 테스트를 위한 추상화밖에 되지 않기 때문에 적용하지 않았습니다.
3. Mockito 라이브러리를 이용하여 Dao 를 Mock 객체로 생성하는 방법
  - gradle 로 Mockito 라이브러리 의존성을 추가해야 하기때문에 처음에는 지양했지만, 존재하는 라이브러리를 굳이 열심히 안 쓸 필요도 없다고 생각하였습니다. 이에 따라 의존성을 추가하고 Dao 를 Mock 객체로 생성하여 서비스 로직 테스트를 진행하였습니다.

2022-05-07 17:06 UTC, leo0842 commented on src/main/java/wooteco/subway/application/LineService.java
> +        lineDao.updateLineById(id, name, color);
`기존에 존재하는 다른 노선의 이름으로 수정할 경우` 의 예외 사항을 생각하지 못했습니다 ㅠㅡㅠ

토니의 피드백대로 수정시 `기존에 존재하는 다른 노선의 이름으로 수정할 경우` 에 대한 예외 사항을 추가하였습니다. 지적 감사드립니다!

2022-05-07 17:07 UTC, leo0842 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +@Repository
- `@Component`
-

2022-05-07 17:14 UTC, leo0842 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    }
1단계 때 사용하다가 2단계 때 사용처가 모두 없어졌는데 미처 지우지 못했습니다 😢  해당 메서드는 바로 제거하였습니다!

2022-05-07 17:15 UTC, leo0842 commented on src/main/java/wooteco/subway/domain/Line.java
> +//    private int distance;
3단계와 그 다음 미션에서 쓰일 예정으로 알고 있어서 남겨두었는데, 괜히 코드만 지저분해져 보이네요 😢  

피드백대로 해당 주석은 바로 제거하였고, 다음에 사용하게 될 때 추가하도록 하겠습니다!

2022-05-07 17:22 UTC, leo0842 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @GetMapping(value = "/lines", produces = MediaType.APPLICATION_JSON_VALUE)
`produces` 옵션은 매핑된 메서드로 오는 요청에 대한 __응답 미디어 타입__ 을 지정해주는 것으로, 해당 API 는 application/json 타입을 반환한다는 것을 명시하기 위해 사용하였습니다.

다만, Response Body 가 있는 API 의 경우, 해당 옵션 없이도 application/json 이 자동으로 설정되는 것을 확인하였고 이외에도 반환 타입이 ResponseEntity인 경우에도 application/json 이 자동으로 설정되는 것을 확인할 수 있었습니다.

2022-05-07 17:26 UTC, leo0842 commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
>  public class StationAcceptanceTest extends AcceptanceTest {
인수 테스트는 실제 운영 환경에서 사용될 준비가 되었는지 최종적으로 확인하기 위해, 사용자의 관점으로 수행하는 테스트입니다.

각각의 API 에 대해 처음의 요청부터 DB 까지 확인하고, 반환되는 응답까지 확인하는 End-to-End Test 의 특징을 지니고 있습니다. 

이에 따라 해당 API 가 어떤 목적으로 만들어지고, 어떤 기능을 하는지 확인할 수 있고, 해당 API 가 가지는 예외 사항들에 대해서도 모두 잘 작동되는지 검증하기 위해 인수 테스트를 작성하였습니다!

2022-05-08 00:25 UTC, toneyparky approved these changes
안녕하세요 에덴 좋은 아침이에요!

리뷰 반영 깔끔하게 해주셨네요! 제가 드린 질문에 대해서도 열심히 고민하시고 답변해주셔서 기분이 좋네요 😎

추가로 드릴 질문을 조금 남겼으니 확인 후 답변 부탁드려용~
그리고 수정하면 좋을 사항을 조금 남겼어요. 다음 단계 시작할 때에 반영 부탁드립니다!

이번 미션은 머지할게요! 고생하셨고 남은 주말 즐겁게 보내세요!

2022-05-08 00:25 UTC, toneyparky commented on src/test/java/wooteco/subway/application/StationServiceTest.java
> +    @Mock
`@Mock` 어노테이션 이외에 `@MockBean` 어노테이션이 있는데요, 둘의 차이는 무엇일까요? 댓글로 남겨주세요~!

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/StationController.java
>      public ResponseEntity<Void> deleteStation(@PathVariable Long id) {
사용자가 존재하지 않는 식별자를 가진 역으로 삭제 요청을 보낼 경우에는 어떤 상황에 마주할까요?

빠트리는 예외 사항이 있을 수 있기에 `README.md`에 최대한 잘 정리해보셔도 좋겠어요 😉

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/StationController.java
> +    }
`toStationResponse` 메서드가 인자로 받는 Station이 new인지 알 필요가 있을까요?

2022-05-08 00:25 UTC, toneyparky commented on src/test/java/wooteco/subway/application/LineServiceTest.java
> +}
파일의 마지막 라인에 공백이 없을 경우에는 깃헙에서 아래와 같은 경고를 보여주는데요, 왜 이런 경고를 보여주는지 확인해볼까요?

<img width="255" alt="image" src="https://user-images.githubusercontent.com/37579660/167276436-6194aac1-17d7-4907-828f-147d47c2badd.png">

2022-05-08 00:25 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    @DisplayName("기존에 존재하지 않는 지하철 노선 ID로 지하철 노선을 조회하면 에러를 응답한다.")
테스트의 DisplayName을 명시적으로 잘 써주셔서 테스트 내용을 파악하기 쉬워요 💯 

어떤 행위를 했을 때에 어떤 결과를 기대한다는 내용이 잘 표현되어있네요!

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/application/LineService.java
> +public class LineService {
에덴이 고민을 많이하고 리뷰를 반영해주셨네요!! 말씀주셨듯 통합 테스트 혹은 슬라이싱 테스트를 진행할 수 있죠! 통합 테스트는 다른 곳에서 진행하고 있기에 서비스 테스트에서는 굳이 진행하지 않아도 된다는 점에 동의합니다!

Dao를 처음부터 추상화해뒀다면 Mock 객체로 쉽게 바꿀 수 있었지만 그런 구조가 아니라 모키토를 사용하셨군요. 현업에서도 사용하는 라이브러리라 좋은 선택이라 생각해요! 다만 무분별한 모킹의 단점에 대해서는 차차 학습해보시면 좋겠어요 😊

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/application/LineService.java
> +        lineDao.updateLineById(id, name, color);
네, 보통 개발 요구사항이 내려오면 예외 상황에 대해서는 기획자께서 잘 명시해주시고 저희는 그에 따라 구현하면 되요. 하지만 100% 정확도를 보장할 수 없기에 개발자도 적극적으로 예외 상황을 확인하고 아이디어를 제안해야 한답니다! 

지금처럼 숨어있는 예외를 잘 파악해보죠! 3단계 구현하실 때에도 있을 수 있어요 😁

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/dao/LineDao.java
> +@Repository
에덴이 정리를 잘 해주셨어요! 레포지토리 어노테이션도 결국 컴포넌트 어노테이션의 하위에 있다는 점을 알고 계시면 충분할거 같아요!

다만 이름이 `@Repository`이기에 명시적으로 영속성 레이어의 빈임을 표현할 수 있다는 장점이 있죠! 적어주셨던 영속성 예외를 스프링의 예외로 변환한다는 기능도 있구요! 추가로 학습할 내용은 없어 보여요 👍 

---

소소한 팁 하나 전달할게요! 깃헙상에서 댓글이나 PR을 날릴 떄에 골뱅이가 들어가는 단어를 사용하면 백틱(`)을 이용하여 감싸주면 좋아요. 그렇지 않으면 아래의 이미지와 같이 깃헙 사용자를 태그하게 된답니다 호호..

<img width="889" alt="image" src="https://user-images.githubusercontent.com/37579660/167275742-8beb38ec-47c2-410b-8906-f26c25d6c6b0.png">

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/domain/Line.java
> +//    private int distance;
네, 불필요한 주석은 코드 읽는 사람에게 불필요한 컨텍스트를 요구할 수 있어요. 혼란을 가져다줄 수 있죠! 

깃의 형상 관리를 믿고 과감하게 지워버리시죠!

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @GetMapping(value = "/lines", produces = MediaType.APPLICATION_JSON_VALUE)
자동으로 세팅이 되는군요~! 코드상으로 확인하고 싶어서 조금 찾아봤는데 시간을 많이 들이지 않아 명확한 내용은 발견하지 못했네요 😭

아래와 같이 전역적으로 세팅해주는 방법은 있습니다 :
https://www.logicbig.com/tutorials/spring-framework/spring-web-mvc/content-negotiation-default-media-type.html

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/StationController.java
> +    }
좋아요! 스프링에서 컨트롤러 - 서비스 - 영속성 이라는 레이어를 관습적으로 사용하지만 왜 이렇게 사용하는지를 직접 체험하셨다 생각되네요! 무조건 관습을 따르기보다는 관습이 왜 나왔는지를 이해한다면 프레임워크를 더 효율적으로 사용할 수 있겠죠?

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
Static의 단점과 객체의 관리에 있어 불편함이 핵심이군요! 정리 잘 해주셨네요! 스프링을 사용하는 이유기도 하니까요! 위에서도 적었듯 이렇게 경험을 통해 체화된 지식은 에덴의 머릿속에 오래 남아있을거에요 💯

2022-05-08 00:25 UTC, toneyparky commented on src/main/java/wooteco/subway/ui/SubwayExceptionController.java
> +public class SubwayExceptionController {
네 잘 처리해주셨어요! 예상 못한 예외는 저희가 사용하는 라이브러리나 써드파티 API에서 발생할 수 있어요. 그렇기에 개발할 때에는 예상치 못한 예외를 고려해야 해요. 다만 모든 상황에서 고려할 수 없으니 최소한의 방어책으로 지금과 같은 처리를 해주는거죠!

2022-05-08 00:25 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
좋네요! 테스트 코드도 개발자가 관리해야 하는 코드죠! 왜냐하면 저희가 작성하고 읽기 때문이에요. 그렇기에 가독성을 위해 어느정도 처리를 해두자구용

2022-05-08 00:25 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
>  public class StationAcceptanceTest extends AcceptanceTest {
크... 좋네요. 잘 설명해주셨어요. 인수 테스트만을 보고도 사용자가 의도한 행위와 결과를 확인할 수 있으면 좋아요. 그리고 인수 테스트는 말 그대로 고객사(혹은 프론트 엔드 개발자나 기획자)에게 에덴이 개발한 프로젝트를 인수(최종 구매)할지 결정할 수 있도록 검증하는 과정이기에 정상 동작과 예외 동작까지 다 표현할 수 있어야 해요.

아래의 코멘트에서 여쭤봤듯 예외에 대해서 처리가 부족했기에 에덴이 인수 테스트를 어떻게 생각하시는지 여쭤봤습니다!

2022-05-08 00:25 UTC, toneyparky commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    @DisplayName("지하철 노선을 제거한다.")
확인했습니다~!

2022-05-08 00:26 UTC, merged