[Spring 지하철 노선도 - 1,2단계] 리차드(전형중) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #211
Opened 2022-05-04 08:01 UTC by HJ-Rich

미르 안녕하세요!
리차드라고 합니다. 만나뵙게 되어 반갑습니다! 🤗 

이번 미션에서 개인적인 목표는 다음과 같습니다!
- 궁금한 부분에 대해 리뷰어, 코치, 크루들과 자주 소통하기
- 동작 원리에 대한 학습은 잠시 미루고 구현에 집중하여 빠른 PR, 잦은 PR로 짧은 주기로 피드백 받기
- PR과 PR 사이에 공식 문서를 통해 학습하고 내가 사용한 코드를 개선해보기

이번 미션에서 미르를 뵙게 되어 정말 감사하고 기쁩니다!
잘부탁드립니다!! 🙇

2022-05-04 08:04 UTC, HJ-Rich commented on src/main/java/wooteco/subway/ui/LineController.java
> +package wooteco.subway.ui;
초기 패키지 구성 상 컨트롤러가 ui 라는 패키지에 담겨 있었어요.
레이어드 아키텍처를 살짝 찍먹만 해봤는데요,
거기에서도 컨트롤러를 프리젠테이션 레이어로 분류하더라고요.

그런 관점이라면, 프리젠테이션 레이어에는 도메인이 반환되면 안된다고 생각해요.
그러나 서비스가 서비스를 의존하는 경우에 DTO를 받으면 후속 처리가 번거로워지기 때문에,
컨트롤러에 도메인이 오는 것을 트레이드 오프로 여기고 더 많은 장점을 취하기 위해
컨트롤러가 도메인을 DTO로 변환하는 역할을 받는 게 더 이점이 있다고 생각해요.

혹시 이 부분에 대한 미르의 생각과 실제 업무환경에서의 경험을 들려주실 수 있을까요?!

2022-05-04 08:08 UTC, HJ-Rich commented on src/main/java/wooteco/subway/ui/StationControllerAdvice.java
> +    public ResponseEntity<Void> duplicateStation() {
데이터베이스에 중복된 값이 저장되면 안되는 경우, 두 가지 선택지가 있는 것 같아요.

- DB의 Unique 규칙에 검증 역할 맡겨서 DuplicateKeyException 던지게 하기
- 질의하여 존재하는지 확인 후 Java에서 커스텀 예외 던지기

저는 아래와 같은 이유로 Java에서 검증하는 게 낫다고 생각해요.
- 중복되지 않는 경우에도 질의해야 하는 비용이 발생하는 것은 인정
- 그러나 그 비용 보다 질의해온 결과를 Java 코드로 다루는 것이 더욱 객체지향적
- 가령 1단계에서 DB없이 구성했을 때, Equals&HashCode를 이용한 contains로 검증했는데, 
선 질의 후 Java 검증이면 이러한 구조가 가능해짐
- Java에서 검증 시, StationDuplicateException, LineDuplicateException과 같이
상세한 예외를 발생시킬 수 있고, 이는 개발자의 업무 효율 증대에 도움이 됨
- 추가적으로 상세한 예외는 상세한 예외코드 분기로 API 사용자의 DX 증대에 도움이 됨

현재 코드는 페어의 의견을 따라 DuplicateKeyException으로 구성된 상황이에요.

이 부분에 대한 미르의 생각과 업무에서의 경험이 궁금합니다!

2022-05-04 08:10 UTC, HJ-Rich commented on src/test/resources/application.yml
> +    driver-class-name: org.h2.Driver
프로덕션 프로파일에서는 H2의 url, user, password 설정값이 추가로 있는데요,
이를 그대로 사용하니 테스트에서는 Rollback이 제대로 적용되지 않았는지 실패가 발생하더라고요.

왜 이렇게 수정해야 테스트코드가 정상 작동하는지는 이해하지 못하고 있는 상태인데요,
페어가 코치분께 이런 조언을 받은 적이 있어서 변경했고, 정상 동작함을 확인했습니다.
이 부분에 대해선 공식 문서로 추가로 학습해보겠습니다.

2022-05-04 08:18 UTC, HJ-Rich commented on src/main/java/wooteco/subway/dao/LineDao.java
> +        final String sql = "select id, name, color from LINE where id = :id";
현재 구성 상 LineDao, StationDao는 id값 또는 요청Dto를 받아 도메인 객체를 반환하고 있어요.

저는 Dao는 데이터베이스에 접근하는 역할만 해야 하고, 테이블의 모든 컬럼을 필드로 갖는 Entity를 반환해야 한다고 생각해요.
그리고 그 Entity를 Repository가 받아서 도메인 객체로 변환해서 Service에게 반환해야 한다고 생각해요.

DDD, Eric Evans 2003 에서 정의한 Repository를
영속 데이터에 저장된 객체를 컬렉션처럼 사용하게 해주는 것이라고 저는 이해했어요.
그렇기에 저장 요청시엔 Dto나 Entity등이 올 수도 있지만, 반환값은 도메인 객체가 되는 게 맞는 것 같아요.

JPA를 사용하게 될 경우, Service가 Repository를 의존하기 때문에,
Entity가 반환되고, 이를 변환하는 과정이 Service 레이어에 담길 수밖에 없다고 생각해요.
그러나 만약 Dao와 Repository를 모두 직접 구현한다면, Repository가 마치 일급 컬렉션처럼
도메인 객체를 요청에 따라 생성하고, 삭제하고, 조회해서 반환하도록 구성하는 게 맞는 것 같아요.

그런데 이렇게 컬렉션을 모방해 도메인 객체를 관리해주는 역할로 Repository를 바라보면,
자동차미션에서 Car객체를 Cars가 관리했듯이, Station을 StationRepository가 관리하는 것이 되고,
이렇게 되면 Cars가 그렇듯, StationRepository도 도메인 객체로 볼 수 있을까? 하는 생각도 들었어요.

뭐가 정답이다 딱! 그런 건 없을 수도 있지만..
레이어드 아키텍처, Dao와 Repository, Service 및 Controller의 역할과 필요성 등등
지난 미션부터 고민해왔던 부분들을 우다다다 쏟아내봤어요.

미르의 의견이 궁금합니다!

2022-05-05 19:44 UTC, HJ-Rich commented on src/main/java/wooteco/subway/dao/AbstractRepository.java
> +public abstract class AbstractRepository<T, ID> {
Dao가 늘어날 떄마다 유사한 로직들이 반복되는 것을 확인했습니다.
JPA를 모방하여 Repository를 구현해봤습니다.

JPA 내부의 동작 원리에 대해서는 간단하게 배운 적 있지만,
내부 구현 코드가 어떻게 되어있는지는 몰라서
메서드 시그니처를 유사하게 가져가고,
Entity만 전달하면 CRUD가 구현되게끔만 모방해봤습니다.

Dao는 Entity를 받고 Entity를 반환하고,
Repository는 여러 Dao를 의존하여 하나의 Entity를 반환하고,
Service는 Entity를 도메인 객체로 변환하여 메시지를 보내고, 결과를 도메인 객체로 반환하고,
Controller는 도메인 객체를 Response로 변환하여 반환한다는 레이어드 아키텍처 구상으로 진행해봤습니다.

각 레이어별 Dto를 독립적으로 갖게 함으로써 의존성의 방향을 위에서 아래로만 흐르게 구성하려 했습니다.
아직은 이러한 구성의 레이어간 결합도를 낮춘다는 장점에 대해 완전히 공감하진 못한 상태입니다.
이론적으론 공감이 되나, 실익이 얼마나 될지에 대해서는 의문입니다.
큰 규모의 애플리케이션을 만나보지 못했기 떄문이기도 하고, 
실제로 트레이드오프이기도 하기 떄문일 것이라 추측하고 있습니다.

2022-05-05 19:47 UTC, HJ-Rich commented on src/main/java/wooteco/subway/service/dto/StationServiceRequest.java
> +public class StationServiceRequest {
**Request, **Response는 Controller의 요청과 응답에만 사용하는 것으로 설계해봤습니다.
Service는 **ServiceRequest를 매개변수로 받아 도메인 객체를 반환하도록 설계했습니다.

Controller에서 Service로 매개변수를 전달할 때 변환 과정과
Service에서 응답한 도멩니 객체를 **Response로 변환하는 과정은 Controller에서 갖도록 했습니다.

Repository는 Service에 의해 의존되며,
매개변수와 응답값으로 모두 **Entity를 사용하도록 설계했습니다.

이렇게 구성함으로써 레이어간 결합도 저하,
레이어간 변경에 유연함 향상,
서비스 레이어의 재사용성 향상을 꾀했습니다.

2022-05-05 19:52 UTC, HJ-Rich commented on src/main/java/wooteco/subway/dao/StationRepository.java
> +public class StationRepository extends AbstractRepository<StationEntity, Long> {
미션 시작 시 Dao는 모든 로직을 Static 메서드로 가지고 있었습니다.
그 결과 어느 컨텍스트에서나 호출할 수 있어서 의존성 관리에 어려움이 있었습니다.
static 영역에 하나의 클래스만 생성되어 재사용가능하다는 점은 장점이었습니다.

Spring을 사용하는 중요한 이유가 저는 객체지향적 코드의 장점을 살리면서도,
복잡한 의존성을 개발자가 관리하지 않아도 된다는 점이라고 생각합니다.

가령 JdbcTemplate을 현재 간단하게 Spring의 의존성 주입을 통해 사용하고 있지만,
실제 Application Context 내에서 JdbcTemplate이 생성되려면
수많은 다른 Spring Bean들이 관여하고 있기에 개발자가 직접 관리하기엔 무리가 따릅니다.

이러한 구조가 발생한 원인은 객체지향의 장점을 살리기 위해, 의존성을 낮추기 위해
인터페이스를 의존하는 구조로 설계가 되었기 때문이라고 생각합니다.

이러한 객체의 생명주기, 객체의 조립은 규모가 커질수록 개발자가 직접 관리하기 어려울 뿐더러
핵심 관심사가 아닙니다. 

추가적으로 static을 사용할 경우, 상속 등의 객체지향의 장점을 살릴 수 없게 됩니다.

Repository 애너테이션을 이용해 간단히 Spring Bean으로 등록해두고,
필요한 곳에서 생성자를 통해 의존성 주입을 받게 함으로써,
객체의 조립 책임을 스프링에게 위임하면서도, Repository가 사용되는 컨텍스트를 개발자가 손쉽게 제한할 수 있습니다.

추가적으로 내부에서는 Spring Bean이 기본 설정으로 싱글턴으로 관리되기 떄문에
여러 컨텍스트에서 사용되더라도 불필요하게 여러 인스턴스가 생성되지도 않습니다.

2022-05-06 02:07 UTC, ddu0422 requested changes
안녕하세료 리차드 ! 미르예요 :)

1, 2단계 미션 빠르게 구현해주셨네요!
간단한 코멘트 남겼으니 확인해주시면 감사하겠습니다 🙏🏻 

이번 주도 화이팅이예요 🔥

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +        final String sql = "select id, name, color from LINE where id = :id";
네 저도 반환값은 도메인 객체가 되어야 한다고 생각해요.
저도 Repository는 도메인 객체로 볼 수 있다고 생각합니다 !

> 그러나 만약 Dao와 Repository를 모두 직접 구현한다면, Repository가 마치 일급 컬렉션처럼
도메인 객체를 요청에 따라 생성하고, 삭제하고, 조회해서 반환하도록 구성하는 게 맞는 것 같아요.

Dao와 Repository를 구현한다는 말이 와닿지가 않는데 부연 설명 가능할까요?
다른 이름을 사용하지만 같은 역할을 한다는 의미일까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +        final String sql = "select id, name, color from LINE where id = :id";
[해당 글](https://bperhaps.tistory.com/entry/Repository%EC%99%80-Dao%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90)을 참고하면 도움이 될까요..?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/StationDao.java
>  public class StationDao {
Annotation을 작성할 때와 작성하지 않았을 때 어떤 점이 많이 바뀌었을까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
사용하지 않는 메서드로 바뀌었으니 해당 메서드도 제거하는건 어떨까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/dto/LineRequest.java
> +    }
현재 Controller, Service, Repository까지 사용하고 있는데 LineRequest의 책임은 어디까지일까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/AbstractRepository.java
> +                .collect(Collectors.toList());
훌륭한시도입니다! 깊은 고민을 하셨다는게 느껴지네요 ㅎ_ㅎ

하지만, 제약 조건이 너무 강하게 설정되어있지 않을까요?
필드명을 id로 사용하고 싶지 않을 수도 있고, Table에서 기본키 이름을 id로 사용하지 않을 수도 있지 않을꺼요?
클래스명도 Entity로 짓고 싶지 않을 수도 있지 않을까요?
이는 나중에 고민을 좀 더 해보면 좋겠어요 ㅎ_ㅎ..
현재는 미션에 집중해보아요 !_!

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/AbstractRepository.java
> +                    .filter(getter -> getter.getName().toLowerCase().contains(field))
CamelCase로 작성한 Field는 NoSuchElementException이 발생하지 않을까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/AbstractRepository.java
> +                tEntity = clazz.newInstance();
newInstance()는 자바 9에서 Deprecated 되었습니다 😄
자바 11을 사용하니 [newInstance() Docs](https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html#newInstance--)를 참고하여 다른 메서드로 대체해보는건 어떨까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/StationRepository.java
> +public class StationRepository extends AbstractRepository<StationEntity, Long> {
스프링을 사용한 느낌점을 물어보고 싶었는데 자세히 설명해주어 감사합니다 🙏🏻

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/exception/LineDuplicateException.java
> +public class LineDuplicateException extends RuntimeException {
Custom Exception 👍🏻 👍🏻

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/exception/NoStationFoundException.java
> +public class NoStationFoundException extends RuntimeException {
상수명이 `NOT_FOUND` 인 것 처럼, `NotFoundStationException`은 어떨까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/SpringLineService.java
> +        LineEntity lineENtity = new LineEntity(null, lineServiceRequest.getName(), lineServiceRequest.getColor());
LineEntity에서 생성자 오버로딩을 활용하지 않은 특별한 이유가 있을까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/SpringLineService.java
> +        }
[Optional vs Null](https://tecoble.techcourse.co.kr/post/2021-06-20-optional-vs-null/)을 참고하여 orElseThrow를 활용하는건 어떨까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/SpringLineService.java
> +            throw new NoSuchElementException();
클라이언트에게 에러 메시지를 반환하지 않는다면 어떤 이유에서 에러가 발생했는지 어렵지 않을까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/LineController.java
> +package wooteco.subway.ui;
리차드의 생각을 듣고 싶네요 ㅎ_ㅎ..

1. 클라이언트 입장에서는 해당 내용이 Domain인지 Dto인지 알 수 없을텐데 Controller에서 Domain을 반환하면 안된다고 생각한 이유가 있을까요?

2. 꼭 계층이 Controller, Service, Repository로만 나뉘어야할까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/dto/StationServiceRequest.java
> +public class StationServiceRequest {
👍🏻 👍🏻

2022-05-06 02:07 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/StationControllerAdvice.java
> +    public ResponseEntity<Void> duplicateStation() {
어떤 내용에 동의하여 페어의 의견을 따라갔을까요?

> Java에서 검증 시, StationDuplicateException, LineDuplicateException과 같이
상세한 예외를 발생시킬 수 있고, 이는 개발자의 업무 효율 증대에 도움이 됨

이 부분은 try catch로 한번 감싸고 원하는 에러로 변경하여 에러를 처리할 수 있을 것 같아요 😄

2022-05-06 02:07 UTC, ddu0422 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
중복되는 부분을 찾아서 제거할 수 있지 않을까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/test/java/wooteco/subway/dao/LineDaoTest.java
> +        void save_Fail_If_Exists() {
Camel Case를 사용하는데 언더바를 제거하는건 어떨까요?

2022-05-06 02:07 UTC, ddu0422 commented on src/test/resources/application.yml
> +    driver-class-name: org.h2.Driver
오호.. 이부분은 저도 확인해볼게요 !

2022-05-06 08:13 UTC, HJ-Rich commented on src/test/java/wooteco/subway/dao/LineDaoTest.java
> +        void save_Fail_If_Exists() {
제거 완료했습니다!

2022-05-06 08:15 UTC, HJ-Rich commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
상위 클래스인 `AcceptanceTest`에 `get`, `post`, `delete`, `put` 메서드를 protected로 선언한 뒤,
이를 하위 클래스에서 재사용하도록 하여 중복을 제거해봤습니다!

중복을 제거하고 나니 테스트코드의 흐름을 이해하는 것이 훨씬 수월해져서 마음이 편안해졌습니다! 😄

2022-05-06 08:18 UTC, HJ-Rich commented on src/main/java/wooteco/subway/service/SpringLineService.java
> +            throw new NoSuchElementException();
맞습니다. `NoSuchElementException`만으로는 클라이언트가 
어떤 이유에서 에러가 발생했는지 확인하기 어려울 것 같습니다.

혹시 String message를 생성자 매개변수로 전달했다면 조금 나았을 수도 있을 것 같습니다.

개인적으로는 다소 Custom Exception이 많아지더라도,
개발자를 위해 매 상황별 Custom Exception을 만들어서
Exception 종류만 보고도 어디에서 어떤 이유로 예외가 발생했는지
파악하기 수월한 구조를 만들어두는 것이 장기적으로 유지보수 비용을 줄일 수 있는 방안이라 생각합니다.

각각의 경우에 Custom Exception을 만들어 던지도록 개선해보았습니다!

2022-05-06 08:19 UTC, HJ-Rich commented on src/main/java/wooteco/subway/service/SpringLineService.java
> +        }
```java
final LineEntity lineEntity = lineRepository.findById(id)
        .orElseThrow(() -> new NotFoundLineException(id));
```

orElseThrow를 활용하여 조건문도 사라지고 가독성도 향상되었네요!
감사합니다 미르! 🙏

2022-05-06 08:23 UTC, HJ-Rich commented on src/main/java/wooteco/subway/service/SpringLineService.java
> +        LineEntity lineENtity = new LineEntity(null, lineServiceRequest.getName(), lineServiceRequest.getColor());
특별한 이유는 없었습니다.. 
빠르게 구현한다는 생각만 하며 코드를 작성하다 크게 놓친 것 같습니다.
빠른 구현에 집중하더라도 설계적인 측면에 대해선 놓치지 않도록 주의하겠습니다!

현재는 아래와 같이 생성자 오버로딩을 활용하여 코드를 개선했습니다!

```java
public LineEntity(Long id, String name, String color) {
    this.id = id;
    this.name = name;
    this.color = color;
}

public LineEntity(String name, String color) {
    this(null, name, color);
}
```

2022-05-06 08:24 UTC, HJ-Rich commented on src/main/java/wooteco/subway/exception/NoStationFoundException.java
> +public class NoStationFoundException extends RuntimeException {
NotFound가 두괄식으로 보다 분명히 의미를 전달하는 것 같습니다!
말씀해주신 방향으로 관련 예외 클래스 네이밍을 모두 수정했습니다!

2022-05-06 08:25 UTC, HJ-Rich commented on src/main/java/wooteco/subway/exception/LineDuplicateException.java
> +public class LineDuplicateException extends RuntimeException {
클라이언트에게 어떤 이유로 처리가 되지 않았는지 알려준다는 측면도 크지만,
저는 개발자에게 큰 도움이 된다는 측면에서 Custom Exception을 아주 좋아합니다!

어떤 예외인지만 보고도 어느 로직에서 어떤 이유로 발생한 예외인지 파악할 수 있다면,
시간이 지날수록 유지보수 비용을 크게 줄여줄 거라 생각합니다!

2022-05-06 08:30 UTC, HJ-Rich commented on src/main/java/wooteco/subway/dao/AbstractRepository.java
> +                .collect(Collectors.toList());
맞습니다. 제약조건도 강하고.. 빈틈이 많이 있습니다.
코드 품질도 극악입니다.. ^^;
리플렉션을 직접 다뤄보고 싶기도 했고, Dao의 중복 로직을 줄여보고 싶기도 했습니다.
이 부분은 개인적인 흥미로 구현해봤습니다.
많이 부족하지만, 최초 의도했던 바를 이뤄낸 것 같아 과정도 즐거웠고 결과도 뿌듯.. 합니다 ㅋㅋㅋ;;

테이블명에 대해서는 애너테이션을 활용한 메타 데이터를 가져오는 방향으로 대처가 가능할 것 같다고 생각합니다만,
커스텀 애너테이션을 만들고 활용하는 법은 아직 몰라 적용하지 못했습니다.

기본키의 이름이 "id"로 고정인 부분에 대해서도 필드에 애너테이션으로 메타 데이터를 할당하여
이 메타 데이터가 존재하는 필드명을 사용하는 방향으로 대처 가능할 것 같다고 생각은 듭니다만,
직접 구현은 당장은 어려울 것 같습니다.

하지만 여러 지적해주신 부분처럼
제약도 많고 빈틈도 많고 deprecated된 메서드를 호출하고, 예외처리도 부실합니다.

현재 미션에 집중하기 위해 AbstractRepository 관련 피드백해주신 부분에 대해선
간단히 저의 생각을 코멘트로 남긴 것으로 대신하고,
조금 더 중요한 부분에 집중하도록 하겠습니다!

부족한 코드에도 꼼꼼하게 살펴주셔서 감사합니다 미르!

2022-05-06 10:35 UTC, HJ-Rich commented on src/main/java/wooteco/subway/dto/LineRequest.java
> +    }
Controller에서 매개변수로 받는 Dto는 
Controller 내부에서 변환해서 다른 레이어로 전달되지 않도록 개선하였습니다!

변환한 결과는 Service 에서 사용하는 매개변수가 되게 구성했습니다.

이렇게 함으로써 레이어간 의존을 줄이고,
변경에 유연하게 되고,
서비스의 재사용성을 증대할 수 있다고 생각합니다.

그러나 한편으로는, 이론적인 부분에 대해서는 공감이 되지만,
이러한 구성을 통한 실익이 있는지에 대해서는 의문이 남아있습니다.

직접 구현해보고 경험해봐야할 것 같습니다!
미르의 의견도 궁금해요~! 😄

2022-05-06 10:36 UTC, HJ-Rich commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
제거 완료했습니다! :)

2022-05-06 10:40 UTC, HJ-Rich commented on src/main/java/wooteco/subway/dao/StationDao.java
>  public class StationDao {
@Repository 애너테이션 안에 있는 @Component 애너테이션으로 인해,
StationDao가 Application Context 내 Spring Bean으로 등록됩니다.

Spring Bean으로 등록된다는 것은,
해당 클래스의 인스턴스가 Spring에 의해 생성된다는 의미입니다.

이렇게 생성된 Spring Bean은 기본적으로 싱글턴으로 관리되며, 
해당 인스턴스를 의존하는 객체에게 자동 주입되어 조립됩니다.

이로써 객체간 낮은 결합도를 위한 인터페이스 의존 설계를 가져가면서도,
동시에 복잡한 의존성 관리라는 단점은 사라지게 됩니다.
추가적으로 static이 아니기 때문에 객체지향의 장점들을 더욱 극대화할 수 있게 됩니다.
또한 static은 어디에서나 호출이 가능하지만,
Spring Bean으로 등록된 객체를 의존 받아 사용하는 경우,
사용되는 컨텍스트를 개발자가 제한할 수 있습니다.

2022-05-06 10:45 UTC, HJ-Rich commented on src/main/java/wooteco/subway/dao/LineDao.java
> +        final String sql = "select id, name, color from LINE where id = :id";
Dao와 Repository를 구현한다 는 다음과 같은 의미로 사용했습니다!

- JPA의 Repository는 도메인 객체가 아닌, Entity를 반환합니다.
- 그러나 학습한 이론에 따르면 Repository는 도메인 객체를 영속적으로 관리해주는 역할을 하므로, 도메인 객체를 반환하는 것이 적절하다고 생각합니다.
- 다만 도메인 객체를 만들어내는 역할까지 추상화하여 만들어둘 수 없기 떄문에, JPA Repository를 사용할 경우, Entity를 반환 받아 서비스 레이어에서 도메인 객체로 변환한다고 생각합니다.
- JPA Repository를 사용하지 않고, 지금처럼 Dao와 Repository를 직접 구현하는 경우에는 Dao가 Entity를 반환하고, Repository에서 도메인 겍체를 생성하도록 구성해도 될 것 같다는 생각이었습니다!

미르의 의견을 공유해주셔서 감사합니다!
주신 링크도 여러번 읽어보겠습니다 !

2022-05-06 10:50 UTC, HJ-Rich commented on src/main/java/wooteco/subway/ui/StationControllerAdvice.java
> +    public ResponseEntity<Void> duplicateStation() {
사실 페어의 의견에 설득되지는 않았지만, 
서로 충분히 주장하는 바의 근거를 공유한 이후에는 빠르게 한 쪽으로 협의하여 진행하는 쪽이 낫다고 생각해서 양보했어요.
추후 수정하려 하더라도 큰 어려움 없이 수정할 수 있는,
아주 크리티컬한 포인트는 아니라고 생각했어요!

DuplicateKeyException 도 Java에서 핸들링해도록 개선해보겠습니다!

2022-05-06 10:53 UTC, HJ-Rich commented on src/main/java/wooteco/subway/ui/LineController.java
> +package wooteco.subway.ui;
1. Controller에 Domain을 반환하면 안된다고 생각한 이유

- 사실 저 스스로도 납득되지 않는 이유이긴 한데요,
레이어드 아키텍처를 살짝 학습해보니, Controller가 프리젠테이션 레이어에 속한다.
프리젠테이션 레이어에는 도메인이 반환되면 안된다. 와 같은 논리였습니다.... ^^;;

2. Controller Service Repository 계층 분리에 대하여

- 경우에 따라 다르게 나뉠 수도 있다고 생각합니다
- 그럼에도 그러한 계층 분리가 많이 언급되는 이유는 애플리케이션을 개발하는 과정에서 발생하는 공통적인 문제에 대한 보편적인 해결방법으로서 제시된 것이라고 생각합니다!

2022-05-07 02:12 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/AbstractRepository.java
> +                .collect(Collectors.toList());
아니예요 ㅎㅎ 그런 시도를 하면 할수록 경험치가 많이 쌓인다고 생각해요. 앞으로도 자주 ! 도전해보아요 ㅎ-ㅎ

2022-05-07 02:15 UTC, ddu0422 commented on src/main/java/wooteco/subway/exception/LineDuplicateException.java
> +public class LineDuplicateException extends RuntimeException {
저도 같은 생각이예요. 😁 Custom Exception을 활용하면 에러 메시지를 한 곳에서 관리할 수 있어서 자주 활용해요.

2022-05-07 02:29 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/LineController.java
> +package wooteco.subway.ui;
저는 당연히 규칙을 지키려면 비용이 커진다고 생각해요. 언제나 트레이드 오프죠..!

몇가지 고민해볼 사항이 있을 것 같아요.

1. 서비스가 다른 서비스를 얼마나 참조하는가? 정말 많이 참조한다면 Domain으로 반환하는게 이득이지 않을까요?

2. Service는 Domain을 반환하고 다른 계층을 만들어서 그 계층에서 Dto로 변환하여 Controller에 반환하고 Service끼리 Domain을 주고 받을 수 있는 역할을 지녀도 괜찮을까?
보편적으로 문제를 할 수 없다면 다른 방법을 찾아봐야하지 않을까요??

2022-05-07 02:31 UTC, ddu0422 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
보다 많은 부분을 고려해주셨군요 ㅎ-ㅎ 멋지네요!!

2022-05-07 02:44 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/StationControllerAdvice.java
> +    public ResponseEntity<Void> duplicateStation() {
CustomException으로 변환하고 싶다면

```java
        try { 
            final LineEntity saved = lineRepository.save(lineEntity);
            return new Line(saved.getId(), saved.getName(), saved.getColor());
        } catch (DuplicateKeyException e) {
            throw new LineDuplicateException();
        }

```
처럼 사용할 수 있을 것 같아요.
리차드의 의견대로 사용자에게 보다 명확한 에러 전달이 필요하지 않을까해요 ㅎ_ㅎ

2022-05-07 02:59 UTC, ddu0422 approved these changes
안녕하세요 리차드! 미르예요 :)

피드백 빠르게 반영해주셨네요 ! 이만 머지해도 될 것 같아서 머지할게요 !_!
간단한 코멘트 남겨드렸어요 ㅎ_ㅎ 3단계때 참고해주세요 😄 

3단계까지 화이팅이예요 🔥

2022-05-07 02:59 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/dto/StationServiceRequest.java
> +    private String name;
final 이여도 될 것 같아요 ㅎ_ㅎ

2022-05-07 02:59 UTC, ddu0422 commented on src/main/java/wooteco/subway/ui/StationControllerAdvice.java
> +@RestControllerAdvice(basePackageClasses = {LineController.class, StationController.class})
굳이 Coontroller를 제한해야할 이유가 있을까요?

2022-05-07 02:59 UTC, ddu0422 commented on src/test/java/wooteco/subway/dao/LineRepositoryTest.java
> +        final LineEntity save2 = lineRepository.save(lineEntity2);
변수 선언은 삭제해도 괜찮지 않을까요?

2022-05-07 02:59 UTC, merged