[Spring 지하철 노선도 - 1,2단계] 아키(허영운) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #214
Opened 2022-05-04 08:44 UTC by yeongunheo

안녕하세요 또링!

지하철 노선도 피드백 요청드리게 된 아키입니다.

미션을 진행하면서 궁금한 점은 아래 코멘트로 남겨두겠습니다.

잘부탁드립니다!

2022-05-04 08:51 UTC, yeongunheo commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +        params.put("name", "잠실역");
`AcceptanceTest`를 상속받아 만든 `StationAcceptanceTest`의 `createStation()` 테스트를 진행할 때
개별테스트만 돌릴 때에는 잘 되었는데도 불구하고, test 폴더의 모든 테스트를 모두 돌릴 경우 이 테스트만 통과되지 않는 문제가 있더라구요. 이때 "강남역"이 이미 DB에 있기 때문에 저장할 수 없다는 에러메시지가 출력되었습니다.

그래서 마지막에 "강남역"을 "잠실역"으로 수정하여 테스트를 통과하도록 만들었습니다.

원인을 찾아보니 `RANDOM_PORT`로 테스트를 돌릴 경우 롤백이 자동으로 되지 않아 다른 테스트에서 저장한 DB가 남아있기 때문인 것이었는데요,

테스트에서 `RANDOM_PORT`를 사용할 경우 테스트가 끝날 때마다 자동으로 롤백이 되게 설정하는 방법이 있는지 궁금합니다.

2022-05-05 09:01 UTC, yeongunheo commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +        params.put("name", "잠실역");
다른 크루분이 이 문제의 원인을 슬랙에 공유해주셨네요! 코치님께서 지금 이 문제는 신경쓸 필요 없다고 이야기해주셔서 넘어가도 좋을 것 같습니다!

> 통합 테스트 진행 시 SubwayApplicationTests 내의 contextLoads 테스트 이후의 테스트가 실패할 경우(DuplicateKeyException 발생) 해당 메서드에서 데이터베이스가 열렸다가 다음 context 로딩 시에 데이터베이스가 제대로 안 닫혀서 삽입되었던 데이터가 그대로 남아있어서 문제가 발생하는 것이었습니다. (로그를 까보면 각 테스트 종료 시에 닫혀야 할 HikariCP가 모든 테스트 종료 전까지 닫히지 않는 로그를 확인할 수 있었습니다.).
test/java/wooteco/subway/resources 내에 빈 application.properties 또는 application.yml 파일을 생성해주시거나, SubwayApplicationTests 를 지워주시는 방법으로 해결이 가능합니다. 개인적으로 application.yml 생성을 추천 드립니다. 빈 파일을 만들어주게 되면 매 테스트마다 각기 다른 랜덤한 db에 연결되어 테스트가 실패하지 않습니다. (테스트의 port 설정을 모두 RANDOM_PORT 또는 DEFINE_PORT로 통일해주면 된다고는 하는데,  이 부분은 잘 모르겠어요!)

2022-05-06 08:59 UTC, jnsorn requested changes
안녕하세요, 아키! 리뷰어 또링입니다. 👋 만나서 반가워요! 
전반적으로 깔끔하게 구현해주셨고, 이전 단계에서 다양한 학습을 하신 것 같아 보였어요. 테스트도 꼼꼼하게 잘 작성해주셔서 좋았습니다. 👍 
몇 가지 코멘트 남겨두었는데 확인해주시고, 궁금한 점은 편히 DM 남겨주세요!

2022-05-06 08:59 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
StationController와 중복되는 코드네요! 어떻게 중복을 제거할 수 있을까요?
또, 모든 Exception에 대해 badRequest()로 내려주는 게 적절할지도 같이 고민해보면 좋을 것 같아요.

2022-05-06 08:59 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @PostMapping("/lines")
컨트롤러 내의 중복되는 URI는 `@RequestMapping`을 이용해 관리하면 좋을 것 같아요!

2022-05-06 08:59 UTC, jnsorn commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
생성자가 많네요 😃 사용하지 않는 생성자는 제거해주시고, 중복되는 코드는 this를 이용해볼까요?

2022-05-06 08:59 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
body에 map이 아닌 객체를 바로 넣을 수도 있어요 :)

2022-05-06 08:59 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    }
현재는 API 응답 결과만 확인하고 있는데, 실제로 변경된 데이터를 조회해서 수정 및 삭제가 되었는지 확인해보면 어떨까요?

2022-05-06 08:59 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
모든 테스트에 하나이상의 노선을 생성하는 로직이 중복되고 있어요. 어떻게 중복을 줄일 수 있을까요?

2022-05-06 08:59 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/StationController.java
> +    private StationService stationService;
final로 선언하지 않은 이유가 있을까요~? (다른 코드 보아하니 실수인 것 같긴하지만 확인차 질문! 😃)

2022-05-06 08:59 UTC, jnsorn commented on src/main/resources/schema.sql
> +);
<img width="246" alt="image" src="https://user-images.githubusercontent.com/31095063/167099017-1ccac0c9-a808-4151-b0e2-a84c35c78606.png">
이 경고는 어떤 경고일까요? 🧐

2022-05-06 08:59 UTC, jnsorn commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
checkExistLine은 boolean을 반환할 것 같은 이름인데 Line을 반환하고 있어요! 더 적절한 이름 없을까요?

2022-05-06 08:59 UTC, jnsorn commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
Transaction에 대해 학습하셨군요 👍 
` @Transactional`과 ` @Transactional(readOnly = true)`은 어떻게 다른지, 왜 사용했는지 공유해주실 수 있나요~?

2022-05-06 08:59 UTC, jnsorn commented on src/main/java/wooteco/subway/dao/LineDaoImpl.java
> +public class LineDaoImpl implements LineDao {
테스트에서만 사용하고 있는것으로 보이는데, 프로덕션 패키지에 두신 이유가 있을까요~?

2022-05-06 08:59 UTC, jnsorn commented on docs/README.md
> +   매번 생성하지 않아도 되는 객체와 싱글톤이나 static으로 구현되었던 객체들을 스프링 빈으로 관리해도 좋음
이 과정에서 어떤 점이 좋았는지(혹은 싫었는지(?)) 공유해주실 수 있나요? 😃

2022-05-09 05:43 UTC, yeongunheo commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
모든 예외를 `ExceptionController`에서 처리할 수 있도록 수정했습니다!

2022-05-09 05:51 UTC, yeongunheo commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @PostMapping("/lines")
`LineController`와 `StationController`에서 `@RequestMapping`을 사용하도록 수정했습니다!

2022-05-09 07:43 UTC, yeongunheo commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
`Line`은 DTO가 아님에도 빈생성자와 모든필드가 있는 생성자를 만들어버렸네요🥲
필요없는 생성자는 제거하고, 생성자체이닝을 적극 활용하도록 수정했습니다!

2022-05-09 08:01 UTC, yeongunheo commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
`Line` 객체를 생성해 body에 바로 넣으면 아래와 같이 입력하지 않은 값은 null로 표시되더라구요!
저는 api 문서에 기반해 name과 color만을 넣어서 테스트하려고 했었는데, 이렇게 null값이 들어가도 괜찮을까요?

```
{
    "id": null,
    "name": "신분당선",
    "color": "bg-red-600",
    "stations": null
}
```

2022-05-09 11:16 UTC, yeongunheo commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    }
데이터 생성, 수정, 삭제와 같이 명령 쿼리를 일으키는 API를 테스트할 때 실제로 데이터가 변경되었는지 확인할 수 있도록 수정했습니다!

2022-05-09 11:39 UTC, yeongunheo commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
`@BeforeEach`을 사용해 중복코드를 제거했습니다!

2022-05-09 11:40 UTC, yeongunheo commented on src/main/java/wooteco/subway/ui/StationController.java
> +    private StationService stationService;
앗 `final`을 빠뜨렸네요ㅠ 이부분도 수정했습니다!

2022-05-09 11:55 UTC, yeongunheo commented on src/main/resources/schema.sql
> +);
파일 끝에 개행을 추가하지 않아서 생기는 경고이네요! 이전에 페어가 저에게 말해준 적이 있었는데, 덕분에 이번 기회에 다시금 알아갑니다:)

✅파일 끝에 개행을 추가해야 되는 이유
1. POSIX 명세 표준이다. => 규약이므로 지키는게 좋다!
2. 마지막 줄바꿈이 없다면 오류를 발생하는 프로그램들이 있다.
3. 맨 끝에 개행을 추가하지 않고 커밋했을 경우, 다른사람이 IDE에서 개행을 자동으로 추가하도록 설정했다면 유효코드작성 없는 빈 커밋이 생성될 수 있다.

2022-05-09 12:13 UTC, yeongunheo commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
곰곰이 생각해보니 `checkExistLine`은 검증하는 메서드인데 Line을 반환하는게 맞을까? 라는 의문이 들더라구요.
제 생각엔 메서드가 2가지 책임(검증, id에 대응하는 Line을 반환)을 한다는 생각이 들었습니다!
그래서 반환타입은 void로 수정하고, id에 대응하는 Line이 존재하지 않을 때는 에러를 출력하도록 변경했습니다.

또링 생각에는 메서드이름이 check로 시작하는데 반환타입이 void인건 어색하다고 느껴지나요?

2022-05-09 12:18 UTC, yeongunheo commented on src/main/java/wooteco/subway/dao/LineDaoImpl.java
> +public class LineDaoImpl implements LineDao {
스프링 어노테이션을 사용하는 방향으로 리팩토링하면서 기존에 사용하던 코드를 그대로 프로덕션 패키지에 남겨두었습니다.
지금은 사용하지 않는 코드이니 삭제하는게 좋을까요?

2022-05-09 12:27 UTC, yeongunheo commented on docs/README.md
> +   매번 생성하지 않아도 되는 객체와 싱글톤이나 static으로 구현되었던 객체들을 스프링 빈으로 관리해도 좋음
매번 객체를 생성하지 않아도 되어서 중복코드가 제거되었습니다. 그리고 스프링에서 자동으로 빈 객체를 주입해주니까 이부분이 편리하다고 느꼈습니다!

싫었던점?이라면 빈 등록이 제대로 안되어있을 경우 `UnsatisfiedDependencyException: Error creating bean with name`이라는 에러가 출력되면서 스프링이 제대로 되지 않는 것이었는데요, 이 부분은 런타임 단계에서 에러를 잡아주니 오히려 장점이라고 할 수 있겠네요!

2022-05-09 12:43 UTC, yeongunheo commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
`@Transactional(readOnly = true)`을 사용한 이유는 `명령쿼리분리원칙` 때문입니다. 조회 쿼리만을 사용하는 메서드에는 `readOnly = true`을 붙여 상태를 변경시키는 행위(생성,수정,삭제)를 금지할 수 있습니다. 

또한,`readOnly = true`가 메서드에 붙어있다면, 다른사람이 보기에 이 메서드는 상태를 변경시키지 않는 쿼리라고 생각할테니 프로그램의 안정성에 기여할 것이라는 생각을 했었습니다.

`readOnly=true`를 사용함으로써 얻을 수 있는 또다른 장점은 성능이 향상된다는 것입니다. 이것이 어떻게 성능을 향상시키는지는 좀 더 찾아봐야겠네요.

2022-05-09 12:44 UTC, yeongunheo commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
Exception마다 다른 HTTP 상태코드를 반환하도록 만드는 것에 대해선 좀 더 고민해봐야 할 것 같습니다.

2022-05-10 07:06 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
넵 👍 보통 bad request는 클라이언트의 요청이 잘못된 상황에서 내려주는데, 현재는 서버에러를 포함한 전체 에러에 대해 bad request가 내려가고 있어서 드린 리뷰였어요. 천천히 고민해보시고, 궁금한 점 생기면 편히 DM주세요 :)

2022-05-10 07:10 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @PostMapping()
```suggestion
    @PostMapping
```
🙂

2022-05-10 07:10 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
map으로 해도 내부에서 생성되는 객체는 위와 같지 않나요? ㅎ_ㅎ

2022-05-10 07:25 UTC, yeongunheo commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
RestAssuredUtils 클래스를 생성하여 중복코드를 제거했습니다!
제 생각에는 모든 테스트마다 노선을 생성하는 로직을 넣어주는 것이 좀 더 직관적이라고 생각하는데 이걸 `@BeforeEach`에 위임하는게 맞는지 고민이네요.

2022-05-10 07:41 UTC, jnsorn approved these changes
아키! 리뷰 반영 잘해주셨어요 👍 
이번 단계는 여기서 마무리해도 좋을 것 같아요.
코멘트 남겼는데 다음 단계 진행하면서 확인해주세요 ㅎㅎ
수고 많으셨어요. 다음 단계에서 만나요 😊

2022-05-10 07:41 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    }
`@BeforeEach`를 사용하여 중복 코드를 제거하셨네요 👍 다만 createLine을 봤을 때 바로 assert 문이 나와서 가독성이 떨어지는 느낌을 받았어요. 개인적으로 `@BeforeEach` 보다는 생성 메서드로 추출해서, 필요한 테스트에서 호출하는 게 더 좋지않을까라는 생각이 드네요! 🤔 ㅎ_ㅎ

2022-05-10 07:41 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .collect(Collectors.toList());
Location에서 id를 추출하는 작업도 반복되고 있어요!

2022-05-10 07:41 UTC, jnsorn commented on src/main/resources/schema.sql
> +);
인텔리제이에서 설정하는 방법도 있어요 :) [intellij 파일끝에 개행을 자동으로 추가하는 방법](https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)

2022-05-10 07:41 UTC, jnsorn commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
넵 ㅎㅎ 좋아요. check/valid등 검증 메서드는 void여도 괜찮다고 생각해요 :)

2022-05-10 07:41 UTC, jnsorn commented on src/main/java/wooteco/subway/dao/LineDaoImpl.java
> +public class LineDaoImpl implements LineDao {
넵 사용하지 않는다면 삭제해주세요~

2022-05-10 07:41 UTC, merged

2022-05-10 07:42 UTC, jnsorn commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
슬랙은 증발되니까.. 여기에 남겨둘게요 :)

JDBC와 JPA에 대한 내용은 https://www.youtube.com/watch?v=Ppqc3qN75EE 이 테코톡 참고하면 도움 되실것 같고, JDBC에서의 readOnly와 JPA에서의 readOnly는 https://kwonnam.pe.kr/wiki/springframework/transaction 이 글의 Read Only 파트 살펴보시면 좋을 것 같아요! :미소짓는_얼굴:

2022-05-10 07:44 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
오 같은 걸 느끼셨군요 ㅋㅋㅋㅋ :) (아래 코멘트 달아두었어요)