[Spring 지하철 노선도 - 1,2단계] 야호(최지연) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #226
Opened 2022-05-04 13:23 UTC by pup-paw

안녕하세요 루피!! 레벨2로 돌아온 야호입니다 😆
레벨1 때 리뷰어분들과 dm을 주고받지 못한게 많이 아쉬웠는데, 이렇게 루피를 다시 만나서 너무 반갑네요!!
`개발왕루피`도 구독하고 잘 보고 있습니다 ㅋㅋㅋㅋㅋ

이번 미션에는 spring 학습 테스트를 통해 알게된 `namedParameterJdbcTemplate` 과 `simpleJdbcInsert` 를 적용해보았습니다!
그리고 체스 미션때 잘 적용하지 못했던 TDD 를 다시 적용해보려 노력했습니다 :)

저번에는 테스트에서 실제 프로덕션 DB를 함께 사용해보았는데, h2 를 처음 사용해보니 정말 편하고 좋은 것 같습니다!!
그리고 2단계에서 어노테이션을 사용해 객체들을 스프링 컨테이너가 관리할 수 있도록 수정하니 스프링이 편리함을 체감하게 되었습니다 😀

시차 적응하며 리뷰해주시느라 힘드실텐데 화이팅 하세요!! 외쿡.. 넘 부럽네요.. 🥺
이번에도 리뷰 잘 부탁드립니다~!~!

2022-05-05 08:47 UTC, TheDevLuffy requested changes
야호 안녕하세요~ 또 만났네요 ㅎㅎ

잘 지내셨나요. 이번 코드 리뷰는 스위스🇨🇭 열차🚅 안에서 하고 있어요.
이번 미션은 요구사항이 복잡하지 않아 미션 진행이 어렵진 않았을 것 같은데요.

관련해서 몇 가지 코멘트 남겨두었으니 확인 부탁드려요 !

2022-05-05 08:47 UTC, TheDevLuffy commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private void checkDuplicateName(String name) {
이름의 중복 여부는 비즈니스 규칙, 즉 도메인의 역할로 봐야하지 않을까요 ?

2022-05-05 08:47 UTC, TheDevLuffy commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
기본 생성자와 name, color 만 받는 생성자의 경우는 인자가 모두 있는 생성자를 이용할 수 있을 것 같아요 ㅎㅎ

필드를 모두 final 로 변경해볼까요 ?

2022-05-05 08:47 UTC, TheDevLuffy commented on src/main/java/wooteco/subway/domain/Line.java
> +    public boolean equals(Object o) {
해당 equals 로 보았을 때 Line 의 동등성은 name, color 두 개로 판단하는 것 같은데 의도하신 것 일까요 ?

2022-05-05 08:47 UTC, TheDevLuffy commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        params.put("color", "bg-red-600");
Map 을 사용하지 않고 구현이 불가능할까요 ?

한번 고민해봐주시면 좋을 것 같아요. Map 을 사용했을 때 발생할 수 있는 문제점은 무엇일까요 ?

2022-05-05 08:47 UTC, TheDevLuffy commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
status 에 대한 검증만 한다면, `extract()` 메서드를 굳이 사용하지 않고, RestAssured 로도 충분히 가능할 것 같아요.

2022-05-05 08:47 UTC, TheDevLuffy commented on src/main/java/wooteco/subway/ui/StationControllerAdvice.java
> +public class StationControllerAdvice {
예외 응답을 처리하는 방법에 대해서 고민해보면 좋을 것 같아요.
아래 세 가지 방법이 있습니다 ㅎㅎ

* try catch 를 통해 컨트롤러 메서드 안에서 응답을 return 하는 방법
* 동일한 클래스 내에서 `@ExceptionHandler` 를 정의하는 방법
* 별도 `@RestControllerAdvice` 클래스로 `@ExceptionHandler` 를 정의하는 방법

2022-05-06 07:01 UTC, pup-paw commented on src/main/java/wooteco/subway/domain/Line.java
> +    public boolean equals(Object o) {
현재 id를 db에 저장할때 임의로 생성하도록 만들어 두었는데요,
만약 id 생성 전 line과 db에 저장되어 id가 생성된 db의 line을 꺼내와 비교할 경우에 두 line이 다른 객체로 인식되는 경우를 방지하려고 id를 제외하고 equals를 재정의 해두었습니다.

name과 color가 동일한 경우에 다른 id 를 갖는 line은 생성될 수 없도록 만들어 두었기 때문에 id를 포함하지 않더라도 equals의 기능에는 문제가 없을거라고 판단했습니다!

2022-05-06 08:54 UTC, pup-paw commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
앗 그런 방법이 있었네요! 반영하겠습니다 :)

2022-05-06 08:59 UTC, pup-paw commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        params.put("color", "bg-red-600");
map을 사용하면 만약 request에서 필요한 값이 name, color, amount 로 변경되었을때 dto만 변경하는 문제가 있을 것 같습니다.
또는 변경이 일어나지 않았다고 하더라도 필요한 값들을 직접 확인해봐야 하는 문제가 있는 것 같습니다.

그래서 map 대신 실제 controller 에서도 request로 받는 lineRequest를 사용하는 방향으로 리팩터링 해보았습니다!
이렇게 수정하고 나니, 인수 테스트의 의미인 `실제 사용자 시나리오에 맞춰 진행되는 테스트` 에 더욱 적합한 테스트 코드라는 생각이 들었습니다 :)

좋은 의견 감사합니다!!

2022-05-06 09:20 UTC, pup-paw commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
생각하고 있었는데 깜빡했네요!! 알려주셔서 감사합니다 ㅎㅎ 수정하겠습니다 :)

2022-05-06 21:47 UTC, TheDevLuffy approved these changes
야호 안녕하세요 !

전반적으로 잘 반영해주신 것 같아요. 도메인에 대한 꾸준한 고민을 해주시는 것 같아 보기 좋은 것 같아요.
이번 미션은 더 이상 추가로 피드백 드릴 것이 없는 것으로 보여서 이만 머지하도록 할께요.

이제 곧 서울로 갑니다. 서울에서 뵈어요~!

2022-05-06 21:47 UTC, TheDevLuffy commented on src/main/java/wooteco/subway/domain/Line.java
> +        this(null, name, color);
👍

2022-05-06 21:47 UTC, TheDevLuffy commented on src/main/java/wooteco/subway/domain/Name.java
> +public class Name {
도메인이 더 풍부해지겠군요.

잘 추출해주신 것 같아요

2022-05-06 21:47 UTC, TheDevLuffy commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        LineRequest request = new LineRequest("신분당선", "bg-red-600");
👍

2022-05-06 21:47 UTC, merged