[Spring 지하철 노선도 - 1,2단계] 찬(김찬) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #236
Opened 2022-05-05 02:22 UTC by kimchan123

안녕하세요 또링!!
지하철 노선도 미션으로 만나게 돼 정말 영광입니다!

이번 미션은 구현이 그렇게 어렵진 않았는데 E2E 테스트가 생소해서 테스트 부분에 대한 공부를 많이 할 수 있었습니다.

부족한 코드 리뷰 잘 부탁드립니다!! 감사합니다

2022-05-07 02:40 UTC, jnsorn requested changes
안녕하세요, 찬! 리뷰어 또링입니다. 👋 만나서 반가워요.
요구사항에 맞춰 깔끔하게 잘 구현해주셨네요. 
조금 더 고민해보면 좋을 부분에 대해 코멘트 남겨두었으니 확인해주세요.
궁금한 부분이 생기면 언제든 편히 DM 주시구요! 😃

2022-05-07 02:40 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @PostMapping("/lines")
공통되는 URI는 `@RequestMapping`을 이용해볼까요?

2022-05-07 02:40 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/SubwayControllerAdvice.java
> +    }
전역 ControllerAdvice를 생성해 예외를 처리하고 있네요 👍 
예외에 따라 다양한 처리/응답 너무 좋아요.

- 다른 컨트롤러와 응답 형식을 맞춰 여기도 `@RestControllerAdvice`를 이용해보면  어떨까요? 
- 페이지를 찾을 수 없을때 정말 위 메세지가 내려가고 있을까요? [SpringBoot 존재하지 않는 API 요청의 응답 커스마이징하기]( https://tecoble.techcourse.co.kr/post/2021-11-24-spring-customize-unhandled-api/) 참고해보시면 좋을 것 같아요! 지금 미션에서 중요한 것은 아니니 패스하셔도 좋습니다. :)

2022-05-07 02:40 UTC, jnsorn commented on src/main/resources/schema.sql
> +);
unique 제약 💯

2022-05-07 02:40 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/AcceptanceTest.java
>  public class AcceptanceTest {
테스트에 `@Transactional`을 붙인 이유를 듣고싶어요! 어떤 문제를 해결하기 위해 사용하였고 어떤 장단점이 존재하는지 공유해주실 수 있나요? 👀

2022-05-07 02:40 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
`deleteLines` 보다는 `deleteLine`이 더 어울릴 것 같네요 :)

2022-05-07 02:40 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        params.put("color", "red");
`Map`이 아닌 `LineRequest` 객체를 바로 이용할 수 있어요 :)

2022-05-07 02:40 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
모든 테스트에 노선을 생성하는 로직이 중복되네요! 어떻게 중복을 제거할 수 있을까요?

2022-05-07 02:40 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    }
정확한 테스트 결과 비교 좋네요 😋

2022-05-07 02:40 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    }
여기도 더 정확한 검증을 해보면 어떨까요? 정말 수정되었는지 데이터를 확인하면 좋을 것 같아요.

2022-05-07 02:40 UTC, jnsorn commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    }
exist 쿼리 사용 👍

2022-05-07 02:40 UTC, jnsorn commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
this를 사용해 생성자간의 중복을 제거해볼까요?

2022-05-07 09:08 UTC, kimchan123 commented on src/test/java/wooteco/subway/acceptance/AcceptanceTest.java
>  public class AcceptanceTest {
사실 @Transactional과 @DirtiesContext는 코드를 받았을 때부터 있어서 따로 주의깊게 보지 않았습니다 ㅠㅠ
또링 덕분에 살짝 인수테스트 시 테스트 격리 방법에 대해 알아봤어요!

1.  @Transactional 사용 
@Transactional 어노테이션을 붙이면 트랜잭션이 끝난 뒤 롤백이 된다. 하지만, 인수 테스트 경우 port를 지정해 서버를 띄우게 되는데 이 때, 클라이언트와 서버가 각각 다른 스레드에서 실행되기 때문에 의미가 없다. (이 부분은 무슨 의미인지 아직 잘 모르겠습니다)
2. @DirtiesContext
@DirtiesContext 어노테이션은 실행시키고자 하는 컨텍스트에 이미 빈이 등록되어 있으면, 컨텍스트를 새로 로드한다. 하지만, 매번 테스트 하기전에 컨텍스트를 로드 하기 때문에 시간이 굉장히 오래걸린다.

**결론**
따라서 저는, @DirtiesContext와 @Transactional 어노테이션을 제거하고 매 테스트 이후 Truncate 쿼리로 테이블을 초기화하는 방법을 선택했습니다. 이 방법의 단점은 엔티티 혹은 테이블이 추가될 때 마다 파일을 수정해줘야 한다는 점입니다. 하지만, 지금의 경우 프로그램의 규모가 작고 수정해야 한다는 단점보단 테스트의 속도를 훨씬 향상시킬 수 있다는 장점이 더 큰 것 같아 해당 방법을 사용했습니다.

2022-05-07 09:10 UTC, kimchan123 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
테스트 픽스쳐를 만들었습니다!

2022-05-07 09:35 UTC, kimchan123 commented
또링! 리뷰 정말 감사드려요 ㅎㅎ
제가 테스트 코드를 잘 신경쓰지 않는 나쁜 습관이 있는데 이번에 꼭 바로 잡겠습니다!

2022-05-09 00:54 UTC, jnsorn commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
새로운 내용을 학습하셨군요 👍

2022-05-09 00:54 UTC, jnsorn commented on src/main/java/wooteco/subway/dto/LineRequest.java
>      private String name;
```suggestion
    @NotBlank(message = "이름을 입력해주세요.")
    private String name;
```
검증 실패 시 예외에 담을 메세지를 명시해줄수도 있어요. 😎

2022-05-09 00:54 UTC, jnsorn commented on src/main/java/wooteco/subway/dto/LineResponse.java
> +    }
여기도 생성자 중복이 보이네요!

2022-05-09 00:54 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/AcceptanceTest.java
>  public class AcceptanceTest {
좋습니다. 제대로 학습하셨네요 👍 
말씀하신 부분은 [[10분 테코톡] 🐶보스독의 테스트 격리](https://www.youtube.com/watch?v=OM_bN4wzd0g) 에서 인수테스트 격리 참고하시면 좋을 것 같아요. 😃

2022-05-09 01:03 UTC, jnsorn commented on src/test/java/wooteco/subway/dao/JdbcLineDaoTest.java
> +@Sql("/schema.sql")
`@JdbcTest`에는 `@Transactional`이 포함되어있어, 기본적으로 각 테스트 수행시 롤백 될거예요 :)

2022-05-09 01:04 UTC, jnsorn approved these changes
찬 👋 리뷰 반영 잘해주셨어요!
이번 단계는 여기서 마무리해도 좋을 것 같아 머지하도록 할게요.
코멘트 몇 개 남겨두었는데, 다음 단계 진행하면서 같이 확인해주세요!
수고 많으셨어요! 다음 단계도 화이팅입니다. 😃

2022-05-09 01:05 UTC, merged

2022-05-09 05:03 UTC, kimchan123 commented on src/main/java/wooteco/subway/dto/LineResponse.java
> +    }
체이닝으로 제거했습니다!