[Spring 지하철 노선도 - 1,2단계] 라라(박세은) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #249
Opened 2022-05-05 08:11 UTC by sure-why-not

`던` 안녕하세요!! 👋🏻👋🏻👋🏻 !!!!! 
이번 1,2단계 미션을 부탁드리게 된 `라라`입니다.👍🏻

1단계에서는 Collection 을 사용하여 DB 를 직접 구현했습니다. 싱글톤 객체로 직접 관리하다보니 매번 모든 테스트마다 deleteAll()을 해줘야하는 번거로움이 있더라구요.
2단계에서는 스프링이 Bean 으로 관리하도록 변경하니 이러한 번거로움을 덜어주는 이점을 느꼈습니다!! 🤭

스프링이 아직 익숙하지 않아서 부족한 점이 많을 것 같습니다. 많은 피드백 부탁드려요!!
잘 부탁드립니다. 🙇🏼‍♂️  ♥️

2022-05-05 09:12 UTC, gch01410 requested changes
안녕하세요 라라! 리뷰어 던입니다.
깔금하게 코드 작성해주셨네요! 👍 
코멘트 남겼으니 확인부탁드릴게요~!

2022-05-05 09:12 UTC, ghost commented on src/main/java/wooteco/subway/ui/StationController.java
>      @PostMapping("/stations")
`@RequestMapping`을 이용해서 경로중복을 제거해볼까요~?

2022-05-05 09:12 UTC, ghost commented on src/main/java/wooteco/subway/ui/StationController.java
>          return ResponseEntity.created(URI.create("/stations/" + newStation.getId())).body(stationResponse);
Request dto를 도메인 객체로 변환하는 작업, 도메인 객체를 Response dto로 변환하는 작업을 컨트롤러에서 하는게 좋을지 고민해봐주세요!
컨트롤러에서 도메인 객체에 직접 의존하고 있으면 어떤 불편한점이 생길지도 생각해볼 수 있을까요?

2022-05-05 09:12 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +        Optional<Station> foundStation = stationDao.findByName(station.getName());
Optional을 적절하게 사용하셨네요! 👍

2022-05-05 09:12 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +            throw new DataNotExistException("존재하지 않는 역입니다.");
라라의 커스텀 예외와 자바 기본 예외를 사용하는 기준을 알 수 있을까요~??

2022-05-05 09:12 UTC, gch01410 commented on src/main/java/wooteco/subway/dao/JdbcStationDao.java
> +        return new Station(id, station.getName());
저장한 후의 결과로 받은 데이터로 Station을 만들어야하지않을까요? 지금은 저장하려는 데이터로 값을 Station을 만들고 있네요!
rowMapper를 이용하도록 변경해봐요!

2022-05-05 09:12 UTC, gch01410 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    }
Line객체의 `equals, hashcode` 메서드를 재정의하면 좋을 것 같아요!

2022-05-05 09:12 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Line.java
> +public class Line {
domain패키지에 있는 클래스들도 테스트 코드를 작성해야하지 않을까요~?

2022-05-05 09:12 UTC, gch01410 commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
>          assertThat(resultLineIds).containsAll(expectedLineIds);
id뿐만 아니라 reponse body의 값들에 대해 확인해볼 수 있을까요~?

2022-05-05 11:00 UTC, sure-why-not commented on src/main/java/wooteco/subway/ui/StationController.java
>      @PostMapping("/stations")
앗 그렇네요!! @RequestMapping을 이용해서 경로중복을 제거했습니다~! 감사합니다!

2022-05-05 15:14 UTC, sure-why-not commented on src/main/java/wooteco/subway/service/StationService.java
> +            throw new DataNotExistException("존재하지 않는 역입니다.");
어플리케이션에서 공통적인 상황으로 분리하여 예외를 처리하고자 할 때 커스텀 예외를 사용하려했습니다. 표준예외를 사용하면 어디서 발생할지 모르는 내부적인 예외들과 함께 묶여 처리가 될 수 있기 때문에요! 그 외에는 상황에 맞는 표준 예외를 사용하려 하는 편인데, 혹시 잘못된 생각일까요?! 🤔

2022-05-05 15:53 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Line.java
> +public class Line {
앗 추가했습니다!! 🧐

2022-05-05 16:11 UTC, sure-why-not commented on src/main/java/wooteco/subway/dao/JdbcStationDao.java
> +        return new Station(id, station.getName());
이 부분에 대해서는 제가 해결 방법을 잘 못찾는 것 같아서 디엠드렸습니다!! 편하실 때 답변해주신다면 감사하겠습니닷!!! 🙏🏻🥺

2022-05-05 17:44 UTC, sure-why-not commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    }
해당 메서드는 테스트에서 저장/변경된 Line 의 name과 color 를 비교하려는 목적으로 만들었습니다.
그런데 equals, hashCode를 재정의해서 비교하게되면 entity의 핵심 식별자인 id 값을 포함해야하는데
테스트하는 목적과는 다르다고 생각하여 해당 메서드 네이밍을 isSameName 과 같이 변경해서 해결해보았습니다!
혹시 잘못된 생각이라면 알려주시면 감사하겠습니다!!

2022-05-06 06:18 UTC, sure-why-not commented on src/main/java/wooteco/subway/ui/StationController.java
>          return ResponseEntity.created(URI.create("/stations/" + newStation.getId())).body(stationResponse);
Controller 가 Dto 와 도메인간 변환 로직을 알아야할까?라는 의문이 들었습니다!
따라서 Dto 에서 책임을 갖는 것이 맞다고 생각하여  해당 로직을 수행하도록 변경했습니다!!

> 컨트롤러에서 도메인 객체에 직접 의존하고 있으면 어떤 불편한점이 생길지도 생각해볼 수 있을까요?
도메인 객체가 ui 랑 연결된 프레젠테이션 계층에 전달된다면 핵심로직을 가진 도메인 객체의 비즈니스 로직이 노출되어 객체가 전달되는 과정에서 변경될 가능성이 있는 문제가 있을 것 같습니다. 또는 도메인 객체의 노출되어선 안되는 중요 정보가 view 로 쉽게 접근하여 전달될 가능성도 있을 것 같습니다. 그런데 현재 도메인 객체는 불변객체이고, 중요 정보를 포함하진 않기 때문에 이 부분이 크게 문제되진 않는다고 생각한 것 같습니다! 🤔
2. 컨트롤러는 프레젠테이션 계층으로 변경이 일어날 가능성이 높은 반면 도메인 계층은 핵심 로직을 담고 있으므로 변경 가능성이 상대적으로 낮습니다. 근데 컨트롤러가 도메인 객체에 직접 의존하면 컨트롤러에 의해 도메인이 변경될 가능성 생기는 문제도 있을 것 같습니다.
3. 
제 생각은 여기까지만 드는데,, 혹시 던의 생각을 여쭤봐도 될까요?! 🥺

2022-05-06 06:18 UTC, sure-why-not commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
>          assertThat(resultLineIds).containsAll(expectedLineIds);
앗 그렇네요!! StationResponse 전체를 비교하도록 수정했습니다!! 😆

2022-05-06 06:20 UTC, sure-why-not commented
던 안녕하세요!! 👋🏻
생각지 못한 부분을 피드백해주셔서 감사합니다!! 🥺👍🏻
피드백 주신 내용 반영 및 궁금한 점을  코멘트 댓글로 달아두었습니다!
이번에도 잘 부탁드립니다~! 🙇🏻‍♀️

2022-05-07 10:55 UTC, gch01410 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    }
entity 식별자 개념도 이미 이해하고 계시군요! 👍 
라라 생각이 맞습니다! entity의 id외의 다른 값들이 같다고 같은 entity라고 볼 수는 없으니깐요!
`equals, hashcode를 재정의해서 값을 비교하는 방법도 있다!` 라는 것을 알려드리려고 피드백 남겼었습니다.
코드는 수정안하셔도 될 것 같습니다!

2022-05-07 11:13 UTC, gch01410 commented on src/main/java/wooteco/subway/service/StationService.java
> +            throw new DataNotExistException("존재하지 않는 역입니다.");
`어플리케이션에서 공통적인 상황으로 분리하여 예외를 처리하고자 할 때 커스텀 예외를 사용하려했습니다. 표준예외를 사용하면 어디서 발생할지 모르는 내부적인 예외들과 함께 묶여 처리가 될 수 있기 때문에요!`
-> 저도 라라의 생각에 동의합니다!

`그 외에는 상황에 맞는 표준 예외를 사용하려 하는 편인데, 혹시 잘못된 생각일까요?! 🤔`
-> 상황에 맞는 커스텀 예외를 만들 수는 없을까요? 
이미 등록된 역을 생성하려는 경우에는 IllegalArgumentException를 발생시키고 존재하지 않는역을 조회하는 경우 DataNotExistException를 발생시키고 있는데요. 이 2케이스는 Station과 관련된 처리를 하다가 발생한 공통적인 상황이 아닌가해요. 조금 더 구체적으로는 Statiodl 이미 있어서 발생하는 상황, 조회하려는 Station이 없어서 발생하는 상황으로 나눌 수는 있겠지만요!

DB,Web과 관련된 예외를 제외하고 자바 표준 예외를 그대로 사용하는것은 지양하는게 좋아요. 예외를 발생시켜야하는 새로운 상황이 추가될때마다 자바 표준예외를 사용하고 있는 모든 곳을 확인해서 같이 처리해도 되는지를 확인하는건 불편한 작업이 될 것 같네요.

2022-05-07 11:34 UTC, gch01410 commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +        assertThat(expectedStationResponses).containsAll(stationResponses);
💯 💯

2022-05-07 11:34 UTC, gch01410 commented on src/main/java/wooteco/subway/ui/StationController.java
>          return ResponseEntity.created(URI.create("/stations/" + newStation.getId())).body(stationResponse);
잘 이해하고 계시군요! 👍 
저도 라라와 같은 생각입니다. 더 생각나는 건 딱히 없네요..ㅎ
다만 request dto에서 직접 entity로 변환하고 있는데, Service 레이어에서 변환한다면 request dto와 entity의 의존성도 끊을 수 있겠어요. 지금은 entity의 값을 dto가 모두 갖고 있기때문에 직접 변환이 가능한데, entity가 조금 더 복잡하다면 사용하기 불편한 방식이 될 수있겠네요.
다음 단계 진행하시면서 고민해봐주세요!

2022-05-07 11:34 UTC, gch01410 approved these changes
안녕하세요 라라!
피드백 잘 반영해주셔서 딱히 코멘트 남길 부분이 보이지않네요.
다음 단계도 잘 부탁드리겠습니다.
수고하셨습니다!

2022-05-07 11:34 UTC, merged