[Spring 지하철 노선도 - 1,2단계] 제로(공재호) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #256
Opened 2022-05-05 09:53 UTC by asebn1

희봉 안녕하세요!!! 제로입니다. 😄 
처음뵙겠습니다. 잘부탁드려요!

이번미션에서는 이전 미션(체스)에 비해서는 어렵다고 느끼진 않았습니다.
그래서 페어와 구현하는 과정에서 궁금한 점을 하나하나 더 따져가며 페어프로그래밍을 진행하였습니다.
진행하면서 궁금한 점을 적어보았습니다. 희봉의 생각이 궁금해요!

---
db의 `LINE` 테이블은 id, name, color가 존재하며, name, color는 unique입니다. 그렇다면 LINE 테이블 비교 과정(equals, hashCode)에서, unique형태인 name, color값을 통해 같은지 판별할지, primary key인 id로 비교할지, primary key, unique 모두 함께 비교해야 할지에 대해 궁금증이 생겼습니다. 저는 모든 3가지를 모두 같이 판별하는 것이 좋겠다는 생각이 들었습니다!

2022-05-05 15:21 UTC, heebong requested changes
안녕하세요, 제로! 리뷰어 희봉입니다 😄 
미션에 맞게 코드를 잘 작성해주셨네요 👍 특히 코드 작성만 하지 않고 페어와 많은 논의를 나눴다는게 좋습니다. 새로운 프레임워크를 배워가는 과정이라 피상적인 기술적 스킬보다는 왜 이렇게 하는지 고민하는 것도 굉장히 중요합니다 👍 
몇가지 생각해보면 좋을 것들을 코멘트로 남겼어요. 질문주신 내용도 해당하는 부분에 댓글로 남겼습니다. 확인 부탁드려요. 😄 궁금한 내용이 생기면 언제든 DM 보내주세요!

2022-05-05 15:21 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +    private ExtractableResponse<Response> createPostStationResponse(Map<String, String> params) {
중복되는 부분 함수로 재사용 👍

2022-05-05 15:21 UTC, heebong commented on src/main/java/wooteco/subway/controller/StationAdvice.java
> +                HttpStatus.BAD_REQUEST
예외 메시지가 응답으로 내려가면 더 친절할 것 같아요 🙂

2022-05-05 15:21 UTC, heebong commented on src/main/java/wooteco/subway/controller/StationAdvice.java
> +public class StationAdvice {
advanced 🆙  `Station` 뿐 아니라 `Line`도 포함하는데 이름이 `Station`이네요. 더 적절한 이름이 없을까요? 😄 
(그냥 `ControllerAdvice`도 괜찮을 것 같아요 🙂 )

2022-05-05 15:21 UTC, heebong commented on src/main/java/wooteco/subway/ui/StationController.java
> +        StationResponse stationResponse = StationService.createStation(stationRequest.getName());
빈을 사용하지 않을때는 `dao`도, `service`도 `static` 클래스처럼 사용하셨네요. `Static` 클래스처럼 사용했을 때 어려웠던 점은 없었나요? 빈처럼 관리하는 것과 `static`으로 관리하는건 어떤 차이가 있을까요? 🤔 
hint 🖊️  아마 다형성을 사용하지 못할 것 같네요. 또 무엇이 있을까요? 😄

2022-05-05 15:21 UTC, heebong commented on src/main/java/wooteco/subway/ui/LineController.java
> +        List<Line> lines = LineDao.findAll();
`controller`에서 `service`를 건너뛰고 바로 `dao`를 사용하네요. `controller`가 `service`만 사용하는 것과, `service`와 `dao`를 모두 사용하는 것은 어떤 차이가 있을까요?

hint 🖊️  추상화, 계층

2022-05-05 15:21 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/LineAcceptance.java
> +        assertThat(response.header("Location")).isNotBlank();
`response` `body` 내용을 확인하면 더 촘촘한 검증이 될 것 같아요 🙂

2022-05-05 15:21 UTC, heebong commented on src/main/java/wooteco/subway/service/StationService.java
> +                .anyMatch(it -> it.getName().equals(name));
`Station`한테 `name`이 같냐고 물어봐도 좋을 것 같아요 😄

2022-05-05 15:21 UTC, heebong commented on src/main/java/wooteco/subway/service/StationService.java
> +    public StationResponse createStation(String name) {
advanced 🆙 `controller`의 `StationResponse`를 `service`가 알고있네요. (체스처럼) 만약 새로운 프론트가 생긴다면 `StationService`를 재사용할 수 있을까요? 👀

2022-05-05 15:21 UTC, heebong commented on src/main/java/wooteco/subway/domain/Line.java
> +        return Objects.hash(id, name, color);
`equals`, `hashCode` 기준에 대해 여쭤보셨죠. 👍 현재 코드에서 제로가 생각하기에 3가지 필드가 모두 동일해야 같은 도메인으로 판단한다면 괜찮습니다. 하지만 아래 내용을 생각해보면 좋겠어요.

3가지 조건을 모두 동일성 조건에 추가한다면 `hashCode`는 지금처럼 `id, name, color`로 조합이 되겠죠. 하지만 우리는 `Line`을 조회할 때 `Id`로 조회합니다. 만약 도메인이 `HashMap`에 `hashCode` 기준으로 들어있다면, `id`만을 가지고 도메인을 조회할 수 있을까요? 이런저런 생각을 해보는 것도 좋을 것 같네요 😄

2022-05-05 15:21 UTC, heebong commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private final JdbcTemplate jdbcTemplate;
advanced 🆙 jdbcTemplate을 왜 쓰는걸까요?
이번 미션의 주 내용이 jdbcTemplate 사용은 아니지만 왜 jdbcTemplate을 사용하는지 정리하고 가면 좋을 것 같습니다.
스파크에서 사용했던 것처럼, DriveManager로 Connection을 직접 만들어서 사용하지 않는 이유는 무엇일까요? 🤔 
우선 
1. jdbcTemplate이 어디서 bean으로 등록되는지 찾아보고
2. DataSource와 jdbcTemplate의 차이점이 무엇인지
3. 왜 Connection을 직접 관리하지 않고 DataSource를 사용하는지

알아보면 기초를 다지는데 도움이 될 것 같아요 😄 

hint 1 🖊️ 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/21075774/166217620-3028eeb9-60f4-48a2-bbe9-af8328eaf307.png">
DI 받는 곳에서 버튼을 클릭하면 빈이 선언된 곳을 갈 수 있어요!

hint 2 🖊️ 
책 [자바 웹 개발 워크북] `5.12 DB 커넥션풀 5.13 DataSource와 JNDI` 읽어보기 (이제 교육장 출근하면 책 빌려읽을 수 있을거에요 🙂 )

2022-05-06 23:40 UTC, asebn1 commented on src/main/java/wooteco/subway/controller/StationAdvice.java
> +public class StationAdvice {
변경하겠습니다!

2022-05-07 00:21 UTC, asebn1 commented on src/main/java/wooteco/subway/ui/StationController.java
> +        StationResponse stationResponse = StationService.createStation(stationRequest.getName());
우선, 1단계 진행을 static 클래스로 사용했을 때 가장 어려웠던 점은 테스트코드였습니다. 같은 static 변수를 공유하기 때문에, 하나의 테스트 결과가 다른 테스트 결과에 영향을 미쳤습니다. 이에 테스트 하나를 짜더라도 다른 테스트코드를 봐야 했습니다(unique 설정으로인한 다른 테스트에 사용했던 테스트값을 사용하지 않도록 하기 위함이었습니다!)

- static을 사용하면 다형성을 사용하지 못합니다.  또한, 상속 등 객체지향의 장점 또한 살릴 수 없습니다. 어플리케이션 실행시점에 메모리 단에 남아있고, 객체가 필요할 때 new 키워드가 아닌 전역함수처럼 사용한다는 점이 객체지향으로부터 멀어진다고 느껴졌습니다.
- 이에반해 `@Repository`, `@Service` , `@Controller` 등의 애너테이션을 스프링 빈에 간단히 등록할 수 있었습니다. 기본적으로 싱글턴으로 관리가 되며, 개발자가 필요한 곳에서 생성자를 통해 의존성 주입을 받을 수 있게 되었습니다.

결국, 의존성을 주입을 한 곳에서 처리해주는 DI 컨테이너를 통해 의존관계를 자동으로 주입해줄 수 있었습니다. 스프링 사용은 개발자의 편의도 도와주며 좋은 객체지향 코드에 더 다가갈 수 있게 도와주는 프레임워크구나를 느꼈습니다.

2022-05-07 01:00 UTC, asebn1 commented on src/main/java/wooteco/subway/ui/LineController.java
> +        List<Line> lines = LineDao.findAll();
계층간 가지는 의존성이 다르다고 생각합니다. 1단계 때 명확하게 구현하지 못한 것 같아요.
controller에서 dao를 사용하는 것은 문제라고 생각합니다.
스프링 계층으로 [프레젠테이션, 서비스, 데이터 접근] 3가지로 크게 나눌 수 있는데 각자 하는 역할이 다르다고 생각합니다. 계층 간 역할 추상화는 관리가 수월해져 개발 시점에서 많은 이점이 있다고 생각합니다.
- 프레젠테이션 계층 : 클라이언트 요청/응답 -> 비즈니스 단위
- 서비스 계층 : 애플리케이션, 도메인 모델의 적합성 -> 트랜잭션 단위
- 데이터 접근 계층 : CRUD -> DB 쿼리 단위

2022-05-07 01:28 UTC, asebn1 commented on src/main/java/wooteco/subway/service/StationService.java
> +    public StationResponse createStation(String name) {
재사용을 위해서 domain 형태로 반환해주는 것이 좋을 것 같아요!

2022-05-07 15:08 UTC, asebn1 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +    private final JdbcTemplate jdbcTemplate;
### 결론

- JbdcTemplate 장점
    - 코드 중복 감소 및 재사용성 증가
    - 추가 및 확장이 쉬움

### 1. 기존 JDBC의 사용

- 드라이버로딩 → DB연결 → SQL 작성/전송 → 자원해제
1. Connection 연결
2. 쿼리 작성 후 PreparedStatement 실행
3. 결과 처리 (resultSet)
4. Connection 닫기

### 2. JdbcTemplate 사용

- JdbcTemplate에 드라이버 로딩, DB연결, 자원해제 기능을 맡긴다

 → 개발자는 SQL작성/전송에 집중할 수 있다!

```java
jdbcTemplate.query(인자, 인자);
jdbcTemplate.query(인자, 인자)
```

- jdbcTemplate의 빈 등록
![image](https://user-images.githubusercontent.com/57438644/167260172-db21e1b5-360a-40a6-8cfe-a37a05698421.png)



### 3. DataSource란?

- JDBC 명세의 일부분이며 일반화된 연결 팩토리
- DB와 관계된 Connection정보를 담고 있으며, bean으로 등록하여 인자로 넘긴다.
- 하는일
    - DB 서버와 연결 (Property 설정: url, driver, username, password)
    - 트랜잭션 처리
    - DB Connection Pooling 기능 : 일정량의 Connection을 미리 생성시켜 저장소 저장, 프로그램 요청이 있으면 connection에서 꺼내 시간을 절약
- 관련코드
    
    ```java
    jdbc.driver = com.mysql.jdbc.Driver
    jdbc.url = jdbc:mysql//localhost:3306/databaseName
    jdbc.username = root
    jdbc.password = password
    ```
    

월요일 교육장에서 책 빌려 한번더 공부해보겠습니다!  :)

2022-05-07 16:29 UTC, asebn1 commented on src/main/java/wooteco/subway/service/StationService.java
> +    public StationResponse createStation(String name) {
dto를 각 계층마다 관리하도록 변경하였습니다!

2022-05-07 16:35 UTC, asebn1 commented
희봉, 안녕하세요! 빠른 피드백 감사합니다.

https://github.com/woowacourse/atdd-subway-map/pull/256#discussion_r866020753
가장 많이 고민했던 부분입니다.
- 처음 재사용을 위해 service에서 controller에 domain을 넘겨주도록 변경하였습니다. 하지만, controller는 클라이언트의 요청/응답을 위한 계층이기에 도메인값이 아닌 응답값을 넘겨주어야 한다는 결론을 내렸습니다.
- 이에 DTO를 어떻게 설계할지 다시 공부하였습니다. 기존에는 `god class`처럼 하나의 dto가 통해 중복을 허용하며 계층 어느곳이든 사용되었습니다. 이에 변경 대상 클래스 숫자(DTO)가 늘어나게 되었습니다. 관리할 대상이 많아지기에 나쁜 설계가 아닌가 하는 의문도 들었습니다. 
- 하지만, **지향점은 변경 대상 클래스 수가 적어지는 설계가 아닌, 필요한 부분에 집중해서 변경하도록 범위를 제한하는 것**. 그것이 설계/책임이 구분되도록 도메인 모델을 망치지 않는다는 점을 깨달았습니다.

[공부하며 정리한 글](https://jaehhh.tistory.com/70)

---

이번기회에 DTO 설계를 다시 시도해보면서 시간이 좀 더 걸렸던 것 같아요!
이번에도 리뷰 잘 부탁드려요! :)

2022-05-08 04:11 UTC, heebong approved these changes
안녕하세요, 제로! 리뷰어 희봉입니다 😄 
피드백을 잘 반영해주셨네요 👍 추가로 dto에 대한 정리까지 👍 고생하셨습니다.
이번 단계는 여기서 머지하도록 할게요. 코멘트를 조금 남겼으니 다음 단계를 진행할 때 같이 확인 부탁드려요 😄 
언제든 궁금한 내용이 있으면 DM 아시죠? 😉 그럼 다음단계에서 만나요~

2022-05-08 04:11 UTC, heebong commented on src/main/java/wooteco/subway/controller/StationController.java
> +                .map(it -> ControllerDtoAssembler.stationResponseByDTO(it))
메서드 참조로 변경할 수 있네요. IDE의 추천을 따라볼까요 😄

2022-05-08 04:11 UTC, heebong commented on src/main/java/wooteco/subway/controller/ControllerAdvice.java
> +    @ExceptionHandler({IllegalArgumentException.class, NoSuchElementException.class})
advanced 🆙 리소스가 없을 때는 `notFound()`도 좋습니다 🙂 (`NoSuchElementException`와 `IllegalArgumentException`를 나눠도 좋을 것 같아요)

2022-05-08 04:11 UTC, merged