[Spring 지하철 노선도 - 3단계] 후니(최재훈) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #263
Opened 2022-05-10 11:40 UTC by jayjaehunchoi

안녕하세요 제이! 
3단계 마무리하여 리뷰 요청드립니다.

이번 단계를 진행하면서 몇가지 궁금했던 점이 있어 질문 드립니다.

### 1. 인수테스트 주도 개발을 한다면 각 레이어에 대한 단위테스트를 해야하는가?
이번 개발을 진행하며 도메인 로직은 tdd로 전체 요청에 대한 응답은 atdd로 개발했습니다.
이 때 이미 도메인은 테스트 하였고, repository 레이어도 테스트 했다보니, Service 로직에 대한 테스트가 크게 필요하지 않다고 느꼈습니다.
이런 경우에도 Service에 대한 테스트 코드를 타이트하게 짜주는게 좋을까요?

### 2. 인수테스트에서 Repository를 직접 사용해도 괜찮은가?
인수테스트를 위한 환경을 세팅하는 데 있어 Repository의 save를 직접 호출했습니다. 기존에 존재하는 환경은 db에 저장되어 있는 것을 사용하는 것이다 보니 이런 선택을 했는데요. 이런 관점으로 사용해도 괜찮을까요?

atdd를 처음 겪다 보니 아직 미숙한 점이 많은 것 같네요.
그리고 제이가 조언 주신 내용은 아직 고민 중이라 이번 단계에서 계속 고민 더 해보겠습니다. 

리뷰 잘 부탁드립니다!

2022-05-13 02:30 UTC, kang-hyungu requested changes
후니 몇 가지 코멘트 남겼어요
수정해보시고 리뷰 재요청주세요.

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/dao/LineRepository.java
>  package wooteco.subway.dao;
클래스명은 repository인데 패키지는 dao네요

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/dao/LineRepository.java
> +    static class LineSection {
repository에서 클래스를 정의하는 이유가 무엇인가요?

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/dao/LineRepository.java
> +        String sql = "SELECT l.id as line_id, l.name, l.color, "
as는 왜 소문자로 쓰시나요?

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Line.java
> +            throw new IllegalArgumentException("[ERROR] 잘못된 입력값입니다.");
어떤 값이 잘못된 입력일까요? 클라이언트가 어떻게 알 수 있을까요?

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Line.java
> +        this(null, name, color, null);
id, sections를 null로 설정할 수 있게 했을 때, 클라이언트에서 잘못 사용해서 NPE를 발생시킬 수 있는 여지를 만드는 것은 아닐까요?

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final Long lineId;
Line 객체를 사용해도 되지 않나요?

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Section.java
> +    public Section(final Long id,
자바 스타일 가이드를 참고해봅시다.

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Section.java
> +        return equals(section)
isSameSection 메서드와 다른 형태로 엔터가 들어가 있네요
자바 스타일 가이드 참고해서 정리해보시기 바랍니다.

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Sections.java
> +        this.values = new ArrayList<>(values);
add 메서드와 달리 기본 생성자에서는 유효성 검사를 안해도 될까요?

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Sections.java
> +        validateExistSection(section.getUpStation(), section.getDownStation());
getter를 제거해보시기 바랍니다.

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .ifPresent(value -> {
ifPresent는 예외를 던지기 위한 목적으로 쓰지 않습니다.
anyMatch로 값을 찾아서 if절 추가해서 예외 던지는게 어떨까요

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .orElseThrow(() -> new SectionCreateException(SECTION_NOT_CONNECT_MESSAGE));
소나린트에서 경고를 띄우네요
<img width="806" alt="image" src="https://user-images.githubusercontent.com/15669435/168199588-e168e480-f310-47b6-9386-c754ec1564f0.png">

2022-05-13 02:30 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private void cutInSection(final Section section) {
좀더 개선할 방법 없을까요?

2022-05-13 04:44 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/dao/LineRepository.java
> +    static class LineSection {
해당 레포지토리에서 join쿼리를 수행하고 가져온 값을 객체로 래핑해서 반환하려고 사용했습니다. repository에서만 사용하기 때문에 inner class로 정의해두었습니다.

2022-05-13 04:47 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/dao/LineRepository.java
> +        String sql = "SELECT l.id as line_id, l.name, l.color, "
수정하였습니다!

2022-05-13 04:50 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final Long lineId;
제가 lineId를 사용한 이유는 아래와 같습니다.

1. Line을 직접 사용하는 로직이 존재하지 않는다.
2. Line은 id로 식별이 가능하다.

2022-05-13 04:52 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/domain/Sections.java
> +        this.values = new ArrayList<>(values);
생성자를 쓰는 경우는 이미 저장된 값을 db에서 조회하여 객체로 생성할 때입니다. 그런 이유에서 유효성 검사를 추가하지 않았습니다!

2022-05-13 05:51 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .orElseThrow(() -> new SectionCreateException(SECTION_NOT_CONNECT_MESSAGE));
함수 호출 후 부작용이 없음에도 해당 결과값을 사용하지 않으면 이 함수 자체는 의미가 없고, 예상대로 작동하지 않을 가능성도 있다고 하네요. (사용하지 않음으로써 예상 작동과 달라질 수 있다는 의미라고 생각합니다.)

따라서, 필터 내용을 `anyMatch`를 통해 boolean으로 반환하고 에러를 던지는 방향으로 수정했습니다.

2022-05-13 06:07 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/domain/Section.java
> +    public Section(final Long id,
닫는 괄호를 파라미터에 이어서 작성하였습니다!

2022-05-13 06:08 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/domain/Section.java
> +        return equals(section)
non-assignment 연산자에서 줄 바꿈이 일어날 경우 바꿈은 기호 이전에 위치한다. 
다만 쉼표는 이전 토큰과 사용하고 줄바꿈을 한다.

2022-05-15 09:40 UTC, jjj0611 requested changes
안녕하세요 후니! 리뷰어 제이입니다.

구현해주신 코드 잘 봤습니다 👍

간단하게 코멘트 몇 개 남겨두었으니 확인 부탁드려요!

크지 않은 부분이라 빠르게 보실 수 있으실 거에요 :)

2022-05-15 09:40 UTC, jjj0611 commented on build.gradle
> +	//implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
왜 주석처리 하셨나요??

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/ui/ControllerAdvice.java
> +        return ResponseEntity.internalServerError().body(new ErrorResponse("[ERROR] 데이터를 조회할 수 없습니다."));
모든 Exception에 대한 응답이 데이터를 조회할 수 없다는 응답으로 적절한가요??

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/StationService.java
> +        validateDuplicateName(stationRepository.findByName(stationRequest.getName()).isPresent());
이렇게 validation을 했을 때, 방어되지 않는 케이스는 없을까요??

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/StationService.java
>  public class StationService {
delete할 때 해당 역이 특정 라인에 등록되어 있으면 어떻게 되나요??

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +        validateDuplicateName(lineRepository.findByName(lineRequest.getName()).isPresent());
여기도 마찮가지로 이렇게 판단할 경우 어떤 문제가 발생할 수 있을까요??

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +        Line line = new Line(id, lineRequest.getName(), lineRequest.getColor(), new Sections(Collections.emptyList()));
여기서 라인을 한 번 더 생성할 필요가 있나요??
아래 쪽에 section까지 저장이 되었을 때,
section을 넣은 상태로 저장하면 안되나요??

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    public List<Section> delete(final Station station) {
section에서 station 하나를 delete하면 sections 내부에도 merge된 section이 있어야 하지 않을까요?

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        cutInSection(section);
이 유효성 검증 부분이 조금 단순하게 풀어질 수 없을까요??

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/SectionService.java
> +        sections.pickUpdate(sectionRepository
이 로직은 왜 필요할까요?
sections.add(section);
sectionRepository.save(sections);
를 하면 충분하지 않을까요?

2022-05-15 09:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    public void delete(final Long lineId, final Long stationId) {
여기도
sections.delete(station);
sectionsRepository.update(sections);
를 하면 안될까요??

2022-05-16 02:51 UTC, jayjaehunchoi commented on build.gradle
> +	//implementation 'net.rakugakibox.spring.boot:logback-access-spring-boot-starter:2.7.1'
사용하지 않는 디펜던시라 주석해두었는데 지우질 않았네요 수정했습니다!

2022-05-16 05:20 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/service/SectionService.java
> +        sections.pickUpdate(sectionRepository
기존에 존재하지만 달라진것으로 판단하여 update를 날리고자 하였습니다.

제이라면 어떤 방법을 사용하시나요?

2022-05-16 05:22 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/service/SectionService.java
> +    public void delete(final Long lineId, final Long stationId) {
sections 전체를 update로 넘기면 쿼리가 모든 구간에 대해 전부 나가는데 이런 부분은 고려하지 않아도 될까요?

2022-05-16 05:53 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/service/LineService.java
> +        validateDuplicateName(lineRepository.findByName(lineRequest.getName()).isPresent());
optional 값이 코드에서 오염이 될경우 문제가 생길수도 있다고 판단했습니다.

따라서 데이터베이스 자체에서 EXISTS쿼리를 던져 boolean으로 반환받도록 변경했습니다.

다른 문제가 더 있을까요?

2022-05-16 05:53 UTC, jayjaehunchoi commented on src/main/java/wooteco/subway/service/StationService.java
>  public class StationService {
검증해주도록 수정했습니다!

2022-05-16 14:37 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/LineService.java
> +        validateDuplicateName(lineRepository.findByName(lineRequest.getName()).isPresent());
다른 문제가 더 있을 수 있는데
이건 미션을 좀 더 진행하면서 고민해보도록 하면 좋을 것 같아요 :)

2022-05-16 14:40 UTC, jjj0611 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    public void delete(final Long lineId, final Long stationId) {
엇 고려할 수 있으면 당연히 좋습니다!
저는 코드적인 측면으로 말씀드린거였어요.

그러면 그걸 고려할 수 있도록 코드를 추상화 할 수도 있겠죠?
혹은 고려하지 않고 로직을 짤 수도 있구요.

이것도 다음 단계를 계속 진행하면서 같이 고민해보면 좋을 것 같아요 :)

2022-05-16 14:42 UTC, jjj0611 approved these changes
안녕하세요 후니. 리뷰어 제이입니다!

리뷰 남겨드린 것 잘 확인해주셨네요.
코멘트 달아주신 내용에 답글 조금 남겨드렸어요.

전반적으로 다음 미션을 진행하시면서 계속 고민해보면 좋을 것 같습니다!

코드는 다음 미션 진행을 위해 여기서 이만 머지할게요!
고생하셨습니다 :)

2022-05-16 14:42 UTC, merged