[Spring 지하철 노선도 - 3단계] 써머(최혜원) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #265
Opened 2022-05-10 12:24 UTC by hyewoncc

안녕하세요, 로운! 저번에 남겨주신 피드백은 다 반영했습니다 
부족한 점이 제 눈에도 많이 보이는 코드지만, 더 늦어지면 다음 미션 때문에 피드백을 반영할 시간이 없을 것 같아 pr 올렸습니다 😭💦  
이번 미션을 진행하면서 `atdd`를 처음 접해서 궁금한 점이 하나 있었습니다!

현재 제 코드의 컨트롤러 메서드는 대부분 굉장히 짧게 이루어져 있는데요, 
`service` 메서드를 호출해 반환값을 바로 `ResponseEntity`에 넣거나, 아니면 반환도 없이 응답 코드를 지정하는 것이 많습니다  
컨트롤러에 대한 유닛 테스트를 `mockito` 라이브러리를 이용해 한 번 작성해봤는데요, 
컨트롤러 내 로직이 짧아서 그런가 인수 테스트와 큰 차이점을 느끼지 못했습니다 
`mock`으로 넣은 반환 지정값을 바로 검사하는 것 처럼 보였고요  
이런 경우에는 해당 메서드 테스트를 생략했다가 나중에 로직이 추가 됐을 때 작성하는 건 좋지 않은 방안일까요?  
예외처리는 `mock`으로 테스트 하니 좋게 느껴졌습니다 👍

3단계도 잘부탁드려요!!

2022-05-11 00:31 UTC, lowoon commented
네 controller테스트에 대해서는 같이 하고 있는 페어 혹은 팀에 따라 달라질 수 있을텐데요.
controller 테스트를 어떤 테스트로 볼 것이냐에 따라 달라질 수 있을 것 같아요.
써머가 진행을 한 방식은 mock을 이용한 단위테스트인데, 그렇게 되면 현재 통합테스트는 없거든요.
각각의 테스트가 무엇을 의미하는지, 어떤 테스트를 하는게 나을지 고민을 해보면 좋을것 같아요.
고민해보고 써머의 생각을 말씀해주시면 제 개인적으로 생각하는 것을 말씀드릴게요!

https://tecoble.techcourse.co.kr/post/2021-05-25-unit-test-vs-integration-test-vs-acceptance-test/

2022-05-11 02:24 UTC, hyewoncc commented
링크해주신 글 잘 읽었습니다, 인수 테스트는 내부를 모르는 `블랙박스` 테스트 라는 표현이 와 닿네요! 
글을 읽고 `LineController` 클래스를 기준으로 생각한 방안을 정리해봤어요  
- `controller`가 `service`에서 반환받은 값을 바로 보내는 메서드의 경우에도 `단위 테스트`가 필요하다  
  - 경로 매핑이 제대로 되었는지, status나 헤더값이 올바르게 반환되는지를 확인하기 위함이다  
- `controller`의 `통합 테스트`는 메서드 별로 작성하며, 실제 객체를 이용한다  
  - 하위 `service`, `repository` 등의 클래스와 제대로 협력하는지 알기 위함이다  
  - 또한 `JdbcTemplate` 같이 내가 제어할 수 없는 요소를 묶어 테스트하기 위함이다  
- `인수 테스트`는 컨트롤러와 별개로 사용자 관점의 가상 시나리오대로 작성한다  
  -  ex. `통합 테스트`에서 중복 역 등록 불가 예외를 검사할 때
    - 통합 테스트 : DB에 역 값을 넣어두고 같은 값을 넣어서 예외 처리 메서드가 제대로 동작하는지 확인한다  (내부 구현을 안다)  
    - 인수 테스트 : 사용자가 같은 이름의 역을 두 번 생성했다고 가정하고 요청을 실행한다  (내부 구현을 모르기에 요청 -> 결과만 확인한다)  

`인수 테스트`는 시나리오대로 작성해야 하니 컨트롤러 별로 작성한다는 관점보다, 흐름에 따라 요청(복수가 될 수 있음) -> 결과 확인에 중점을 두어야 한다고 이해했습니다

2022-05-11 04:03 UTC, lowoon commented
네 맞습니다! 💯 
저의 개인적인 의견으로는 service는 비지니스 로직과 연관이 있기 때문에 mock으로 단위 테스트를 진행하고,
controller는 통합테스트를 진행하는 것 같아요. 단위테스트와 통합테스트를 모두 하는 것은 시간과 노력, 유지비용이 많이 든다고 생각하기 때문에 통합테스트 하나만 진행을 하는 것 같구요.
말씀하신 것과 같이 통합테스트와 인수테스트는 목적이 다르기때문에 모두 작성하면 좋다고 생각하는데 팀의 상황이나 컨벤션에 따라 둘 중 하나만 할 수도 있다고 생각합니다!
현재는 학습을 하고 있는 상황이니 모두 작성하는게 좋지 않을까 생각합니다!

2022-05-11 06:44 UTC, lowoon requested changes
반가워요 써머! 2단계도 잘 부탁해요 😄 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점이 생기면 언제든지 DM 혹은 댓글남주세요 ^-^

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/dto/SectionRequest.java
> +        NullChecker.validateInputsNotNull(upStationId, downStationId, distance);
`@Valid`를 활용하는 검증을 사용해보면 어떨까요?

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/error/ExceptionAdviser.java
> +        return ResponseEntity.notFound().build() ;
클라에 보여지는 메세지가 사라진 이유가 있나요?

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/repository/LineRepository.java
> +public class LineRepository {
repository의 역할을 domain 반환, dao의 역할을 db의 데이터 반환(dto)로 정한걸까요?

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Station.java
>      public Station() {
이 부분도 private이여도 될거 같아요~

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/repository/LineRepository.java
> +            Station up = stationDao.findById(sectionDto.getUpStationId());
가져온 구간들의 stationId들을 매번 조회하고 있는데요.
모든 id들을 취합한 후에 `findByIdIn`과 같이 한번에 조회하면 query를 한번만 사용해도 되지 않을까요?

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Sections.java
> +        LinkedList<Section> sections = new LinkedList<>(List.of(mixedSections.remove(0)));
상행 종점의 경우 Station up이 null일텐데요.
이 section을 찾은 다음에 down을 순서대로 찾아가면 좀 더 로직이 파악하기 쉽지 않을까요?

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Relation.java
> +    EXTEND,
이 enum의 역할이 필요한가 싶은 개인적인 생각이 드네요 🧐

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Sections.java
> +            Section origin = sections.get(i);
for문을 메서드로 빼는 방법이 있을 것 같구요.
for문으로 index만 찾고 divideBy의 return 값이 List를 반환하도록 해서 addAll을 해줄 수도 있을 것 같아요.
하나의 메서드에서 너무 많은 로직이 있는 것 같아요~

2022-05-11 06:44 UTC, lowoon commented on src/test/java/wooteco/subway/controller/LineControllerTest.java
> +class LineControllerTest {
section에 대한 테스트는 없네요?

2022-05-11 06:44 UTC, lowoon commented on src/test/java/wooteco/subway/controller/StationControllerTest.java
> +class StationControllerTest {
테스트 질문에 답변 단 부분을 고민해보고 써머가 맞다고 생각하는 방향으로 작업해주시면 될 거 같아요~

2022-05-11 06:44 UTC, lowoon commented on src/test/java/wooteco/subway/repository/LineRepositoryTest.java
> +class LineRepositoryTest {
다른 repository에 대한 테스트는 없네요?

2022-05-11 06:44 UTC, lowoon commented on src/main/java/wooteco/subway/repository/SectionRepository.java
> +    public SectionRepository(JdbcTemplate jdbcTemplate, StationDao stationDao) {
주입받은 StationDao가 안쓰이는 것 같은데요??

2022-05-11 07:41 UTC, hyewoncc commented on src/main/java/wooteco/subway/error/ExceptionAdviser.java
> +        return ResponseEntity.notFound().build() ;
api 문서 상 404를 반환해야 해서 바꿨는데, notFound()는 메서드 체이닝으로 바디를 붙일 수 없어서 원래 404 응답은 body를 보내지 않는 건가 싶어 뺐었습니다 😅
찾아보니 status code 따로, body 따로 지정하면 보내줄 수 있어서 그렇게 수정했어요!

2022-05-11 07:43 UTC, hyewoncc commented on src/main/java/wooteco/subway/repository/LineRepository.java
> +public class LineRepository {
네 맞습니다 ..!

2022-05-11 12:08 UTC, hyewoncc commented on src/main/java/wooteco/subway/domain/Sections.java
> +        LinkedList<Section> sections = new LinkedList<>(List.of(mixedSections.remove(0)));
`Section`은 무조건 두 `Station`으로 이뤄져 있어요!
일단 로직이 제가 보기에도 지저분한 것 같아 개선해보겠습니다

2022-05-11 12:58 UTC, hyewoncc commented on src/main/java/wooteco/subway/domain/Sections.java
> +            Section origin = sections.get(i);
메서드 분리 후 List 반환되도록 수정했습니다! 훨씬 낫네요

2022-05-12 00:36 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Sections.java
> +        LinkedList<Section> sections = new LinkedList<>(List.of(mixedSections.remove(0)));
아 저거는 제가 했던 방식이였네요 😭 
저는 무조건 있어야한다고 생각하지 않아서 첫번째 section의 up을 null, down을 첫번째 stationId로 했는데 이러한 방법이 있다고만 참고하시면 될 거 같아요.
저 방식대로 수정할 필요는 없고 저런 방식도 있으니 section을 정렬하는 나은 방법이 없는지 한번 고민만 해보시면 좋을 것 같습니다!

2022-05-13 06:32 UTC, hyewoncc commented
안녕하세요, 로운! 주신 피드백 감사하게 잘 읽었습니다 ☺️ 
컨트롤러와 서비스의 경우 내부 로직이 없는 경우가 대부분이라 통합테스트를 추가하는 방향으로 개선했습니다  
특히 서비스는 `repository`에서 도메인을 꺼내오고, 도메인의 메서드를 실행시키는 부분이 대부분이라,

2022-05-14 04:42 UTC, lowoon commented on src/main/java/wooteco/subway/error/ExceptionAdviser.java
> +        return ResponseEntity.notFound().build() ;
네 이 부분은 어떻게 진행하냐에 따라 달라질 수 있을텐데요.
404가 api 자체가 존재하지 않는 경우에는 클라에서 404 페이지를 보여줄 수 있을텐데, 만약 역이 없다는 것을 404로 내려주었을 때에는 그에 맞는 메세지가 필요할 것 같아서요.
이 부분 역이 없을 때 404를 내리지 않고 400을 내리거나 클라에서 404의 메세지에 따라 다르게 보여주는 등의 방식으로 할 수 있을 거라 팀 혹은 페어와 이야기해서 결정하면 될 거 같습니다~

2022-05-14 05:12 UTC, lowoon approved these changes
안녕하세요 써머!😄
이제 그만 지하철 노선도 미션을 마무리해도 될 것 같아요.
고민해보면 좋을 코멘트를 남겼으니 확인 부탁드려요ㅎㅎ
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

1, 2단계 지하철 노선도 미션 수고하셨습니다!

2022-05-14 05:12 UTC, lowoon commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
>  public class LineAcceptanceTest extends AcceptanceTest {
시나리오 테스트라는 것은 실제 사용자가 사용하는 흐름으로 진행하는 것을 테스트하는데요.
예외에 대한 것들도 테스트가 필요하지만 예외보다는 실제 사용자가 제대로된 흐름으로 동작을 했을 때 제대로 동작하는 지가 더 중요할 거라고 생각해요. 실제 사용자가 사용하는 흐름을 시나리오로 적거나 정리해보면 어떨까요?
```
Feature: 지하철 노선 관리
    Scenario: 지하철 노선 생성
        When 지하철 노선 생성을 요청하면
        Then 지하철 노선 생성이 성공한다.
    Scenario: 지하철 노선 목록 조회
         Given 지하철 노선 생성을 요청하고
...
```
```
Feature: 지하철 노선 관리

  Scenario: 지하철 노선을 관리한다.
    When 지하철 노선 n개 추가 요청을 한다.
    Then 지하철 노선이 추가 되었다.
    
    When 지하철 노선 목록 조회 요청을 한다.
    Then 지하철 노선 목록을 응답 받는다.
    And 지하철 노선 목록은 n개이다.
...
```
위의 두가지 경우처럼 나눌 수도 있고 더 다양하게 나누는 방법이 있을텐데요.
써머가 생각하는 시나리오를 한번 생각해보고 그것에 맞게 테스트를 작성해 보면 좋을 것 같아요!

2022-05-14 05:12 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Sections.java
> +        LinkedList<Section> sections = new LinkedList<>(List.of(mixedSections.remove(0)));
다른 분이 한 방법중에는 downStationId를 가져온 후 upStationId와 겹치는 것이 없는 section을 찾아 상행종점을 찾은 후에 정렬을 시키는 방식으로 하더라고요.
이 부분은 시스템의 효율성과 코드의 명확성 사이에서 고민이 있을 수 있을텐데요.
다른 사람이 볼 때 이해하기 쉬운 코드와 for문의 반복을 줄여 시스템의 효율성을 높이는 방법 중에서 어떤 부분이 더 중요한지 어떤 상황에서 어디에 더 중점을 둘 것인지 한번 고민해보면 좋을것 같아요ㅎㅎ

2022-05-14 05:12 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Sections.java
> +        }
```suggestion
     method1
        for (int i = 0; i < sections.size(); i++) {
            Section origin = sections.get(i);
             if (origin.isSameUpStation(section) || origin.isSameDownStation(section)) {
                 return i;
             }
        }
       
       method2
        sections.remove(i);
        sections.addAll(i, origin.divideBy(section));
```
저는 이렇게 2 부분으로 나누는 방법을 생각했습니다!
어떻게 하는게 나을지는 써머가 생각해보고 정하면 될 것 같아요ㅎㅎ

2022-05-14 05:13 UTC, merged

2022-05-14 05:29 UTC, lowoon commented on src/main/java/wooteco/subway/service/LineService.java
> +    private final LineRepository lineRepository;
lineService가 StationRepository를 가지고 있는데요.
StationService가 station과 관련된 로직을 담당하는 서비스인데 이곳에서 StationRepository를 가지는 것이 맞을까요?
역할과 책임에 대해 한번 고민해보면 좋을것 같아요!