[Spring 지하철 노선도 - 3단계] 열음(이주형) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #270
Opened 2022-05-11 00:08 UTC by Juhyung990122

안녕하세요 릭! 열음입니다:)
1,2단계 피드백 반영 및 3단계 구현을 마쳐서 리뷰요청 드려요.
아쉬운 부분이 많이 보이는데 리뷰 반영하기에 시간이 부족할 것 같아서 일단 pr 보내놓고 계속 수정하고 있겠습니다.
+) 리뷰남겨주신 컨트롤러 테스트도 해보고 있을게요!😆
언제나 감사합니다ㅎㅎ

2022-05-12 12:22 UTC, wbluke requested changes
3단계도 잘 진행해 주셨네요 ㅎㅎ
다만 프로덕션 코드와 테스트 모두 전체적으로 리팩토링 해야할 부분이 많이 보이는데요.
차근차근 진행해보면 좋을 것 같아요 🙂

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/service/SectionService.java
> +                    .orElseThrow(() -> new IllegalArgumentException("해당 역이 존재하지 않습니다."));
음 Service 로직 전체적으로 `find()` 후에 `orElseThrow()`를 하면서 동일한 예외 메시지를 던지는 부분이 많은데요.
사용자향 메시지가 달라지거나 하면 전부 수정해야 하지 않을까요? 중복 로직이기도 하고요 :)

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Section.java
> +    public Section(SectionRequest sectionRequest, long lineId) {
도메인 객체가 DTO를 알게 되면 어떤 문제가 있을까요? :)

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Section.java
> +        return lineId == section.lineId && upStationId == section.upStationId && downStationId == section.downStationId && distance == section.distance;
https://github.com/woowacourse/atdd-subway-map/pull/227#discussion_r871277904
코멘트 참고해 주세요 :)

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private List<SectionWithStation> sections;
Sections 일급컬렉션이라면 Section으로 이루어진 컬렉션을 가지고 있어야 할 것 같아요.
그리고 SectionWithStation이라는 도메인은 잘 리팩토링한다면 불필요한 도메인인 것 같아요.
 id 기반으로 이루어진 Section만을 활용해서 전체적으로 수정해볼 수 있을까요? :)

(힌트: Station이라면 나중에 Service에서 stationId를 가지고 조회해도 충분해요)

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return sections.size() <= 1;
Sections를 만들 때 empty를 허용하지 않는다면 size가 1인지 체크하는 API만 있어도 충분할 것 같아요 :)

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/dto/LineRequest.java
> +    @NotBlank
보통 요런 validation을 할 때 message도 같이 남겨서 어떤 필드가 문제가 되는지를 클라이언트에게 알려주면 좋습니다 :)
```java
@NotBlank(message = "이름 값은 필수입니다.")
```

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/dto/LineResponse.java
> +    public LineResponse(Long id, String name, String color, List<StationResponse> stations) {
`List<Station>`을 받아서 내부에서 StationResponse를 만들어도 될 것 같아요 :)

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
음 파라미터의 station이 모든 구간의 downStation과 일치하지 않는다고 해서 첫번째 Station임을 보장할 수 있을까요?
위에 isLastStation() 도 마찬가지네요.

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Sections.java
> +    public List<StationResponse> sortStations() {
Section에도 남겼는데, 도메인 객체가 DTO를 알고 있다면 어떤 문제가 발생할까요?

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .filter(section -> isLastStation(section.getDownStation()))
sections stream을 돌면서 isLastStation에서 또 stream을 도네요.
N x N 만큼 루프가 돌면 Section이 늘어날 수록 성능 저하가 있겠네요.
더 개선해볼 수 없을까요?
(Hint. 구간 정렬을 할 때가 문제인 것 같은데, 특정 위치에 있는 구간을 찾으려고 하기보다 상행역으로만 검색하여 구간을 찾는 API 하나, 하행역으로만 검색하여 구간을 찾는 API 하나를 각각 만들어서 로직을 개션해보면 어떨까요?)

2022-05-12 12:22 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Sections.java
> +public class Sections {
핵심 도메인 객체인데 단위 테스트가 없네요!

2022-05-12 12:22 UTC, wbluke commented on src/test/java/wooteco/subway/ui/LineControllerTest.java
> +    }
테스트 작성하실 예정인가요?

2022-05-12 12:22 UTC, wbluke commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +@Transactional
저는 통합테스트에 트랜잭션 롤백을 사용하는 것을 좋아하지 않는데요.
왜냐하면 이렇게 되었을 때 Service에 트랜잭션이 누락된 경우 테스트는 통과하고 프로덕션 코드는 트랜잭션이 보장되지 않아 문제가 있는 채로 배포되어 장애를 야기할 수도 있습니다.
after 절에서 Test Fixture 일괄삭제를 진행해보면 어떨까요?

2022-05-12 12:22 UTC, wbluke commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    @DisplayName("기존 구간의 길이가 추가하려는 구간의 길이보다 짧다면 예외를 발생시킨다.")
보통 경계값 테스트를 하는 것이 중요한데요.
10과 20 보다는
- 1 차이 나서 구간 등록이 실패하는 경우
- 구간 길이가 같아서 구간 등록이 실패하는 경우

이렇게 케이스를 설정해야 할 것 같아요.

2022-05-12 12:22 UTC, wbluke commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +        assertThat(sectionDao.findByLine(line.getId()).get()).hasSize(1);
1-2-3 중에 2를 삭제했다면 남은 구간의 역이 1, 3번 역이라는 것도 검증해야 하지 않을까요? :)

2022-05-12 12:22 UTC, wbluke commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    @DisplayName("삭제하려는 역이 포함된 구간이 존재하지 않으면 예외를 발생시킨다..")
아련미..

2022-05-12 12:22 UTC, wbluke commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +        assertThat(sectionDao.findByLine(line.getId()).get()).hasSize(2);
세 테스트 모두 size 체크에서 끝나는 것이 아니라, 구간 별 역과 길이가 정확하게 책정되었는지를 검증해야 할 것 같아요.

2022-05-12 12:22 UTC, wbluke commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    @DisplayName("구간을 추가한다(중간)")
중간 추가 테스트는
- 1-3 구간에 1-2를 추가하는 경우
- 1-3 구간에 2-3을 추가하는 경우

이렇게 세분화해야 하지 않을까요? :)

2022-05-13 23:22 UTC, Juhyung990122 commented on src/test/java/wooteco/subway/ui/LineControllerTest.java
> +    }
넵! 나눠서 커밋하려다보니 이렇게 빈것들이 올라갔네요🥲
지금은 전부 작성했습니다!

2022-05-13 23:22 UTC, Juhyung990122 commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    @DisplayName("삭제하려는 역이 포함된 구간이 존재하지 않으면 예외를 발생시킨다..")
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ삭제했습니다^_^

2022-05-14 23:42 UTC, Juhyung990122 commented on src/main/java/wooteco/subway/service/SectionService.java
> +                    .orElseThrow(() -> new IllegalArgumentException("해당 역이 존재하지 않습니다."));
수정할때 번거로울 것 같아서 중복적으로 사용하는 메세지들을 utils의 ExceptionMessage 클래스에 분리해두었습니다~!

2022-05-15 00:21 UTC, Juhyung990122 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
오.. 이거 오래 고민해봤는데 어떤 조건이 누란된건지 잘 모르겠어요...! 구간 내에서 가장 시작역과 끝역은 딱 한번 나오게 되는데 어떤게 문제가 될까요...!

2022-05-15 00:54 UTC, Juhyung990122 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private List<SectionWithStation> sections;
꼭 Station 단위로 움직이지 않아도 됐군요ㅎㅎ 수정했습니다!!

2022-05-15 01:14 UTC, Juhyung990122 commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +@Transactional
넵! 말씀해주신 부분도 공감이 됐고, @Transactional 어노테이션의 본질적인 쓰임새와도 좀 다른 것 같아서 Test 내에 있는 @Transactional은 다 걷어내었구요! 대신 일괄삭제 sql 문을 테스트 전마다 실행하게끔 하는 어노테이션을 추가했습니다:)

2022-05-15 01:24 UTC, Juhyung990122 commented on src/main/java/wooteco/subway/domain/Section.java
> +    public Section(SectionRequest sectionRequest, long lineId) {
둘사이에 의존관계가 생기게 됩니다.  
dto는 ui와 맞닿아있어서 변경이 잦은데 도메인이랑 직접적으로 연결되어있으면 
ui단의 변경이 도메인에도 영향이 가게 되어서 위험해지는 것 같아요.

저는 생각해봤을때 요정도 이유가 있었는데 아니라면 말씀해주셔요ㅎㅎ 
좀 더 생각해볼게요!

2022-05-15 04:08 UTC, Juhyung990122 commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .filter(section -> isLastStation(section.getDownStation()))
역으로만 검색하는 걸로 개선해보았습니다!

2022-05-15 04:18 UTC, Juhyung990122 commented on src/main/java/wooteco/subway/domain/Sections.java
> +public class Sections {
헉 추가했습니다~!

2022-05-15 05:21 UTC, Juhyung990122 commented
안녕하세요 릭! 열음입니다ㅎㅎ
남겨주신 코멘트 바탕으로 리팩토링 진행해보았어요.
이해한대로 하긴 했는데 의도하신 바와 맞지 않는 부분이 있으시다면 언제든 말씀해주세요!
더불어 진행하면서 궁금하거나 긴가민가했던건 코멘트로 남겨두었으니 확인 부탁드립니다.

시간내어 리뷰해주셔서 언제나 감사합니다!

2022-05-16 13:25 UTC, wbluke approved these changes
피드백 반영하느라 고생 많으셨어요 👍 
미션은 마무리하지만 몇 가지 다시 고민해볼만한 코멘트 남겼으니 확인해 보셔요 ㅎㅎ
다음 미션도 화이팅입니다 🙂

2022-05-16 13:25 UTC, wbluke commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .noneMatch(s -> s.getDownStationId() == stationId);
> 오.. 이거 오래 고민해봤는데 어떤 조건이 누란된건지 잘 모르겠어요...!
해당 라인에 있는 구간들 내에서
가장 상행역은 구간들 내에서 딱 한번 어떤 section의 upStation으로만 나오고
가장 하행역은 구간들 내에서 딱 한번 어떤 section의 downStation으로만 나오게 되니
해당 조건만으로도 보장되지 않나요?-?

지금 조건이 누락되어 기능에 문제가 있다기 보다는, 추상화한 메서드의 이름과 실제 구현부가 일치하지 않는 것 같다는 말이었어요 ㅎㅎ
Sections의 공개(public) API인데, 해당 메서드가 외부에서 사용된다고 가정했을 때 전혀 관련없는 역의 stationId가 파라미터로 들어온다면 어떻게 될까요?
해당 메서드는 true를 반환하고 실제로는 Sections 안에 없는 역인데도 첫번째 역임을 잘못 판단해주지 않을까요?
첫 번째 역을 판단하는 방식을 noneMatch()로 가져가는게 위험해 보이는데요, 그보다는 차라리 정직하게 구간들을 역 순서에 맞게 정렬 후, 실제 첫 번째 역과 같은 id인지를 비교하는 게 맞을 것 같아요.

공개 API인 만큼 이런 부분을 더 신경써야 합니다 ㅎㅎ
애플리케이션의 요구사항을 만족하는 것 뿐만 아니라, 객체의 행위와 미래 시점의 사용 가능성에 대해서도 같이 고민하는 연습을 해보면 좋을 것 같아요 :)

2022-05-16 13:25 UTC, wbluke commented on src/main/java/wooteco/subway/service/SectionService.java
> +                .orElseThrow(() -> new IllegalArgumentException(ExceptionMessage.NO_SECTION));
메시지를 분리하라는 의미 보다는, find하고 orElseThrow 하는 부분이 중복이라 메서드로 추출할 수 있지 않냐는 뜻이었어요 :)

2022-05-16 13:25 UTC, wbluke commented on src/main/java/wooteco/subway/service/SectionService.java
> +    public Sections makeSections(long lineId) {
public이어야 하는 메서드일까요?

2022-05-16 13:25 UTC, wbluke commented on src/test/java/wooteco/subway/domain/SectionsTest.java
> +    }
`해당 역이 상행종점인지 검사한다. - 참`, `해당 역이 상행종점인지 검사한다. - 거짓` 보다는
`주어진 역의 id가 상행종점의 id라면 참을 반환한다.` 와 같은 구체적인 **테스트 행위**를 명세해주는 것이 좋습니다 :)

2022-05-16 13:25 UTC, wbluke commented on src/test/java/wooteco/subway/ui/ControllerTest.java
> +public class ControllerTest {
이런 상위 테스트 클래스라면 추상 클래스로 만드는 것이 좋겠네요 :)

2022-05-16 13:25 UTC, merged