[Spring 지하철 노선도 - 3단계] 리버(구동희) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #285
Opened 2022-05-11 11:52 UTC by gudonghee2000

안녕하세요 던!
이번 미션은 도메인 로직이 들어가면서
많이 복잡했던 미션인거같아요😞

그래서 많은 시간 고민하고 프로그램을 구현해보았어요!
이번 리뷰도 잘부탁드립니다 던!!
감사합니다😊

2022-05-12 15:38 UTC, gch01410 requested changes
안녕하세요 리버!
3단계도 깔끔하게 잘 구현해주셨네요! 👍 
코멘트 남겼으니 확인부탁드릴게요~

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @GetMapping()
애노테이션 값을 설정하지않으면 `()`를 삭제해주세요~

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +            throw new StationNotFoundException("존재하지 않는 역입니다.");
구체적인 예외사용 👍 👍 
예외 메시지에 id값도 넣어줘서 어떤 id의 역이 없었는지 더 구체적으로 표현할 수 있을 것 같아요
지금은 예외 메시지의 내용이 그대로 프론트에 노출되고 있어서 id가 노출되면 안될 것 같긴하네요
조금 더 구체적으로 예외상황을 알릴 수 있다 정도로 참고만 하시면 좋을 것 같아요.
String의 format 메서드를 사용할 수 있습니다~

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/service/LineService.java
>      }
saveSection 메서드 실행중에 지하철역이 없어서 예외가 발생해도
`final Line newLine = lineDao.save(line);` 에서 저장된 Line 데이터는 계속 저장되어 있어요.
생성된 Line 데이터는 어떻게 처리되는게 좋다고 생각하시나요?

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/dao/SectionDaoImpl.java
> +                + "where line_id = (?);";
join을 사용하셨군요! 👍 
쿼리를 String으로 표현할때 select, from, where, join, on 같은 SQL 키워드는 대문자로 적어주면 가독성이 올라갑니다!
그리고 `from`전에 한번 줄바꿈 해주면 더 좋겠네요!

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private final List<Section> sections;
적절하게 일급컬렉션 사용 잘하셨네요! 💯

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/domain/Sections.java
> +        addStationInSection(stations, section);
`addStationInSection` 메서드에서 stations를 반환하도록 해도 될 것 같아요

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
더 적절한 메서드명을 지어볼 수 있을까요?
이름이 동사로 시작하면 이해하기 더 좋을 것 같아요

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/service/LineService.java
>      }
lineDao.findById 메서드에 이미 예외처리가 되어있어서 여기서 예외처리는 안해도 괜찮지않을까요~?

2022-05-12 15:38 UTC, gch01410 commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
validateExist 메서드가 불필요하다는 생각이 드네요!
그리고 Line객체를 새로 생성하지않고 dao를 통해 가져온 Line객체를 사용해도 되지않을까요?
dao에서 Line객체를 가져왔으면 이미 exist검증은 된거니깐요!

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/ui/LineController.java
>  public class LineController {
```java
@DeleteMapping("/{id}")
public ResponseEntity<Void> modifyLine(@PathVariable Long id) {
    lineService.deleteLine(id);
    return ResponseEntity.ok().build();
}
```
이 로직에 코멘트를 남길 수 없어서 여기에 남겨요!
메서드 이름이랑 로직이랑 안맞는것 같아요.

2022-05-12 15:38 UTC, gch01410 commented on src/main/java/wooteco/subway/service/LineService.java
>      private void validateExist(final long id) {
deleteLine메서드에 코멘트가 안남겨져서 여기에 남겨요!

```java
public int deleteLine(final Long id) {
    validateExist(id);
    return lineDao.delete(id);
}
```

아래처럼 하면 같은 검증로직을 2번 하는것을 한번으로 줄일 수 있겠어요
```java
public int deleteLine(final Long id) {
    Line line = lineDao.findById(id);
    return lineDao.delete(line.getId());
}
```

2022-05-12 15:38 UTC, ghost commented on src/main/java/wooteco/subway/dao/SectionDaoImpl.java
> +}
soft delete 에 대해서도 알아보시면 좋을 것 같아요!
이번 미션에서 적용해야한다는건 아니고 참고차 공유드립니다 ㅎ.ㅎ
실제 서비스에서 왠만하면 데이터를 DB에서 아예 삭제하지 않습니다.
DB에서 아예 데이터를 삭제시킬때는 정말 삭제해야하는지 신중하게 접근합니다.
정말 필요없는 데이터라고 확신이 들면 db에서 삭제하기도 합니다.

2022-05-16 05:44 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/ui/LineController.java
> +    @GetMapping()
삭제하였어요!

2022-05-16 05:49 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/service/StationService.java
> +            throw new StationNotFoundException("존재하지 않는 역입니다.");
넵 감사합니다 던!!

2022-05-16 05:52 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/service/LineService.java
>      }
만약 section을 저장하는 과정에서 문제가 생기면, 생성된 Line 데이터가 DB에 저장되지 않게 해야된다고 생각해요!
그래서 `@Transactional`을 통해서 LineService.save() 에서 문제 발생시 DB에 데이터를 저장하지 않도록 하였어요!

2022-05-16 05:52 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/dao/SectionDaoImpl.java
> +                + "where line_id = (?);";
select, from, where, join, on에 대문자를 적용하고 줄바꿈을 하였어요!

2022-05-16 05:52 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private final List<Section> sections;
감사합니다 던!!

2022-05-16 05:53 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        addStationInSection(stations, section);
`addStationInSection` 메서드가 `List<Station>`을 반환하도록 변경하였어요!

2022-05-16 05:53 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
`getStationsFromSection()` 이라는 이름의 메서드 명으로 변경하였어요!

2022-05-16 05:54 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/service/LineService.java
>      }
불필요한 예외처리를 모두 제거하였어요!

2022-05-16 05:54 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
불필요한 예외처리를 모두 제거하였어요!
그런데, 새로운 Line 객체를 생성하는 것은 update하기위한 데이터를 가진 Line 객체를 생성하는것이여서 변경하지 않았어요!

2022-05-16 05:54 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/ui/LineController.java
>  public class LineController {
메서드이름을 로직에 맞게 변경하였어요!!

2022-05-16 05:54 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/service/LineService.java
>      private void validateExist(final long id) {
중복되는 예외처리를 제거하였어요!!

2022-05-16 06:30 UTC, gudonghee2000 commented on src/main/java/wooteco/subway/dao/SectionDaoImpl.java
> +}
soft delete를 적용하여 hard delete를 제거해보았어요 던!!

2022-05-16 06:32 UTC, gudonghee2000 commented
안녕하세요 던!! 말씀해주신 피드백들을 적용해보았어요!
주말간 몸이 조금 좋지 않아서 리팩터링을 하지못하여서 PR을 늦게 드리게 되었어요....😔

이번 리뷰도 잘부탁드립니다 던!!
감사합니다😊😊

2022-05-16 14:34 UTC, gch01410 approved these changes
안녕하세요 리버!
피드백 정말 잘 적용해주셨습니다! 💯 💯 
간단한 코멘트들 남겼으니 확인 부탁드릴게요~
이번 미션 구현하시느라 수고많으셨습니다!

2022-05-16 14:34 UTC, ghost commented on src/main/java/wooteco/subway/service/LineService.java
>      }
```java
private boolean hasDuplicateLine(final LineRequest lineRequest) {
    return lineDao.findAll()
            .stream()
            .anyMatch(line -> line.getName().equals(lineRequest.getName()));
}
```

조건절없이 테이블의 모든 데이터를 조회하는 방식은 지양하는게 좋습니다. 테이블의 데이터 수가 많다면 메모리가 부족한 상황이 발생할 수 있어요! 실제 서비스라면 아주 위험할 수 있겠어요! (신입시절에 findAll 메서드로 테이블의 모든 데이터를 조회해서 메모리 부족으로 서버 터뜨렸던 기억이 갑자기 났네요..ㅎ)
모든 Line데이터를 조회하지않고 경로 이름으로 Line을 조회해서 확인해볼 수 있을 것 같아요

2022-05-16 14:34 UTC, ghost commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
createSortedStations 메서드에서 station 리스트를 생성해서 addStationInSection 메서드로 넘기지않고 addStationInSection안에서 station 리스트를 생성하는게 좋아보이네요!
createSortedStations 메서드에서 생성해서 넣어줘야만 하는 상황은 아니니깐요!

2022-05-16 14:34 UTC, gch01410 commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
`getStationsFromSection` 메서드명만 보면 파라미터로 Section(or sectionId)를 넘길것 같은데 lineId를 넘기고 있어서 약간 어색한 것 같아요!
```java 
private List<StationResponse> getStationsFromLine(long lineId) {
```
이건 어떠신가요?

2022-05-16 14:34 UTC, ghost commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
lineDao에서 조회한 데이터를 사용안하는게 살짝 어색하게 느껴지네요.
```java
Line line = lineDao.findById(id);
Line lineForUpdate = new Line(line.getId(), lineRequest.getName(), lineRequest.getColor());
```
이렇게하면 어떤 Line을 업데이트하는지 더 명확하게 드러낼 수 있지않을까요?!? 데이터 존재여부 검증도 자연스럽게 하면서요!
개인적인 의견입니다!

2022-05-16 14:34 UTC, ghost commented on src/main/java/wooteco/subway/dao/StationDaoImpl.java
>      }
soft delete 를 이용하는 경우에, 조회 시 deleted 처리된 데이터는 제외하는것이 중요합니다!
잘 적용 하셨습니다! 💯

2022-05-16 14:34 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +            throw new StationDuplicateException("이미 등록된 지하철역 이름입니다.");
다른 리뷰이분에게 남긴 코멘트인데 리버한테도 공유드려요!
리버는 커스텀 예외를 잘 사용하셔서 아주 좋습니다! 👍 
참고사항으로만 봐주세요!

```
저는 비즈니스 로직의 예외는 모두 커스텀 예외를 사용하고 있어요. 정확한 문제가 무엇인지 이해하는 데 도움이 됩니다. 
예외 메시지는 +알파로 더 상세하게 예외 상황을 드러내는 보조역할이라고 생각해요

아래 글 들을 참고해보면 좋을 것 같아요!
https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/
https://vitalflux.com/4-reasons-need-create-customs-exceptions/
```

2022-05-16 14:35 UTC, merged