[Spring 지하철 노선도 - 3단계] 호호(유현호) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #289
Opened 2022-05-11 12:46 UTC by yhh1056

안녕하세요 범블비!
https://d2owgqwkhzq0my.cloudfront.net/
서버 실행시키고 위 링크에서 실행할 수 있습니다!

3단계 미션은 구간을 추가하고 삭제하는 과정에서 어려움을 겪어 제출이 늦어졌습니다😭

### SectionDao만 존재
SectionController와 SectionService를 만드는 방법도 있었지만 만들지 않았습니다.
컨트롤러가 없는 이유는 아직 구간이 라인 카테고리 안에 들어가있다고 생각해서 만들지 않았습니다.
서비스가 없는 이유는 같은 계층에 있는 클래스끼리 의존하다가 순환참조가 발생할 수 있는 문제가 있다고 생각했고 컨트롤러에서 2개의 서비스를 의존하는 방법도 있지만 조회해온 도메인객체를 주고받아야 해서 SectionDao가 하나 존재하게 되었습니다. 
구간에 관련된 API가 늘어나게되면 한 곳에 모든 코드가 들어가져서 이 구조를 다시 고민해봐야할 것 같아요🧐

### 객체지향, DB간의 모순(?)
처음에 요구사항을 보고 Sections를 만들어서 구간을 관리하려 했지만 변경된 객체에 대해서 DB에 업데이트 하는 과정이 쉽지 않더라구요. 테이블을 전부 삭제하고 다시 추가하는 방법도 고려해봤지만 deleteAll을 사용하는 것 보다 더 좋은 방법이 없을까 고민했어요. 변경할 구간들만 서비스에 반환해주는 식으로 변경하게 되었는데 코드 자체가 찝찝하게 만들어졌습니다.

### 도메인을 DAO와 주고받다보니
DAO와 도메인을 주고 받다 보니 조회시에는 도메인 객체를 만들기 위해서 Id값으로 다시 디비에 조회해와 객체를 만들어야 했고 저장할때도 객체를 생성하기 위해서 id로 조회해야했어요. 그래서 불필요하다고 느낀 부분은 entity를 만들어 id만 주고받게 되는데 도메인을 넘기거나 엔티티를 넘기는 두가지 방식을 혼용해서 사용해도 괜찮을까요?

### 테스트코드의 중요성
빠르게 개발하기 위해 테스트 코드를 작성하지 않고 코드를 계속 만들었어요. 결국 버그가 터지게 되고 버그를 찾기위해 계속 서버를 껐다켰는데 확실히 테스트코드를 작성하는게 시간도 줄이고 더 빠르게 개발할 수 있다는 걸 제대로 느낀시간이네요😂

2022-05-12 16:49 UTC, ddaaac requested changes
안녕하세요 호호!

도메인 로직에 대해서 고민을 많이 한 흔적이 느껴진 코드네요 👏 👏 👏 

몇 가지 코멘트 남겼으니 확인부탁드립니다.

2022-05-12 16:49 UTC, ddaaac commented on src/main/java/wooteco/subway/domain/Section.java
> +    public List<Section> splitFromUpStation(Section other) {
전반적으로 Section과 Sections에 도메인 로직이 많은데 테스트 코드가 부족한 것 같아요.
쉽지 않겠지만 도메인 로직에 대한 테스트를 많이 작성해주세요 😄 

+) 서비스 코드에 대한 테스트는 많이 작성해주셨어요 👍 
다만, 작성하시면서 느끼셨겠지만 서비스 레이어는 다른 기술들이 많이 섞입니다. 그래서 테스트 코드를 읽는 게 쉽지 않아요.
최대한 로직을 도메인으로 넣어주시면서 도메인 레이어에 대한 테스트를 많이 작성해주시면 좋을 것 같습니다!

2022-05-12 16:49 UTC, ddaaac commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +    public void update(Section section) {
> DAO와 도메인을 주고 받다 보니 조회시에는 도메인 객체를 만들기 위해서 Id값으로 다시 디비에 조회해와 객체를 만들어야 했고 저장할때도 객체를 생성하기 위해서 id로 조회해야했어요. 그래서 불필요하다고 느낀 부분은 entity를 만들어 id만 주고받게 되는데 도메인을 넘기거나 엔티티를 넘기는 두가지 방식을 혼용해서 사용해도 괜찮을까요?

이렇게 구현하게 되면 Section의 로직을 실행하기 위해서 Station, Line이 필요한지 여부를 Section 도메인 객체가 아닌 SectionService가 알게 될 거 같아요. 또한 SectionService는 SectionEntity로부터 Section을 만들어내는 책임 또한 생겼네요.

만약 도메인과 DB 엔티티의 분리가 필요하다고 하면 저라면 이렇게 구현했을 것 같습니다.
SectionService <- Section -> SectionRepository <- SectionEntity -> SectionDao
서비스와 레포는 도메인을 주고 받고 레포와 DAO는 엔티티를 주고 받도록이요. 
조금 난이도가 있을 수 있기 때문에 해당 코멘트는 반영하지 않아도 괜찮아요. 하지만 Repository와 Dao의 차이점에 대해서는 가볍게 한번 짚어보셨으면 좋겠습니다.

2022-05-12 16:49 UTC, ddaaac commented on src/main/java/wooteco/subway/domain/Section.java
> +        validateShortDistance(other.distance);
Section 관점에서 바라봤을 때 두 개의 메서드가 하나로 합쳐져도 될 것 같네요. `splitBy(Section other)` 요런 시그니처 정도 가지면 어떨까요? 혹시 Section의 구조상 반영이 불가능한 코멘트라면 넘어가셔도 됩니다!

2022-05-12 16:49 UTC, ddaaac commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private final List<Section> values;
취향차가 있겠지만 저는 그냥 `sections`로 이름 짓는 편이 낫더라구요 😄

2022-05-12 16:49 UTC, ddaaac commented on src/main/java/wooteco/subway/service/LineService.java
> +            );
두 Section을 합치는 **도메인 로직**이네요. `Sections` 또는 `Section` 내부로 넣어볼까요?

2022-05-12 16:49 UTC, ddaaac commented on src/main/java/wooteco/subway/domain/Station.java
> +        return Objects.equals(name, station.name);
식별자가 있는 객체의 동등성을 비교할 떄는 식별자끼리만 비교해도 되지 않을까요?

2022-05-12 16:49 UTC, ddaaac commented on src/main/java/wooteco/subway/service/LineService.java
> +        if (removedSections.size() == 2) {
size가 2인 경우가 어떤 경우를 나타내는지 표현해주면 좋을 것 같습니다

2022-05-12 16:49 UTC, ddaaac commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    private Map<String, Object> lineParam(String name, String color, Long upStationId, Long downStationId) {
테스트 코드도 유지보수의 대상이죠. 적당히 메서드 분리 잘해주셨어요 👍

2022-05-12 16:49 UTC, ddaaac commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +        SectionRequest sectionRequest = new SectionRequest(강남.getId(), 양재.getId(), 11);
로직을 보면 "기존 구간보다 길거나 같은"이 맞을 것 같습니다. 테스트도 경계값인 10으로 해도 될 것 같구요.

2022-05-12 16:49 UTC, ddaaac commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    @Autowired
슬라이스 -> 통합테스트로 변경되었군요. 변경의 이유가 궁금하네요 😄

2022-05-12 16:49 UTC, ddaaac commented on src/main/java/wooteco/subway/service/LineService.java
> +        }
> > 처음에 요구사항을 보고 Sections를 만들어서 구간을 관리하려 했지만 변경된 객체에 대해서 DB에 업데이트 하는 과정이 쉽지 않더라구요. 테이블을 전부 삭제하고 다시 추가하는 방법도 고려해봤지만 deleteAll을 사용하는 것 보다 더 좋은 방법이 없을까 고민했어요. 변경할 구간들만 서비스에 반환해주는 식으로 변경하게 되었는데 코드 자체가 찝찝하게 만들어졌습니다.

Spring의 Data 시리즈(ex Spring Data Jpa)를 사용해보시면 `save`는 기본적으로 id 필드가 null이면 insert, 값이 있으면 update 쿼리를 수행합니다. 만약 save가 그런 식으로 구현되어있다면 여기서는 `updatedSections`를 모두 save 하면 해결될 것 같네요.
이 부분 역시 코드에 반영하실 필요는 없습니다. 나중에 라이브러리를 사용하게 되면 자연스럽게 익히실 수 있을 거에요.

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
삭제를 이곳에서 하도록 리팩토링을 해볼게요😅

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +    public void update(Section section) {
무슨 구조인지는 느낌이 오는 것 같아요! 레퍼지토리와 DAO의 차이를 알아볼게요~!

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/domain/Section.java
> +    public List<Section> splitFromUpStation(Section other) {
도메인에 대한 로직이 거의 없었네요😭 이번에 테스트 코드 위주로 많이 작성해보면서 리팩토링을 해보겠습니다!!

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/domain/Section.java
> +        validateShortDistance(other.distance);
한번 수정해보겠습니다!!

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private final List<Section> values;
처음에는 괜찮았는데 메서드가 많아지면서 읽기 불편한점도 생기더라구요. 여러 방법을 사용해볼게요~!

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/domain/Station.java
> +        return Objects.equals(name, station.name);
식별자가 있으니 식별자로 구분해도 같은 객체라는 걸 알 수있네요!! 👍👍
id없이도 Station이 생성 가능한 부분이라 중복이 불가능한 이름으로 비교했어요. 
코드를 수정해보고 문제가 없는지 확인헤보겠습니다😃

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/service/LineService.java
> +        }
설명해주신 구조와 이 방법도 흥미가 가서 테스트코드를 구현해보면서 적용해보고싶어졌어요😃 한번 적용해보고 느낀점을 전해드릴게요!!

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/service/LineService.java
> +        if (removedSections.size() == 2) {
상수로 분리하겠습니다!

2022-05-13 05:28 UTC, yhh1056 commented on src/main/java/wooteco/subway/service/LineService.java
> +            );
네 수정하겠습니다👍👍

2022-05-15 00:30 UTC, yhh1056 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +        SectionRequest sectionRequest = new SectionRequest(강남.getId(), 양재.getId(), 11);
수정했습니다!!

2022-05-15 00:34 UTC, yhh1056 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    @Autowired
제가 왜 변경했는지 코멘트를 안남겼네요!😂

Mock객체를 우선 지양하고 통합테스트를 사용해보라는 수업이 있었어요.
그래서 스스로 mock을 사용한 테스트의 장단점을 모두 알고 사용하는가?를 되물었고 장단점에 대해서 뚜렷하게 느끼지 못 하고 있더라구요.

통합테스트를 먼저 사용해보면서 각각의 장단점을 느끼고자 통합테스트로 변경하게 되었어요

2022-05-15 04:21 UTC, yhh1056 commented
안녕하세요 범블비!
설명해주신 구조에 대해서 고민해보고 적용해보았습니다👍

확실히 서비스레이어의 테스트 코드는 복잡해서 서비스 코드만 보고 비즈니스를 파악하는게 쉽지 않은 것 같아요. 도메인 관련 테스트를 추가하게 되면서 도메인 테스트 코드의 중요성을 또 느꼈어요. 테스트 코드를 작성하면서 기존 서비스에서 하고있던 비즈니스 로직을 도메인으로 이동시킬 수 있었습니다!

저번 리뷰에서 repository를 만들어 도메인과 엔티티를 분리하도록 수정했어요. repository는 도메인과 관련된 영역으로, dao는 db와 데이터를 주고 받는 역할로 분리가 되었습니다! 한가지 고민을 했던 점은 section 도메인 객체를 생성하기 위해 Station 객체가 필요했어요. repository가 stationDao도 의존하게 되었는데 Section 객체도 Station을 포함하고 있으니 Repository가 여러 dao를 가지고 있는게 자연스럽다고 생각해서 의존하게 되었습니다!

2022-05-15 15:15 UTC, ddaaac approved these changes
안녕하세요 호호 ✋ 

정말 잘 구현해주셨고, 리뷰도 너무 잘 반영해주셨어요 💯 
열심히 해주시는 모습이 엄청 인상적이었습니다.

이번 단계 고생 너무 많이 하셨고 다음 미션을 위해 이만 머지할게요.
앞으로 남은 미션들도 화이팅입니다~

2022-05-15 15:15 UTC, ddaaac commented on src/main/java/wooteco/subway/domain/Section.java
> +        return List.of(other);
이 부분은 궁금한 점인데 테스트 코드에도 해당 케이스는 없는 것 같아서 질문 남겨요.
up / down이 모두 일치하지 않으면 split의 결과로 other를 반환하는 건 어떤 의도인가요?

2022-05-15 15:15 UTC, ddaaac commented on src/test/java/wooteco/subway/domain/SectionsTest.java
> +class SectionsTest {
테스트 꼼꼼하게, 보기 좋게 너무 잘 구현해주셨습니다 💯

2022-05-15 15:15 UTC, ddaaac commented on src/test/java/wooteco/subway/domain/SectionsTest.java
> +    @DisplayName("상행역을 기준으로 구간을 추가하면 분리된 구간들을 반환한다.")
```java
    /**
     * 
     * 기존: 강남 ---------- 잠실
     * 추가: 강남 -- 삼성
     */
```
이런 식으로 테스트 코드를 보기 편하게 주석을 작성할 수도 있습니다! 이 부분은 반영 안해주셔도 돼요~

2022-05-15 15:15 UTC, ddaaac commented on src/main/java/wooteco/subway/service/LineService.java
> +        }
조금 특이한 모양일 수도 있지만
`Sections@findDeleteSections`가 dto를 활용해서 `삭제해야할 섹션들`과 `합쳐진 섹션`을 한꺼번에 반환하는 것도 괜찮을 거 같은데 호호의 생각은 어떠신가요?

2022-05-15 15:15 UTC, ddaaac commented on src/main/java/wooteco/subway/domain/Sections.java
> +            .filter(value -> value.isEqualToUpOrDownStation(station))
```suggestion
            .filter(value -> value.isEqualToLine(line) && value.isEqualToUpOrDownStation(station))
```

어떤 차이가 있을까요?

2022-05-15 15:15 UTC, ddaaac commented on src/main/java/wooteco/subway/repository/LineRepository.java
> +        return line;
진짜 구현해주셨군요... 👍 👏

2022-05-15 15:15 UTC, ddaaac commented on src/main/java/wooteco/subway/repository/SectionRepository.java
> +    private final StationDao stationDao;
>  한가지 고민을 했던 점은 Section 객체를 생성하기 위해 Station 객체가 필요했어요. repository가 stationDao도 의존하게 되었는데, Section 객체도 Station을 포함하고 있으니 Repository가 여러 dao를 가지고 있는게 자연스럽다고 생각해서 의존하게 되었습니다!

보통 Repo는 인터페이스이고 해당 도메인에 대한 조회/저장 등의 인터페이스만 정의되어있습니다. (지금은 굳이 나눌 필요는 없어보입니다)
그리고 구현체에서는 그 인터페이스를 달성하기 위한 구체적인 동작을 구현하죠. 만약 Section을 만들기 위해서 Station이 필요하다면 SectionRepo의 구현체는 StationDao도 필요하겠죠. 잘 구현해주셨어요.

2022-05-15 15:15 UTC, ddaaac commented on src/main/java/wooteco/subway/service/LineService.java
> +        Station upStation = findStation(request.getUpStationId());
[`find vs get`](https://tuhrig.de/find-vs-get/)을 읽어볼까요?
사소할 수 있지만 이런 부분에서 컨벤션을 잡아놓으면 나중에 코드 읽기가 한층 편해집니다 :)

2022-05-15 15:15 UTC, ddaaac commented on src/test/java/wooteco/subway/domain/fixtures/TestFixtures.java
> +    public static final Station 삼성 = new Station(2L, "삼성");
픽스쳐 사용 👍

2022-05-15 15:15 UTC, merged

2022-05-16 07:37 UTC, yhh1056 commented on src/main/java/wooteco/subway/domain/Section.java
> +        return List.of(other);
추가할 구간이 분리되지 않는다면 상행종점 또는 하행종점이 추가되는 경우가 되는 로직으로 흘러갑니다.
```java
성수 ---------- 홍대   // 해당 구간에 `강남-성수` 구간을 넣을 경우 분리되지 않음
강남 ---성수--- 홍대
```
`return List.of(other);` 이 코드가 의도가 제대로 전달되지 않는 느낌은 있네요. split이라는 메서드명을 사용한다면 빈 컬렉션을 반환해서 Sections에서 처리하는 방법도 괜찮을 것 같아요. 테스트 케이스도 추가해봤습니다!

2022-05-16 07:37 UTC, yhh1056 commented on src/main/java/wooteco/subway/repository/LineRepository.java
> +        return line;
어려운 부분이 아니었고 리팩토링의 이득이 너무 컸습니다. 감사합니다 👍

2022-05-16 07:37 UTC, yhh1056 commented on src/test/java/wooteco/subway/domain/SectionsTest.java
> +    @DisplayName("상행역을 기준으로 구간을 추가하면 분리된 구간들을 반환한다.")
테스트 코드도 문서화의 목적도 있다고 생각해서 이해하기 쉽게 주석으로 설명해주는 것도 좋아보이네요!!👍👍
다음 미션에서도 고려해보겠습니다!!

2022-05-16 07:37 UTC, yhh1056 commented on src/main/java/wooteco/subway/domain/Sections.java
> +            .filter(value -> value.isEqualToUpOrDownStation(station))
<img width="387" alt="스크린샷 2022-05-16 오후 3 50 37" src="https://user-images.githubusercontent.com/58363663/168535242-33da8c18-beb1-4588-8835-1701c94e86e2.png">
 
이런식으로 예제 코드를 만들어보았는데요 필터가 2개면 첫번째 필터를 탄 후에 거기서 걸러진 대상들을 다음 필터에서 조회하더라구요.
그래서 성능에는 어떤 영향이 있을까 궁금했어요.

```java
@Test
void filter() {
    List<Member> members = new ArrayList<>();
    for (int i = 0; i < 100000; i++) {
        members.add(new Member("woowa " + i, RandomUtils.nextInt(0, 20)));
    }
    for (int i = 0; i < 100000; i++) {
        members.add(new Member("kakao " + i, RandomUtils.nextInt(0, 20)));
    }
    Collections.shuffle(members);

    StopWatch stopWatch = new StopWatch();
    stopWatch.start();

    // 필터 1개
    members.stream()
        .filter(member -> member.ageCondition() && member.nameCondition())
        .collect(Collectors.toList());

    // 필터 2개
//        members.stream()
//            .filter(Member::ageCondition)
//            .filter(Me
mber::nameCondition)
//            .collect(Collectors.toList());

    stopWatch.stop();
    System.out.println(stopWatch.prettyPrint());
}
```
20만 데이터를 넣은 결과

필터가 1개인 경우 0.01초 후반 ~ 0.02초의 속도가 자주 나왔고
<img width="375" alt="스크린샷 2022-05-16 오후 4 12 17" src="https://user-images.githubusercontent.com/58363663/168538470-52a7cdd1-5525-4d14-934c-994ce9fae72b.png"> 

필터가 2개인 경우 0.02초 초반 ~ 0.02초 후반의 결과를 보여줬습니다.
<img width="375" alt="스크린샷 2022-05-16 오후 4 13 58" src="https://user-images.githubusercontent.com/58363663/168538746-3c9409a5-529a-4934-a7b3-ccaac6a0cb23.png">


이정도의 성능차이라면 가독성을 좋게 가져가는 게 더 좋다고 생각합니다! 아니면 2개의 조건을 하나의 메소드로 변환하는 것도 가독성과 아주 조금의 성능도 얻을 수 있을 것 같아요.

2022-05-16 07:37 UTC, yhh1056 commented on src/main/java/wooteco/subway/service/LineService.java
> +        Station upStation = findStation(request.getUpStationId());
데이터가 반드시 올 것이라는 보장이 있으면 get을 사용하고 없을수도 있는 경우에 find를 사용하는 방향으로 컨벤션을 만들어도 좋을 것 같아요!

이전 기억으로는 Jpa메서드중에 getById와 findById가 있었는데 왠지 여기에도 차이가 있을것 같네요.

2022-05-16 07:37 UTC, yhh1056 commented on src/main/java/wooteco/subway/service/LineService.java
> +        }
변경하려면 네이밍부터 수정해야겠군요. 업데이트의 경우에는 save메서드가 insert와 update를 처리해주는데 delete의 경우 id로 삭제할지, insert를 해야할지 결정해야하는데 이 로직을 repository서 처리해야할지, service에서 처리해야할지 고민이 되네요.

if (removedSections.size() == Sections.COMBINE_SIZE) <- 해당 분기문이 도메인 로직을 서비스에서 하고 있어서 내부로 숨기는게 괜찮을 것 같아요!

2022-05-16 12:37 UTC, ddaaac commented on src/main/java/wooteco/subway/domain/Sections.java
> +            .filter(value -> value.isEqualToUpOrDownStation(station))
테스트까지 👍 
개인적으로는 가독성에 큰 차이가 없다고 생각해서 한 파이프라인을 더 탈 필요는 없다고 생각해요. 이 부분은 지금처럼 호호의 의견을 만들어가면 좋을 것 같습니다!