[Spring 지하철 노선도 - 3단계] 조시(조현근) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #293
Opened 2022-05-11 16:06 UTC by hyunrrr

스티치 안녕하세요!!!
이번 미션은 어떻게 구현해야 할지 감이 너무 안잡혀서 오랫동안 고민하느라 제출하는데 오래걸렸습니다.. 
주로 고민한 내용은 
- 도메인을 어떻게 서비스에서 분리할까 
- dto 변환로직을 어디서 처리할까 
- 저장소에 접근하는 객체(dao와 같은 객체)는 서비스에서만 호출해야 되나 입니다!!

## 1. 도메인을 서비스에서 분리
미션을 진행하면서 도메인에 대한 이해가 높아질수록 어떤 책임을 도메인으로 분리해야 할지 조금씩은 감이 잡혔습니다. Line, Station, Section과 같은 도메인 객체 이용해 subWay라는 도메인 객체에 비즈니스 로직을 요청하는 식으로 구현했습니다.
혹시 아직 분리하지 못한 도메인 로직이 있다면 피드백 부탁드립니다!!!

## 2. dto 변환로직
dto를 도메인 객체로 변환하거나, dto에서 다른 dto로 변환하는 로직들은 모두 해당 dto 객체안에 넣었습니다.
예를들어 Station 도메인 객체를 이용해 StationResponse를 만드는 로직은 StationResponse객체의 생성자로 처리했고,
SectionRequest dto를 이용해 SectionEntity를 만드는 로직은 SectionRequest안의 메서드로 처리하고,
LineRequest dto를 SectionRequest dto로 변환하는 로직은 lineRequest의 생성자로 처리했습니다.
List<Station>을 List<StationResponse>로 만드는 로직 역시 StationResponse 객체의 클래스 메서드로 처리했습니다.
이런 변환 로직을 dto 안에 둔 이유는 
1. 이런 로직이 서비스에 존재하면 서비스가 너무 커지는 느낌이 듦
2. 서비스에 이런 로직이 있나 dto 내부에 있나 코드가 수정되었을때 변화되는 코드의 양이 똑같다고 느낌
입니다.
혹시 이런 방법을 어떻게 생각하시나요?? 혹시 더 좋은 방법이 있을지 궁금합니다..

## 3. dao와 같은 저장소 관련 객체는 서비스에서만 호출해야 할까?
이번 고민은 사실 해결하지 못하고 코드에 반영하지 못했습니다. 
저는 도메인 객체 section을 sectionEntity와 분리했습니다. db의 section테이블이 스키마로 station과 line의 id를 가지고있는데, 이를 그대로 도메인 객체로 사용하기가 너무 어색했습니다. 그래서 id 대신 실제 해당하는 객체(line, station)를 필드로 가지는 section이라는 객체를 만들고 sectionEntity와 분리했습니다.
sectionEntity를 section으로 변환하는 로직이 필요했는데, 이 로직은 dao에 접근할 수 밖에 없습니다.
이런 변환 로직을 서비스에서 분리하고 싶은데 dao엔 접근할 수 밖에 없고, 이럴땐 어떤 좋은 방법이 있는지 궁금합니다.. dao엔 service만 접근할 수 있다는 제약을 거니 메서드를 다른 객체로 분리할 수가 없더라고요..

2022-05-14 08:10 UTC, lxxjn0 requested changes
조시, 3단계 미션 반영하신 부분 잘 봤습니다!!

제가 이번 주에 일정이 바빠서 빨리 리뷰해드리지 못한 점 죄송합니다 ㅠㅠ 리뷰 반영하시면 빠르게 다시 확인해보도록 할게요!!

이번 리뷰에서는 코드 레벨적인 부분에 대해서 주로 피드백을 남겨두었는데 한번 확인 부탁드려요!! :)

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
혹시 기존에 생성자를 정적 팩토리 메서드로 변경한 이유가 있을까요?? 어떠한 의도로 정적 팩토리 메서드를 정의하였을까요?

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Lines.java
> +    private List<Line> lines;
사이에 공백이 빠졌어요!!

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Section.java
> +    private Long id;
상수의 접근 지정자 확인과 상수와 필드 사이 공백을 둬야하는데 자바 코딩 컨벤션을 한번 확인해주세요 :)

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Section.java
> +    public static Section of(Long id, Section other) {
이런 경우에는 정적 팩토리 메서드를 만들고 section을 넘겨줘서 새로운 객체를 생성하기 보다는 인스턴스 메서드로 자기 자신에서 id를 갱신한 객체를 만들어서 반환하도록 하는 것이 어떨까요??

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Section.java
> +    }
여기서만 유효성 검증을 해주는 이유가 있을까요? 위에 생성자나 다른 정적 팩토리 메서드를 통해서 생성되는 객체의 경우 유효성이 검증되지 않은 객체가 될 것 같아요!!

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        sortDownToUp();
sortDownTop 메서드에서 정렬된 sections를 반환하고 그 값으로 this.sections를 초기화하는 방법이 더 좋을 것 같아요!! 지금은 불필요한 sections 초기화가 발생하는 것 같습니다!!

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return new ArrayList<>(stations);
스트림을 사용하면 좀 더 간단하게 고칠 수 있을 것 같아요!!

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/service/SubwayService.java
> +    private SectionDao sectionDao;
해당 필드들을 final로 가져가면 좀 더 안전하게 사용할 수 있지 않을까요???

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        orderedSections.add(sections.get(0));
이런 곳에서 사용하는 0은 상수로 관리해볼 수 있을 것 같아요!! 해당 로직에서 왜 0번째 구간을 추가를 하는지를 좀 더 자세히 설명해줄 수 있을 것 같아요!!

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Subway.java
> +public class Subway {
해당 객체가 가지고 있는 로직들을 보면 굳이 도메인으로 존재해야 하는 로직인가? 하는 생각이 들어요! 각각의 일급 컬렉션의 행위를 호출하는 정도로만 사용되는 것 같은데 이렇게 객체를 분리한 이유가 있을까요??

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/entity/SectionEntity.java
> +    public static List<Long> extractStationIds(List<SectionEntity> sectionEntities) {
이 부분은 한번 고민해볼 필요가 있을 것 같아요!! section이랑 sectionEntity가 동일한 로직을 가지고 있는데 이렇게 코드가 분산되면 추후 변경이 발생하는 경우 빠르게 추적하고 반영하기 어려울 것 같습니다!! sectionEntity를 section으로 바꿔서 도메인 로직을 실행하거나 또는 다른 방법을 한 번 고민해보면 좋을 것 같아요!!

2022-05-14 08:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/service/SubwayService.java
> +        Line line = Line.of(lineRequest.getName(), lineRequest.getColor());
lineRequest에서 line을 생성해주면 이러한 로직이 좀 더 깔끔하게 해결될 수 있을 것 같아요!!

2022-05-15 06:32 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
생성시 필요한 매개변수가 각각 달라서 정적 팩토리 메서드로 오버로딩해서 사용하면 어떨까 생각했습니다!! 사실 큰 이유가 있었다기 보단 생성자 오버로딩보단 정적 팩토리 메서드 오버로딩이 더 낫지 않을까라고 막연하게 생각했습니다.
이펙티브자바에서 빌더패턴을 소개하더라고요. 그래서 빌더 패턴을 한번 적용해보았습니다!

2022-05-15 10:39 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return new ArrayList<>(stations);
stream에 flatMap이라는 기능이 있었네요!!! 이 기능을 이용해 간단하게 줄일 수 있었습니다!! 감사합니다!

2022-05-15 15:59 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/Section.java
> +    private Long id;
넵!! 신경쓰겠씁니다!!

2022-05-15 15:59 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/Section.java
> +    public static Section of(Long id, Section other) {
넵 그렇게 변경했씁니다!!!

2022-05-15 15:59 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/Section.java
> +    }
빌더패턴을 적용하면서 모두 검증할 수 있도록 변경했습니다!!!

2022-05-15 16:00 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/Sections.java
> +        sortDownToUp();
그렇네요!! 감사합니다!!!
sections에 정렬 알고리즘이 필요없어져서 우선 삭제했습니다!!!

2022-05-15 16:01 UTC, hyunrrr commented on src/main/java/wooteco/subway/service/SubwayService.java
> +    private SectionDao sectionDao;
전체적으로 final을 붙일 수 있는 인스턴스 변수에 모두 붙였습니다!!!

2022-05-15 16:01 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/Sections.java
> +        orderedSections.add(sections.get(0));
그렇네요!! 상수로 추출했습니다!!

2022-05-15 16:03 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/Subway.java
> +public class Subway {
일급 컬렉션을 생성하고 일급컬렉션에 요청을 보내는 것이 도메인 로직 같다는 생각이 들었씁니다!! 서비스의 책임을 최대한 줄일려고 생각하다 보니 비록 2줄이긴 하지만 subway객체를 만들고 도메인 로직으로 책임을 분리해보았씁니다!!

2022-05-15 16:03 UTC, hyunrrr commented on src/main/java/wooteco/subway/service/SubwayService.java
> +        Line line = Line.of(lineRequest.getName(), lineRequest.getColor());
그렇네요!!! dto에서 생성하도록 변경했습니다!!!

2022-05-15 16:13 UTC, hyunrrr commented on src/main/java/wooteco/subway/domain/entity/SectionEntity.java
> +    public static List<Long> extractStationIds(List<SectionEntity> sectionEntities) {
이 부분을 고민해보았는데, 우선 첫번째로 sectionEntity를 section으로 사용하기가 좀 껄끄러웠습니다. sectionEntity에서는 lineId, stationId를 가지고 있는데, 추후에 도메인 로직 내부에서 sectionEntity의 구성요소인 LineId의 실제 객체(line), stationId의 실제 객체(station)과 상호작용을 하게 된다면 id값이 아닌 실제 객체가 필요하겠다 생각했습니다. 결국 db에서 조회해야 하는데 dao의존성이 없는 도메인에서 해결하기가 매우 껄끄러울거 같아 section과 sectionEntity를 분리했습니다.
우선 section에 존재하는 add알고리즘을 개선해 정렬이라는 중복되는 코드를 삭제하였고, extractStation라는 불필요 메서드를 section에서 삭제함으로써 최대한 중복되는 코드를 줄여보았습니다.

사실 미래의 막연한 변경가능성을 생각해 section과 sectionEntity를 분리했는데 현재 요구사항에선 코드가 좀 더 복잡해졌네요..
추가로 도메인 객체가 다른 도메인 객체가 아닌 다른 객체의 특정 필드(id)를 컴포넌트로 가진다는게 불편했는데 section과 sectionEntity를 분리한 것이 적절한 건 궁금합니다!

2022-05-17 11:35 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Line.java
> +    }
기존의 코드는 정적 팩토리 메서드가 단순히 생성자를 감싼 그 이상, 이하도 아니라는 생각이 들어서 한번 여쭤봤습니다!! 정적 팩토리 메서드가 가지는 여러 장점들을 활용할 수 있는 상황에서 적용을 해보면 좋을 것 같아요!

또는 조시가 코드 전체적으로 특정한 의도를 가지고 정적 팩토리 메서드를 사용한다면 코드를 이해하는 사람 입장에서는 더 와닿지 않을까 싶어요!! 저의 경우는 보통 객체가 가지는 프로퍼티만을 사용해서 객체를 생성할 때는 생성자를 사용하고 만약 내부적으로 어떠한 로직을 처리해서 객체를 생성해야 하는 경우에는 정적 팩토리 메서드를 사용합니다!!

이것처럼 개발자가 어떠한 기술을 사용할 때는 그 목적을 정확히 가지고 사용하는 것도 중요하다고 생각해요 :) 조시도 다음에 만약 어떠한 기술을 사용할 때 그 목적을 정확히 정하고 사용한다면 코드 전체적으로 통일감도 있고 이해하기 좋은 코드를 작성할 수 있을 거에요!! (물론 저도 잘 지키지는 못하는 부분이라 많은 노력이 필요한 것 같아요 ㅠㅠ)

2022-05-17 11:45 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Subway.java
> +public class Subway {
저의 생각으로는 현재 클래스에 있는 코드는 로직의 흐름이라고 생각하고 실제로 추가 여부를 확인할 수 있는 도메인 로직은 lines 내부에 있지 않은가요?? lines를 생성하고 메서드를 호출하는 정도는 도메인 로직이라고 보기엔 어려울 것 같아요!!

도메인 로직은 해결하고자 하는 문제를 해결하기 위한 로직인데 lines에 check를 하는 로직은 도메인 로직이라고 생각이 들지만 현재의 코드들은 서비스에 있는게 더 적절하지 않나 생각이 들어요!!

2022-05-17 15:10 UTC, lxxjn0 approved these changes
조시, 미션 완료 일자를 제대로 확인하지 못하고 이번에 피드백을 너무 급하게 남겨서 꼼꼼히 리뷰를 드리지 못했네요.. ㅠㅠ

지난 피드백에 대한 답변이랑 이번에 추가로 생각해보면 좋을 만한 부분에 대해서 조금 남겨보았어요!! 그리고 추가적으로 여기에 포함되지 않은 부분들 중에서 한번 고민해보면 좋을 만한 부분에 대해서 몇 가지 남겨둘 테니 한번 고민해보면 좋을 것 같아요!!

이번 지하철 노선도 미션 진행하느라 고생많았어요 :)

---

- `SectionController`를 보니 `/lines/{id}/sections`를 uri로 두었더라구요. 그렇다면 리소스의 위치가 section이 line의 내부에 있다는 말인데 실제 코드는 section이 line을 가지고 있어요!! 도메인 개념 상으로도 노선에 구간이 포함되어야 하는데 현재 도메인은 너무 데이터베이스 중심적으로 설계가 된 느낌도 듭니다. 이 부분을 한번 도메인 중심적인 구조로 설계해보고 바꿔보는 것도 많은 도움이 될 것 같네요 👍🏼 
- 현재는 `SubwayService`에서 모든 서비스 로직들을 관리하고 모든 도메인의 dao 접근을 하고 있는 것 같아요!! 각각의 도메인에 맞게 서비스를 분리하고 관리한다면 더 응집도 있는 서비스 객체를 만들 수 있을 것 같아요!! :)
- 리뷰에 남겨두긴 했지만 클래스를 작성하거나 메서드를 작성할 때 스스로의 기준이나 명확한 목적을 가져보는 연습을 해보는 것도 좋을 것 같아요!! 만약 틀린 방법이라 할 지라도 스스로의 기준과 목적을 가지고 일관되게 코드를 작성하는 것이 중요하다고 생각해요!! 그렇게 된다면 전반적은 코드의 관리와 이해가 더 쉽다고 생각되고요! 이번 기회에 한번 이러한 부분들을 채워나간다면 많은 도움이 될 것 같습니다!! 👍🏼

2022-05-17 15:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Line.java
>      }
이런 스타일의 메서드의 경우는 with을 메서드 명에 많이 사용하는 것 같아요!! `withId` 이런 식으로요!! 👍🏼

2022-05-17 15:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Section.java
> +    }
보통 클래스에서 코드 나열 순서가 프로퍼티 > 생성자 > 정적 메서드 > 인스턴스 메서드 > 이너 클래스 이런 식으로 나열되는 것으로 알고 있어요!! 만약 순서가 헛갈린다면 intellj에서 제공하는 formatting을 사용해보는 것도 좋을 것 같아요!!

> 파일을 우클릭하고 reformat code를 클릭하고 rearrange를 사용하면 될 거에요!!

![image](https://user-images.githubusercontent.com/48052622/168808854-4bf2fe16-f95e-4f4c-a113-38c18364a106.png)

2022-05-17 15:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Section.java
> +            validate(this);
유효성 검증을 생성자에서 가져가는 것은 어떤가요?? 만약 나중에 생성자를 통한 객체 생성이 필요해 질 경우 유효성 검증 로직이 중복으로 구현되어야 할 것 같아서요!!

2022-05-17 15:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    private SectionBuffer divideSection(Section newSection, Optional<Section> dividedSection, SectionBuffer sectionBuffer) {
Optional 객체에 대해서 한번 공부해보면 좋을 것 같아요!! 현재 매개변수로 Optional 객체를 받고 있는데 Optional 객체의 사용 용도와 맞지 않은 것으로 보여요!! Optional 객체가 어떠한 목적으로 어떻게 써야 하는지 한번 공부해본다면 도움이 많이 될 거에요 :)

2022-05-17 15:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        SectionBuffer sectionBuffer = new SectionBuffer();
해당 메서드 내부에서 buffer를 생성해서 linkUpStation, linkDownStation 메서드로 전달해주지 않고 각각의 매서드 내부에서 직접 생성해서 반환하는 것이 더 코드가 적절할 것 같아요!!

2022-05-17 15:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/Sections.java
>      }
`linkUpStation` 메서드와 `linkDownStation` 메서드가 section의 `isSameUpStation`, `isSameDownStation` 두 개의 메서드만 차이가 나는 것 같아요!! 이런 경우 함수형 인터페이스로 코드를 작성하면 하나의 메서드에서 모두 처리할 수도 있을 것 같아요 :)

하지만 이렇게 함수형 인터페이스로 처리하는 것이 좋은 방법인가를 물어보면 사실 그렇게 좋지도 나쁘지도 않은 방법이라고도 생각이 듭니다.. 그래서 한번 이런 식으로도 개선해 볼 수 있겠구나 하는 체험만 해보는 것도 좋을 것 같아요!!

2022-05-17 15:10 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/entity/SectionEntity.java
> +    public static List<Long> extractStationIds(List<SectionEntity> sectionEntities) {
entity를 따로 가져가는 것이 안 좋은 방법은 아니라고 생각해요!! 만약 sectionEntity를 DB에서 읽어온 데이터만 관리하는 목적이라면 그에 맞는 책임만 가지고 이외의 도메인과 관련된 로직은 section으로 변경 후 section의 도메인 로직을 사용하는게 좋다고 생각해요!! 

그렇다면 도메인 로직은 한 곳에서만 관리되고 section은 그에 따른 도메인 로직을 관리하는 책임을 가지게 될 것이니깐요 :) 이전에는 책임이 명확히 분리되지 못하고 동일한 로직이 양 쪽에 모두 존재했기 때문에 잘못된 구조라고 생각이 들었습니다!! 엔티티는 엔티티로, 도메인은 도메인으로 책임의 범위를 명확히 정하고 상황에 맞게 적절히 사용하는 것이 좋을 것 같아요 👍🏼

2022-05-17 15:10 UTC, merged