[Spring 지하철 노선도 - 3단계] 이브(이유정) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #297
Opened 2022-05-11 17:05 UTC by 2yujeong

안녕하세요 럿고!
3단계 미션 제출합니다🙂

2022-05-14 00:07 UTC, ksy90101 requested changes
안녕하세요 이브 :)
3단계 미션도 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니 확인해주세요~

2022-05-14 00:07 UTC, ksy90101 commented on src/main/java/wooteco/subway/dao/JdbcSectionDao.java
> +            );
이 부분이 중복같은데 한번 함수형 인터페이스로 빼면 좋지 않을까요?

2022-05-14 00:07 UTC, ksy90101 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return sections.size() == 2;
매직넘버!

2022-05-14 00:07 UTC, ksy90101 commented on src/main/java/wooteco/subway/service/LineService.java
> +            .collect(Collectors.toList());
불변으로 리턴해주면 더 좋을거 같네요 :)

2022-05-14 00:07 UTC, ksy90101 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
두개를 분리해두신 이유가 있나요?

2022-05-14 00:07 UTC, ksy90101 commented on src/main/java/wooteco/subway/ui/SectionController.java
> +        return ResponseEntity.ok().build();
내려줄 값이 없다면 no_content가 좋을거 같네요!

2022-05-14 00:07 UTC, ksy90101 commented on src/main/java/wooteco/subway/ui/SectionController.java
> +        return ResponseEntity.ok().build();
created 201로 하면 어떨까요?

2022-05-14 00:07 UTC, ksy90101 commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +        return RestAssured.given().log().all().body(lineRequest);
한줄에 점 하나로 가독성을 높어보죠 :)

2022-05-14 00:07 UTC, ksy90101 commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +            .extract();
여긴 공통 템플릿처럼 빼지 않은 이유가 있나요?

2022-05-14 00:07 UTC, ksy90101 commented on src/main/java/wooteco/subway/domain/Sections.java
> +public class Sections {
section 도메인에 들어가도 되는 로직들이 보이는거 같은데, 한번 책임을 나눠볼까요?

2022-05-14 05:25 UTC, 2yujeong commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
SectionRequest에서 getter로 값을 꺼내는 코드가 가독성을 해치는 것 같아서 메소드 오버로딩으로 분리해줬어요!
리팩토링을 진행하면서 코드 가독성이 향상되니까 굳이 분리할 필요가 없다고 생각돼서 다시 하나로 리팩토링했습니다😀

2022-05-14 05:30 UTC, 2yujeong commented on src/main/java/wooteco/subway/ui/SectionController.java
> +        return ResponseEntity.ok().build();
럿고가 말씀하신 대로  반환 값이 없을 때의 상태 코드는 no_content가 좋다고 생각해서 수정해줬어요!
제공된 프론트엔드 페이지와 연동해서 테스트할 때도 제대로 동작하는데, API 명세에 보면 구간 제거 요청에 대한 응답이 다음처럼 200으로 되어있어요.

> HTTP/1.1 200 OK

같은 200번대의 상태 코드라면 서버쪽에서 유연하게 상태 코드를 변경해서 반환해줘도 괜찮을까요?

2022-05-14 05:39 UTC, 2yujeong commented on src/main/java/wooteco/subway/ui/SectionController.java
> +        return ResponseEntity.ok().build();
created()를 사용하면 생성된 리소스의 경로를 함께 넘겨줘야 하는데 구간 추가 요청은 한 번의 요청으로 두 개의 구간이 생성되는 경우가 있어서 반환 값을 넘겨주지 못했어요😥
구간 A-C 사이에 A-B라는 구간을 추가하면 A-B, B-C 총 두 개의 구간이 생기는데 이런 경우는 어떻게 처리하는 게 좋을까요?

2022-05-14 05:46 UTC, 2yujeong commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +            .extract();
기존에 상위 클래스에서 공용 메소드로 처리해줬던 DELETE Request는 body()가 존재하지 않아서 body()가 포함된 SectionAcceptanceTest는 따로 빼주지 않았었어요!
SectionAcceptanceTest도 빼주는 게 좋을 거 같아서 메소드 오버로딩을 활용했습니다!

2022-05-14 06:06 UTC, 2yujeong commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return sections.size() == 2;
메소드명으로도 의미를 알기에 충분한 경우라 매직넘버를 사용해도 괜찮다고 생각했어요!
막상 상수화하려니 적당한 네이밍이 떠오르지 않더라고요ㅜㅜ
다른 매직넘버가 사용된 부분들은 확인하고 상수화로 빼줬습니다!

2022-05-16 10:42 UTC, ksy90101 approved these changes
이브 안녕하세요 :) 
미션 하시느라 너무 고생 많으셨습니다 💯 
간단한 피드백을 드렸습니다! 이건 머지하시고도 충분히 수정할수 잇을듯 해서 머지하겠습니다.
혹시라도 더 보면 좋을것이 있다면 언제든지 슬랙으로 연락주세요~

2022-05-16 10:42 UTC, ksy90101 commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    @DisplayName("상행종점을 삭제한다.")
여긴 Parameterized Test를 사용해볼수 있지 않을까요?

2022-05-16 10:42 UTC, ksy90101 commented on src/main/java/wooteco/subway/ui/SectionController.java
> +        return ResponseEntity.ok().build();
그런 경우에는 line을 내려줘도 좋을거 같아요.
지금 보니 sections에 대한 단일 조회는 없네요 :)

2022-05-16 10:42 UTC, ksy90101 commented on src/main/java/wooteco/subway/ui/SectionController.java
> +        return ResponseEntity.ok().build();
앗 API문서가 있는지 따로 몰랐습니다 ㅠㅠ

2022-05-16 10:42 UTC, merged