[Spring 지하철 노선도 - 3단계] 코린(유현지) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #298
Opened 2022-05-11 17:20 UTC by hamcheeseburger

카일 안녕하세요~~ 3단계로 다시 뵙게됐네요!!

도메인을 활용하면서 구현을 하려다보니 많이 헤맸던 것 같아요🥲

이번 리뷰도 잘 부탁드립니다!

2022-05-14 05:51 UTC, KIMSIYOUNG requested changes
안녕하세요 코린! 
3단계 미션도 잘 구현해주셨네요. 
테스트도 꼼꼼하게 작성해주시고 로직도 도메인 중심으로 잘 구현해주신 것 같아요.
몇가지 코멘트 남겼으니 확인 부탁드려요!

2022-05-14 05:51 UTC, KIMSIYOUNG commented on README.md
> +   - [ ] upStationId, downStationId, distance를 추가로 받도록 변경한다.
얘도 체크해주세요🙂

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Line.java
> +    public boolean equals(Object o) {
요건 왜 선언하셨나요?

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final Station upStation;
id값이 아니라 Station을 직접 갖도록 설계해주셨네요🙂 혹시 어떤 차이와 장단이 있는지 공유해주실 수 있을까요?

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Section.java
> +    public Section(final Station upStation, final Station downStation, final int distance) {
부생성자👏

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Section.java
> +    public Section createSectionByUpStation(final Section section) {
아래와 같이 표현해도 충분히 의미가 담기는 것 같아요.

```public Section create(final Section upStation)```

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Sections.java
> +public class Sections {
도메인로직을 담당하는 객체를 잘 설계해주셨네요👏

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Sections.java
> +        origin.removeAll(sections);
섹션의 식별자를 기준으로 제거하는 것이 적절할 것 같아요. 섹션의 식별자는 무엇인가요?

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Sections.java
> +        mergeSection(sections.get(0), sections.get(1)).ifPresent(value::add);
0과 1이 어떤 의미를 담고 있는지 상수로 포장하면 어떨까요?

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/dto/LineRequest.java
> +    @NotBlank(message = "노선 이름은 공백일 수 없습니다.")
NotBlank도 Null인 경우도 벨리데이션을 하고 있기 때문에 NotNull은 제거해주셔도 될 것 같아요.

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/dto/SectionRequest.java
> +    public static SectionRequest from(final Section section) {
사용하지 않는 코드는 제거해주세요🙂 어떤 이유로 요게 생겼었나요?

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/service/LineService.java
> +        if (lineDao.findByName(line.getName()).isPresent()) {
Exist나 Count쿼리가 아니라 값을 직접 찾아오는 이유가 있나요?

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/service/SectionService.java
> +    @Transactional
트랜잭션 어노테이션을 잘 사용해주셨네요🙂 LineService에도 같이 추가해볼까요?

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/service/SectionService.java
> +    public SectionService(final SectionDao sectionDao, StationDao stationDao) {
전체적으로 final을 사용한 곳과 아닌 곳이 공존하는데요 어떤 기준으로 나뉘는 걸까요?

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/acceptance/AcceptanceTestFixture.java
> +    public static ExtractableResponse<Response> post(String uri, Object param) {
깔끔하게 잘 추상화해주셨네요👏

2022-05-14 05:51 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +@Transactional
테스트에서 해당 어노테이션을 사용하는 이유가 있나요?

2022-05-14 13:39 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/domain/Line.java
> +    public boolean equals(Object o) {
테스트에서 Line이 갖는 필드들이 같은 값인지 비교하기 위해서 만든 메소드들 입니다!
프로덕션에서 사용하지 않는다면 제거하는게 좋을까요??

2022-05-14 13:43 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final Station upStation;
- Section이 Station을 가질 때
    
    Section을 불러올 때 Station을 join하여 가져오므로, 도메인에서 비지니스 로직을 처리하기 용이하다는 장점이 있습니다.
    
    하지만 join 연산이 비용이 높은 것이 단점인 것 같아요. Station을 활용하는 일이 없을 때도 무거운 쿼리가 실행되겠네요!
    
- Section이 StationId를 가질 때
    
    select 쿼리 연산이 간결하고 빠르다는 장점이 있을 것 같아요.
    다만, Station이 필요한 로직에서 추가적인 select 쿼리가 필요해진 다는 점이 단점일 것 같습니다.
    

현재 미션에서 Section에서 Station 정보까지 필요한 경우가 대다수이므로 Section이 Station을 가지고 있는 방향이 좀 더 적절하다고 생각이 들어 구현하게 되었습니다.

2022-05-14 13:43 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/domain/Section.java
> +    public Section createSectionByUpStation(final Section section) {
메소드명을 변경하려고 보니 필요없는 메소드인 것 같아 삭제하였습니다 🙂

2022-05-14 13:45 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/domain/Sections.java
> +        origin.removeAll(sections);
> 섹션의 식별자를 기준으로 제거하는 것이 적절할 것 같아요.
    
확실히 전달되는 배열을 Sections의 배열에서 바로 제거하는 것 보다, 원본 객체들을 찾고 해당 객체들을 삭제하는 것이 의미있는 값들을 삭제한다는 느낌이 드네요! 
    
> 섹션의 식별자는 무엇인가요?

Section의 식별자는 id입니다! 그런데 지금 변경한 로직에서는 Section의 모든 필드가 식별자가 되는 상황입니다.😢 이렇게 구현하게 된 이유를 아래에서 설명 드리겠습니다.

Sections의 `extract()`는 전달 받은 배열과 Sections의 배열을 비교하여 `값이 바뀐 객체`들을 가져오기 위해 만들어진 메소드 입니다! `값이 바뀐 객체` 에는 id는 그대로지만 다른 필드들이 업데이트 되는 객체도 포함이 되어 있어요. 그렇게 때문에 식별자인 id로 값을 찾게 되면 제가 원하는 `값이 바뀐 객체` 를 찾아올 수가 없었습니다!

그래서 현재 Section의 모든 필드들을 비교하여 객체를 찾아오고 해당 객체들을 삭제하여 반환하는 방식으로 구현하였습니다. Section의 모든 필드가 식별자가 되는 상황이죠.. ㅠㅠ

혹시 몰라서 변경된 코드를 첨부하겠습니다.

```java
public List<Section> extract(final List<Section> sections) {
    List<Section> origin = new ArrayList<>(value);
    origin.removeAll(findSections(sections));
    return origin;
}

private List<Section> findSections(List<Section> sections) {
    return sections.stream()
                .map(this::findSection)
                .filter(Optional::isPresent)
                .map(Optional::get)
                .collect(Collectors.toList());
}

private Optional<Section> findSection(Section section) {
    return value.stream()
                .filter(originSection -> originSection.equals(section))
                .findFirst();
}
```

카일은 위의 코드에 대해서 어떻게 생각하시는지 궁금합니다! 어색하게 느껴지시거나 잘못 설계된 것 같다면 말씀해주시면 감사하겠습니다🙏🏻

2022-05-14 13:47 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/dto/SectionRequest.java
> +    public static SectionRequest from(final Section section) {
사실 필요해서 만든 메소드가 아니라 그냥 ‘필요하지 않을까?’ 싶어서 미리 만들어 놓은 메소드였습니다..🥲 response dto로 헷갈렸던 것 같아요 ㅠㅠ
사용하지 않으면 제 때 지웠어야 했는데, 꼼꼼하게 확인하지 못한점 죄송합니다.

2022-05-14 13:47 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/service/LineService.java
> +        if (lineDao.findByName(line.getName()).isPresent()) {
저번 리뷰 때도 말씀 드렸듯이, exist나 count 쿼리는 `값이 존재하는지 확인하는 로직` 에만 치중된다고 생각했어요! `findByName()` 이라는 메소드를 만들어 놓으면, 나중에 다른 로직에서 사용할 가능성이 더 높다고 생각했기 때문입니다.

특히나 DAO의 메소드에서는 비지니스 로직이 포함되지 않게 하고 그저 값을 조회,수정,삭제,삽입 하는 용도로만 쓰고 싶었습니다!

카일은 이런 상황에서 어떤 방법으로 구현하실지 궁금합니다!

2022-05-14 13:48 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/service/SectionService.java
> +    public SectionService(final SectionDao sectionDao, StationDao stationDao) {
이것 또한 저의 불찰입니다.. ㅠㅠ final을 붙이는 것으로 수정하였습니다!

2022-05-14 13:51 UTC, hamcheeseburger commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +@Transactional
`@Transactional` 을 말씀하시는게 맞으실까요??

Line과 Station의 name이 DB에서 unique하게 처리되어 있는데요,
beforeEach로 계속 Line과 Station을 저장해주는 로직때문에 각 테스트가 끝나면 rollback하기 위해 `@Transactional` 을 사용하였습니다! Mock을 사용한 테스트가 아니고 Dao단까지 내려가는 통합테스트 라서 `@JdbcTest` 를 사용하여 `@Transactional` 을 제거할 수 있을 것 같다는 생각도 듭니다!

카일은 어떤 방법이 더 낫다고 보시나요?? 제가 생각한 방법 외에도 좋은 방법이 있다면 알려주시면 감사하겠습니다!! 🙏🏻

2022-05-14 16:53 UTC, hamcheeseburger commented
안녕하세요 카일! 
1,2단계 때 [리뷰](https://github.com/woowacourse/atdd-subway-map/pull/199#discussion_r868558246)해주신 `서비스 레이어에서의 DTO 사용`에 대해 말씀드리려고 합니다!

링크가 걸려있는 리뷰의 댓글로 달았던 내용인데, 여기에도 첨부할게요!

### 서비스 레이어에서의 DTO 사용

저는 서비스 레이어에서 DTO를 사용하게 되면 DTO로의 변환 로직이 너무 많아질 것 같아, 비지니스 로직을 담당하는 본래의 역할을 해친다고 생각했습니다!

하지만 이번에 3단계 미션을 하면서, Line을 저장함과 동시에 Section을 함께 저장해야 하는 기능 때문에 LineService의 `create()`가 아래와 같이 변경되었습니다.

```java
public Line create(Line line, Section section) {
}
```

이와 같이 request가 변경될 때 마다 전달되어야 하는 파라미터가 달라지게 되면, 코드 재사용성이 떨어질 것 이라는 생각이 들더라구요.

이 때 LineRequest가 전달 되면 요청값이 달라지더라도 create() 메소드의 전달 파라미터 값은 변하지 않기 때문에 이런 부분에서 이점을 볼 수 있다고 생각했습니다.

```java
public Line create(LineRequest lineRequest){
}
```

### 컨트롤러와 DAO가 도메인을 반환했을 때 단점
컨트롤러가 도메인을 반환하게 되면 민감하고 불필요한 정보까지 뷰로 전달이 된다는 것이 단점일 것 같습니다.

DAO가 도메인을 반환하게 되면 불필요한 비지니스 로직을 DAO에서 사용할 가능성이 있다는 것이 단점이 될 것 같습니다.

하지만 지금 지하철 노선도 미션에서는 도메인과 db 테이블 구조가 동일하고, DAO에서는 new 키워드를 통해 도메인을 생성하고 있을 뿐인지라 오히려 Entity와 같은 추가적인 객체를 만드는 것이 불필요하다는 생각이 들었습니다!
<br>
그래서 이번 PR에서는 Service로 request dto로 전달하고 response dto를 반환하는 식으로 변경하였습니다!

2022-05-14 16:54 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
안녕하세요 카일! 
1,2단계 때 [리뷰](https://github.com/woowacourse/atdd-subway-map/pull/199#discussion_r868558246)해주신 `서비스 레이어에서의 DTO 사용`에 대해 말씀드리려고 합니다!

링크가 걸려있는 리뷰의 댓글로 달았던 내용인데, 여기에도 첨부할게요!

### 서비스 레이어에서의 DTO 사용

저는 서비스 레이어에서 DTO를 사용하게 되면 DTO로의 변환 로직이 너무 많아질 것 같아, 비지니스 로직을 담당하는 본래의 역할을 해친다고 생각했습니다!

하지만 이번에 3단계 미션을 하면서, Line을 저장함과 동시에 Section을 함께 저장해야 하는 기능 때문에 LineService의 `create()`가 아래와 같이 변경되었습니다.

```java
public Line create(Line line, Section section) {
}
```

이와 같이 request가 변경될 때 마다 전달되어야 하는 파라미터가 달라지게 되면, 코드 재사용성이 떨어질 것 이라는 생각이 들더라구요.

이 때 LineRequest가 전달 되면 요청값이 달라지더라도 create() 메소드의 전달 파라미터 값은 변하지 않기 때문에 이런 부분에서 이점을 볼 수 있다고 생각했습니다.

```java
public Line create(LineRequest lineRequest){
}
```

### 컨트롤러와 DAO가 도메인을 반환했을 때 단점
컨트롤러가 도메인을 반환하게 되면 민감하고 불필요한 정보까지 뷰로 전달이 된다는 것이 단점일 것 같습니다.

DAO가 도메인을 반환하게 되면 불필요한 비지니스 로직을 DAO에서 사용할 가능성이 있다는 것이 단점이 될 것 같습니다.

하지만 지금 지하철 노선도 미션에서는 도메인과 db 테이블 구조가 동일하고, DAO에서는 new 키워드를 통해 도메인을 생성하고 있을 뿐인지라 오히려 Entity와 같은 추가적인 객체를 만드는 것이 불필요하다는 생각이 들었습니다!
<br>
그래서 이번 PR에서는 Service로 request dto로 전달하고 response dto를 반환하는 식으로 변경하였습니다!

2022-05-15 14:08 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Line.java
> +    public boolean equals(Object o) {
네네! 만약 추후에 사용할 일이 있다면, 도메인 객체에서 equals & hashcode 를 오버라이드 할 때는 어떤 값이 적절할지 고민해보면 좋을 것 같아요.

2022-05-15 14:09 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final Station upStation;
좋은 생각인 것 같습니다. 

말씀하신대로 어플리케이션의 코드는 깔끔해지고 로직이 줄어든다는 장점이 있지만 불필요한 데이터도 모두 가져오게 되는 단점도 존재하기 때문에 이 부분을 인지하고 있으시면 좋을 것 같아요.🙂

2022-05-15 14:17 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/domain/Sections.java
> +        origin.removeAll(sections);
변경이 되는 값을 업데이트할 때 업데이트의 대상이 되는 값들을 저장해두는건 어떨까요? 이 방법은 왜 고려되지 않았는지 설명해주실 수 있나요? 

일단 현재 방식으로 구현한 이유에 대해서는 이해했습니다🙂

2022-05-15 14:21 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/dto/SectionRequest.java
> +    public static SectionRequest from(final Section section) {
아녜요! 죄송할 필요 전혀 없습니다🙂

사용하지 않는 코드들은 오인할 수 있으니 바로바로 제거해주세요🙂

2022-05-15 14:24 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/service/LineService.java
> +        if (lineDao.findByName(line.getName()).isPresent()) {
저도 현재라면 코린처럼 작성했을 것 같아요🙂

보다 추상화된 (단순히 있따 없다가 아닌 값 자체를 제공하는) 메소드는 더 많은 사용의 여지를 남겨주니까요🙂 

다만 여기서 필요한 기능은 `Exist`임을 인지하고 있지만 재활용성을 위해 + 현재는 성능상의 이슈를 일으키지 않는다는 생각을 가지고 구현하셨는지 여쭤보고 싶었어요. 잘 구현해주신 것 같아요.

2022-05-15 14:28 UTC, KIMSIYOUNG commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +@Transactional
트랜잭션을 롤백과 동일한 의미로 바라보고 사용하시면 안될 것 같아요. 

말씀하신대로 `각 테스트간의 데이터격리를 통한 격리환경 구축`을 위해서 사용할 수도 있는 방법이긴하지만 트랜잭션은 그러한 용도로 만들어진게 아니기에 적절하지 않은 것 같아요.  (사용할 순 있습니다. 개인적으로 이러한 형태로 사용되면 안된다고 생각할 뿐입니다.)

말씀하신 방법은 아래의 블로그에 잘 정리되어 있는 것 같아요🙂

https://tecoble.techcourse.co.kr/post/2020-09-15-test-isolation/

2022-05-15 14:38 UTC, KIMSIYOUNG commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
안녕하세요 코린! 너무 좋은 관점인 것 같습니다🙂

저는 `컨트롤러와 DAO가 도메인을 반환했을 때 단점` 이 부분이 중요하다고 생각했어요. 두 레이어는 도메인을 알아도 되는가? 라는 것은 고민해볼만한 주제였고 이 고민의 결과물로 서비스가 도메인을 받을 `수`도 있게 되니까요. 현재의 코린의 생각에 충분히 근거가 있고 적절한 선택인 것 같아요. 

서비스레이어에서 DTO를 사용해서 필요한 값만을 전달받고 변경에 대해서도 파라미터만 달라지는 것도 좋은 선택지인 것 같아요.

2022-05-15 14:40 UTC, KIMSIYOUNG approved these changes
안녕하세요 코린!
리뷰 반영 잘 해주셨네요. 리뷰에 대한 코린 생각도 잘 정리해주셔서 감사합니다. 
댓글에 대해서 제 의견도 조금 추가했는데 확인 부탁드립니다.
이번 미션은 여기서 머지하면 좋을 것 같아요.
추가적으로 궁금하신 내용은 편하게 말씀해주세요🙂

2022-05-15 14:40 UTC, merged

2022-05-18 03:47 UTC, hamcheeseburger commented on src/main/java/wooteco/subway/domain/Sections.java
> +        origin.removeAll(sections);
값을 저장해두라는 말씀은 Sections에 필드를 하나 추가하라는 말씀으로 이해해도 될까요??
제가 이해한 바로는 일급 컬렉션이 다른 상태를 갖는 필드를 두어도 될까? 라는 고민 때문에 최대한 두지 않는 방향으로 고려를 했던 것 같아요.

그런데 생각을 조금 다르게 하니, 일급 컬렉션에 다른 필드를 두면 안되는 이유가 딱히 없을 것 같아요. 다른 필드가 있음에도 일급 컬렉션은 컬렉션을 감싸는 래퍼 클래스로써의 역할을 충분히 한다고 생각하거든요!

카일이 말씀하신 방법대로 구현한다면 수정할 객체들을 불러오는 로직히 훨씬 간결해질 것 같아요 🙂