[Spring 지하철 노선도 - 3단계] 잉(유영우) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #304
Opened 2022-05-11 18:31 UTC by Yboyu0u

안녕하세요 철시✋🏻 잉입니다.
지하철이 생각보다 어려워서 늦게 PR을 보내게 됐네요.

많은 지적 부탁드립니다🥲

2022-05-12 22:35 UTC, pkch93 requested changes
안녕하세요 잉~ 👋
3단계 미션 구현 잘해주셨네요 👍 
몇가지 피드백 남겼는데 확인부탁드릴께요 ㅎㅎ

2022-05-12 22:35 UTC, pkch93 commented on src/test/java/wooteco/subway/domain/SectionsTest.java
> +    }
getSectionForCombine1는 하행과 연결되는 부분에 대한 테스트이고 getSectionForCombine2는 상행과 연결되는 구간에 대한 테스트로 보이네요. 각각 테스트 이름 및 설명도 이에 맞게 지정해주면 좋을거 같아요.

2022-05-12 22:35 UTC, pkch93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +                upStationSection.getDownStationId());
station을 지우면서 station에 연결된 구간도 다시 연결되는 로직으로 이해햇는데요. 거리를 다시 계산해 주는 로직은 보이지 않아서요. 혹시 누락일까요?

2022-05-12 22:35 UTC, pkch93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +        if (jdbcSectionDao.isExistByUpStationIdAndDownStationId(upStationId, downStationId)) {
createSection 내에서 입력값 검증을 위해 여러 쿼리를 사용하는데요. sections를 조회해서 Sections 객체를 만들어낸다면 위 쿼리는 제거가능하지 않을까요?

2022-05-12 22:35 UTC, pkch93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +            addBranch(section, upStationId, downStationId, distance, lineId);
검증 메서드 내부에서 따로 저장하는 로직이 들어가 있는데요. 메서드 이름에 맞게 이 메서드에서는 구간을 추가할 수 있는지만 체크하고 실제 추가하는 부분은 createSection으로 올려서 한눈에 로직을 볼 수 있게 구성하면 어떨까요?

2022-05-12 22:35 UTC, pkch93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    private void addBranch(Section section, Long upStationId, Long downStationId, int distance, Long lineId) {
addBranch의 로직은 `Sections#getSectionForCombine` 내부에서도 처리할 수 있지 않을까 싶은데요.
지금 저장된 구간에 대한 정보를 가장 잘알고 있는 Sections로 옮겨볼 수 있을까요?

2022-05-13 08:34 UTC, Yboyu0u commented on src/test/java/wooteco/subway/domain/SectionsTest.java
> +    }
테스트에 설명을 달아놓았습니다!!

2022-05-14 17:13 UTC, Yboyu0u commented on src/main/java/wooteco/subway/service/SectionService.java
> +                upStationSection.getDownStationId());
앗 거리를 다시 넣어주는 것을 깜빡했네요...!! 추가해 놓았습니다🙃

2022-05-14 18:22 UTC, Yboyu0u commented on src/main/java/wooteco/subway/service/SectionService.java
> +    private void addBranch(Section section, Long upStationId, Long downStationId, int distance, Long lineId) {
음... 이 부분에 대해 고민을 해봤는데 addBranch() 로직이 Sections로 들어가게 된다면,
dao를 사용하는 부분도 Sections 내부에 들어가야 할 것 같아요. (제가 피드백을 잘 못 이해한 걸 수도....)

이렇게 되어도 괜찮을까요?? 
Sections#getSectionForCombine에서 저 로직이 들어가게 되면 좀 더 효율적인 코드가 될 것 같다는 생각은 듭니다!

2022-05-15 05:13 UTC, pkch93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    private void addBranch(Section section, Long upStationId, Long downStationId, int distance, Long lineId) {
결국은 `getSectionForCombine`을 통해서 상행 또는 하행역이 같은 경우 해당 Section을 업데이트해주기 위함이잖아요. 지금은 `getSectionForCombine`에서는 상행, 하행이 같은지 여부만 판단해서 반환하고 Service에서 추가로 판단하는 로직이 들어가 있는데 `getSectionForCombine`에서 모든 판단을 하고 Service에서는 업데이트 대상인 Section을 그대로 Dao로 넘겨서 수정할 수 있을거 같아요.

2022-05-15 07:28 UTC, Yboyu0u commented
안녕하세요. 철시✋🏻
매번 소중한 리뷰 감사합니다🙏🏻

피드백받은 것 이외에 
1. 지하철역 구간 삭제 시 구간이 등록되어 있으면 예외 발생 로직 (Sections)
```
java

 public List<Long> getStationIds() {
        List<Long> stationIds = new ArrayList<>();
        Section firstSection = getFirstSection();
        stationIds.add(firstSection.getUpStationId());
        Long nextStation = firstSection.getDownStationId();
        while (nextStation != NOTING) {
            stationIds.add(nextStation);
            nextStation = getNextStation(nextStation);
        }
        return stationIds;
    }
```

2. 지하철 구간 구간별로 정렬하는 로직 (StationService)
```
java

    public boolean deleteStation(Long id) {
        if (sectionDao.isExistByStationId(id)) {
            throw new IllegalArgumentException("구간이 등록되어 있기 때문에 역을 삭제할 수 없습니다.");
        }
        return stationDao.deleteById(id);
    }
```

를 추가하였습니다!

많은 지적 부탁드릴게요🥲

2022-05-15 07:36 UTC, Yboyu0u commented on src/main/java/wooteco/subway/service/SectionService.java
> +    private void addBranch(Section section, Long upStationId, Long downStationId, int distance, Long lineId) {
앗 코멘트 남겨주신 것 지금 봤네여! 감사합니다. 
좀 더 고민해 보도록 하겠습니다!!

2022-05-15 14:36 UTC, pkch93 approved these changes
지하철 노선도 미션이 쉽지 않았을텐데 고생하셨습니다 잉~ 💯 
잉의 이번 지하철 노선도 미션은 마무리 할께요.
다음 미션도 화이팅입니다. 💪

2022-05-15 14:36 UTC, pkch93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    public boolean deleteSection(Long lineId, Long stationId) {
createSection이나 deleteSection에서는 여러 쿼리가 나가는데요.
트랜잭션과 함께 Spring에서 선언적으로 트랜잭션을 사용할 수 있도록 도와주는 `@Transactional`에 대해서도 학습해보면 좋을거 같아요.

`@Transactional` 참고: https://goddaehee.tistory.com/167

2022-05-15 14:37 UTC, merged