[Spring 지하철 노선도 - 3단계] 파랑(이하은) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #306
Opened 2022-05-11 19:33 UTC by summerlunaa

안녕하세요 로운! 파랑입니다.

3단계가 어려워서 시간이 많이 걸렸네요ㅠㅠ 수정하고 싶은 부분이 많은데 우선은 PR 보냅니다!

특히나 예외 처리, stations, test 부분을 계속해서 수정할 것 같습니다.

부족한 코드이지만 많은 피드백 부탁드립니다!

감사합니다!

2022-05-12 08:39 UTC, lowoon requested changes
반가워요 파랑! 2단계도 잘 부탁해요 😄 
몇 가지 코멘트 남겼으니 확인해주세요ㅎㅎ
궁금한 점이 생기면 언제든지 DM 혹은 댓글남주세요 ^-^

2022-05-12 08:42 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Sections.java
> +public class Sections {
Line이 sections를 가지는 방법은 생각해보셨을까요?

2022-05-12 08:43 UTC, lowoon commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
>  public class LineAcceptanceTest extends AcceptanceTest {
사용자의 시나리오대로 잘 하셨네요!

2022-05-12 08:43 UTC, lowoon commented on src/main/java/wooteco/subway/ui/LineController.java
>  public class LineController {
controller에 대한 테스트가 없는거 같아요!

https://tecoble.techcourse.co.kr/post/2021-05-25-unit-test-vs-integration-test-vs-acceptance-test/

2022-05-12 08:47 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Sections.java
> +        Set<Long> downStationIds = getDownStationIds(sections);
downStationIds를 찾은 후에 상행종점을 찾는군요 💯 

참고만 하시면 될 것 같은데요. 저는 상행종점의 upStationId를 null로 해서 찾는 방법을 활용했습니다!
이러한 방법도 있구나라고 참고만 하시면 될 것 같아요!

2022-05-12 08:47 UTC, lowoon commented on src/main/java/wooteco/subway/ui/SectionController.java
> +@RequestMapping("/lines/{lindId}/sections")
lines에 포함되는데 sectionController를 따로 만든 이유가 있을까요?

2022-05-12 08:52 UTC, lowoon commented on src/main/java/wooteco/subway/service/SectionService.java
> +        if (sections.isRequireUpdateForSave(section)) {
필요한 경우에만 update를 하고 있는데요 👍 
추후를 위해 saveAll과 같이 여러개를 저장하는 방법도 학습해놓으시면 좋을것 같아요~

2022-05-12 08:56 UTC, lowoon commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    private Long postStation(StationRequest stationRequest) {
acceptanceTest에서 중복으로 사용되는 부분이라면 AcceptanceTest에 넣어두어서 상속받는 곳에서 모두 사용하도록 할 수도 있을 것 같아요~

2022-05-12 08:59 UTC, lowoon commented on src/main/java/wooteco/subway/service/LineService.java
> +    private final SectionDao sectionDao;
dao가 service들에서 중복으로 사용되는 경우가 있는데요. 어떻게 하는것이 역할에 맞을까요?
역할과 책임에 대해 한번 고민해보면 좋을것 같아요!

2022-05-15 12:41 UTC, summerlunaa commented on src/main/java/wooteco/subway/ui/SectionController.java
> +@RequestMapping("/lines/{lindId}/sections")
lines에 포함되긴 하지만 domain에서부터 service까지 전부 line과 section을 분리했기 때문에 controller도 분리하였습니다!

2022-05-15 12:41 UTC, summerlunaa commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    private Long postStation(StationRequest stationRequest) {
오 그 생각을 못했네요ㅎㅎ 중복되는 메서드를 AcceptanceTest로 이동시켰습니다!

2022-05-15 13:39 UTC, summerlunaa commented on src/main/java/wooteco/subway/ui/LineController.java
>  public class LineController {
지금의 acceptance test는 controller에 대한 테스트까지 함께 해주고 있다고 생각이들었습니다. 그래서 controller test에 대한 필요성을 느끼지 못해서 추가하지 않았습니다! 뭔가 두 개의 테스트가 분명히 다르면서도 비슷한 부분을 검증해주고 있다는 생각이 드네용🤔.

2022-05-15 13:47 UTC, summerlunaa commented on src/main/java/wooteco/subway/domain/Sections.java
> +public class Sections {
그렇게 한 크루들이 있다고 해서 둘 중에 어떤 방법을 할까 고민하다가 일단 나눠서 만들어보자는 생각으로 Line 안에 포함시키지 않았습니다. 근데 포함시키지 않았을 때 크게 안 좋은점을 느끼지 못해서 그대로 두었습니다😅
지금 다시 생각해보면 노선 없이는 구간이 존재할 수 없고, 구간은 무조건 노선에 포함되기 때문에 Line이 sections를 가지는 게 좀 더 맞는 것 같기는 한데.. Line이 sections를 가졌을 때 어떤 장점이 있는지 잘 생각이 안 나네요ㅠㅠ. 로운은 어떻게 생각하시나요?

2022-05-15 14:39 UTC, summerlunaa commented
안녕하세요! 피드백 반영하였습니다. 확인 부탁드려요☺️
이전에 시간 관계상 하지 못했던 커스텀 예외 적용, getter 사용을 줄이고 Section 객체에 메시지를 던지도록 수정, test 메서드 리팩토링을 해보았습니다!

service의 역할과 책임에 대해서는 궁금한 점이 있어 DM 드렸습니다~ 감사합니다!

2022-05-16 06:28 UTC, lowoon commented on src/main/java/wooteco/subway/ui/LineController.java
>  public class LineController {
시나리오 테스트라는 것은 실제 사용자가 사용하는 흐름으로 진행하는 것을 테스트하는데요.예외에 대한 것들도 테스트가 필요하지만 예외보다는 실제 사용자가 제대로된 흐름으로 동작을 했을 때 제대로 동작하는 지가 더 중요할 거라고 생각해요.실제 사용자가 사용하는 흐름을 시나리오로 적거나 정리해보셨을까요?

```
Feature: 지하철 노선 관리
    Scenario: 지하철 노선 생성
        When 지하철 노선 생성을 요청하면
        Then 지하철 노선 생성이 성공한다.
    Scenario: 지하철 노선 목록 조회
         Given 지하철 노선 생성을 요청하고
...
```
```
Feature: 지하철 노선 관리

  Scenario: 지하철 노선을 관리한다.
    When 지하철 노선 n개 추가 요청을 한다.
    Then 지하철 노선이 추가 되었다.
    
    When 지하철 노선 목록 조회 요청을 한다.
    Then 지하철 노선 목록을 응답 받는다.
    And 지하철 노선 목록은 n개이다.
...
```
위의 두가지 경우처럼 나눌 수도 있고 더 다양하게 나누는 방법이 있을텐데요.
파랑이 생각하는 시나리오를 한번 생각해보고 그것에 맞게 테스트를 작성해 보면 좋을 것 같아요!

2022-05-16 06:31 UTC, lowoon commented on src/main/java/wooteco/subway/domain/Sections.java
> +public class Sections {
저는 개인적으로 2개가 종속적이고 line을 조회하는 경우에 sections가 항상 필요하다고 하면 같이 조회되도록 line이 가지고 있는게 낫지 않나 생각합니다ㅎㅎ
내부에 필드로 가지고 있다는 것이 의미하는 부분도 있지 않을까요?
우리가 객체에 필드를 정하고 역할을 정하는 것과 마찬가지로 sections도 line의 도메인의 데이터인지, 비지니스 로직을 진행하는데 필요한 데이터인지 생각해보면 좋을것 같아요!

2022-05-16 06:38 UTC, lowoon commented on src/main/java/wooteco/subway/ui/SectionController.java
> +@RequestMapping("/lines/{lindId}/sections")
정답은 없으니 이 방법이 좋을수도 있고, lineContoller에 있는 것이 좋을 수도 있는데요.
정답이 없는 만큼 어떤 방식으로 한 이유가 중요하다고 생각해서 물어보게 되었어요!
비대해진다는 의미가 역할이 커진다는 의미일까요??
코드량이 많아지는 것보다 역할에 부합하는지를 고민해야한다고 생각하는데요!
위에서 sections를 line이 가지게 할것이냐와 비슷하게 section을 line에 종속된 것으로 보느냐에 따라 달라질 것 같아요!
이 부분은 파랑이 고민해보고 정하면 될 것 같아요!

2022-05-16 07:12 UTC, summerlunaa commented on src/main/java/wooteco/subway/service/LineService.java
> +    private final SectionDao sectionDao;
처음엔 service가 다른 service를 가지는 게 왠지 어색했는데 dao를 가지는 것보다는 이미 검증 등의 기능이 완성된 service를 가져와서 메세지를 전달하는 것이 더 낫다는 생각이 들었습니다! 감사합니다☺️👍

2022-05-16 08:20 UTC, lowoon approved these changes
안녕하세요 파랑!😄
이제 그만 체스 미션을 마무리해도 될 것 같아요.
이전 코멘트에 고민해보면 좋을만한 답글만 남겼으니 확인 부탁드려요.
미션은 끝났지만 궁금한점 있으면 DM이나 코멘트로 남겨주세요!

1, 2단계 지하철 노선도 미션 수고하셨습니다!

2022-05-16 08:20 UTC, merged