[Spring 지하철 노선도 - 3단계] 배카라(박성우) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #311
Opened 2022-05-12 01:43 UTC by seong-wooo

# 안녕하세요 희봉 

미션 구현이 어려워서 조금 늦게 보냈습니다.

1, 2 단계와 다르게 controller에서는 domain 을 모르게 하였습니다.

lineResponse 같이 domain 만으로는 안되는 응답을 보내줘야할 때가 있더라구요.

2022-05-12 14:06 UTC, heebong requested changes
안녕하세요, 배카라! 리뷰어 희봉입니다 😄 (일찍 보내요ㅎㅎ)
미션을 잘 구현하셨네요! 도메인이 어려웠을 텐데 요구사항을 잘 구현하셨습니다. 👍 
제가 코멘트를 인수테스트 위주로 남겼는데요, ATDD 관점에서, 브라우저에서 했을 법한 테스트 케이스를 기준으로 남기다보니 양이 많아졌어요 😅 하지만 모두 advanced니 전부 반영하지 않으셔도 됩니다. 공감가는 것 위주로 반영해주시면 됩니다. 🙂 
추가로 생각해보면 좋을 부분도 코멘트로 남겼습니다. 확인 부탁드려요. 언제든 궁금한 내용 있으면 DM 아시죠? 😉

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +        assertThat(response.jsonPath().getLong("id")).isEqualTo(5L);
id값을 특정할 수 있을까요? 🤔 해당 테스트의 목적은 응답에 id값이 있는지만 확인해도 충분할 것 같아요 🙂

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
>          assertThat(response.jsonPath().getString("name")).isEqualTo("강남역");
advanced 🆙 `response`를 `StationResponse`로 바꾸면 확인하기 더 쉽겠네요 🙂

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .containsExactly(tuple(1, "신도림역"), tuple(2, "왕십리역"));
순서 확인 👍 
advanced 🆙 여기도 `LineResponse` 클래스로 변환하면 더 쉽게 데이터를 확인하겠네요 🙂

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
>          ExtractableResponse<Response> response = RestAssured.given().log().all()
(밑에 남길 수 없어 여기 남길게요) advanced 🆙 예외 메시지도 확인하면 더 꼼꼼할 것 같아요

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
>      @DisplayName("전체 노선 목록을 조회한다.")
advanced 🆙 `size`만 확인하지 않고 내용을 모두 확인하면 더 정확하겠네요

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
>          ExtractableResponse<Response> response = RestAssured.given().log().all()
advanced 🆙 수정 후 조회를 해서 제대로 수정이 됐는지 확인하면 좋을 것 같아요 🙂

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("구간을 추가한다.")
advanced 🆙 구간을 추가한 뒤 조회해서 추가가 잘 되었는지 확인하면 좋을 것 같네요 🙂

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("구간을 추가한다.")
advanced 🆙 상행쪽, 하행쪽, 중간 구역을 나눠 구간이 잘 추가되는지 확인하면 더 꼼꼼할 것 같아요

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("구간을 삭제한다.")
advanced 🆙 없는 구간을 삭제하는 테스트도 있으면 촘촘할 것 같아요 🙂

2022-05-12 14:06 UTC, heebong commented on src/main/java/wooteco/subway/controller/SubwayControllerAdvice.java
>          return ResponseEntity.notFound().build();
메시지를 추가하면 더 친절하고 로그 트래킹에도 좋을거에요 😄

2022-05-12 14:06 UTC, heebong commented on src/main/java/wooteco/subway/controller/SubwayControllerAdvice.java
>      }
(밑에 추가가 안돼서 여기에 남길게요) advanced 🆙 `RuntimeException`이 5xx 에러일까요? 🤔

2022-05-12 14:06 UTC, heebong commented on src/main/java/wooteco/subway/service/LineService.java
> +    public LineResponse save(final LineRequest lineRequest) {
`controller`에서 사용하는 `request`와 `response`를 `service`에서 사용하는군요.
지난 미션인 체스를 생각해볼까요? 만약 콘솔, 스파크, 스프링을 서비스해야한다면 `LineService`를 재사용 할 수 있을까요? 🤔 
또한 `controller`에서 사용하는 `request`과 `response`는 프론트 영역입니다. 여기서 `LineService`는 도메인 영역이고요. 변경 원인이 다른 두 가지를 한 곳에 두는게 맞을까요? 이런 부분을 생각해보면 좋겠어요.

여기서 `response`를 리턴하게 된 이유는 `section` 때문으로 보이네요. 어떻게하면 해결할 수 있을까요?

hint 🖊️ `controller`에서 `lineService`와 `sectionService`를 사용할 수도 있겠네요. 😄 문제를 인지했다면, 해결할 수 있는 방법이 무엇일까 고민해봅시다.

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +                .containsExactly(1L, "분당선", "bg-red-600");
포함하고 있는 역까지 확인하면 좋겠네요 🙂

2022-05-12 14:06 UTC, heebong commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    @DisplayName("등록하려는 구간의 상행 기존 구간의 상행과 겹치는 경우 구간 등록 테스트")
다양한 경우의 수 확인 👍

2022-05-13 05:39 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
> +        assertThat(response.jsonPath().getLong("id")).isEqualTo(5L);
id는 제가 작성한 schema.sql 상황에 따라 달라질 것 같아요! id 값만 있는 지 확인만 하는 것으로 바꾸겠습니다 !

2022-05-13 07:55 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/StationAcceptanceTest.java
>          assertThat(response.jsonPath().getString("name")).isEqualTo("강남역");
StationResponse 형태로 변경하였습니다 !

2022-05-13 08:19 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .containsExactly(tuple(1, "신도림역"), tuple(2, "왕십리역"));
LineResponse 형태로 변경하였습니다 !

2022-05-14 07:34 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
>          ExtractableResponse<Response> response = RestAssured.given().log().all()
예외 메시지 확인 로직 추가하였습니다.

2022-05-14 09:33 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
>      @DisplayName("전체 노선 목록을 조회한다.")
내부의 값까지 확인하는 로직 추가하였습니다 !

2022-05-14 09:42 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
>          ExtractableResponse<Response> response = RestAssured.given().log().all()
수정 후 조회하여 테스트 진행했습니다!

2022-05-14 10:11 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("구간을 추가한다.")
구간 추가 후 조회하는 테스트까지 진행해보았습니다 !

2022-05-14 14:05 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("구간을 추가한다.")
다양한 경우를 테스트해보았습니다 !

2022-05-14 14:32 UTC, seong-wooo commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("구간을 삭제한다.")
없는 구간 삭제시 예외가 발생하는 테스트 작성하였습니다 !

2022-05-14 15:14 UTC, seong-wooo commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +                .containsExactly(1L, "분당선", "bg-red-600");
확인했습니다 !

2022-05-15 05:52 UTC, seong-wooo commented on src/main/java/wooteco/subway/controller/SubwayControllerAdvice.java
>          return ResponseEntity.notFound().build();
예외마다 메시지 추가하였습니다 !

2022-05-15 06:12 UTC, seong-wooo commented on src/main/java/wooteco/subway/controller/SubwayControllerAdvice.java
>      }
클라이언트에 의해 runtimeException이 발생하는 경우는 클라이언트 에러로 처리를 하고 
나머지 서버에 의해 발생하는 에러는 exceptionHandler에 의해 500 에러로 자동적으로 처리가 될 것이므로 
runtimeException을 처리하는 메서드를 삭제하였습니다!

2022-05-15 12:52 UTC, heebong approved these changes
안녕하세요, 배카라! 리뷰어 희봉입니다.
피드백을 잘 반영해주셨네요 👍 반영하시느라 고생하셨어요 👍 
이번 미션은 여기서 머지하도록 하겠습니다. 아직 고민되는 내용이 많을텐데 앞으로 미션을 통해 배카라의 기준과 경험이 쌓이면 좋겠네요. 💪 
몇가지 코멘트를 추가했으니 함께 확인 부탁드려요. 이번 미션 고생하셨습니다~ 👏 👏

2022-05-15 12:52 UTC, heebong commented on src/main/java/wooteco/subway/controller/SubwayControllerAdvice.java
>      }
`ControllerAdvice`에서 핸들링하지 않은 `RuntimeException`이 발생할 수 있으니, `RuntimeException`도 핸들링 해주는게 좋답니다 🙂

2022-05-15 12:52 UTC, heebong commented on src/main/java/wooteco/subway/controller/SubwayControllerAdvice.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body("NoSuchElementException");
advanced 🆙 전부 같은 메시지가 내려가네요. 예외를 발생시키며 추가한 메시지를 사용하지 않는 이유가 있을까요? 예외 메시지의 역할에 대해서도 생각해보면 좋겠습니다. 🙂

2022-05-15 12:52 UTC, heebong commented on src/main/java/wooteco/subway/service/SectionService.java
> +                        1L));
매직넘버! 변수로 빼는것도 좋겠네요 🙂

2022-05-15 12:52 UTC, heebong commented on src/main/java/wooteco/subway/service/SectionService.java
> +    private Section createSection(Long lineId, long upStationId, long downStationId, int distance, Long lineOrder) {
advanced 🆙 `createSection`이 `firstSave`에서만 쓰이네요 👀 더 좋은 방법이 없을지 고민해봅시다 😄

2022-05-15 12:52 UTC, heebong commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .orElseThrow(() -> new IllegalArgumentException("ㅋㅋ"));
예외 메시지에 상황을 확인할 수 있는 내용이 담기면 좋습니다 🙂

2022-05-15 12:52 UTC, merged

2022-05-15 13:13 UTC, seong-wooo commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .orElseThrow(() -> new IllegalArgumentException("ㅋㅋ"));
아 이거는 깜빡하고 수정하지 못했네요 ,, ,ㅎ

2022-05-15 14:00 UTC, seong-wooo commented on src/main/java/wooteco/subway/controller/SubwayControllerAdvice.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body("NoSuchElementException");
예외 메시지를 사용하도록 변경하였습니다 !