[Spring 지하철 노선도 - 3단계] 라라(박세은) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #316
Opened 2022-05-12 06:04 UTC by sure-why-not

안녕하세요!! `던` 👋🏻👋🏻👋🏻 !!!!! 
이번 3단계 미션을 다시 부탁드리게 된 `라라`입니다. 👩🏻‍💻👩🏻‍💻👩🏻‍💻🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️
3단계도 페어와 함께 진행하여 커밋 기록에 반영되어 있습니다!

이번 3단계 PR 코드에서 부족하다고 느낀점입니다. 
1. 현재 도메인에서 Line 과 Section 의 관계가 드러나지 않습니다. 도메인만으로 해당 어플리케이션의 도메인을 이해할 수 있어야 한다고 생각하기 때문에 이 부분이 변경되어야 할 것 같습니다.
2. 일반 도메인 객체와 테이블에 매핑되는 Entity 가 적절히 분리되어있지 않습니다.
3. SQL 쿼리가 최적화되지 않아 한 기능에서 여러번 요청되고 있습니다. join 같은 문법을 사용해 한 번에 데이터를 가져와서 해결할 수 있을 것 같습니다.
4. SectionService 이 너무 많은 책임을 가지고 있는 것 같습니다. 😭

최대한 더 반영해보겠습니다!! 많은 피드백 부탁드려요!! 🙏🏻🙏🏻🙏🏻
잘 부탁드립니다. 🙇🏻‍♀️  ♥️

2022-05-13 16:22 UTC, gch01410 requested changes
안녕하세요 라라!
3단계는 많이 복잡했을텐데 잘 구현해주셨습니다 👍
테스트 코드 정말 꼼꼼하게 작성하셨네요 💯 
코멘트 남겼으니 확인부탁드릴게요~

2022-05-13 16:22 UTC, ghost commented on src/main/java/wooteco/subway/dao/StationDao.java
>  import wooteco.subway.domain.Station;
import가 중복으로 되어있네요 👀

2022-05-13 16:22 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +            .orElseThrow(() -> new DataNotExistException("존재하지 않는 역입니다."));
데이터가 존재하지않을때의 예외는 보통 ~~NotFoundException (StationNotFoundException)로 네이밍합니다!

2022-05-13 16:22 UTC, ghost commented on src/main/java/wooteco/subway/ui/LineController.java
>      }
컨트롤러에서 여러 서비스의 메서드를 호출하고 받은 결과값을 조합하고 있네요!
이 로직은 비즈니스 로직이 아닐까해요! 서비스 레이어에서 처리하는건 어떠신가요?

2022-05-13 16:22 UTC, ghost commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final int distance;
> 일반 도메인 객체와 테이블에 매핑되는 Entity 가 적절히 분리되어있지 않습니다.

일반 도메인 객체와 엔티티를 분리하려고 하는 이유를 알 수 있을까요?
분리해야하만 하는 이유가 잘 안보이네요

2022-05-13 16:22 UTC, ghost commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
매번 Station객체를 새로 만드는 이유를 알 수 있을까요?? 
stationService에서 반환한 Station객체를 그대로 사용해도 될 것 같아서요!

2022-05-13 16:22 UTC, ghost commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
메서드 분리하면 가독성이 더 좋아질 것 같아요!

2022-05-13 16:22 UTC, gch01410 commented on src/main/java/wooteco/subway/service/SectionService.java
> +        Sections sections = new Sections(convertedSections);
Sections 객체 생성자에서 Section 리스트를 정렬하는건 어떠실까요~?
SectionService에서의 중복로직을 제거할 수 있을 것 같아요

2022-05-13 16:22 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
이 부분은 코드 이해가 쉽지않네요
조금 더 리팩토링 해볼 수 있을까요?

2022-05-13 16:22 UTC, gch01410 commented on src/main/java/wooteco/subway/service/LineService.java
>      }
sectionService.createSection() 메서드에서 예외가 발생하면 `Line newLine = lineDao.save(line);`으로 저장한 Line은 어떻게 처리되어야할지 고민해보세요!
트랜젝션에 대해서도 같이 알아보면 좋을 것 같아요!

2022-05-15 09:50 UTC, sure-why-not commented on src/main/java/wooteco/subway/dao/StationDao.java
>  import wooteco.subway.domain.Station;
앗 StationEntity 랑 Station을 합치면서 이런 중복 코드가 발생했네요!! 삭제했습니다!!! 🤭

2022-05-15 09:53 UTC, sure-why-not commented on src/main/java/wooteco/subway/service/StationService.java
> +            .orElseThrow(() -> new DataNotExistException("존재하지 않는 역입니다."));
앗 그렇군요. `DataNotFoundException` 로 이름을 변경했습니다! 좋은 정보 감사합니닷. 👍🏻👍🏻👍🏻
현재 데이터가 존재하지 않는 경우가 4~5개밖에 없어서 `DataNotFoundException` 로 묶어서 커스텀 예외처리를 하였는데 `StationNotFoundException` `LineNotFoundException` 이런식으로 세분화하여 예외처리하는 것이 좋은 방법일까요?🤔

2022-05-15 09:56 UTC, sure-why-not commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
엇 그렇네요, StationEntity 와 Station 이 분리되어있었는데, 하나로 통일시키는 과정에서 이렇게 수정되었던 것 같네요. ㅎㅎ
`stationService.findById(stationId)` 값을 바로 반환하도록 변경했습니다! 감사합니다. 😆👍🏻

2022-05-15 17:06 UTC, sure-why-not commented on src/main/java/wooteco/subway/ui/LineController.java
>      }
앗 그렇네요! 🤭
처음에 service 에서 service를 호출하는 것이 어색하다고 느껴서 이렇게 했었던 것 같네요. 😭
같은 계층에서는 순환참조가 생기지 않는 선에서 소유하고 있는  것이 괜찮다고 판단했고, 얻어온 데이터를 조합하는 것은 비즈니스 로직이기 때문에 LineService 에서 처리하도록 수정했습니다!! 🕺

2022-05-15 17:18 UTC, sure-why-not commented on src/main/java/wooteco/subway/service/LineService.java
>      }
앗 미처 생각하지 못한 부분까지 알려주셔서 감사합니다!! 👍🏻👍🏻👍🏻👍🏻
일련의 과정을 실패시 모두 원복시키도록 @Transactional 을 사용하여 해결했습니다!! 감사합니다 ☺️

2022-05-15 17:21 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
이 메소드는 얼리 리턴이 존재해서 분리하기가 쉽지 않았습니다. 😭
최대한 추상화시켜 리팩토링 해보았습니다!! 🥺
```
    public Section add(Section newSection) {
        validateAddable(newSection);

        if (getUpDestination().equals(newSection.getDownStation())) {
            values.add(0, newSection);
            return newSection;
        }

        if (getDownDestination().equals(newSection.getUpStation())) {
            values.add(newSection);
            return newSection;
        }

        for (Section section : values) {
            if (section.hasSameUpStation(newSection)) {
                return insertAfterUpStation(newSection, section);
            }

            if (section.hasSameDownStation(newSection)) {
                return insertBeforeDownStation(newSection, section);
            }
        }
        throw new IllegalStateException("구간을 추가할 수 있는 상태가 아닙니다.");
    }
```

2022-05-15 17:24 UTC, sure-why-not commented on src/main/java/wooteco/subway/service/SectionService.java
> +        Sections sections = new Sections(convertedSections);
음 그렇게 되면 중복 로직도 제거할 수 있고,
일단 데이터를 정렬하는 로직이 Sections 의 책임이 더 적당하다는 생각이 드네요!!
좋은 아이디어를 제시해주셔서 감사합니다.👍🏻👍🏻👍🏻

2022-05-15 17:41 UTC, sure-why-not commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
메서드가 굉장히 길었네요. 😭🙄😭🙄😭🙄
적당한 책임을 나누어 메서드를 분리했습니다!!! 감사합니다 👍🏻

2022-05-15 17:43 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final int distance;
음 기존 방식대로 생성자를 여러개 두어 도메인과 엔티티 객체를 혼용해서 사용할 수도 있다고 생각합니다!

테이블에 매핑되는 엔티티는 테이블 특성에 맞게 id 값에 종속될 수 밖에 없습니다. 하지만 순수 도메인 객체는 db 와 연관된 id 가 아닌 객체 참조를 통해 관계를 표현하고 해당 도메인이 어떻게 작동하는 지 파악할 수 있어야 한다고 생각했습니다!! 그래서 일반 도메인 객체와 엔티티를 분리해야 한다고 생각했는데, 혹시 잘못된 생각일까요?!?! 🥺🤔🥺🤔🥺🤔

2022-05-16 02:39 UTC, gch01410 commented on src/main/java/wooteco/subway/service/StationService.java
> +            .orElseThrow(() -> new DataNotExistException("존재하지 않는 역입니다."));
지금은 예외처리가 같기때문에 도메인별로 나누지않아도 되긴하지만, 예외가 발생했을때 어떤 예외가 발생했는지만 보고서도 더 명확하게 예외상황을 파악할 수 있어요.
메시지로 예외가 발생한 상황을 구분하면 메시지를 잘 남겨야하는 부담도 있을 수 있겠어요.

2022-05-16 02:52 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final int distance;
> 순수 도메인 객체는 db 와 연관된 id 가 아닌 객체 참조를 통해 관계를 표현하고 해당 도메인이 어떻게 작동하는 지 파악할 수 있어야 한다고 생각했습니다!!

맞아요! 순수 도메인 객체를 사용할때 얻을 수 있는 장점을 잘 설명해주셨네요! 그러면 순수 도메인 객체를 사용할때의 단점도 생각해볼 수 있을까요? 그리고 지금 프로젝트에 실질적으로 각 장단점이 잘 적용되는지? 를 한번 고민해보면 좋을 것 같아요.

저는 이렇게 생각이 드네요. 엔티티를 사용해서 객체 참조를 통해 관계를 표현이 불가능한것이 아니고, 지금 구조에서 순수 도메인 객체를 사용함으로써 해당 도메인이 어떻게 작동하는지 더 명확해졌는가?를 생각해보면 살짝 의문이 있거든요.
그리고 순수 도메인 객체를 분리한다면 모든 엔티티와 도메인을 분리해야하는것이 아닌지? Section만 분리하고 다른 엔티티는 분리하지않음으로써 오히려 구조가 더 복잡해진건 아닌지? 하는 생각이 드는데 정답이 있는건 아니라서 라라가 고민해보고 어떻게 적용할지 고민해보면 좋겠네요!

2022-05-16 03:38 UTC, gch01410 requested changes
안녕하세요 라라!
피드백 코멘트에 대해 답글 남겨두었어요.
확인 부탁드립니다!
거의 다 왔습니다! 💪

2022-05-16 03:38 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
insertStation 메서드를 만들고 메서드 안에서 분기처리하면 add메서드에서 분기처리하지 않을 수 있겠어요
insertAfterUpStation메서드와 insertBeforeDownStation메서드는 구조가 비슷해보여서요!

2022-05-16 03:38 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +            throw new IllegalArgumentException("추가하려는 구간의 거리가 기존 구간의 거리보다 작아야합니다.");
저는 비즈니스 로직의 예외는 모두 커스텀 예외를 사용하고 있어요. 정확한 문제가 무엇인지 이해하는 데 도움이 됩니다. 예외 메시지는 +알파로 더 상세하게 예외 상황을 드러내는 보조역할이라고 생각해요

아래 글 들을 참고해보면 좋을 것 같아요!
https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/
https://vitalflux.com/4-reasons-need-create-customs-exceptions/

2022-05-16 03:38 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +            isInvalidCountInMiddle(foundSections) || isSameWithDestinations(foundSections);
```suggestion
        return hasAnySectionWithSameStations(foundSections, section) ||
            isInvalidCountInMiddle(foundSections) || 
            isSameWithDestinations(foundSections);
```
한 줄씩 띄어주면 더 읽기 편할 것 같아요 😄

2022-05-16 03:38 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
2가 어떤 값을 의미하는지 상수로 드러내면 더 이해에 도움될것 같아요
`foundSections.containsAll(List.of(values.get(0), values.get(values.size() - 1)))` 도 메서드로 분리해서 의미를 더 드러낼 수 있을 것 같아요

2022-05-16 05:29 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Sections.java
> +            isInvalidCountInMiddle(foundSections) || isSameWithDestinations(foundSections);
한 줄에 코드가 너무 길지 않으면 개행을 넣지 않으려 했었는데 던이 남겨주신 피드백을 보고 판정 메서드마다 줄을 나눠서 가독성을 비교해보았습니다. 판정 메서드별로 줄을 나눈 것이 더 빠르게 파악할 수 있다는게 느껴져서 반영했습니다!! 좋은 피드백 감사합니다. 👍🏻👍🏻👍🏻👍🏻

2022-05-16 07:08 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
앗 !!! 던의 피드백을 받고 해당 로직을 살펴보았다가 불필요한 검증이 포함되어 있다는 것을 알게 됐습니다!!
```
    private boolean isSameWithDestinations(Section section) {
        return section.contains(getUpDestination()) && section.contains(getDownDestination());
    }
```
이처럼 추가하려는 구간이 상행/하행 종점을 모두 포함하고 있는지 검증하는 로직을 깔끔하게 수정했습니다!! 감사합니다~👍🏻👍🏻👍🏻

2022-05-16 07:18 UTC, sure-why-not commented on src/main/java/wooteco/subway/service/StationService.java
> +            .orElseThrow(() -> new DataNotExistException("존재하지 않는 역입니다."));
아 그런 장점이 있겠군요!!!
메시지를 잘 남겨야한다는 부담이 생길거라는 생각은 못 해본 것 같아요.
항상 IllegalArgumentException  예외 메시지를 작성할 때 마다 많은 고민을 했던 이유가 이거였나보네요,,😱
도메인이 더 복잡해진다면 세부 상황들로 예외를 나누는 것이 더 좋은 방법이라는 생각이 드네요!!! 
좋은 피드백을 해주셔서 너무 감사합니다!!! 👍🏻👍🏻👍🏻👍🏻

2022-05-16 08:42 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final int distance;
던의 피드백에 대해 생각해보고 저의 생각을 적어보았습니다!

> 지금 구조에서 순수 도메인 객체를 사용함으로써 해당 도메인이 어떻게 작동하는지 더 명확해졌는가?
> 순수 도메인 객체를 분리한다면 모든 엔티티와 도메인을 분리해야하는것이 아닌지?

이 부분에 대해 저의 의견이 설득력 없었던 이유는 현재 프로젝트에서 도메인과 엔티티가 완전히 분리되지 않았기 때문이라고 생각합니다!!! 😂😂😂  저도 모든 엔티티와 도메인을 분리해야한다고 생각합니다!
현재 Section만 분리되어 있고 Section 만 도메인<->엔티티 변환 과정을 가지고 있어 일관성이 없다고 생각합니다. 🧐 

Line 도메인 객체가 Sections 를 가지고 있고, Section 이 Station 을 가지고 있으며, 구간을 추가할 때 `line.addSection(section)` 과 같은 식으로 추가하며 완벽하게 모든 도메인 객체와 엔티티가 분리되어야 한다고 생각합니다. 이런식으로 도메인이 분리된다면 해당 도메인이 어떻게 작동하는지 더 명확해질 것이라고 생각했습니다 !!! 🤔🥺🤔🥺🤔


> 순수 도메인 객체를 사용할때의 단점도 생각해볼 수 있을까요? 그리고 지금 프로젝트에 실질적으로 각 장단점이 잘 적용되는지?

데이터를 지속적으로 저장하려면 자바 프로그램만으로 해결할 수 없기 때문에 db 가 필연적으로 필요합니다. 
순수 도메인 객체를 사용할 때의 단점 중 하나는 db 데이터와의 변환 과정이 추가되는 부분이라고 생각합니다. (도메인이 복잡해지면 이 과정이 더 복잡해질 것 같네요!!) 그리고 도메인이 엔티티로 db 에 저장되기 때문에 db 의 식별자인 id 값을 도메인이 갖게 될 수 밖에 없더라구요. 😹 그래서 id 값을 갖지 않는 완전하지 못한 도메인 객체가 만들어질 때가 생기는 단점도 있다고 생각합니다. 

도메인에서 id 값을 분리시키는 단점은 해결하지 못했지만,
(모두 분리하여 적용한다면) 순수 도메인에서 객체 참조를 통해 관계를 표현하고 해당 도메인이 어떻게 작동하는 지 파악할 수 있는 장점을 살릴 수 있을 것이라고 파악했습니다. 또 지금 프로젝트에선 필요없지만, 웹 프로젝트가 아니라 콘솔프로그램으로 변경되도 쉽게 변경될 수 있을 것 같아요!

그래서 결론적으로 저는 분리되는 것이 더 좋은 방법이라는 판단을 내렸습니다!!! 🕺 
이 부분을 생각하고 적용해보다 변경사항이 굉장히 많아서 😭 시간 내에 제출하지 못하고 답변으로 생각을 정리해서 남겼습니다!!
혹시 잘못된 생각이 있다면 따끔하게 피드백 부탁드립니다!! ㅎㅎㅎㅎ 
좋은 고민을 깊게 해볼 수 있게 피드백을 남겨주셔서 정말 감사합니다. 😄👍🏻👍🏻👍🏻👍🏻

2022-05-16 09:10 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
```suggestion
        for (Section section : values) {
            Optional<Section> insertedSection = insertStation(newSection, section);
            if (insertedSection.isPresent()) {
                return insertedSection.get();
            }
        }

        throw new IllegalStateException("구간을 추가할 수 있는 상태가 아닙니다.");
    }

    private Optional<Section> insertStation(Section newSection, Section section) {
        if (section.hasSameUpStation(newSection)) {
            return Optional.of(insertAfterUpStation(newSection, section));
        }
        if (section.hasSameDownStation(newSection)) {
            return Optional.of(insertBeforeDownStation(newSection, section));
        }
        return Optional.empty();
    }
```

얼리 리턴때문에 메서드를 분리함면 null 을 반환해줘야 하는 상황이 생겨서 Optional 을 사용해서 분리해보았습니다 !!
로직이 깔끔해지긴 한 것 같은데, `insertStation` 메서드만 보았을 때 추가된 Station 을 받는게 명확하게 파악되지 않을 것 같다는 걱정도 되네요. 😹 일단 최선의 방법으로 선택해보았습니다!! 제안해주셔서 감사합니다. 😆👍🏻👍🏻👍🏻👍🏻

2022-05-16 09:16 UTC, sure-why-not commented
`던` 안녕하세요!!! 
이번 리뷰를 통해 제가 생각지 못한 부분까지 꼼꼼하게 리뷰해주셔서 정말 감동이었습니다. 🥺🥺👍🏻👍🏻👍🏻
새로운 것을 깊게 생각해보는 기회가 되었고, 많은 것을 배웠습니다!!!
마지막 피드백까지 반영하고 생각을 댓글로 남겨두었습니다!!
감사합니다 던!!! 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️♥️

2022-05-16 09:37 UTC, sure-why-not commented on src/main/java/wooteco/subway/domain/Sections.java
> +            throw new IllegalArgumentException("추가하려는 구간의 거리가 기존 구간의 거리보다 작아야합니다.");
좋은 글 공유해주셔서 감사합니다!!👍🏻👍🏻
도메인 내에서는 잘못된 값이 들어왔을 때 `IllegalArgumentException` 만을 던져주도록 하고, 
 view 까지 도달해야하는 상황에 대한 예외만을 고려하고 커스텀 예외를 생각했었는데, 던의 생각에 공감이 가네요! 👍🏻
제가 예외 메세지를 작성할 때마다 많은 고민을 했던 이유를 알 것 같기도 하네요. 앞으로는 커스텀 예외를 적극적으로 사용하고, 예외 메세지를 상세하게 보여주기 위하도록 사용해봐야겠어요! 좋은 피드백을 주셔서 정말 감사합니다 !!! 🕺 👍🏻👍🏻👍🏻

2022-05-16 14:55 UTC, ghost commented on src/main/java/wooteco/subway/domain/Sections.java
> +            throw new IllegalArgumentException("추가하려는 구간의 거리가 기존 구간의 거리보다 작아야합니다.");
지금은 예외처리로 예외 메시지만 응답으로 내려주지만, 더 다양한 처리를 해야할 수도 있어요.
예외가 발생했을때 새로운 데이터를 insert해야할 수도 있고, 기존 데이터를 update해야할 수도 있고, 다른 시스템에 실패상황을 알림으로 전달해줘야할 수도 있고,, 등등..
이때 자바 기본 예외가 아니라 커스텀 예외를 사용한다면 처리하기 더 쉬워질 수 있어요

2022-05-16 14:55 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
아.. `throw new IllegalStateException("구간을 추가할 수 있는 상태가 아닙니다.");` 이 코드가 for문 밖에 있었군요..
for문 안에 있다고 생각해서 insertStation 메서드 안에서 예외를 발생시키도록하면 add메서드를 정리할 수 있을줄 알았어요..
라라 생각대로 insertStation 메서드가 살짝 모호해졌네요.  변경전 코드가 더 나을 수 있겠어요. 😹

그래도 최대한 반영해주셔서 감사합니다!

2022-05-16 15:20 UTC, ghost commented on src/main/java/wooteco/subway/domain/Sections.java
> +        throw new IllegalStateException("구간을 추가할 수 있는 상태가 아닙니다.");
다른 코멘트에 남겼듯이 비즈니스 예외는 커스텀 예외로 처리하는게 좋아요!
세분화해서 커스텀 예외를 만드는게 어렵다면 우선 간단하게라도 `StationException` 처럼 만드시는건 어떠신가요?

2022-05-16 15:20 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +        if (stations.size() != 2) {
2를 상수로 분리해서 의미를 드러내면 코드이해가 더 쉬워질 것 같아요!

2022-05-16 15:20 UTC, gch01410 commented on src/main/java/wooteco/subway/service/LineService.java
> +            stationService.findBothStationsByIds(lineDto.getUpStationId(), lineDto.getDownStationId()));
```suggestion
        List<Station> stations = stationService.findBothStationsByIds(lineDto.getUpStationId(), lineDto.getDownStationId())
        return new Line(newLine, stations);
```
한번 끊고 가면 보기에 조금 더 편할 것 같아요! 😄

2022-05-16 15:20 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final int distance;
> 이 부분을 생각하고 적용해보다 변경사항이 굉장히 많아서 😭 시간 내에 제출하지 못하고 답변으로 생각을 정리해서 남겼습니다!!
혹시 잘못된 생각이 있다면 따끔하게 피드백 부탁드립니다!! ㅎㅎㅎㅎ

당장 코드로 구현해서 적용하는것보다 지금처럼 고민하는 것이 더 값어치 있다고 생각해요! 잘못된 생각은 딱히 보이지 않네요 ㅎ
앞으로 미션하면서 이렇게도 적용해보고 저렇게도 적용해보면서 직접 느껴보시는걸 추천해요! 그러면서 느끼는것들을 하나하나 라라의 방식대로 정리해나가면서 라라만의 코드규칙을 쌓아가시면 될 것 같아요!

2022-05-16 15:21 UTC, gch01410 approved these changes
안녕하세요 라라!
미션하면서 많이 고민한것이 느껴져서 좋았네요 ㅎ
간단한 코멘트들 남겼으니 확인부탁드릴게요!
이번 미션 구현하시느라 수고많으셨습니다! 👍

2022-05-16 15:21 UTC, merged