[Spring 지하철 노선도 - 3단계] 소주캉(강승주) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #317
Opened 2022-05-12 06:04 UTC by sojukang

안녕하세요 `코니`🌟👋👋!!!
지하철 노선도 3단계 리뷰 부탁드리는 `소주캉`입니다🤸‍♂️. 
3단계도 페어랑 같이 진행하여 커밋 기록에 반영되어 있습니다😮!
현재로서 부족하다고 느낀 점은 다음과 같습니다. 

1. 일반 도메인 객체와 테이블에 매핑되는 Entity 가 적절히 분리돼있지 않음
2. 너무 많은 책임을 가지는 SectionService  
3. SQL 쿼리가 최적화되지 않아 여러 번 요청됨

이후에도 빠르게 수정 반영해보겠습니다🧑‍💻
최대한 꼼꼼하게 테스트를 작성하려 노력하다보니 프로덕션 코드가 부족한 점이 많이 보이네요...😭
바쁜 와중에도 리뷰해주셔서 감사드립니다.  잘 부탁드립니다👻!!

2022-05-13 14:56 UTC, choihz requested changes
안녕하세요, 소주캉!

지하철 노선도 미션 3단계도 잘 구현해 주셨네요 👍 간단한 피드백 먼저 남겨 보았고, 조금 더 디테일한 피드백도 추후 드리도록 할게요. 궁금한 점 또는 의견이 있으실 땐 코멘트 또는 DM 주세요 😉

2022-05-13 14:56 UTC, choihz commented on README.md
> +- [ ] 두 종점간의 연결 정보를 이용하여 노선 추가 시 구간(Section) 정보도 함께 등록
체크가 빠진 것 같네요 😅

2022-05-13 14:56 UTC, choihz commented on src/main/java/wooteco/subway/ui/LineController.java
>      }
컨트롤러에서 너무 많은 일들이 이뤄지고 있는 것 같은데 이에 대해 어떻게 생각하시나요? 👀

2022-05-13 14:56 UTC, choihz commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
존재하는 구간 사이에 구간을 추가하려 할 때, 기존 구간 이상의 거리로 새 구간을 추가하려 하면 어떤 예외 메시지가 노출되고 있는지 확인해 볼까요?

2022-05-13 14:56 UTC, choihz commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
또한, 특정 구간에 속한 역을 삭제하면 어떻게 되나요?

2022-05-13 14:56 UTC, choihz commented on src/main/java/wooteco/subway/ui/LineController.java
>          lineService.deleteById(id);
<img width="407" alt="스크린샷 2022-05-13 오후 11 41 14" src="https://user-images.githubusercontent.com/18049492/168308003-9681c079-21dd-47aa-b510-2d2e7e219157.png">

1번 노선을 삭제한 후 구간 테이블을 조회해 보았는데 데이터가 이렇게 남아 있군요 🤔

2022-05-13 14:56 UTC, choihz commented on src/main/java/wooteco/subway/service/LineService.java
>      }
만약 이 메서드를 실행하는 도중에, `Line`이 DB에 무사히 저장되었는데 `Section`은 저장 과정에서 실패했다면 저장된 `Line`은 어떻게 될까요?

2022-05-13 14:56 UTC, choihz commented on src/test/java/wooteco/subway/domain/SectionsTest.java
> +public class SectionsTest {
테스트 코드를.. 정말 열심히 작성하셨군요 😮👍

2022-05-14 07:20 UTC, sojukang commented on README.md
> +- [ ] 두 종점간의 연결 정보를 이용하여 노선 추가 시 구간(Section) 정보도 함께 등록
앗!!! 진행 상황을 반영하였습니다. 감사합니다🙏

2022-05-14 07:21 UTC, sojukang commented on src/main/java/wooteco/subway/ui/LineController.java
>      }
이전 LineController의 createLine은 다음과 같은 책임을 수행하고 있었습니다. 
1. 두 Station 조회
2. LineService에 노선 생성 요청 
3. LineResponse 생성 및 반환

이중 비즈니스 로직으로 판단되는 1, 2번을 Service Layer에 이관하고, 3번을 LineResponse 객체의 책임으로 할당하여 
응답과 요청이라는 Controller의 역할에 집중하여 컨트롤러의 책임을 가볍게 만들었습니다.

2022-05-14 07:35 UTC, sojukang commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
기존 구간 이상의 거리로 새 구간을 추가하려 할 경우 400 응답을 던지고, 
 "message": "거리는 0보다 작을 수 없습니다." 예외 메시지가 노출되고 있었군요!!!
해당 메시지는 Section 객체 생성시 사전 검증메서드에서 던져진 예외가 넘어온 것인데, `Sections` 에서 상황에 적절한 예외 메시지를 던져주는 게 낫다고 판단하여 `Sections`에서 다음과 같이 수정하였습니다. 

 ```java
private int getNewDistance(Section section, Section newSection) {
        int newDistance = section.getDistance() - newSection.getDistance();
        if (newDistance <= 0) {
            throw new IllegalArgumentException("추가하려는 구간의 거리가 기존 구간의 거리보다 작아야합니다.");
        }
        return newDistance;
    }
```

2022-05-14 07:38 UTC, sojukang commented on src/main/java/wooteco/subway/service/LineService.java
>      }
`Transaction 원자성`을 지키지 못하고 있군요!! 변경의 단위를 한 번에 묶어서 처리하기 위해 `@Transactional` 을 도입하였습니다.

2022-05-14 08:39 UTC, sojukang commented on src/main/java/wooteco/subway/ui/LineController.java
>          lineService.deleteById(id);
`LINE` 테이블과 `SECTION` 테이블 사이 `line_id`로 관계를 맺어주지 않아서 노선을 삭제해도 구간이 삭제되지 않고 있었군요😭. `SECTION` 테이블에 `line_id`를 FK로 설정하고 `on delete cascade` 옵션으로 `line_id`가 삭제되면 해당하는 구간도 삭제되도록 변경해보았습니다🤸‍♂️.

2022-05-14 09:42 UTC, sojukang commented on src/main/java/wooteco/subway/ui/LineController.java
> +    }
특정 구간에 속한 역도 삭제할 수 있군요 😭. `STATION`와 `SECTION` 테이블 사이 `up_station_id`와 `down_station_id`로 FK를 설정하여 특정 구간에 속한 역을 삭제하려 할 경우 예외를 던지도록 수정하였습니다!!

2022-05-14 10:49 UTC, sojukang commented
안녕하세요 `코니`👋👋 다시 리뷰 요청 드리는 `소주캉`입니다. 
일정이 변경되어서 바쁘신 와중에도 빠른 리뷰 주셔서 정말 감사드립니다👍👍.
기본적으로 남겨주신 피드백을 바탕으로 리팩토링 진행하였으며, 고려한 내용은 다음과 같습니다. 

1. Controller -> Service 로직 이동
2. Service -> Domain(Sections) 로직 이동 
3. 연관 데이터 FK <-> PK로 관계 형성
4. 테스트 케이스 추가 

### 궁금한 점
현재는 FK를 설정하여 연관 테이블간 관계를 주었는데, JPA등 ORM 기술을 이용한다면 연관된 모든 데이터를 조회하기 때문에 FK를 자제한다는 의견을 들었습니다. 그리하여 연관 데이터의 삭제는 Service 단에서 각각 처리해주는 게 좋다는 생각이 들었습니다. 현재는 단순히 JDBC를 사용하고 있기 때문에 FK를 사용하였는데, 코니의 생각은 어떠신가요? FK를 자제하고 직접 연관 삭제를 처리해주는 게 좋을까요?   

주말에도 좋은 리뷰 남겨주셔서 감사드립니다👻!!! 이번 리뷰도 잘 부탁드립니다🙏.

2022-05-15 08:14 UTC, choihz requested changes
안녕하세요, 소주캉!

수정해 주신 부분을 확인하고 피드백을 더 남겨 보았습니다. 궁금한 점 또는 의견이 있으실 땐, 아시죠? 😎

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Line.java
> +    private static final int MIN_LENGTH = 1;
**무엇의** 최소 길이일까요?

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Section.java
> +    }
메시지만 봐서는 거리가 0이어도 되는 것 같은데, 맞나요?

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
이건 테스트 코드에서만 사용되는 생성자인가요?

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
방식이 굉장히 독특하네요 ㅎㅎ
그런데, "저장된 구간들 값이 올바르지 않습니다."라는 메시지만으로 상황을 잘 파악할 수 있을까요?

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +                section.contains(newSection.getDownStation()) || section.contains(newSection.getUpStation()))
이것도 `Section`이 메서드로 제공해 줄 수 있을 것 같아 보여요.

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
이 메서드가 지금은 새로운 구간을 추가하려 할 때 확인하는 용도로만 사용되고 있지만, 이 메서드 단독으로만 놓고 보면 파라미터 이름에 `new`가 들어갈 필요는 없어 보이는데 소주캉의 생각은 어떠신가요?
또한 구간"들"과 하나의 구간을 놓고 비교하는 것이니만큼 메서드 이름에는 `anyMatch`의 맥락을 드러낼 필요가 있어 보여요.

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
그런데 다시 보니까, 모든 구간을 대상으로 `section.hasSameStations(newSection)` 확인을 할 필요가 있을까요? `validateAddable()`에서 `findSectionsOverlapped(section)`으로 찾은 구간들을 대상으로만 확인해도 되지 않을까요?

제가 잘못 이해한 부분이 있다면 코멘트 부탁드려요~

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return count < 1 || count > 2;
이거 결국엔 1 또는 2여야 한다는 거죠? 뭔가 헷갈리네요 ㅎㅎ

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +            .orElseThrow(() -> new IllegalArgumentException("삭제할 역이 존재하지 않습니다."));
메시지를 조금 더 명확히 할 수 있을 것 같아요. 역 자체가 존재하지 않는 것이 아니라 특정 노선의 구간(들)에 속하지 않은 상황이니까요.

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +        Section nextSection = findNextSection(section);
`values.indexOf(section)`을 불필요하게 두 번 호출하게 되네요 👀

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/domain/SectionEntity.java
> +public class SectionEntity {
`SectionEntity`라는 엔티티가 도입되었는데, `domain` 패키지에 함께 위치해 있고 또 서비스 레이어에도 노출되고 있네요. 당장 뭔가를 수정해야 한다는 건 아니지만, 이런 구조에서 문제가 될 만한 부분은 없을지 고민해 보면 좋을 것 같아요.

2022-05-15 08:14 UTC, choihz commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
이 로직은 `Sections`의 `findSectionToDelete()`와 유사해 보이는데 제가 잘못 이해한 부분이 있을까요? 또한, "엔티티"를 대상으로 이러한 로직을 수행하는 것이 적절한가요? 엔티티와 도메인을 어떠한 이유로 나누신 걸까요?

2022-05-15 08:14 UTC, choihz commented on src/main/resources/schema.sql
> +    foreign key (line_id) references LINE (id) on delete cascade
> 현재는 FK를 설정하여 연관 테이블간 관계를 주었는데, JPA등 ORM 기술을 이용한다면 연관된 모든 데이터를 조회하기 때문에 FK를 자제한다는 의견을 들었습니다. 그리하여 연관 데이터의 삭제는 Service 단에서 각각 처리해주는 게 좋다는 생각이 들었습니다. 현재는 단순히 JDBC를 사용하고 있기 때문에 FK를 사용하였는데, 코니의 생각은 어떠신가요? FK를 자제하고 직접 연관 삭제를 처리해주는 게 좋을까요?

뭐가 좋으냐 나쁘냐는 언제나 그렇듯 상황에 따라 다르죠! 저는 이번 미션에서 FK를 사용하는 방식도 좋다고 생각해요. 하지만 소주캉이 다른 방식도 사용해 보고 싶다면 그렇게 해 보고, 이 과정을 통해 각 방식의 장단점을 직접 이해한다면 그것 또한 값지겠죠 😊

2022-05-15 08:26 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Line.java
> +    private static final int MIN_LENGTH = 1;
이름과 색상에 동일하게 쓰기 위해 `MIN_LENGTH`라는 네이밍을 해보았습니다. 그런데 남겨주신 피드백을 보고 생각해보니 꼭 이름과 색상이 동일한 최소 길이를 가지지는 않겠다는 생각이 들었습니다. 그래서 메서드와 상수를 따로 나누도록 수정하였습니다. 감사합니다!!!

2022-05-15 08:27 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Section.java
> +    }
앗!! 그렇군요😭 
```suggestion
    private void validateDistance(int distance) {
        if (distance <= MIN_DISTANCE) {
            throw new IllegalArgumentException("거리는 0보다 커야합니다.");
        }
    }
```

2022-05-15 08:34 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
앗!!! 리팩토링 진행하며 프로덕션에서는 필요없게 된 생성자라 테스트에만 남게 되었군요! 해당 생성자를 삭제하고 테스트에서도 프로덕션에서 사용하는 생성자를 사용하도록 수정하였습니다. 감사합니다.

2022-05-15 08:47 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
상행 종점을 찾는 메서드인데 오류 메시지는 관련 내용이 없어서 파악하기 힘들군요🤔. 메서드가 하는 일을 담도록 변경해보았습니다. 감사합니다!!

```suggestion
    private Long findUpDestinationId(List<Section> sections) {
        List<Long> upStations = collectValuesBy(Section::getUpStationId, sections);
        List<Long> downStations = collectValuesBy(Section::getDownStationId, sections);

        upStations.removeAll(downStations);
        if (upStations.size() != 1) {
            throw new IllegalStateException("상행 종점을 찾을 수 없습니다. 구간 목록이 올바르게 저장되지 않습니다.");
        }
        return upStations.get(0);
    }
```

2022-05-15 09:01 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Sections.java
> +                section.contains(newSection.getDownStation()) || section.contains(newSection.getUpStation()))
section 내에서 비교 로직을 수행하도록 다음과 같이 변경해보았습니다. 감사합니다👍👍

```suggestion
                section -> section.isOverlap(newSection)
```

2022-05-15 09:13 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
그렇군요! 메서드 이름만 보면 현재 구간 목록에서 검증하는 것인지, 하나의 구간을 대상으로 검증하는 것인지 명확하지 않군요!!! 구간 목록에서 검증하는 것임을 밝히도록 메서드 명을 수정하고, `validateAddable()`에서 찾은 구간을 대상으로만 확인하도록 변경하였습니다. 개발을 진행할 때는 미처 체크하지 못했던 부분인데, 이렇게 꼼꼼하게 봐주셔서 정말 감사드립니다🙏🙏

```suggestion
   private boolean hasAnySectionWithSameStations(List<Section> foundSections,
        Section section) {
        return foundSections.stream()
            .anyMatch(it-> it.hasSameStations(section));
    }
```

2022-05-15 09:21 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return count < 1 || count > 2;
남겨주신 피드백을 보고 부등호보다 일치 여부로 비교하는 게 더 간단하겠다고 판단하여 수정하였으며, 의미 있는 상수로 추출하여보았습니다👍 감사합니다.
```suggestion
        private boolean isInvalidCountInMiddle(List<Section> foundSections) {
        int count = foundSections.size();
        return count != OVERLAP_COUNT_ADD_DESTINATION && count != OVERLAP_COUNT_ADD_MIDDLE;
    }
```

2022-05-15 09:26 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Sections.java
> +            .orElseThrow(() -> new IllegalArgumentException("삭제할 역이 존재하지 않습니다."));
감사합니다!!! 상황에 알맞는 메시지를 반환하도록 수정해보았습니다.

```suggestion
            .orElseThrow(() -> new IllegalArgumentException("해당 노선 내에 삭제 요청된 역이 포함된 구간이 존재하지 않습니다."));
```

2022-05-15 09:32 UTC, sojukang commented on src/main/java/wooteco/subway/domain/Sections.java
> +        Section nextSection = findNextSection(section);
세세하게 체크해주셔서 정말 감사드립니다🙏🙏. `Section`이 아니라 `index`를 받도록 하여 불필요한 호출을 수정하였습니다.

```suggestion
        int index = values.indexOf(section);
        Section nextSection = findNextSection(index);
        
        private Section findNextSection(int index) {
        return values.get(index + 1);
    }
```

2022-05-15 09:38 UTC, sojukang commented on src/main/java/wooteco/subway/domain/SectionEntity.java
> +public class SectionEntity {
`SectionEntity`를 도입한 이유는 다음과 같았습니다.
### Domain, Entity 분리
테이블과 매핑된 Enitity는 id를 멤버로 가집니다. 
이 Entity는 필연적으로 id에 의존하여 DB와 의존된 로직을 수행합니다. 
도메인의 객체는 DB와 분리되어야한다고 생각하기 때문에 id가 아니라 객체 참조를 가져야한다고 생각했습니다.
 따라서 Domain과 Entity를 분리하였습니다.

여기서 기인한 문제로 한 계층 내에서도 Domain, Entity가 혼용되어 쓰이게 되었으며, 변환 로직을 수행해주어야한다는 문제가 발생하였습니다. 
객체의 특성을 유지하면서도 깔끔하게 분리되어 파악하기 쉬운 설계를 하려면 어떻게 해야할까? 를 고민해보았습니다.

굳이 현재 table 과 매핑된 Entity가 필요할까? 생각하여 Station을 참조로 가지는 Section으로 통합하여 수정해보려고 삽질을 하였으나... Name 속성이 필요한 경우와 id가 필요한 경우가 현재 얽혀있어 반영하지는 못했습니다. 😭

2022-05-15 09:43 UTC, sojukang commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
앗...!!! 해당 로직은 이미 `Sections`의 삭제 가능 여부 검증에서 체크하고 있는데 불필요하게 `Service`에서 체크하고 있었네요. 게다가 Entity를 대상으로 체크하고 있었군요. 로직은 분리한 도메인에서 처리하는 것으로 수정하였습니다. 감사합니다👍

2022-05-15 09:57 UTC, sojukang commented on src/main/resources/schema.sql
> +    foreign key (line_id) references LINE (id) on delete cascade
답변 감사드립니다👍👍👍. 저도 이번 미션에서는 FK를 사용하는 방식이 더 깔끔하게 처리할 수 있다고 생각하여 도입하였습니다. 향후 JPA를 추가 학습하면 해당 문제도 고려하며 DB 테이블을 설계해야겠군요🤸‍♂️

2022-05-15 10:00 UTC, sojukang commented
안녕하세요 `코니`👋!!!
주말에도 빠르고 정말 섬세하게 리뷰 남겨주셔서 정말 감사드립니다👍👍 
기본적으로 남겨주신 피드백 반영하며 리팩토링 하였습니다. 
변경 사항은 답글로도 남겨두었습니다.

다시 한번 감사드리며 미션 마무리까지 잘 부탁드립니다🙏!!

2022-05-15 17:37 UTC, choihz approved these changes
안녕하세요, 소주캉!

수정해 주신 부분과 남기신 코멘트를 모두 확인했습니다 👍 이제 지하철 노션도 미션은 마무리해도 될 것 같아요. 그동안 정말 고생 많으셨고, 함께하는 과정이 즐거웠습니다. 그럼, 다음에 다시 만나요~ 👋

2022-05-15 17:37 UTC, choihz commented on src/main/java/wooteco/subway/domain/Sections.java
> +        List<Section> foundSections = findSectionsOverlapped(section);
여기서 `foundSections`이라는 이름을 정한 이후 다른 메서드들의 파라미터 이름도 이와 같게 되었는데요, 이 이름이 의미를 충분히 전달하고 있는지 고민해 보면 좋을 것 같아요.

2022-05-15 17:37 UTC, choihz commented on src/main/java/wooteco/subway/domain/Section.java
> +        }
보통의 경우, `MIN_DISTANCE`라는 이름은 "최소로 가능한 값"이라는 의미를 가지고 있다고 생각할 것 같아요. 지금은 어떤가요?

2022-05-15 17:37 UTC, choihz commented on src/main/java/wooteco/subway/domain/Section.java
> +    }
```suggestion
    public boolean isOverlapped(Section section) {
        return contains(section.downStation) || contains(section.upStation);
    }
```

😉

2022-05-15 17:37 UTC, choihz commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
이 메서드를 보면 이 클래스 안의 다른 메서드들과 성격이 많이 다르죠. 말씀하신 것처럼 도메인, 엔티티가 동일 레이어에 같이 노출되는 것도 분명히 문제이고요.

이쯤에서 [DAO vs Repository Patterns](https://www.baeldung.com/java-dao-vs-repository) 글을 가볍게 한 번 읽어 보아도 좋을 것 같아요.

2022-05-15 17:37 UTC, merged