Step3
woowacourse/atdd-subway-admin pull request #321
Opened 2022-05-12 07:42 UTC by her0807

2022-05-12 08:10 UTC, her0807 commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
## 효과적인 null 핸들링을 위해  Optional 사용의 단점
- 객체 값을 가져올 때, 계속 orElseThrow() 로 처리해줘야하는 반복 로직에 대해 (?) 불편함을 느껴서 추출했는데
Optional 사용시 예외를 처리하는 방법이 미숙해서 이렇게 묶어서 사용해도 되는지 궁금합니다.

2022-05-12 08:10 UTC, her0807 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    private JdbcTemplate jdbcTemplate;
## Mock 없이 Service E2E test 작성해보기

---

의존 관계를 맺은 객체는 신경쓰지 않고 현재  비지니스 로직만 테스트 하고 싶어 간편한 방법으로 Mock 을 사용해서
테스트 했었습니다. 

그러다보니 실제 동작이 아닌, 가짜로 의존 객체들을 제어하여 나온 결과값에 대해
이게 진짜로 테스트가 된걸까? 살짝.. 의문이 들더라구요.

그래서 Mock 객체 없이 테스트를 수행하려다 보니 한 테스트에서 이렇게 많은 의존성을 가지게 되었습니다. 

- 미르만의 효과적인 인수테스트 방법
- 이런 식으로 의존관계를 가진 객체들을 제어해도 되는지 

위 내용이 궁금합니다. 😄

2022-05-12 08:27 UTC, her0807 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +public class SectionDao {
## SectionDao만 존재하는 이유

구현을 하려다 보니, 구간과 노선이 긴밀하게 연결되어 있음을 알게 되었습니다. 

## LineService 에서 구간 관리
- 한 노선에 중복되는 구간이 있으면 안된다. 
- 노선에 역을 삭제할 때, 구간이 최소 1개 이상 있어야한다.
위 와같은 요구조건들을 효과적으로 관리하기 위한 최적의 구조라고 판단하여 SectionService 없이
LineService와 SectionDao 의 의존 관계를 만들었습니다. 
## LineController 에서 구간 관리
url 이 line 으로 시작하여 LineController 에서 함께 처리해도 되겠다 생각했습니다. 

**구간 생성**
```java
 /lines/1/sections HTTP/1.1
```


**구간 삭제**
```java
 /lines/1/sections?stationId=2 HTTP/1.1
```

## 방향이 맞는가?
제가 판단한 기준이 올바른 방향인지 궁금합니다!

2022-05-12 08:27 UTC, her0807 commented on src/main/java/wooteco/subway/dao/SectionEntity.java
> +public class SectionEntity {
## DAO 반환 값을 Domain 과 Entity  둘 다 혼용해서 사용해도 될까요 ?

DAO와 도메인을 주고 받다 보니 조회, 저장 시
도메인 객체를 만들기 위해서 Id값으로 다시 디비에 조회해와 객체를 만들어야 했습니다. 
그래서 불필요한 쿼리가 생긴다는 느낌이 들었어요 🥺

해결 방안으로  entity를 만들어 부분적으로 도메인 없이 id만 주고받게 변경했습니다. 

이처럼 두가지 방식을 혼용해서 사용해도 괜찮을까요?

2022-05-12 08:27 UTC, her0807 commented on src/main/java/wooteco/subway/service/LineService.java
> +        sectionDao.deleteById(result.get(DELETE_SECTION_DOWN_SECTION_INDEX).getId());
## return; 

역 삭제시 역의 위치  `1) 제일 앞, 뒤 2) 중간` 에 따라서 다른 처리를 해줘야해서 분기문이 생길 수 밖에 없었습니다.
이렇게 분기문 처리를 해도 괜찮을까요?

2022-05-14 06:04 UTC, ddu0422 requested changes
안녕하세요 수달! 미르예요.

3단계 미션도 잘 구현해주셨네요 ㅎㅅㅎ
간단한 코멘트 남겨드렸으니 확인해주시면 감사하겠습니다 🙏 

남은 기간도 화이팅이에요!

2022-05-14 06:04 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +        String sql = "select *  from line where id = ?";
```suggestion
        String sql = "select * from line where id = ?";
```

공백이 한칸 더 있군요!

2022-05-14 06:04 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +public class SectionDao {
네네 굳이 Service와 Controller가 필요하지 않다면 만들지 않아도 된다고 생각해요!

정답은 없기 때문에 수달이 잘 생각해보면 좋을 것 같아요 ㅎㅅㅎ

만약, Contoller와 Service를 따로 만들었을 때는 어떤 장단점이 있을까요?

2022-05-14 06:04 UTC, ddu0422 commented on src/main/java/wooteco/subway/dao/SectionEntity.java
> +public class SectionEntity {
Domain과 Entity의 차이는 무엇일까요??

id는 Application에서 미리 만들고 있어서 재활용할 수 있지 않을까요??

2022-05-14 06:04 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Section.java
> +            throw new IllegalArgumentException("거리는 1이상이어야 합니다.");
여기도 상수가 포함되어 있군요!

2022-05-14 06:04 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Section.java
> +            throw new IllegalArgumentException("거리가 큽니다.");
보다 정확한 메시지를 전달하면 사용자가 이해하기 더 쉽지 않을까요?

2022-05-14 06:04 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        }
indent가 2네요! 1로 만들어보는건 어떨까요??

2022-05-14 06:04 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/LineService.java
> +        sectionDao.deleteById(result.get(DELETE_SECTION_DOWN_SECTION_INDEX).getId());
네네 ㅎㅎㅎ 괜찮다고 생각해요

2022-05-14 06:04 UTC, ddu0422 commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
네!충분히 괜찮다고 생각해요 ㅎ-ㅎ

2022-05-14 06:04 UTC, ddu0422 commented on src/test/java/wooteco/subway/dao/SectionDaoTest.java
> +        Section save = jdbcSectionDao.save(saveSection);
다른 테스트와 동일하게 savedSection으로 작성하는건 어떨까요?

2022-05-14 06:04 UTC, ddu0422 commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +                .extract();
메서드로 추출하셨다가 어떤 문제점이 있어 기존으로 변경한걸까요??

2022-05-14 06:04 UTC, ddu0422 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    private JdbcTemplate jdbcTemplate;
네네 통합테스트를 작성하려면 당연히 해당 객체들을 제어해도 된다고 생각해요!

저는 보통 Mocking을 하여 Service 테스트를 진행하여 고민중입니다!
https://jojoldu.tistory.com/637를 참고하여 다른 방식을 찾아보는 단계라 정확한 답변이 어려울 것 같아요!

2022-05-15 02:53 UTC, her0807 commented on src/test/java/wooteco/subway/service/LineServiceTest.java
> +    private JdbcTemplate jdbcTemplate;
저도 함께 고민하고 정리가 되면 미르에게 공유하겠습니다. ㅎㅎ 👍🏻

2022-05-15 03:14 UTC, her0807 commented on src/main/java/wooteco/subway/domain/Section.java
> +            throw new IllegalArgumentException("거리는 1이상이어야 합니다.");
전체적으로 상수 추출 확인하겠습니다 ☺️

2022-05-15 03:29 UTC, her0807 commented on src/main/java/wooteco/subway/dao/LineDao.java
> +        String sql = "select *  from line where id = ?";
👻

2022-05-15 03:29 UTC, her0807 commented on src/main/java/wooteco/subway/service/LineService.java
> +        sectionDao.deleteById(result.get(DELETE_SECTION_DOWN_SECTION_INDEX).getId());
감사합니다 👍🏻  우선 이렇게 해두고 더 나은 방법은 없는지 고민해보겠씁니다 !!

2022-05-15 03:42 UTC, her0807 commented on src/main/java/wooteco/subway/domain/Section.java
> +            throw new IllegalArgumentException("거리가 큽니다.");
작성할 때는 몰랐는데, 미르가 찝어주시니 제 관점에서만 적은 메세지 같네요 🥲 
앞으로 사용자 관점에서 보다 친절한 메세지를 보내기 위해 고민하고 작성하겠습니다.

2022-05-15 04:26 UTC, her0807 commented on src/main/java/wooteco/subway/dao/SectionEntity.java
> +public class SectionEntity {
현재 이해한 도메인과 엔티티의 차이입니다.

### 도메인
도메인이란 ? 비지니스 로직을 담고 있는 영역이다.

### 엔티티란
엔티티는 DB 에 관련된 처리를 하기 위한 영역이다. 

## 차이점
둘 다 같은 필드를 가질 수 있어서 헷갈릴 수 있다. 허나 도메인은 객체를 필드로 가지고 있어 해당하는 비지니스 로직을 
수행하고, 엔티티는 DB 의 저장, 수정, 삭제등을 하기 위해서 (ex 조인) 의존 관계를 맺고 있는 객체의 Id (고유값) 를 필드로 가지고 있다. 


```java
 // 도메인
public class Section {
    private Long id;
    private Line line;
    private Station upStation;
    private Station downStation;
    private int distance;

```

```java
public class SectionEntity {
    private Long id;
    private Long lineId;
    private Long upStationId;
    private Long downStationId;
    private int distance;
```

2022-05-15 08:41 UTC, her0807 commented on src/main/java/wooteco/subway/dao/SectionEntity.java
> +public class SectionEntity {
중간에 Repository 계층을 만들어서 Dao 에 도메인 의존관계를 제거해보았습니다.

2022-05-16 10:05 UTC, ddu0422 approved these changes
안녕하세요 수달! 미르예요 :)

이번 미션 정말정말 고생하셨어요 ㅎ-ㅎ
다음 미션까지 마무리 잘 해보아요.
충분히 잘해주어 머지할게요 !

궁금한 점이 있으면 언제든지 코멘트나 DM주세요!!

2022-05-16 10:05 UTC, ddu0422 commented on src/main/java/wooteco/subway/domain/Section.java
> +    public static final String DISTANCE_NEGATIVE_ERROR_MESSAGE = "거리는 1이상이어야 합니다.";
숫자 1대신 MIN_DISTANCE를 사용하는 건 어떨까요?
public이 private보다 아래에 위치해야하는 점이 고민이라면 아래 코드처럼 String.format()을 사용하는건 어떨까요?

https://github.com/woowacourse/atdd-subway-map/blob/6086b40e2290a414710a5a1061191f9465caceb7/src/main/java/wooteco/subway/domain/Line.java#L47

2022-05-16 10:05 UTC, ddu0422 commented on src/test/java/wooteco/subway/domain/SectionTest.java
> +        int distance = 100;
동일한 내용이 매 테스트마나 존재하는군요!
BeforeEach를 사용하여 분리하는건 어떨까요?

2022-05-16 10:05 UTC, merged