[Spring 지하철 노선도 - 3단계] 오찌(오지훈) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #323
Opened 2022-05-12 07:59 UTC by Ohzzi

안녕하세요 던! :)

이번에 테코톡이 있어서 테코톡 준비랑 병행하다 보니까 PR도 늦고 코드 퀄리티도 굉장히 떨어지게 되었네요 😢 
새로 추가된 로직들을 구현하는 것 부터 굉장히 힘든 3단계였습니다 ㅠㅠ
인수 테스트가 아직 부족해요! PR 요청 기간이 다가와서 우선 기능 구현을 다 하고 PR 드립니다(어쩌다보니 ATDD가 전혀 아니게 되었네요)
부족한 테스트는 리팩토링 하면서 추가해보도록 하겠습니다 :)

그리고 질문이 하나 있습니다!

---
## Q. 서비스에서 어떤 메서드는 DTO를, 어떤 메서드는 도메인을 반환해도 될까요?

편의를 위해 `LineService`에서 `StationSerivce`를 단방향으로 참조하게 되어있습니다. 그런데 이 때 `StationService`의 다른 메서드들은 `StationResponse`를 반환하는데, `LineService`에서만 필요한 단건조회 메서드만 `Station`을 그대로 반환하고 있습니다. 이런 식으로 사용하지 말고 통일적으로 `StationResponse`를 반환해준 뒤 다시 `Station`으로 돌려줘야 할까요? 던의 생각은 어떤가요?? :)

2022-05-14 05:13 UTC, gch01410 requested changes
안녕하세요 오찌!
3단계 미션 깔끔하게 잘 구현해주셨네요! 👍 
테스트도 꼼꼼하게 잘 작성해주셨어요!
코멘트 남겼으니 확인부탁드릴게요~

2022-05-14 05:13 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +        }
도메인별로 데이터가 존재하지않을때 발생하는 예외를 만들어주는건 어떨까요?
StationNotFoundException 처럼요!
지금은 예외처리가 같기때문에 도메인별로 나누지않아도 되긴하지만, 예외가 발행했을때 어떤 예외가 발생했는지만 보고서도 더 명확하게 예외상황을 파악할 수 있습니다!
메시지로 예외가 발생한 상황을 구분하면 메시지를 잘 남겨야하는 부담도 있을 수 있겠어요.

2022-05-14 05:13 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +        if (!stationDao.existsId(id)) {
boolean을 반환하는 exitst메서드 사용 👍 👍

2022-05-14 05:13 UTC, ghost commented on src/main/java/wooteco/subway/service/StationService.java
> +    }
StationService의 다른 메서드들은 컨트롤러에서 호출하고 있기때문에 Response를 반환해주는게 자연스럽고, findById 메서드는 다른 서비스에서 호출하고 있기때문에 Response가 아닌 Station을 그대로 반환해줘도 괜찮아보입니다!
서비스에 메서드의 반환값이 무조건 Response일 필요는 없습니다. 메서드를 호출하는곳에 맞게 사용하면 될 것 같아요

2022-05-14 05:13 UTC, ghost commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
이 메서드에서 단순히 Line객체를 생성하는것 뿐만 아니라 db에 insert까지 하고 있으니 메서드 이름을 create-보다는 save-로 하는건 어떨까요?

2022-05-14 05:13 UTC, ghost commented on src/main/java/wooteco/subway/service/LineService.java
> +    @Transactional(readOnly = true)
👍

2022-05-14 05:13 UTC, gch01410 commented on src/main/java/wooteco/subway/service/LineService.java
> +        Line persistLine = lineDao.findById(id);
Line이 존재하는지 확인 후에 조회하지않고
LineDao에서 Optional을 반환하도록하면 어떨까요?

2022-05-14 05:13 UTC, gch01410 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +                + " WHERE s.line_id = :line_id";
join 👍 👍 
쿼리를 String으로 표현할때 FROM 앞에서 줄바꿈해주면 가독성이 더 올라갈것 같네요!

2022-05-14 05:13 UTC, gch01410 commented on src/main/java/wooteco/subway/service/LineService.java
> +        Line line = new Line(persistLine.getId(), persistLine.getName(), persistLine.getColor());
새로 Line객체를 만들어서 반환하는 이유를 알 수 있을까요?
persistLine을 그대로 사용해도 될 것 같아요

2022-05-14 05:13 UTC, gch01410 commented on src/main/java/wooteco/subway/service/LineService.java
> +        Line line = lineDao.findById(lineId);
lineId에 해당하는 Line이 없다면 예외가 발생할 것 같아요!

2022-05-14 05:13 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        if (index == 0 || index == sortedStations.size() - 1) {
이 로직을 메서드로 분리해서 의미를 더 드러내볼 수 있을까요?

2022-05-14 05:13 UTC, gch01410 commented on src/main/java/wooteco/subway/exception/DuplicateLineException.java
> +public class DuplicateLineException extends DuplicateDataException {
예외를 잘 쪼개셨네요! 👍

2022-05-14 11:43 UTC, Ohzzi commented on src/main/java/wooteco/subway/service/StationService.java
> +        }
안그래도 NotFound 쪽만 예외가 뭉뚱그려 만들어져 있어서 분리할까 생각했었는데 분리하는게 좋겠네요!

2022-05-14 12:01 UTC, Ohzzi commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
항상 메서드 명에 고민이 많았는데 바꿔봐야겠네요! 감사합니다 :)

2022-05-14 13:06 UTC, Ohzzi commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +                + " WHERE s.line_id = :line_id";
가독성을 높여보려고 고민을 되게 많이 했는데, 확실히 접속사 앞에서는 끊어줄 필요가 있겠네요...!

2022-05-14 13:30 UTC, Ohzzi commented on src/main/java/wooteco/subway/service/LineService.java
> +        Line persistLine = lineDao.findById(id);
validateExist를 만든 이유가 사실 DAO에서 터지는 DataAccessException을 try ~ catch 방식으로 처리해서 조회를 하지 않고 비즈니스 로직 자체로 처리하고 싶었더긴 한데요...!

만약 Optional 반환이라고 하심은 query 메서드의 결과로 나오는 List를 findAny로 Optional을 던지라고 하시는 걸까요?

2022-05-14 13:31 UTC, Ohzzi commented on src/main/java/wooteco/subway/service/LineService.java
> +        Line line = new Line(persistLine.getId(), persistLine.getName(), persistLine.getColor());
이 부분은 제가 제정신이 아닌 상태로 코드를 작성했나보네요 ㅋㅋㅋㅋ
persistLine을 그대로 사용해도 되는 코드여서 수정하겠습니다!

2022-05-14 14:05 UTC, Ohzzi commented on src/main/java/wooteco/subway/domain/Sections.java
> +        if (index == 0 || index == sortedStations.size() - 1) {
체크하는 부분만 메서드로 빼 봐야 겠네요...!

2022-05-16 15:54 UTC, gch01410 approved these changes
안녕하세요 오찌!
구현 잘해주셔서 코멘트 남길 부분이 딱히 없었네요 👍 
가독성 관련해서 간단한 코멘트 남겼으니 확인부탁드릴게요!~
이번 미션 구현하시느라 수고많으셨습니다! 다음 미션도 화이팅입니다!

2022-05-16 15:54 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +                        target.getDownStation()));
```suggestion
        return values.stream()
                .noneMatch(section -> section.containStation(target.getUpStation())
                        && section.containStation(target.getDownStation()));
```
이렇게 변경하는건 어떠신가요? predicate 부분이 조금 더 명확하게 드러나도록 해보았어요.
개인적인 생각이니 오찌가 고민해주세요!ㅎㅎ

2022-05-16 15:54 UTC, ghost commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
if문안에 stream전체를 넣으니 살짝 가독성이 떨어지는 느낌이 들어요!
stream 결과를 로컬변수에 저장한뒤에 처리하는건 어떨까요?

2022-05-16 15:54 UTC, ghost commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
여기도 stream 결과를 로컬변수에 저장해서 로직을 한번씩 끊어서 처리해주면 가독성이 더 좋아질 것 같아요!

2022-05-16 15:54 UTC, gch01410 commented on src/main/java/wooteco/subway/domain/Sections.java
> +                        () -> new InvalidSectionCreateRequestException("구간 시작 역과 끝 역이 모두 노선에 존재하지 않아 추가할 수 없습니다."));
orElseThrow 부분은 한줄에 이어서 작성해도 될 것 같아요!

2022-05-16 15:55 UTC, merged