[Spring 지하철 노선도 - 3단계] 쿤(홍동건) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #329
Opened 2022-05-12 08:34 UTC by Hongdonggeon

2022-05-14 03:45 UTC, JunHoPark93 requested changes
안녕하세요 쿤!
3단계 진행하느라 고생많으셨어요.
코멘트 몇가지 남겼는데 지난 단계에서 아직 반영이 안된것들이랑 해서 같이 봐주셔요!

2022-05-14 03:45 UTC, JunHoPark93 commented on README.md
> +  - [ ] 노선에 구간이 2개만 존재하면 삭제할 수 없다.
요구사항 비어있는것들 한번씩 확인부탁드려요 :)

2022-05-14 03:45 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/Direction.java
> +    UP((section, inputSection) -> section.getUpStationId() == inputSection.getDownStationId()),
enum을 활용해보셨네요 👍

2022-05-14 03:45 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +        return new Section(id, lineId, upStationId, downStationId, distance);
isPresent를 없애보면 어떨까요?

2022-05-14 03:45 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        }
add를 해줬음에도 empty()리턴하는것은 의도하신건가요? 받는쪽에서 empty를 핸들링하면서 section에 하나가 추가됐다고 생각해야하는 로직이라면 개선이 필요해보여요.

2022-05-14 03:45 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +        jdbcSectionDao.delete(stationId, lineId);
이 부분의 optional처리도 개선해보면 좋을거같아요!

2022-05-14 03:45 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/ui/SectionController.java
> +    @PostMapping("/lines/{lineId}/sections")
👍

2022-05-14 03:45 UTC, JunHoPark93 commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    private SectionService sectionService;
서비스레이어 테스트도 해주셨네요~ 인수테스트가 존재하는데 bootTest로 만들어주셨어요. 어떤 이점이 있을까요?

2022-05-14 03:45 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
업데이트가 안되는경우는 어떤경우일까요?
비지니스로직의 경우 update쿼리를 날리기전에 알 수 있는 방법이 있을까요?

2022-05-14 03:45 UTC, JunHoPark93 requested changes
안녕하세요 쿤!
3단계 진행하느라 고생많으셨어요.
코멘트 몇가지 남겼는데 지난 단계에서 아직 반영이 안된것들이랑 해서 같이 봐주셔요!

2022-05-15 03:42 UTC, Hongdonggeon commented on README.md
> +  - [ ] 노선에 구간이 2개만 존재하면 삭제할 수 없다.
넵 확인 잘 하겠습니다!!

2022-05-15 10:52 UTC, Hongdonggeon commented on src/main/java/wooteco/subway/service/SectionService.java
> +        return new Section(id, lineId, upStationId, downStationId, distance);
기존에는 LineService에서 SectionService를 주입받아서, 노선 생성할 때 위의 메서드를 호출하고 있었는데요. 노선에 구간이 존재하지 않을때는 연결점이 없기 때문에 Optional을 사용했었습니다. 
하지만 다시 생각해보니, LineService에서 노선을 생성해서 첫 구간을 저장할 때에는 특별한 검증을 할 필요가 없이 단지 DB에 저장만 하면 된다고 생각이 들어, LineService에서 SectionDao를 주입받게 되면서 isPresent를 없앨 수 있었습니다!

2022-05-15 10:56 UTC, Hongdonggeon commented on src/main/java/wooteco/subway/domain/Sections.java
> +        }
노선에 구간을 처음 저장할 때, 연결점이 없기 때문에 의도한 로직이었는데요!! 위와 같은 LineService의 변경으로 인해서, 첫 노선을 생성할 때 구간이 하나 추가되므로 구간 추가를 할 때 연결점이 없는 경우는 사라지게 되었습니다!!

2022-05-16 05:44 UTC, Hongdonggeon commented on src/main/java/wooteco/subway/service/SectionService.java
> +        jdbcSectionDao.delete(stationId, lineId);
상한역, 하한역을 삭제할 경우에는 비어있는 리스트를 가지고 있는 Sections를 넘겨주었고, 상한역 하한역이 아닌 중간에 껴져있는 역을 제거할 때는 새로 추가할 Section을 추가한 Sections를 넘겨주어서 Optional 처리를 따로 하지 않도록 막아주었습니다!

2022-05-16 06:54 UTC, Hongdonggeon commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
다시 생각해보니, 클라이언트에서 업데이트할 값을 보내주는 것이 아니라, 구간이 새로 추가되면서 업데이트 되는 값을 서버에서 결정하기 때문에 예외상황을 추가할 필요가 없는 것 같다는 생각이 들어서 예외를 검증하는 부분을 삭제했어요! 업데이트가 안되는 경우라면 이미 존재하는 구간의 상행역, 하행역이 모두 일치할때 일 것 같습니다!

2022-05-16 10:44 UTC, Hongdonggeon commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    private SectionService sectionService;
인수 테스트는 사용자 관점에서 테스트하는 블랙박스 테스트 라고 알고 있습니다. 정상적인 값을 받을 수 있으면 내부 로직에 문제가 없는 것이겠지만, 정상적인 값을 받지 못할 시에는 문제를 찾아서 해결해야 할 것입니다. 작성했던 메서드에서 에러가 발생하거나 단위테스트에서도 똑같이 실패하면 로직을 수정하면 되겠지만, 로직상의 문제가 아닌 DB와의 연동과정 및 계층간에 결합을 하다 생긴 문제라면 단위 테스트에서 발견할 수 없기 때문에 통합 테스트를 하면 더 확실해질 것이라고 생각합니다 😃

2022-05-16 10:45 UTC, Hongdonggeon commented on src/test/java/wooteco/subway/service/SectionServiceTest.java
> +    private SectionService sectionService;
또한 저번 1단계 미션을 진행할 때 Mock 테스트를 경험해보았기 때문에, 이번에는 통합 테스트를 경험해보고 싶었습니다!!

2022-05-17 13:19 UTC, JunHoPark93 approved these changes
안녕하세요 쿤!
리뷰 반영하시느라 고생많으셨습니다.
주말간 많은 고민을 해주신 결과를 토대로 반영해주신거같아요.
다음 미션도 화이팅입니다!

2022-05-17 13:19 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return new Sections(sections);
optional 반환이 사라지게 되었네요~ 👍

2022-05-17 13:20 UTC, merged