[Spring 지하철 노선도 - 3단계] 아키(허영운) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #333
Opened 2022-05-12 09:01 UTC by yeongunheo

안녕하세요 또링!

3단계 미션도 잘 부탁드립니다 (_ _)

감사합니다.

2022-05-13 19:33 UTC, jnsorn requested changes
안녕하세요, 아키! 3단계도 잘 구현해주셨네요 :) 
테스트를 꼼꼼하게 잘 작성해주셔서 놀랐습니다. 😮
같이 고민해보면 좋을 부분들 코멘트 남겨두었으니 확인해주세요 ㅎㅎ
언제든 편히 DM 주시구요!

2022-05-13 19:33 UTC, jnsorn commented on src/main/java/wooteco/subway/dao/JdbcLineDao.java
> +            final String sql = "SELECT * FROM LINE WHERE id = ?";
가독성이 좋아졌어요 👍

2022-05-13 19:33 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/SectionController.java
> +    }
아키가 생각하는 객체간의 관계는 어떻게 되나요? URI상으로는 Line이 sections를 포함하는 것 같은데 객체간의 관계에서는 따로 표현하고 있지 않아 보여요.

2022-05-13 19:33 UTC, jnsorn commented on src/main/java/wooteco/subway/entity/LineEntity.java
> +public class LineEntity {
Entity와 Domain 객체를 분리한 이유가 궁금해요! :)

2022-05-13 19:33 UTC, jnsorn commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest extends AcceptanceTest {
와.. 테스트가 엄청 꼼꼼하네요. 굉장히 고생하셨을거 같은데요 👍

2022-05-13 19:33 UTC, jnsorn commented on src/main/java/wooteco/subway/service/LineService.java
> +        if (sections.keySet().contains(upStationId)) {
```suggestion
        if (sections.containsKey(upStationId)) {
```
😎

2022-05-13 19:33 UTC, jnsorn commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
조금 더 명확하게 작성해보면 좋을 것 같아요.

> 등록하려는 구간의 역들이 존재하는 역인지 확인한다. 

라는 요구사항을 다시 생각하면서 작성해보면 어떨까요? (제안이니 반영하지 않으셔도 무방합니다.🙂)

2022-05-13 19:33 UTC, jnsorn commented on src/main/java/wooteco/subway/service/LineService.java
> +    private Map<Long, Long> getSections(Line line) {
`Map<Long, Long>`의 구조가 굉장히 많이 반복되고 있어요. 레벨1때 학습한 일급컬렉션을 활용해볼까요?

2022-05-15 06:41 UTC, yeongunheo commented on src/main/java/wooteco/subway/ui/SectionController.java
> +    }
객체간의 관계에서는 Section이 Line을 알고 있도록 만들었습니다.
처음에는 url상에서처럼 Line이 sections를 포함하도록 만드려고 했었습니다. 그런데 객체설계에 관해 찾아보던중 [우아한객체지향](https://youtu.be/dJ5C4qRqAgA?t=544)이라는 세미나에서 `다중성이 적은 방향을 선택하라` 라는 말이 있더라구요! 그래서 Line이 Sections를 갖고 있는 대신, Section이 Line을 갖고있도록 수정했습니다.

2022-05-15 06:48 UTC, yeongunheo commented on src/main/java/wooteco/subway/entity/LineEntity.java
> +public class LineEntity {
Section을 예로 들면, 원래는 Section에서 line_id, upstation_id 와 같이 다른 객체의 식별자를 갖도록 설계했었습니다. 다른 크루들과 이야기하다보니 다른 객체의 id를 갖고있는 것은 객체중심 설계가 아니라 테이블 중심 설계인 것 같더라구요. 테이블은 자주 변경될텐데 그에따라 도메인도 변경되어야하나? 라는 고민도 있었구요.

그래서 Section이 Line, UpStation 등 객체를 갖도록 수정했습니다. 그리고 Dao에서 데이터를 꺼내와 객체로 변환할 때 잠시 데이터를 담아두는 DTO 개념으로 Entity를 분리했습니다.

2022-05-15 08:53 UTC, yeongunheo commented on src/main/java/wooteco/subway/service/LineService.java
> +        if (sections.keySet().contains(upStationId)) {
다음과 같이 모두 수정했습니다!
- keySet().contains => containsKey()
- values().contains => containsValue()

2022-05-16 13:48 UTC, yeongunheo commented on src/main/java/wooteco/subway/service/LineService.java
> +    private Map<Long, Long> getSections(Line line) {
`List<Section>`을 `Sections` 라는 일급컬렉션으로 변경하였습니다!

2022-05-16 13:51 UTC, yeongunheo commented on src/main/java/wooteco/subway/service/LineService.java
> +    }
메서드 이름을 `checkSectionHasNotAnyStation`로, 에러메시지를 `등록하려는 구간 중 하나 이상의 역은 무조건 노선에 등록되어 있어야 합니다.`로 수정했습니다.

2022-05-16 13:54 UTC, yeongunheo commented on src/main/java/wooteco/subway/ui/SectionController.java
> +    }
Line이 `List<Section> sections`를 갖는 것을 의도적으로 피하도록 설계하면서 생긴 궁금증이 있습니다.

1. 객체가 Collection을 가지면 정확히 어떠한 이슈가 발생하는건가요?
2. URI 상에서와 다르게 이렇게 객체를 다르게 설계해도 괜찮은걸까요? 오히려 다른 사람이 보기에 혼동을 줄 여지는 없는걸까요.

2022-05-17 03:35 UTC, jnsorn commented on src/main/java/wooteco/subway/domain/Station.java
> +        return Objects.equals(getId(), station.getId());
```suggestion
        return Objects.equals(id, station.getId());
```

😎

2022-05-17 03:35 UTC, jnsorn commented on src/main/java/wooteco/subway/entity/LineEntity.java
> +public class LineEntity {
넵 좋습니다. DTO의 개념으로 Entity를 분리하셨군요. 🙂 
(참고만 해주세요) 개인적으로 저라면 domain과 entity를 분리하지 않았을 것 같아요. 우선, 테이블이 변경되면 도메인도 어느정도 영향받는 게 당연하다고 생각해요.ㅎㅎ 결국 데이터를 가지고 여러 행위를 하는 게 객체니까요. 또, 지금 구조에서는 굳이 분리하지 않아도 충분히 객체중심 설계를 할 수 있다는 생각입니다. 객체 설계, DB 설계 그 간극에 대해서는 지금처럼 계속 고민해보시면 좋을 것 같아요. 👍

2022-05-17 03:45 UTC, jnsorn commented on src/main/java/wooteco/subway/ui/SectionController.java
> +    }
1. 이 부분은 직접 경험해보시는게 좋을 것 같아요. 우선 지금 상태에서 Line이 List<Section>을 갖는다면 어떤 문제가 생길까요? 🤔 하나의 데이터가 변경될 때 여러 콜렉션도 같이 변경된다면 어떤 문제가 있을지 다음 미션 진행하면서 고민해보면 좋겠네요 :) 문제가 없어 보인다면 우선 마음가는대로 설계하는 방법도 추천드립니다! (실제 서비스 되는 코드가 아닌 미션이기 때문에 우선 다 경험해보는게 좋다고 생각해요 ㅎㅎ) 
2. Rest API 설계라면 URI로 충분히 도메인간의 관계가 표현되면 좋지 않을까요? Line/id/Section/id 형태로 구성되어있는데, 실제로 그렇게 설계되지 않았다면 혼동이 있을 것 같아요. 보통 REST API에서는 연관관계를 가진 자원을 위처럼 표현하니까요 😁
[REST API 제대로 알고 사용하기
](https://meetup.toast.com/posts/92 )

2022-05-17 03:56 UTC, jnsorn approved these changes
안녕하세요 아키! 리뷰 잘 반영해주셨어요 👍 
질문에 대해 생각도 공유해주셔서 좋았습니다. 
다음 미션을 위해 이번 미션은 머지하도록 할게요. 
수고 많으셨어요!! 다음 미션도 화이팅입니다 ㅎㅎ

2022-05-17 03:56 UTC, jnsorn commented on src/main/java/wooteco/subway/domain/Sections.java
> +public class Sections {
일급컬렉션 👍 테스트도 있으면 좋겠네요!

2022-05-17 03:56 UTC, jnsorn commented on src/main/java/wooteco/subway/domain/Sections.java
> +    }
for문 안에서 upStation과 downStation을 일괄로 추가해줄 수 있지 않을까요? 

```java
        for (Section section : sections) {
            stations.add(section.getUpStation());
            stations.add(section.getDownStation());
        }
```

2022-05-17 03:56 UTC, jnsorn commented on src/main/java/wooteco/subway/domain/Sections.java
> +                .orElseThrow(() -> new NoSuchElementException("상행종점이 없습니다."));
올바른 메세지인가요?

2022-05-17 03:56 UTC, merged