[Spring 지하철 노선도 - 3단계] 이프(송인봉) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #334
Opened 2022-05-12 09:01 UTC by sinb57

2022-05-15 01:34 UTC, lxxjn0 requested changes
이프, 3단계 미션 반영하신 부분 잘 봤습니다!!

제가 이번 주에 일정이 바빠서 빨리 리뷰해드리지 못한 점 죄송합니다 ㅠㅠ 리뷰 반영하시면 빠르게 다시 확인해보도록 할게요!!

전체적으로 코드가 잘 짜여져 있는 것 같아서 제가 코드를 보면서 의문이 든 점들에 대해서 코멘트를 남겨두었습니다!! 한번 확인하고 리뷰 반영해주세요 👍🏼

2022-05-15 01:34 UTC, lxxjn0 commented on docs/API_Document.md
> +# Subway Map V2 API Document
API 문서까지 작성을 해주셨군요!! 👍🏼

2022-05-15 01:34 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/section/Section.java
> +    }
아래 메서드에 대한 접근 지정자를 한번 확인해봐야 할 것 같아요!! 추가로 너무 메서드가 세분화 되어있는 것 같은데 적절한 책임에 따라 분리를 하는 것도 좋을 것 같아요!!

2022-05-15 01:34 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/section/Section.java
> +    }
메서드 명이 조금 모호한 것 같아요!! closer가 가깝다는 의미인데 해당 메서드의 역할은 가까움을 판단하기 보단 짧은 거리를 판단하는 것으로 보여서요!

2022-05-15 01:34 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +        Section upSection = sections.get(0);
매직 넘버는 상수로 만들어서 관리해주세요!!

2022-05-15 01:34 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +                sections.stream().anyMatch(it -> it.containsStation(section.getDownStation()))) {
내부 조건을 한 번에 검증하는 메서드가 section에 있다면 코드가 더 간결해 질 것 같아요!!!

2022-05-15 01:34 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +        Station downStation = sections.get(sections.size() - 1).getDownStation();
만약 sections가 비어있을 때 해당 로직들은 어떠한 문제가 발생할까요?

2022-05-15 01:34 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +    public void append(Section section) {
하나의 메서드의 길이가 너무 긴 것 같아요!! private 메서드로 분리하면서 크기를 줄여보면 좋을 것 같아요!!

2022-05-15 01:34 UTC, lxxjn0 commented on src/main/java/wooteco/subway/repository/SubwayRepository.java
> +public class SubwayRepository implements LineRepository, SectionRepository, StationRepository {
해당 객체는 어떠한 역할과 책임을 가지도록 의도하였을까요? repository는 DB에 데이터를 적제하는 책임을 가지고 있는데 현재 클래스에서는 그 이상의 책임도 함께 가지고 있는 것 같아요!! 유효성 검증이나 내부에서 추가, 삭제할 값들을 로직을 통해 구분하고 DB에 반영하는 등의 로직이 있습니다. 

이렇게 된다면 해당 클래스는 데이터 적제라는 하나의 책임에 대해서만 변경이 발생할 수 있을까요??

2022-05-15 01:34 UTC, lxxjn0 commented on src/main/java/wooteco/subway/repository/SubwayRepository.java
> +public class SubwayRepository implements LineRepository, SectionRepository, StationRepository {
추가로 해당 클래스가 line, section, station 도메인 모두의 repository를 구현하고 있어요!! 그렇다면 해당 객체는 단 하나의 이유로만 변경이 발생할까요? 각각의 도메인 객체에 의해서 변경 영향을 받을 것 같아요!!

2022-05-15 07:37 UTC, sinb57 commented on src/main/java/wooteco/subway/domain/section/Section.java
> +    }
맞아요ㅠ 리팩토링하는 과정에서 의미가 모호함을 확인했고, 현재는 변경된 로직에 맞춰 `isLongerThan`으로 수정했습니다!

2022-05-15 07:41 UTC, sinb57 commented
이전 1,2단계에서의 피드백에 답변을 남겨드리지 못해 이렇게 정리해왔습니다!!
정말 좋은 피드백 감사합니다!

2022-05-15 07:42 UTC, sinb57 commented
이전 1,2단계에서의 피드백에 답변을 남겨드리지 못해 이렇게 정리해왔습니다!!
정말 좋은 피드백 감사합니다!

---

### DTO 답변
[코멘트 링크](https://github.com/woowacourse/atdd-subway-map/pull/233#discussion_r867331197)

> 두 dto에서 변경의 포인트가 달라지는 점이 어떤 상황이 될까? 라는 부분에 마땅한 상황이 잘 생각나지 않는 것 같아요!!

DTO 내 일부 필드값은 @PathVariable 또는 @RequestBody로 전송받도록 API 요구사항이 변경되는 상황을 가정했었고, 장비(PC, IOS, Android) 또는 브라우저 환경(사파리, 크롬, 파이어폭스) 등에 따라 구분된 여러 프론트 팀이 있는 경우 각 상황에 맞춰 Controller를 분리하여 관리해야 하므로 `DTO를 계층별로 분리하는 것`이 좋다고 생각했어요.


> 그래서 만약 저라면 하나의 dto를 기본적으로 사용하되, 이후 변경이 생기는 시점에서 만약 두 dto로 분리하는 것이 더 적절한 상황이면 그때 분리를 하는 것도 좋지 않을까 생각해요.

말씀하신 것처럼 변경 사항이 생긴 시점에서 분리/관리 하는 것이 좋겠다는 점에 동의해요. 이번 3단계에서 뼈저리게 느꼈거든요ㅎ;; 당장의 상황에서 요구되지 않은 조건을 미리 준비하는 행위는, 현재의 요구사항 충족과정에 있어서 꽤나 걸림돌이 되었어요. 기능을 추가하는 과정에서 DTO 분리가 일으킨 `관리대상 증가`로 인해 개발속도가 많이 지체되었어요. 그래서 Controller 계층의 DTO를 과감히 제거했고, Service 계층의 DTO를 Controller와 외부(View)와의 통신에 사용했어요. 혹여나 위에서 언급된 여러 상황이 추후 찾아온다면 그때가서 상황에 맞춰 대응할 수 있겠죠.

본래 갖가지 상황을 가정하면서 개발을 하다보니 이번 DTO와 같이 항상 과설계를 했어요. 물론 이러한 습관이 나쁘다고는 생각하지 않지만, 스스로의 기준이 아직은 미흡하네요. 며칠간 고민한 지금은 `코드를 작성한 이유가 현재의 요구사항을 충족하기 위함이 아니고, 추후의 상황을 대비한 것이라면! 과설계이다`라고 기준을 내렸습니다.

---

### 불필요한 쿼리 요청에 대한 답변
[코멘트 링크](https://github.com/woowacourse/atdd-subway-map/pull/233#discussion_r867331647)

DB에 저장하기 이전에 사용자로부터 받아온 데이터가 DB에 저장될 때 값이 변경될 수 있기 때문에, DB와의 값을 통일시키기 위해 데이터 저장과 별도로 조회로직을 수행하여 DB의 값을 받아왔어요.
처음에는 name, color 데이터가 DB에 저장될 때 트리거를 통해 prefix문자열이 덧붙여지는 등의 상황을 지만 곰곰이 생각해보니 이러한 경우는 DB에서 로직을 처리하는 방식 자체가 오류이므로, 이전에 제가 드린 답변과 코드 방식이 잘못되었음을 깨달았어요.

---

### `AcceptanceTest` 중복 코드 제거
[코멘트 링크](https://github.com/woowacourse/atdd-subway-map/pull/233#discussion_r867333319)

좋은 방법 알려주셔서 굉장히 감사합니다ㅎ 현재 `RequestHandler`를 통해 중복 코드를 제거했고 `LineRequestHandler`, `StationRequestHandler`에 알려주신 방법을 적용했습니다!!

2022-05-15 07:50 UTC, sinb57 commented on src/main/java/wooteco/subway/domain/section/Section.java
> +    }
리팩토링 과정에서 `boolean equalsUpStation(Long stationId)` 메서드가 Repository에서만 사용되는 것을 확인했고, 해당 오버로딩 메서드를 제거했습니다

2022-05-15 17:57 UTC, sinb57 commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +                sections.stream().anyMatch(it -> it.containsStation(section.getDownStation()))) {
Sections 클래스의 로직이 상당히 복잡해서, 어떻게 리팩터링을 진행할지 (메서드 분리 및 객체간의 협력 등) 여러가지를 고민하다보니 수정된 코드를 반영하는 것이 많이 늦어졌습니다!!

현재의 코드에서는 각각의 메서드가 최소한의 책임을 지니도록 분리하였고,
적절한 이름을 통해 의미파악이 쉬워지도록 하였습니다!!

2022-05-15 17:58 UTC, sinb57 commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +    public void append(Section section) {
ditto. 위의 답변과 같습니다!! 메서드 내부의 로직이 서로 연계되어 있다보니 분리하는 과정에서 시간이 오래걸렸습니다ㅜ

2022-05-15 18:15 UTC, sinb57 commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +        Station downStation = sections.get(sections.size() - 1).getDownStation();
sections가 비어있는 경우 `sections.get(sections.size() -1)`에서 음수가 대입되므로 Exception이 발생합니다.

 [이전 코드](https://github.com/woowacourse/atdd-subway-map/blob/fda3786841e5e27d27977bfa58651fe190be473c/src/main/java/wooteco/subway/domain/section/Sections.java) 이 부분을 막고자 생성자에서 `validateSectionsNotEmpty` 유효성 검사를 통해 sections 리스트의 요소가 1개 이상임을 검증했고, 해당 리스트의 요소 개수를 줄일 수 있는 `remove`에서는 `if(sections.size() == 1)` 검증을 통해, 위의 답변과 같이 sections의 크기가 0이 되어 `sections.get(sections.size() - 1)`에서 Exception이 발생할 가능성을 방지했습니다.

[현재 코드](https://github.com/woowacourse/atdd-subway-map/blob/a664f80b1c9ef52f793c4704092747a5ad0a7fcd/src/main/java/wooteco/subway/domain/section/Sections.java) 지금도 `이전 코드`와 마찬가지로 생성자에서의 유효성 검증과 `remove`에서의 유효성 검증을 통해 sections의 크기가 0이 되는 상황을 방지했습니다.

`append` 메서드에서도 `sections의 크기가 1 이상임을 확인하는 유효성 검증`을 진행해도 되겠지만, 지금의 코드에서는 아직 괜찮다고 생각되는데 `스티치`는 어떤 의견이신지 궁금합니다!!!

2022-05-15 19:49 UTC, sinb57 commented on src/main/java/wooteco/subway/repository/SubwayRepository.java
> +public class SubwayRepository implements LineRepository, SectionRepository, StationRepository {
> 해당 객체는 어떠한 역할과 책임을 가지도록 의도하였을까요? repository는 DB에 데이터를 적제하는 책임을 가지고 있는데 현재 클래스에서는 그 이상의 책임도 함께 가지고 있는 것 같아요!! 유효성 검증이나 내부에서 추가, 삭제할 값들을 로직을 통해 구분하고 DB에 반영하는 등의 로직이 있습니다.
> 
> 이렇게 된다면 해당 클래스는 데이터 적제라는 하나의 책임에 대해서만 변경이 발생할 수 있을까요??

SubwayRepository이 무거운 것은 사실이지만, 그렇다고 해서 Repository의 책임을 벗어났다고 아직은 생각하지 않아요.  말씀하신 `Repository는 DB에 데이터를 적제하는 책임을 가지고 있다.` 부분에 대해 이해되지만, 이와 반대로 저는 Repository를 `도메인에 대한 컬렉션`으로 정의하고 있어요. 오히려 DB와 관계를 맺고 DB에 데이터를 적제하는 책임은 DAO의 역할이라고 생각해요.


도메인 객체를 저장 공간(DB 혹은 CSV 엑셀 파일이나 외부 API 서버 등)을 통해 저장하고 관리하기 위해서는 객체를 데이터로 변경해야만 해요. 떄문에 DAO를 이용하는 것이고 이를 통해 영속성을 보장받을 수 있어요. 하지만 이러한 행위는 객체를 객체로 보지 않고 데이터로 보게 하는 문제를 야기하고 도메인 객체 간의 협력 관계를 사라지게 했어요. 객체 간의 비즈니스 로직이 객체 안에 캡슐화되는 것이 아니라 서비스 계층에서 모든 비즈니스 로직이 수행되었고, 여러 서비스 간의 코드 중복이 발생하면서 유지보수가 어려워지는 문제가 뒤따라왔어요.


이러한 단점들로 인해 저는 객체를 데이터가 아닌 `객체 그자체`로 보기 위해 여러 고민을 했고, 그러한 과정 속에서 Repository를 도입하기로 결심했습니다. `DB에 데이터를 저장한다`와 같이 구체적인 단계가 아닌 `Repository에 객체를 저장한다`를 통해 데이터 중심의 흐름이 Service 계층으로 넘어오지 못하도록 경계선 역할을 해줬고, Service 계층에서는 온전히 비즈니스 로직을 수행할 수 있도록 하였습니다.


제가 사용한 Repository는 여러 Dao를 통해 도메인의 저장 및 관리의 책임을 수행하고 있습니다. 객체를 저장하거나 조회, 수정하기 위해서는 해당 객체가 연관된 여러 객체들의 정보가 필요했고 이를 위해서는 하나의 Dao 뿐만 아니라 연관된 모든 Dao를 알아야만 했습니다. 그 결과 SubwayRepository는 LineDao, SectionDao, StationDao 모두를 알게 되었으며, 모든 Dao를 활용해 요청에 맞는 로직을 수행하고 있습니다.


Repository가 `유효성 검증을 수행하고 있다는 점`에 대해서는, Repository가 컬렉션이기 때문에 괜찮다고 생각했습니다. 지하철노선의 이름이나 색상의 중복을 허용하지 않기 위해서는 저장되어 있는 모든 객체의 정보가 필요했고 이에 대한 정보를 알고 있는 것은 Repository 본인입니다. 지금까지의 미션에서 일급컬렉션을 통해 객체의 집합을 관리해오면서 이에 대한 유효성 검증은 일급컬렉션에게 책임을 부여해왔습니다. 그렇다면 도메인에 대한 컬렉션인 Repository 또한 이와 마찬가지로 본인이 이를 수행하는 것이 옳지 않을까 생각합니다.


(해당 부분은 리팩터링 이후의 코드를 기반으로 답변을 남겼습니다.)
`내부에서 추가, 삭제할 값들을 로직을 통해 구분하고 DB에 반영하는 로직이 있다.` 부분은 아마도 `updateSections`에 대한 로직이라고 생각됩니다. 이 부분에 대해서도 위와 마찬가지로 컬렉션이라는 관점에서 허용되는 로직이라고 생각했습니다. Repository를 사용하는 클라이언트측(Service)에서 바라보자면, Line 객체의 Sections 정보가 수정되었고 Service가 변경된 상태를 저장하고자 Repository에게 Line 객체를 넘겨주었을 때, 이 객체를 받아서 상태를 저장하는 것은 온전히 Repository의 책임입니다. 그리고 이 책임을 수행하기 위해, 저장되어 있는 기존의 Sections 정보를 모두 지우고 새로운 Sections 정보를 저장할 수 있지만, 지금처럼 Sections에서 변경된 정보만을 추출하여 상태를 업데이터하는 등 `변경된 상태를 어떠한 방식으로 저장할 것인가`는 온전히 Repository의 권한이라고 판단했습니다.


물론 Repository가 무거워지며 여러 기능을 제공하고 있기 때문에 과도한 퍼블릭 메서드 개방과 유지보수의 문제가 존재합니다. 우선 퍼블릭 메서드의 경우, LineRepository와 StationRepository 인터페이스가 분리되어 있고 SubwayRepository가 이를 다중상속하고 있음을 볼 수 있습니다. 이를 통해 LineService에서는 LineRepository 타입으로 해당 구현체를 사용하므로 LineService에서 필요로 하는 메서드만 퍼블릭으로 제공받을 수 있고, StationService도 이와 마찬가지로 적용되어 있기 때문에 ISP 원칙에 따라 과도한 퍼블릭 메서드 개방은 해결했다고 생각합니다. 문제는 유지보스 관점인데, 이 부분은 문제점이 많음을 인지하고 있습니다. 많은 고민 끝에 지금의 상황까지 도달했지만 어떠한 방법으로 더 좋은 코드를 만들 수 있을지는 잘 모르겠습니다.

2022-05-15 20:06 UTC, sinb57 commented
Sections에 대한 리팩터링이 너무 오랜 시간을 잡아먹었네요ㅠ
여전히 미흡한 부분이 많이 있겠지만(특히 테스트코드...😥)
당장은 본래 목표했던 도메인 설계에 대한 리팩터링(특히 Sections..😡)은 끝마쳐서 PR 요청드립니다!!

---

이전 1,2단계에서의 피드백과 이번 3단계에서의 피드백에 답변을 정리하여 남겨두었습니다!
지금 새벽감성이라..(하핳) 제 생각이 제대로 표현되었을지 걱정되긴 하네요.

2022-05-17 15:19 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/section/Sections.java
> +        Station downStation = sections.get(sections.size() - 1).getDownStation();
먼저 기존 코드에서 가장 신경써야 할 부분은 `sections.get(0)` 입니다! 만약 sections가 비어있었다면 `sections.get(0)`는 null을 반환할 것이고 null에서 `getUpStation` 메서드를 호출하게 되면서 NPE가 발생하게 될 거에요!

링크를 달아주신 부분을 봤을 때 

```java
    private void validateSectionsSizeEnough() {
        if (orderedSections.size() == ALLOWED_MINIMUM_SECTION_COUNT) {
            throw new IllegalStateException("노선의 구간이 하나이므로 구간을 삭제할 수 없습니다.");
        }
    }
```

해당 메서드로는 size가 1인 경우만 확인하고 1보다 작은 경은 확인이 안되어서 앞선 NPE 문제는 그대로 발생할 것 같은데 맞을까요?? 물론 앞서 작성한 remove나 다른 로직의 흐름에서는 방어가 된다고 하더라도 언제 어떠한 메서드가 추가가 되어서 NPE가 발생할 수 있는 상황을 만들지는 우리가 알 순 없습니다! 

그래서 이런 NPE 발생 가능성이 있는 로직에서는 항상 그에 대한 예외를 처리하고 로직을 실행해야 할 것 같아요!! NPE가 발생하면 예외가 발생한 시점을 잡아내기가 상당히 힘들기 때문에 항상 null-safe 한 메서드를 작성하기 위해 신경을 잘 써주면 좋을 것 같아요!! 👍🏼

2022-05-17 16:23 UTC, lxxjn0 commented on src/main/java/wooteco/subway/repository/SubwayRepository.java
> +public class SubwayRepository implements LineRepository, SectionRepository, StationRepository {
이프가 남겨준 코멘트 잘 읽어봤어요!! 👍🏼 제가 생각했던 것보다 훨씬 더 깊이있는 생각을 잘 표현해줘서 다시 한번 더 놀랐네요! 그리고 이프가 남겨준 코멘트에 대한 저의 생각을 한번 작성해보도록 할게요!!

> 물론 제 생각이 맞지 않을 수도 있습니다! 저도 이번에 이프의 코멘트를 보고 한번 공부를 조금 해보고 답변드리는 거라서 불확실한 정보가 함께 포함될 수도 있으니 참고해서 봐주세요 :)

먼저 이프의 전체적인 의견을 정리하면 'DAO는 DB와 관계를 맺는 객체, Repository는 도메인에 대한 컬렉션이다. Repository는 도메인을 관리하는 컬렉션이며 이를 일급 컬렉션처럼 사용하였기 때문에 유효성 검증 등 도메인에 대한 로직을 관리하는 책임을 가져도 어색하지 않다.' 라고 생각되는데 맞을까요??

여기서 먼저 이프가 말한 'Repository는 도메인에 대한 컬렉션이다'와 'Repository가 컬렉션이기 때문에 유효성 검증과 같은 로직이 수행될 수 있다(일급 컬렉션처럼)'은 전혀 다른 말이라고 생각이 들어요!! 

도메인에 대한 컬렉션은 말 그대로 도메인을 담고 있는 컬렉션이라고 생각해요. 마치 `List<Section>`처럼요. 도메인 객체를 컬렉션처럼 담고 있으며 필요할 때 가져다 쓰고 다시 담아두고 할 수 있죠. 그런데 일급 컬렉션은 이러한 '도메인 객체를 담고 있는 컬렉션'을 감싸는 도메인 객체입니다. 컬렉션을 감싼 도메인 객체이지 컬렉션은 아니라고 생각합니다. 일급 컬렉션에 도메인 로직을 둘 수 있는 건 도메인 객체라서 그런거라고 생각해요. 그렇기에 지금의 Repository에 도메인 로직(유효성 검증 등의 로직)이 있다는 이야기는 마치 List 컬렉션에 도메인 로직을 담았다는 이야기와 같다고 생각이 듭니다.

위의 의견을 이야기하는 이유는 우선 이프가 달아둔 `@Repository` 어노테이션에서 부터 확인할 수 있을 것 같아요!! 

![image](https://user-images.githubusercontent.com/48052622/168856171-e4396377-e73c-4b58-a838-b3adfefc6858.png)

위 내용을 간략히 정리해보면 '해당 주석이 달린 클래스는 repository 임을 나타낸다. DDD에서의 repository 개념을 나타내고 기존에 java ee에서 사용한 패턴인 dao와는 차이를 가지고 이해하고 사용해야 한다'로 볼 수 있을 것 같아요!!

그렇다면 DDD에서 말하는 repository에 대해서 한번 살펴보면 좋을 것 같아요! 저는 우선 아래의 2개 글을 참고하여서 알아봤습니다.

- https://bperhaps.tistory.com/entry/Repository%EC%99%80-Dao%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90
- https://infondgndg91.blogspot.com/2020/05/ddddomain-driven-design-repository.html

해당 글을 읽으면서 DDD의 Repository를 간략하게 정리해보면 '단순히 객체의 상태를 관리하는 저장소', '그냥 컬렉션이라는 관점', '컬렉션 지향 repository이지만 영속성 데이터 저장소와 함께 동작' 정도로 볼 수 있을 것 같아요.

그래서 저는 영속성 데이터 저장소에 저장하는 것은 과거의 DAO에서의 역할을 이어 받은 것이 아닌가? 라는 생각을 하고 있고 사용하는 입장에서는 그냥 List를 사용하는 것처럼 동작하도록 하는 것이 Repository 라고 이해했습니다!

그런 관점에서 다시 한번 해당 코드와 이프의 의견을 돌아볼게요. 현재 SubwayRepository는 `@Repository` 어노테이션을 가진 클래스인 만큼 DDD의 repository 관점에 해당하는 클래스로 작성해야 한다고 생각합니다. 그리고 이프가 말한 '도메인에 대한 컬렉션'처럼 정말 말 그대로 List에서 도메인 객체를 가져가고 저장하듯이 사용하면서 이를 영속성 데이터 저장소에 저장하는 형태가 되어야지 Repository에 맞는 객체라고 생각해요.

현재의 코드는 이렇게 단순히 컬렉션으로 관리하는 개념 이상의 개념, 즉 일급 컬렉션이라는, 컬렉션이 아닌 컬렉션을 감싼 도메인 객체처럼 repository를 사용하고 있기 때문에 적절하지 않다고 생각합니다. 

String을 관리하는 List에 빈 문자열을 넣든, 길이가 1000이 넘는 문자열을 넣든 아무런 문제가 발생하지 않습니다. 길이가 10인 문자열만 저장할 수 있다는 도메인 로직이 존재한다고 하더라도요. 컬렉션은 말 그대로 객체를 담는 저장소의 역할만 하기 때문입니다. 그렇기에 저는 현재 repository에 있는 로직은 오히려 service에서 비즈니스 로직에 대한 검증이 필요한 것이지 repository가 가져야 할 책임이 아니라고 생각합니다.

추가로 Repository에서 여러 개의 DAO를 가지는 것은 충분히 그럴 수 있다고 생각합니다. 지금처럼 Line이 Section을 가지고 있고 Line을 저장한다면 당연히 Section을 저장하기 위한 dao가 필요하기 때문이죠. 

하지만 Line, Station 도메인에 대한 repository를 따로 정의하고 그에 대한 구현체를 하나로 처리하는 것은 좋은 방법인지는 잘 모르겠습니다! 앞서 말씀드린 것처럼 만약 LineRepository에 대한 구현체와 StationRepository에 대한 구현체가 따로 있다면 각각의 도메인에 대한 변경사항이 발생하거나 그럴 경우 자신의 도메인에 해당하는 Repository 또는 구현체를 수정하면 되기 때문이죠. 

또한 두 repository에 대해서 하나의 구현체를 관리하는게 어떠한 부분에서 장점이 있는 지는 지금의 저로서는 잘 떠오르지도 않고 공감이 가지도 않는 것 같아요. 추후 각각의 repository에 많은 메서드들이 추가된다면 그때 여러 repository를 구현한 하나의 구현체의 크기는 기하급수적으로 증가하게 될 것입니다. 그런 상황을 고려해보더라도 구테여 각각의 도메인에 대한 repository 구현체를 하나로 가져가야 하나?는 동의하기 힘든 것 같아요.

---

이번에 이프가 여러가지 고민할 거리에 대한 정보를 주셔서 이전에 제가 당연시 사용했던 개념들에 대해서 한번 더 고민해볼 수 있는 계기가 된 것 같아요!! 사실 Repository라는 개념이 DDD로부터 나온 개념이다보니 이해하기도 힘들고 저도 이번에 처음 학습하면서 리뷰를 달게 되었네요. 제가 작성한 내용에 부족한 점들이 많을 거에요. 그래도 학습한 내용과 제가 가지고 있는 생각에 대해서 정리해서 남겨두었으니 한번 이프가 읽어보시고 생각해보면 좋을 것 같네요!! :)

2022-05-17 16:43 UTC, lxxjn0 approved these changes
이프, 지하철 노선도 미션 진행하느라 수고 많으셨어요!!

전체적으로 코드의 수준도 높고 이미 어느정도 충분히 코드가 작성된 것 같아서 이번 리뷰에서는 딱히 리뷰를 달 만한 부분이 없는 것 같더라구요 ㅠㅠ 그래서 한가지 공부해보면 좋을 만한 부분에 대해서만 코멘트 달아두었습니다. 혹시 추가적인 궁금한 부분이 있거나 하면 언제든지 연락주세요 :)

추가로 앞선 리뷰에 대한 코멘트들을 다시 남겨두었는데 해당 코멘트에 대한 의견 한번 읽어보면 좋을 것 같아요!! 이프 덕분에 저도 많이 학습하기도 했고 이번 미션에서 앞선 코멘트들에 대한 의견 교환만으로도 충분히 의미있는 시간이 되었을 것 같아요!! 미션 진행하시느라 수고 많으셨어요 👍🏼

2022-05-17 16:43 UTC, lxxjn0 commented on src/main/java/wooteco/subway/domain/section/Section.java
> +    }
유효성 검증을 생성자에 두고 this 생성자를 호출한 부분 좋네요!! 👍🏼 추가로 방어적 복사는 아니더라도 this 초기화 이후 유효성 검증을 가져가는 부분에 대해서도 한번 알아보면 좋을 것 같아요!!

https://velog.io/@max9106/Java-%EB%B0%A9%EC%96%B4%EC%A0%81-%EB%B3%B5%EC%82%ACDefensive-copy

2022-05-17 16:43 UTC, merged