[Spring 지하철 노선도 - 3단계] 토닉(최우석) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #335
Opened 2022-05-12 09:04 UTC by tonic523

안녕하세요 제이! PR 시간이 늦어서 죄송합니다 ㅠㅠ
구현하는 시간이 늦어져서 우선 PR 요청 드리고 글은 수정하겠습니다!

2022-05-14 02:10 UTC, JunHoPark93 requested changes
안녕하세요 토닉!
마지막 단계 구현하느라 고생많으셨습니다.
몇가지 코멘트 남겼는데 확인해보시고 반영 및 의견 부탁드려요~

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/controller/ExceptionHandlerController.java
> +        e.printStackTrace();
빠져도 될거같아요!

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +    private final SimpleJdbcInsert simpleJdbcInsert;
어떤 기준으로 2개를 나누셨나요?

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    private LineDao lineDao;
주입방식을 통일하면 좋을거같아요~

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
역할을 좀 더 세분화해보면 어떨까요? 
그리고 마지막에 delete는 어떤것때문에 해주시는건가요? 🤔

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/LineService.java
> +                .map(this::getStationOrException)
있으면 반환하고 없으면 예외를 발생시키는 패턴인데요, 메서드명에서 orException은 빼도될거같은데 어떻게 생각하시나요?

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/LineService.java
>          }
저번에 같이 이야기 나눴던 부분인거같아요! 아래처럼 수정해보기로했던걸로 기억해요.
```
lineDao.findById(lineId).ifPresent(line -> {throw new NotFoundException(line.getId() + "에 해당하는 지하철 노선을 찾을 수 없습니다.");});
        lineDao.update(new Line(lineId, name, color));
```

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/LineService.java
>          }
삭제쪽도 마찬가지로요!

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +import wooteco.subway.domain.Section;
> 저번 피드백에서도 같이 얘기를 나누어 이번 미션에 한 번 도메인과 엔티티를 분리하려고 시도해봤습니다.

저번에 차이에 대해서 질문주셔서 구두로 이야기를 나눴었죠. 제가 실제업무에서 분리해서 진행했던 프로젝트에 대해서 설명을 드렸었고, 분리하지 않은 프로젝트에서도 설명을 드렸던걸로 기억해요!

분리하는게 좋다아니다 보다 여기 프로젝트에서 필요한 조치인지 다시 고민해보면 어떨까요?

2022-05-14 02:10 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return new Sections(sections);
도메인에 로직을 잘 몰아주셨어요!
복잡도를 줄여보려면 어떻게 해야할까요?

2022-05-16 12:52 UTC, tonic523 reviewed
안녕하세요 제이!
이번 미션에서는 엔티티와 도메인에 대한 개념에 혼란이 와서 오래걸렸던 것 같네요..
제이가 남겨준 코멘트를 반영했으니 확인부탁드립니다!

## 수정한 부분
- Section의 Long 타입의 id를 객체로 수정
  - 수정은 했지만 Station과 Line이 VO와 다름없어서 큰 차이점을 느끼진 못했습니다..
- 서비스 메서드에 `@Transactional` 붙이기
  - 트랜잭션에 대한 개념을 학습해보았습니다.
- 복잡도를 해결하기 위해 메서드 분리
  - 메서드 네이밍이 어렵다는 것을 체감했습니다..

2022-05-16 12:52 UTC, tonic523 commented on src/main/java/wooteco/subway/controller/ExceptionHandlerController.java
> +        e.printStackTrace();
넵! 해당 로직은 `DuplicateNameException`으로 다시 돌려놓았어요. 원래는 지하철 노선의 이름과 색깔도 unique해야 한다고 생각을 했고 쿼리를 날렸을 때 둘 중 하나라도 중복이 되면 예외가 발생하게 되었습니다. 이 예외에서 어떤 필드에서 중복이 되어 예외가 발생했는지 알 수 없어 dao에서 발생한 예외 그대로 캐치하고 예외 메시지도 포괄적으로 작성하게 되었는데 생각해보니 색깔은 중복되더라도 이름이 다르다면 구분할 수 있다고 생각이 들어 색깔 컬럼에 unique를 뺐습니다.
이 후에는 제이와 얘기했던 것 처럼 예외 메시지를 분명하게 작성하고 따로 `DuplicateNameException`을 구현하여 해당 예외 처리를 할 수 있도록 수정했습니다!

2022-05-16 12:52 UTC, tonic523 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +import wooteco.subway.domain.Section;
직접 분리하여 구현하다보니 같은 객체를 단순 레이어에 따라 분리한 느낌이 들었습니다.
제이가 얘기 해주신 내용 중 여러 DB서버 또는 엔티티에서 각 데이터를 가지고 온다는 내용을 정확히 이해하진 못했었습니다ㅠㅠ 곰곰이 생각해보니 여러 DB의 데이터를 종합하여 비즈니스 로직을 수행해야 할 때 각 DB의 엔티티를 구현하고 엔티티에서 가져온 데이터로 도메인 객체를 만든다는 가정이라면 엔티티와 도메인을 분리하는 것이 좋은 방법인 것 같아요. 이 외에는 도메인과 엔티티를 꼭 다른 객체라고 파악하면 안된다고 생각을 했는데 그 이유는 비즈니스 로직과 DB 스키마는 연관되어야 한다고 생각이 들었기 때문입니다. 두 개념을 달리 본다는 것 자체가 DB 스키마의 설계를 의심해볼 여지가 있는 것이라고도 볼 수 있을 것 같아요.

결론적으로 이번 프로젝트에서는 분리하지 않는게 좋을 것 같습니다. 테이블이 크지 않고 각 스키마가 비지니스 로직에 연관되어 있어 스키마를 그대로 객체로 가져와 충분히 요구사항을 구현할 수 있었어요.

한 크루가 저에게 엔티티에 대한 개념이 없다면 엔티티를 고려했을까? 라고 물었을 때 생각해보니 굳이 분리하려고 시도하지 않았을 것 같았습니다. 다른 사람들의 코드에서 엔티티를 보고 나도 적용해봐야지 라는 생각으로 적용하다가 두 개념에 혼란이 왔던 것 같네요..

2022-05-16 12:52 UTC, tonic523 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +    private final SimpleJdbcInsert simpleJdbcInsert;
어떤 기준이 있었던 것은 아니고 BeanPropertySqlParameterSource 를 통해 쉽게 도메인 객체를 매핑하여 DB에 insert할 수 있어 사용했습니다.

2022-05-16 12:52 UTC, tonic523 commented on src/main/java/wooteco/subway/service/LineService.java
>          }
앗! 넵 이름과 색깔의 중복 구분을 못하여 포괄적으로 작성했는데 다른 메시지도 신경쓰지 못했네요.. 수정하겠습니다!

2022-05-16 12:52 UTC, tonic523 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    private LineDao lineDao;
생성자 주입으로 통일시키겠습니다!

2022-05-16 12:52 UTC, tonic523 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        return new Sections(sections);
넵! 급히 구현하다보니 복잡한 로직으로 구현했네요.. 각 로직을 분리하여 메서드 네이밍을 통해 가독성을 높이는 방법으로 수정하겠습니다.

2022-05-16 12:52 UTC, tonic523 commented on src/main/java/wooteco/subway/service/LineService.java
> +                .map(this::getStationOrException)
네! 이제 보니 굳이 넣지 않아도 예외 발생에 대한 부분은 메서드명에 작성하지 않아도 될 것 같네요!

2022-05-16 12:52 UTC, tonic523 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
도메인 객체를 만드는 과정을 메서드로 분리하겠습니다. 그리고 Section이 가지는 필드를 Long 타입의 id 값이 아닌 Station 객체를 넣어주어 getter 메서드를 줄일 수 있을 것 같아요!

구간을 update하는 과정이 다음과 같습니다.
1. Line에 해당하는 구간을 구한다.
2. 해당 구간에 구간을 추가하거나 삭제한다.
3. 기존 Line에 해당하는 구간들을 DB에서 삭제한다.
4. 업데이트된 구간으로 DB에 batch insert한다.

업데이트된 구간을 추가하고 어떤 구간은 업데이트하는 과정이 복잡하다고 생각해 비지니스 로직과 괴리감이 있지만 위 같은 방법으로 구현했습니다.

2022-05-17 13:22 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/service/SectionService.java
> +    }
넵 저 단계들이 눈에 잘 보이도록 구분이 되면 더 좋을것같다라는 측면에서 남겼었습니다!

2022-05-17 13:24 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/dao/SectionDao.java
> +import wooteco.subway.domain.Section;
넵 이부분은 차차 경험하시게 될거에요! 
데이터를 항상 mysql한군데에서만 가져오게 되지 않을거라 추후 고민할 기회가 분명히 있을거에요.

2022-05-17 13:28 UTC, JunHoPark93 commented
commit이 없는것같은데 origin push확인 부탁드려요 🙏

2022-05-18 09:54 UTC, JunHoPark93 approved these changes
안녕하세요 토닉!
리뷰 반영하시느라 고생하셨어요. 
노선도는 여기서 머지할게요.
다음 미션도 화이팅에요!

2022-05-18 09:54 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/domain/Sections.java
> +        if (sections.size() < DELETABLE_SIZE) {
조금더 명시적으로 바꾸셨네요!

2022-05-18 09:54 UTC, merged