[Spring 지하철 노선도 - 3단계] 페퍼(최수연) 미션 제출합니다.
woowacourse/atdd-subway-admin pull request #336
Opened 2022-05-13 10:14 UTC by SuyeonChoi

안녕하세요 코니!
앞서 3단계 미션의 기간을 자유롭게 주신 것에 대한 감사의 말씀을 전하고 싶습니다.🙏🙏
(멘탈이 흔들렸는데 코니의 말씀 덕분에 힘을 많이 얻어가요❤️!)
3단계를 짧은 시간안에 구현하다보니, 요구사항을 충족하는 것에 초점을 두고 구현해보았어요.
그러다보니 dao가 비즈니스 로직처럼 수행되는거 같아 주말동안 도메인의 책임에 맞게 리팩토링을 진행해야할거 같습니다.

리팩토링과 설계에 대한 고민이 아직 완료되지 않았지만, 남은 기간 동안 최대한 코니와 소통을 많이 하고 싶어 리뷰를 요청드립니다!
그럼 이번 리뷰도 잘 부탁드리겠습니다🤓🤓

2022-05-13 18:45 UTC, choihz requested changes
안녕하세요, 페퍼!

3단계 구현해 주신 부분을 확인하고 코멘트를 남겨 두었습니다. 궁금한 점이나 의견이 있으시다면 언제든 코멘트 또는 DM 주세요~

2022-05-13 18:45 UTC, choihz commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
테스트가 실패하고 있네요 😢

2022-05-13 18:45 UTC, choihz commented on src/test/java/wooteco/subway/acceptance/SectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
또한, 상태 코드를 확인하는 것만으로 충분히 검증했다고 할 수 있을까요? 실제로 구간을 저장하지 않고 해당 상태 코드만 내려줘도 테스트는 성공하게 되지 않을까요?

2022-05-13 18:45 UTC, choihz commented on src/main/java/wooteco/subway/controller/SectionController.java
> +    }
처음에 노선을 생성할 때 2 - 4로 구간을 지정하고, 이 API를 통해 2 - 4로 다시 구간 생성 요청을 보냈더니 201 응답이 오네요 😮 DB를 조회해 보니 아래와 같아요.

<img width="675" alt="스크린샷 2022-05-14 오전 3 16 38" src="https://user-images.githubusercontent.com/18049492/168343787-295748e1-c4af-4f5b-95ad-3c15c9ab5b82.png">

2022-05-13 18:45 UTC, choihz commented on src/main/java/wooteco/subway/service/SectionService.java
> +            throw new DataNotFoundException("존재하지 않는 지하철입니다.");
존재하지 않는 "지하철"이라는 표현은 조금 모호한 것 같은데요, 노선, 구간, 역 등의 표현을 사용하는 것이 더 명확할 것 같아요.

2022-05-13 18:45 UTC, choihz commented on src/main/java/wooteco/subway/service/SectionService.java
> +                .orElseThrow(() -> new IllegalArgumentException("상행역과 하행역 중 하나는 노선에 존재해야합니다."));
특정 구간에 속하는 역을 삭제했을 때(`DELETE /stations/{id}`) 어떤 일이 발생하고 있나요?

2022-05-13 18:45 UTC, choihz commented on src/main/java/wooteco/subway/service/SectionService.java
> +                .orElseThrow(() -> new IllegalArgumentException("상행역과 하행역 중 하나는 노선에 존재해야합니다."));
노선을 삭제했을 때(`DELETE /lines/{id}`) 구간 테이블을 조회하면 어떤 결과가 나오는지도 확인해 볼까요?

2022-05-13 18:45 UTC, choihz commented on src/main/java/wooteco/subway/domain/Line.java
> +    private final List<Station> stations;
혹시 제공된 프론트엔드 페이지의 구간 관리 메뉴를 확인해 보셨나요? 역의 순서는 중요한 의미를 갖지 않나요? 지금은 어떤 순서로 보여지고 있나요?

2022-05-13 18:45 UTC, choihz commented on src/main/java/wooteco/subway/controller/SectionController.java
> +    }
각각이 다른 구간에 속하는 역 둘로 이루어진 새로운 구간 생성 요청을 보냈을 때(예를 들면 `1 - 2 - 3` 구간이 이미 존재하는데  `1 - 3` 구간을 새로 생성하려 할 때) 어떤 메시지를 주고 있는지 확인해 볼까요?

2022-05-13 18:45 UTC, choihz commented on src/main/java/wooteco/subway/controller/SectionController.java
> +    }
이미 존재하는 구간 사이로 새 구간 생성 요청을 보내는데 길이 조건이 맞지 않을 때 어떻게 되는지도 확인해 보아요 😱 여러 번 테스트해 보았는데 생성이 안 되는 경우도 있고 되는 경우도 있는 것 같아요.

2022-05-13 18:45 UTC, choihz commented on src/main/java/wooteco/subway/controller/SectionController.java
> +    }
마지막 남은 구간을 삭제하려 할 때 어떤 메시지를 보내고 있는지 확인해 볼까요?

2022-05-22 02:48 UTC, kang-hyungu approved these changes
페퍼 몇 가지 간단한 코멘트 남겼어요
피드백은 지하철 경로 조회 미션에서 적용해보시기 바랍니다.
궁금한 점 생기면 오프라인으로 질문하셔도 좋습니다.
다음 미션 진행을 위해 pr은 머지 처리할게요

2022-05-22 02:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/service/SectionService.java
> +    private int calculateDistanceDifference(Section section, Section prevSection) {
이 메서드는 도메인 객체 내부에서 처리해도 되겠네요

2022-05-22 02:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/service/SectionService.java
> +        if (sections.size() == 2) {
1. 매직넘버를 제거합시다.
2. 객체지향 생활체조 원칙. 한 줄에 한 점만 찍는다.
3. dao가 필요한 부분을 제외하고 if절 조건을 Sections라는 일급 컬렉션에서 처리하도록 만들면 어떨까요?

2022-05-22 02:48 UTC, kang-hyungu commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +    private final LineRequest lineRequest1 = new LineRequest("1호선", "blue", 1L, 2L, 10);
의미 있는 변수명을 써보시기 바랍니다.
테스트 코드니까 한글 변수명을 사용해보면 어떨까요

```suggestion
    private final LineRequest 지하철_1호선= new LineRequest("1호선", "blue", 1L, 2L, 10);
```

2022-05-22 02:48 UTC, kang-hyungu commented on src/test/java/wooteco/subway/acceptance/LineAcceptanceTest.java
> +        return RestAssured.given().log().all()
RestAssured를 호출하는 코드가 Line, Section, Station 인수 테스트 코드마다 중복해서 발생하고 있네요.
RestAssured로 http를 호출하는 중복 코드를 제거해보시기 바랍니다.

2022-05-22 02:48 UTC, kang-hyungu commented on src/main/java/wooteco/subway/domain/Section.java
> +    private final Long lineId;
다른 객체의 id를 변수로 갖게 되면 객체지향적으로 작성하기 어려워집니다.
다음 단계 미션에서 Line, Station 객체를 사용하도록 만들어보시기 바랍니다.

2022-05-22 02:48 UTC, merged